### ISSUE TITLE
`Resources` improvements

### ISSUE THREAD

**Issue by armanbilge** [etorreborre/specs2#1018]
Spinning out of https://github.com/etorreborre/specs2-cats/issues/6#issuecomment-954608698.

- [ ] Make acquisition of global resources atomic.
- [ ] Make the finalizer independent of the resource being acquired. Right now the finalizer is of the form `T => Execution`; however, acquiring a resource e.g. in Cats Effect gives you something like: `(resource: T, finalizer () => Unit)`. This is workable, but awkward for end users.
- [ ] Cross-build for Scala.js, where the concurrent data structures may not be supported (need to double-check). Worst case, this will require a second independent implementation. This should be confirmed by a spec that runs on both JVM/JS.

I realize none of these is trivial 😅 I'll try and carve out some time to PR this. I'm thinking something like this:
1. Instead of using a concurrent map, use an immutable map inside of an `AtomicRef`. This is supported on JVM/JS.
2. Implement a non-blocking [mini-semaphore](https://github.com/typelevel/cats-effect/blob/7890d8208738868bb2f5c85cae4e3d8e4f182bc6/kernel/shared/src/main/scala/cats/effect/kernel/MiniSemaphore.scala#L28) in terms of `Future` and `Promise`, and use this to address the atomicity issue. This should work across JVM/JS.

**Comment by etorreborre** [comment]
I have made some changes to synchronize the access to global resources and the `ResourceSpec` now runs with both ScalaJVM + ScalaJS. The JVM version is flaky though, I need to work on it.

About the cats-effect finalizer, if we have a `() => unit` we can discard the parameter in the specs2 `release` method and write:
```scala
def release(t: T): Execution = 
  Execution.future { finalizer(); Success() }
```

**Comment by armanbilge** [comment]
Wow, thanks! Will take a look.

Regarding CE, the trouble is to get the finalizer we need to allocate the resource first:
```scala
def allocated: F[(A, F[Unit])]
```
https://github.com/typelevel/cats-effect/blob/3f842bc31ce2e2b70a403beacecb1bbcdde24796/kernel/shared/src/main/scala/cats/effect/kernel/Resource.scala#L376

So it's impossible to statically define a `release` method directly in terms of `A`. Of course we could define `T = (A, Future[Unit])` but that's awkward for the user who just wants `A`.

**Comment by etorreborre** [comment]
Ah of course, that makes sense.

One ugly option could be to write:
```scala
trait CatsResource[T] extends Resource[T]:

  protected def allocate: F[(T, F[Unit])]

  private var finalizer: Option[F[Unit]]

  protected def acquire: Future[T] = 
    allocate.unsafeToFuture.map { (t, f) => 
      finalizer = Some(f)
      t
    }

  protected def release(resource: T): Execution = 
    Execution.future { 
      finalizer.getOrElse(F.fail("!!!")).unsafeToFuture.map(_ => Success())
    }
```
That's not particularly pretty but wouldn't that work?

**Comment by armanbilge** [comment]
So I'm looking at 2c536fdb7f060f77efd14ec2489a2193ae96557b and I'm really sorry but I'm still confused how this guarantees atomicity of global resources. Apologies if I'm being dense, do you mind stepping me through it with the scenario described in https://github.com/etorreborre/specs2-cats/issues/6#issuecomment-955787323?

**Comment by armanbilge** [comment]
> That's not particularly pretty but wouldn't that work?

How does that work with global resources? Also that unsynchronized var makes me nervous 😅

**Comment by etorreborre** [comment]
> How does that work with global resources? Also that unsynchronized var makes me nervous 😅

There is one var per instantiated spec and it is only accessed once, for one of the specification, when the global finalization happens.

**Comment by armanbilge** [comment]
> There is one var per instantiated spec and it is only accessed once, for one of the specification, when the global finalization happens.

Right, but that `var` is set only once, the one time the global resource is acquired. Because the `var` is not shared, wouldn't that necessitate that the same spec that acquires the resource also finalizes it?

**Comment by etorreborre** [comment]
> So I'm looking at 2c536fd 

The real fix is in `c400dbb`, with [`synchronized`](https://github.com/etorreborre/specs2/commit/c400dbb9d94635fcb5524ac8ac0868043c2c565c#diff-30e10cff327c9871e27f2b3f6f591e8ece12c6bcbcb8dba8550f5a552421abc8R89)

**Comment by etorreborre** [comment]
The first specification to acquire the global resource [will also register its own finalizer](https://github.com/etorreborre/specs2/commit/c400dbb9d94635fcb5524ac8ac0868043c2c565c#diff-30e10cff327c9871e27f2b3f6f591e8ece12c6bcbcb8dba8550f5a552421abc8R94).

**Comment by armanbilge** [comment]
Aha, so sorry that I missed that commit!! That looks good 👍

Thanks for explaining about the global resource, I think that makes sense. I'll wrap that `var finalizer` in a ref for concurrency and your workaround should do the trick for `CatsResource` :)

Btw, I am a bit confused about how `synchronized` is implemented on Scala.js, since it is a blocking operation. If it's a no-op, I'm not sure we can rely on it like we do on the JVM. If you don't mind, I will look into this and get back to you.

Thanks again for fixing all this!
