### ISSUE TITLE
`setSeed` for scalacheck props doesn't replicate results

### ISSUE THREAD

**Issue by armanbilge** [etorreborre/specs2#1025]
Sorry to come with another scalacheck bug :(

```scala
"Props" should {
  "repeat themselves" in prop { (x: Int) =>
    println(x)
    ok
  }.setSeed("zfry0jm3tkrfnfe39gCAm-xauJ69rEGWB9r-AZXiaiO=")
}
```

Running this twice gets completely different results (not just the order, but the actual `Int`s generated). I tried adding `sequential` in case it makes a difference.

**Comment by etorreborre** [comment]
Thanks for putting up with my mistakes. After all this time I did not really understand how parameters were used in ScalaCheck

**Comment by armanbilge** [comment]
Not at all! Just tried RC-21 and it's perfect ❤️ thank you for another blazing fast fix! Seriously, much appreciated :)
