### ISSUE TITLE
parse error when using Json matchers

### ISSUE THREAD

**Issue by nadavwe** [etorreborre/specs2#1069]
Hi @etorreborre,
I was happily using the json matchers when I found a peculiar minor bug related to quoting with nested components.
here is [an sbt repo with the failing tests](https://github.com/nadavwe/specs2-json-example)
and the code example:
```scala
package org.example.check

class JsonQuotesMatcherTest extends org.specs2.mutable.SpecWithJUnit with org.specs2.matcher.JsonMatchers {
  "json matchers" should {
    "succeed in parsing quotes" in {
      val a = '\\'
      val b = '"'
      s"""
        {"a": "hello${a}${b}world"}
        """ must /("a" -> """hello"world""")
    }

    "succeed in array quotes" in {
      val a = '\\'
      val b = '"'
      s"""
        [{"a": "hello${a}${b}world"}]
        """ must */("a" -> """hello"world""")
    }

    "succeed in key nested quotes" in {
      val a = '\\'
      val b = '"'
      s"""
        {"values": [{"hello${a}${b}world" : "a"}]}
        """ must /("values").andHave(contain(/( """hello"world""" -> "a")))
    }

    "succeed in value nested quotes" in {
      val a = '\\'
      val b = '"'
      s"""
        {"values": [{"a": "hello${a}${b}world"}]}
        """ must /("values").andHave(contain(/("a" -> """hello"world""")))
    }
  }
}
```
the first two tests pass just fine.
the last two fail with:
```
[info] json matchers should
[info]   + succeed in parsing quotes
[info]   + succeed in array quotes
[error]   x succeed in key nested quotes
[error]    There is 1 failure
[error]    Could not parse
[error]    {"hello"world":"a"} (JsonQuotesMatcherTest.scala:26)
[error]   x succeed in value nested quotes
[error]    There is 1 failure
[error]    Could not parse
[error]    {"a":"hello"world"} (JsonQuotesMatcherTest.scala:34)
```

I got this using latest specs2 version 4.13.2 (but it's also present in 4.8.3).
thanks!

**Comment by etorreborre** [comment]
Thanks @nadavwe for spotting this issue. `4.14.1` is on the way to fix it.

**Comment by nadavwe** [comment]
thanks for the swift fix!
I looked at the fix you've issued - but couldn't fully understand what the actual fix was.
it looks like you've changed the `showJson` method - is that also used for subsequent matches (i.e. the name `showJson` is a bit of a deceptive name? :))

**Comment by etorreborre** [comment]
> it looks like you've changed the showJson method - is that also used for subsequent matches 
Yes that's it. When we do a first match we parse the original string into a `JSONType`. Then if part of that json value, for example the array at a given key, need to be checked with another json matcher we need to print the array as a string so that it can be matched against another json matcher. Hence the `showJson` name where we show a json value as a string by traversing it recursively. 

What was missing before was that any string containing a `"` inside should have it quoted with a `\` in the final displayed string (the `hello"world` string needs to be rendered as `"hello\"world"` for example)

**Comment by etorreborre** [comment]
The new version `4.14.1` is up now
