### ISSUE TITLE
Questions about versions 4.14.0/4.14.1(-cross) and 4.15

### ISSUE THREAD

**Issue by mkurz** [etorreborre/specs2#1078]
Similiar to #1022 can you please clarify what the versions 4.14.0, 4.14.1, 4.14.1-cross and 4.15 are about?
https://repo1.maven.org/maven2/org/specs2/specs2-core_2.13/

You did not git-tag them and there are no release notes for that versions.
I just saw that commit 410b9a95117ce78432f983b6cf956af1e515ba81 which comes immediately after the `SPECS2-4.13.1-cross` tag:
![image](https://user-images.githubusercontent.com/644927/162414391-0ac5a16a-98f0-4a18-b60c-4c7098a99cb2.png)

I don't get it. Are `4.13.1-cross`, `4.14.1-cross` and `4.15` basically cut from the some code base? Is 4.14.x even intended to be used or did you go straight from 4.13.1-cross (which is based on 4.13.3, since you merged that in) to 4.15?
Would be nice if you at least can tag that release if they make it to maven central, because scala-steward will pick them up and opens pull requests. 

Thanks!

**Comment by etorreborre** [comment]
Thanks for asking, I didn't take the time to fully explain the situation. Here it is: https://github.com/etorreborre/specs2/releases/tag/SPECS2-4.15.0

**Comment by etorreborre** [comment]
Oops, fixed.

**Comment by mkurz** [comment]
Is this correct? Or a type?
> 1. a full version of specs2, **4.15.0**, ...
> 1. a version of specs2, **4.15.0**...
...
> of migrating to Scala3, you can use a version **>= 4.15 && < 5**...
> for Scala2 and Scala3, you can use a version **>= 4.15 && < 5**...

Its the same versions every time?

**Comment by etorreborre** [comment]
yes

**Comment by etorreborre** [comment]
The version number is correct but the specs2 code for Scala2 and Scala3 is different:

  - branch specs2-4.x-maintenance -> creates an artifact `specs2-core_2.13/4.15.0` for Scala 2
  - branch specs2-cross -> creates an artifact `specs2-core_3/4.15.0` for Scala 3 (and mostly source compatible with the previous artifact)
  - branch specs2-five -> creates an artifact `specs2-core_3/5.0.0` for Scala 3 (and not source compatible with the previous 2)

**Comment by mkurz** [comment]
OK I got it, you publish the same version (e. g. 4.15.0) once from a branch for Scala 2.12/2.13 and once from another branch for Scala 3. I was a bit confused.

**Comment by mkurz** [comment]
I guess the versions 4.14.0, 4.14.1 and 4.14.1-cross, which were not even tagged but [made their way to maven central](https://repo1.maven.org/maven2/org/specs2/specs2-core_2.13/) can be completely ignored, so the version jump is from 4.13.3 to 4.15.0 actually.
Thanks!

**Comment by etorreborre** [comment]
Yes, sorry for the confusion. I'm not particularly happy to have to maintain 3 branches so I hope people will move to Scala 3 fast!
