### ISSUE TITLE
Probably prefix removal for a dependency in the documentation notes.

### ISSUE THREAD

**Issue by cruiztorresj** [etorreborre/specs2#1092]
Hello there,

RIght now the [Quickstart](https://etorreborre.github.io/specs2/website/SPECS2-5.0.2/quickstart.html) and the [installation](https://etorreborre.github.io/specs2/guide/SPECS2-5.0.2/org.specs2.guide.Installation.html) sections contains the following proposed dependencies in order to get started:
`libraryDependencies ++= Seq("org.specs2" %% "specs2-core" % "SPECS2-5.0.2" % "test")`

I needed to remove the prefix `SPECS2-` in order to make this library work for me. As follows:
`libraryDependencies ++= Seq("org.specs2" %% "specs2-core" % "5.0.2" % "test")`

Sorry if this isn't an issue. And if it is, I volunteer to send that tiny little pull request so you can focus in other areas of the library.

Please note that I am solely using Scala 3. I don't know if that line of code has to remain the same for Scala 2 compatibility purposes.

--
Caleb

**Comment by etorreborre** [comment]
Thanks for noticing this, that should be an easy fix. Let's see if the doc ends up ok online 🤞

**Comment by cruiztorresj** [comment]
I am not sure how long it will take for the new content to be rendered in the docs but the prefix is still there.
Have a look
![screenshot](https://user-images.githubusercontent.com/75508473/178081916-7ce47b3e-d345-4414-8294-02ce43cf8d80.png)

So anyway, glad to be helpful.

Have a good one.

--
Caleb

**Comment by etorreborre** [comment]
The change has been made on the latest tag
<img width="644" alt="image" src="https://user-images.githubusercontent.com/10988/178096948-ec5d7e1c-b5cf-4fae-ae61-1bf845cde6b1.png">
which is the one you get when you come from the main `specs2.org` page in the "Learn" menu
<img width="769" alt="image" src="https://user-images.githubusercontent.com/10988/178096975-8f2cbd11-2731-4608-a45e-e3353f8bbd22.png">

**Comment by cruiztorresj** [comment]
OK buddy, seems like you have this under your belt.

I have spotted two parts within the entire portal with  the opportunity of modification.

- [x]  [Installation section](https://etorreborre.github.io/specs2/guide/SPECS2-5.0.6/org.specs2.guide.Installation.html) ✅ 
- [ ] [Quickstart section](https://etorreborre.github.io/specs2/website/SPECS2-5.0.6/quickstart.html) does still shows the prefix. 🧡

Happy weekend.

--
Caleb

**Comment by etorreborre** [comment]
Thanks @cruiztorresj that will be fixed with the next pushed tag.
