### ISSUE TITLE
Consider re-releasing 4.17.0 as 4.19.0

### ISSUE THREAD

**Issue by george-wilson-rea** [etorreborre/specs2#1119]
It's unfortunate that the latest version in the 4.x series (4.18.0) is the one we shouldn't use. Could you please release the current main branch as 4.19.0? That way the latest version would be a good one. This will help people who like to keep up with the latest version.

**Comment by aaronmarshallrea** [comment]
This would also help for people using scala steward or renovate bot 😁

**Comment by etorreborre** [comment]
That makes sense: https://repo1.maven.org/maven2/org/specs2/specs2-core_2.13/4.19.0
