### ISSUE TITLE
v4.19 not published to Maven Central (?)

### ISSUE THREAD

**Issue by mkurz** [etorreborre/specs2#1120]
We get
```
...
[error]   not found: https://repo1.maven.org/maven2/org/specs2/specs2-junit_3/4.19.0/specs2-junit_3-4.19.0.pom
...
````
Missing here: https://repo1.maven.org/maven2/org/specs2/specs2-junit_3/

**Comment by etorreborre** [comment]
It seems that you are using the "cross" version of specs2 for which I did not publish a 4.18.0, so 4.17.0 should be ok. Anyway I am going to publish a 4.19.0 so that everything is flush.

**Comment by mkurz** [comment]
Yeah it's just that scala steward opens pull requests which then fail for us. Thanks!

**Comment by mkurz** [comment]
Thanks!
