### ISSUE TITLE
`Around` not working in specs 4 Scala 3

### ISSUE THREAD

**Issue by mkurz** [etorreborre/specs2#1136]
`Around` makes use of `DelayedInit`:
* https://github.com/etorreborre/specs2/blob/specs2-cross/core/shared/src/main/scala/org/specs2/mutable/Around.scala#LL14C48-L14C59

But that does not work anymore in Scala 3: https://docs.scala-lang.org/scala3/reference/dropped-features/delayed-init.html

Code still compiles, even tests may pass, but the [`around` method](https://github.com/etorreborre/specs2/blob/specs2-cross/core/shared/src/main/scala/org/specs2/specification/Context.scala#L136) will not be executed anymore, which means custom init code or cleanup code won't run. For example I had code that "stopped" an application, but then I couldn't run other tests because not all resources of the app were cleaned up. In Scala 2 everything still works.

I think that should be mentioned in: https://github.com/etorreborre/specs2/releases/tag/SPECS2-4.13.1-cross

**Comment by mkurz** [comment]
Also see
* https://github.com/scalatest/scalatest/issues/351#issuecomment-1441189962
* https://github.com/scalatest/scalatest/pull/2228

**Comment by etorreborre** [comment]
Thanks, I updated the release notes. Out of curiosity do you have the possibility to switch to Scala3 only?

**Comment by mkurz** [comment]
> Out of curiosity do you have the possibility to switch to Scala3 only?

We are not going to publish Scala 3 artifacts only soon. We will cross publish to 2.13 for quite a while. We could publish different artifacts for _2.13 and _3 but defenetily not for our next major release.
