### ISSUE TITLE
specs2-mock depends on older mockito

### ISSUE THREAD

**Issue by NAJ10** [etorreborre/specs2#1138]
specs2-mock 4.19.2 depends on mockito 3.11.2 which was released a couple of years ago. On our project we also use mockito-scala-scalatest and when I try to upgrade it from 1.16.55 to 1.17.22 I start to get NoSuchMethodError on org.mockito.Mockito.verifyZeroInteractions which specs2-mock is trying to call because it seemed to get renamed/removed in mockito (presumably starting with 4.0.0)

Can you consider making specs2-mock depend on a more modern version of Mockito please?

**Comment by etorreborre** [comment]
I propose to take [the latest `4.x` version for Mockito](https://mvnrepository.com/artifact/org.mockito/mockito-core) which must be what everyone is using (and maybe not `5.x` which a lot more recent). Would that work for you?

**Comment by etorreborre** [comment]
I have now published `specs2-4.20.0` with an upgraded mockito dependency. Please tell me how it works for you.

**Comment by NAJ10** [comment]
Yes. That seems to work for me. Thank you
