### ISSUE TITLE
Release 4.20.0 does not have tag or release notes

### ISSUE THREAD

**Issue by eejbyfeldt** [etorreborre/specs2#1143]
There is a release 4.20.0 available on maven: https://mvnrepository.com/artifact/org.specs2/specs2-core_2.12/4.20.0 but as release does not seem to have a tag or release notes associated with it.

**Comment by etorreborre** [comment]
Sorry about that, it is fixed now: https://github.com/etorreborre/specs2/releases/tag/SPECS2-4.20.0. That release just updated the mockito dependency.
