### ISSUE TITLE
Release 4.20.0 not published for Scala 3

### ISSUE THREAD

**Issue by mkurz** [etorreborre/specs2#1148]
Good: https://repo1.maven.org/maven2/org/specs2/specs2-core_2.13/4.20.0/
Bad: https://repo1.maven.org/maven2/org/specs2/specs2-core_3/4.20.0/

This is annoying for projects that cross build against Scala 2.13 and Scala 3, scala-steward kicks in but CI fails because the dependency can not be found...

**Comment by etorreborre** [comment]
Sorry about that! The jar is available on Sonatype and should be in the central maven repository soon 
<img width="319" alt="image" src="https://user-images.githubusercontent.com/10988/234997503-f7a94ed1-da3f-4921-9b34-0d1d230c3cd8.png">

**Comment by mkurz** [comment]
Thanks!
