### ISSUE TITLE
specs2-mock does not support Scala 3

### ISSUE THREAD

**Issue by george-wilson-rea** [etorreborre/specs2#1156]
Can you please add a Scala 3 release of specs2-mock 4.20.0?

**Comment by etorreborre** [comment]
Unfortunately I have dropped the support for `specs2-mock` for Scala 3 because this was a terrible hack. I described the move [here](https://medium.com/@etorreborre_99063/becoming-reasonable-361d7f674ee0) with other assorted changes.

**Comment by tmccombs** [comment]
So, what is the recommended replacement for scala 3? The first blog post mentions mockito-scala, but that  doesn't support scala 3, and probably won't in the foreseeable future.

**Comment by etorreborre** [comment]
I was hoping that other libraries, like ScalaMock, would adapt faster to Scala3. Yet, [as you've noticed](https://github.com/paulbutcher/ScalaMock/pull/490), work is still ongoing. I think that, if we want to use mocks in Scala, we really need to embrace the language and have a specific library for it.

I must also say that, in my own practice, I don't use mocks anymore. I tend to implement traits with my own stubs and in general:

 - either use those as a model of the behaviour I'm expecting when testing something else
 - use them to collect data when my app is having side-effects (for logging, sending messages to other systems etc...)
