### ISSUE TITLE
Inconsistent behavior for Props created with Matcher vs created with extension method 'must'

### ISSUE THREAD

**Issue by kneisslm** [etorreborre/specs2#1185]
I've got a problem with Forms/Props: I'd expect that the following two expressions work effectively the same.

```
Form().tr(Prop("street", "1234").must(startWith("foo")))
```

and

```
Form().tr(Prop("street", "1234", startWith("foo")))
```

But actually the first one executes to Pending with "No expected value" and the second one to Failure with "1234 doesn't start with foo". I'd expect that both work like the second.

**Comment by etorreborre** [comment]
Good catch! I have now fixed this issue (in `4.20.2` and `5.3.2`)
