### ISSUE TITLE
`ContainWithResult` can have misleading failure messages with certain options

### ISSUE THREAD

**Issue by coreywoodfield** [etorreborre/specs2#1201]
```scala
import org.specs2.matcher.ValueCheck
import org.specs2.mutable.Specification

class Spec extends Specification {
  "strings" should {
    "all be unique" in {
      val strings = List("foo", "foo", "bar", "qux")
      strings.map { string =>
        strings must contain(string: ValueCheck[String]).exactly(1.times)
      }
    }
  }
}
```
fails with the message
```
List(foo, foo, bar, qux) does not contain foo
```
which is obviously false. It's not a huge deal with such small lists, but when lists have hundreds of elements, and you just read the beginning and the end of the failure message, it can be a lot more confusing:
```
List(foo, bar, qux, ...) does not contain foo
```

**The methods that change the behavior of `ContainWithResult` should also change the failure message.**

**Comment by etorreborre** [comment]
Thanks for reporting this issue. You can see some examples of fixed messages [here](https://github.com/etorreborre/specs2/commit/68afff639c415bdc28dd951f8594798963c84ed2#diff-5b1f713f4672736351dd1e1e7c1cce32882c18fc229357a1af11abc436a327bfR40). I will release a new version very soon.
