### ISSUE TITLE
ExecutionEnv is not shutdown, eventually leading to OOME

### ISSUE THREAD

**Issue by OlegYch** [etorreborre/specs2#1211]
specs2 v5.2.0
running tests in sbt without fork hangs on to classloader which eventually blows up Metaspace

https://github.com/etorreborre/specs2/blob/ad4e1d1deeb38b9058e5e23fe99d3bdedcda489a/common/shared/src/main/scala/org/specs2/concurrent/ExecutionEnv.scala#L13 for some reason is a noop....

![image](https://github.com/etorreborre/specs2/assets/268312/f614811f-3a79-4162-8cd9-f4f6d2e2de95)

**Comment by OlegYch** [comment]
also https://github.com/OlegYch/specs2/blob/751ec0bd90b4d49a9669501b362f771b87b61dbf/common/shared/src/main/scala/org/specs2/control/Operation.scala#L157
and some other places...

**Comment by etorreborre** [comment]
@OlegYch I have made some good progress during the week-end but I cannot yet release a fix now. I hope I'll fix it this week.

**Comment by OlegYch** [comment]
@etorreborre sounds nice
here is a sample project https://github.com/OlegYch/specs-sbt

**Comment by etorreborre** [comment]
Hi @OlegYch. I just released specs2-5.5.0. Thanks for your sample project, I can confirm that it works fine now.
And thanks for all your pointers, I indeed had to patch some serious holes.

**Comment by OlegYch** [comment]
cheers 🍻
