### ISSUE TITLE
Release for Scala Native 0.5

### ISSUE THREAD

**Issue by JD557** [etorreborre/specs2#1234]
I'm not sure what's the current status of Specs2 v4 and Native support... My understanding is that Specs2 v5 does not yet support Native yet, however Specs2 v4 still receives updates.

As such, would it be possible to release a new version of Specs2 v4 with Scala Native 0.5 support? Or is that version out of commission for good?

**Comment by etorreborre** [comment]
specs2-4.x now supports Scala Native 0.5, thanks to @xuwei-k. The version is [`4.20.6`](https://ossindex.sonatype.org/component/pkg:maven/org.specs2/specs2-core_2.13@4.20.6). I haven't had a look at that for specs2-5.x though.

**Comment by JD557** [comment]
Oops, sorry, I should have checked before (I did check a few days ago, and assumed it was not released... looks like I should have checked again today 😓 )

**Comment by etorreborre** [comment]
No worries at all. Do you need Scala Native for specs2-5.x as well?

**Comment by JD557** [comment]
No, 4.x is enough for me, thanks 👍

**Comment by xuwei-k** [comment]
- 😢 https://github.com/etorreborre/specs2/issues/1239
