### ISSUE TITLE
Version 5.5.2 was released against Scala 3.4.2

### ISSUE THREAD

**Issue by TonioGela** [etorreborre/specs2#1244]
Version 5.5.2 of the library was built against Scala 3.4.2 -- https://github.com/etorreborre/specs2/blob/SPECS2-5.5.2/build.sbt#L41.

This forces all libraries to upgrade to 3.4.x as well, but the 3.4 series isn't intended for use by library authors. See https://www.scala-lang.org/blog/2024/02/29/scala-3.4.0-and-3.3.3-released.html for details.

Can we release a 5.5.3 that builds against Scala 3.3.3 to fix this?

**Comment by etorreborre** [comment]
Sorry about that. Here is the build: https://github.com/etorreborre/specs2/actions/runs/9380207889

**Comment by TonioGela** [comment]
> Sorry about that. Here is the build: https://github.com/etorreborre/specs2/actions/runs/9380246683

No problem, thanks for re-releasing 👍
