### ISSUE TITLE
Specs2 for Scala Native 0.5 is published under different versions

### ISSUE THREAD

**Issue by TonioGela** [etorreborre/specs2#1248]
If you take a look [at Maven Central](https://central.sonatype.com/search?q=specs2-scalacheck_native0.5) it's clear that specs2 was published for scala native 0.5 under different versions for Scala 2 and Scala 3.

More in detail, the only available versions are:
Version `4.20.7` for `specs2-scalacheck_native0.5_3`
Version `4.20.6` for `specs2-scalacheck_native0.5_2.13`
Version `4.20.6` for `specs2-scalacheck_native0.5_2.12`

**Comment by etorreborre** [comment]
Done. It might take a bit more time to propagate to Maven Central.

**Comment by TonioGela** [comment]
Thanks Eric!
