### ISSUE TITLE
Support more versions of pandoc

### ISSUE THREAD

**Issue by phdoerfler** [etorreborre/specs2#1286]
Hi Eric,

the user guide indicates that the only supported version of pandoc is 2.3 which is from 2018. Are there any plans to officially support newer versions of pandoc?

Thanks a lot in advance

**Comment by etorreborre** [comment]
PR accepted! But joke aside I'll try to have a look at it when I have a moment :-).

**Comment by phdoerfler** [comment]
Thank you! It’s not super urgent. In fact, we are using specs2 in version 2.4 and 4.x together with a newer version of pandoc (3.1.x iirc) and have yet to run into issues. Is there anything in particular to look out for?

**Comment by etorreborre** [comment]
> specs2 in version 2.4 and 4.x
version `2.4` of specs2?

**Comment by etorreborre** [comment]
Oh, 2.4 is for `pandoc` I suppose.

**Comment by phdoerfler** [comment]
We are using both an ancient 2.4 version of specs2 in one branch a less ancient 4.0.8 version of specs2 in a different branch. In both cases we simply rely on the system installed pandoc which happens to be version 3.1 or slightly newer.

**Comment by etorreborre** [comment]
Wow, I had no idea that such an old version was still running!

**Comment by phdoerfler** [comment]
Yeah, it's still going strong. So strong, as it turns out, that it does markdown processing on its own without pandoc. This renders my previous comment about how specs2 2.4.17 works great with pandoc 3.1 moot. Sorry for the confusion.

It seems that pandoc started to be necessary somewhere between 2.4.17 and 3.6.3. I couldn't narrow it down further because the releases in between failed to resolve properly (due to scalaz) ;)

**Comment by etorreborre** [comment]
Yes, I remember switching from a Markdown Scala library to Pandoc at some stage because I had plenty of bugs with the existing libraries. Eventually shelling out to Pandoc seemed to work a lot better.

To come back to this issue, I haven't seen an issue with the latest specs2 4.x version and Pandoc. Besides updating the User Guide what should I do?

**Comment by phdoerfler** [comment]
Ah yes that makes sense.
Well, if you don’t notice any issues then I don’t see why a simple update of the user guide shouldn’t suffice. I guess I expected hard to overcome limitations since the user guide very much emphasises this one specific version. But even better if that’s not the case!

Thank you so much for taking the time to look into this!

**Comment by etorreborre** [comment]
I updated the user guide to remove the mention about the supported pandoc version and changed CI so that I always test with the latest version. So if there's a breakage I will hopefully know about it.
