### ISSUE TITLE
Logging of exceptions

### ISSUE THREAD

**Issue by fommil** [etorreborre/specs2#145]
This was originally discussed on the mailing list, but I would like to have a ticket against it so that I can track it in my own projects.

Original discussion: https://groups.google.com/d/msg/specs2-users/3cCUf-kUsaU/wgr5PEy1rTsJ

Basically, in order to correctly pass exceptions to the runtime logging infrastructure, a hacky `StacktraceFilter` must capture, log, and rewrite the stacktrace.

Unfortunately, this doesn't seem to work when the spec itself throws an exception, such as Akka's `expectMsg`, and the logging framework is bypassed.

Assuming the stack trace filtering is going to continue, I would recommend that all exceptions are passed to it, not just a subset.

**Comment by etorreborre** [comment]
Wow, "tomorrow" eventually took 2 years and your specs2-exceptions project has moved on somewhere else. Is that still something that you are looking for? I was thinking that maybe you could use a custom [`Notifier`](http://etorreborre.github.io/specs2/guide/org.specs2.guide.Runners.html#With+your+own) to achieve this. Then you would get access to any Throwable thrown during the execution of an example.

**Comment by fommil** [comment]
:smile: I guess I must have done a clean up at some point. To be honest I'm using scalatest these days so I don't have a need for this anymore, but thanks for checking up on it :smile:

**Comment by etorreborre** [comment]
That's what I figured :-). Thanks for the update, I'm closing this issue now.
