### ISSUE TITLE
Indentation and HTML reporting

### ISSUE THREAD

**Issue by asflierl** [etorreborre/specs2#162]
Hi Eric,

please forgive me if I'm missing something but I've read the new user guide and your blog post but could not find a solution to this issue, which seems like a bit of an oversight. 

Anyway, please consider the following simple spec:

```scala
import org.specs2._

class Meep extends SpecificationWithJUnit { def is = s2"""
This is a simple, hierarchial specification
  If things are indented
    and examples are nested
      this should be reflected
        in the console                   $ok
        as well as the HTML report       $ko
      just as expected
        by me                            $ok
        or maybe someone else            $todo
    or if there's only text, indentation
    possibly on multiple following lines
      should also work                   $ok
      and not quote lines as code        $ko
"""
}
```

Executing it shows a nice result on the console, i.e. all the different indentation levels are carried over just as expected:
![console](https://f.cloud.github.com/assets/106175/558860/1d72a056-c435-11e2-8b95-012848a6819b.png)

The HTML report in contrast is lacking many of the layout features and shows some unwanted things:
![html](https://f.cloud.github.com/assets/106175/558853/beee5fd4-c434-11e2-9ef4-b4ecc9280d24.png)

So, my biggest issue is that the indentation is not reflected at all anymore (this works a lot better with the "traditional" acceptance spec).

The second problem is that any text that is indented 4 or more spaces is interpreted as a code block. While this is standard markdown behaviour, it is really unwanted for nested examples.

The third issue is a rather minor one: the "todo" appears as two examples, rather than one "i" icon, followed by the example text and then the "TODO" text all on one line.

So far, these issues would mean I cannot do hierarchial specs with the new interpolated spec feature, which is a real pity because of all the other advantages this style offers.

Also, I kinda *have* to do things in this hierarchial way if I want to avoid repitition and also because I can only use one line of text per example (without interpolating inside the interpolation... which just reads awful).

It would be cool if you could look into this at some point.

Thanks a lot in advance.

**Comment by etorreborre** [comment]
Hi Andreas, now that specs2 3.0 is out, can you please check that this works for you? Note that you will have to install Pandoc to create Html documents now. I'm not happy about having to impose an external  dependency but that was the best thing I could find to make Markdown *really* work.

**Comment by etorreborre** [comment]
Don't spend time on it right now. There was a regression I am currently investigating.

**Comment by etorreborre** [comment]
The regression is that you should use Pandoc 1.12.4.1 or Pandoc 1.13.2 with the `markdown_attribute` extension on.

**Comment by etorreborre** [comment]
Closing this for now. Please test in 3.1.
