### ISSUE TITLE
Add `NoAutoHtmlLinkFragments` trait disabling stringToHtmlLinkFragments(2)

### ISSUE THREAD

**Issue by sirthias** [etorreborre/specs2#220]
Currently the

```
implicit def stringToHtmlLinkFragments(s: String): HtmlLinkFragments
implicit def stringToHtmlLinkFragments2(s: String): HtmlLinkFragments2
```

implicits collide with application-level pimps of `~` onto Strings.
In spray we therefore added `NoAutoHtmlLinkFragments` trait (in analogy to the `NoTimeConversions` mixin that is already available with specs2):
https://github.com/spray/spray/blob/c826c2c7015ed4e044885b1edd793ae4907688db/spray-testkit/src/main/scala/spray/testkit/Specs2Interface.scala#L33

Now we discovered that we need the same thing again for parboiled2.
It'd be great if specs2 could incorporate this trait directly.

**Comment by FranklinChen** [comment]
What happened to this features in 3.6?

**Comment by etorreborre** [comment]
@FranklinChen sorry I missed that. I've now re-introduced some traits for deactivating the DSL operations. You can now use `org.specs2.specification.dsl.NoReferenceDsl` in `3.6-20150530005327-c890398`.
