### ISSUE TITLE
Scala 2.11 + Scalaz

### ISSUE THREAD

**Issue by kryptt** [etorreborre/specs2#268]
I am trying to run specs2 tests alongside scalaz 7.1.0-M7 and scala 2.11

but the latest specs2 release seems to have a binary incompatibility.

I am trying to checkout from source and publish something locally but I'm at a little bit of a loss here..

The runtime exception I get when trying to run tests are:
java.lang.IncompatibleClassChangeError: Found class scalaz.syntax.FunctorOps, but interface was expected

**Comment by jordancoded1** [comment]
Getting the same error :(
Can someone elaborate on How exactly do we "use a jar" in a play 2.3.x?

**Comment by idot** [comment]
like:

https://github.com/etorreborre/specs2/issues/296#issuecomment-56656739

in build.sbt
