### ISSUE TITLE
2.4.3: scalaz-stream can't be resolved

### ISSUE THREAD

**Issue by eamelink** [etorreborre/specs2#295]
I'm trying 2.4.3, but `scalaz-stream 0.5a` can't be resolved; probably because it's not on Central but on Bintray?

**Comment by kflorence** [comment]
@etorreborre is the `scalaz` library now required by `specs2-core`? This leads me to believe so: https://etorreborre.github.io/specs2/website/SPECS2-3.3.1/quickstart.html

**Comment by etorreborre** [comment]
`scalaz` has been a mandatory dependency of `specs2-core` even before `3.x` and since `3.x` `scalaz-stream` is also required.

**Comment by kflorence** [comment]
@etorreborre thanks for the quick update, I assumed that to be the case, but wanted to clarify for people that end up here via search (like me).

**Comment by benmccann** [comment]
A project that's published to Maven Central should not have dependencies that are not in Maven Central. The dependency on scalaz should either be removed or published to Maven Central

Also, you should never ever ever set `"scalaz-bintray" at "http://dl.bintray.com/scalaz/releases"` in your build. It opens you up to cross build injection attacks. Only use https to add a repository to your build

**Comment by etorreborre** [comment]
@benmccann as you've seen [here](https://github.com/scalaz/scalaz-stream/issues/258#issuecomment-95975632) the subject is being debated... Also thanks for the tip on `http vs https` for resolvers.

**Comment by francisdb** [comment]
Time to switch to the latest version of scalaz-stream which is available in central :-)

**Comment by etorreborre** [comment]
@francisdb I can't find it: http://search.maven.org/#search%7Cga%7C1%7Cscalaz-stream.

**Comment by francisdb** [comment]
Has not been indexed yet.
https://repo1.maven.org/maven2/org/scalaz/stream/scalaz-stream_2.11/

**Comment by etorreborre** [comment]
@francisdb ok, got it from [there](https://repo1.maven.org/maven2/org/scalaz/stream/scalaz-stream_2.11/0.7.2a/scalaz-stream_2.11-0.7.2a.jar).  This will be available in the next specs2 release.

**Comment by francisdb** [comment]
Great :+1:

**Comment by etorreborre** [comment]
@francisdb you can now try specs2 `3.6.2-20150723082059-c023894` if you want.

**Comment by francisdb** [comment]
thanks, resolved correctly without scalaz repo
