### ISSUE TITLE
 java.lang.IncompatibleClassChangeError: Found class scalaz.Tree

### ISSUE THREAD

**Issue by idot** [etorreborre/specs2#296]
The error java.lang.IncompatibleClassChangeError: Found class scalaz.syntax.FunctorOps ... is gone after update, but java.lang.IncompatibleClassChangeError: Found class scalaz.Tree, but interface was expected is there.

specs2: 2.4.2
scalaz: 7.1.0

**Comment by pjrt** [comment]
Had same issue. Added both, fixed the issue.

**Comment by wir33658** [comment]
Great, helped me too. Still, would be nice to know why, but who cares for now ;-)

**Comment by ozeebee** [comment]
tried to add both but without success in my case :(
will stick to the 2.3.x branch until fixed

**Comment by pauldraper** [comment]
I had the same problem, and solution.

```
"org.specs2" %% "specs2-core" % "2.4.17" % "test"
```

doesn't work, but

```
"org.specs2" %% "specs2-core" % "2.4.17" % "test",
"org.specs2" %% "specs2-junit" % "2.4.17" % "test"
```

does.

**Comment by outsideMyBox** [comment]
Adding junit doesn't work for me:

it compiles for

    "org.specs2" %% "specs2" % "2.3.13" % "test"


but I've got "java.lang.IncompatibleClassChangeError: Found class scalaz.syntax.FunctorOps, but interface was expected" for:

    "org.specs2" %% "specs2" % "2.4.17" % "test",
  
and "java.lang.IncompatibleClassChangeError: Found class scalaz.EitherT, but interface was expected" for:

    "org.specs2" %% "specs2-core" % "2.4.17" % "test",
    "org.specs2" %% "specs2-junit" % "2.4.17" % "test",

and

    "org.specs2" %% "specs2-core" % "3.5" % "test",
    "org.specs2" %% "specs2-junit" % "3.5" % "test",

**Comment by etorreborre** [comment]
You should check your scalaz version and make sure it is `7.1.1`. You might have `scalaz-7.0.6` imported by another library (especially if you are using Play then you might have to use the `specs2` jars with `scalaz-7.0.6` in the version: `specs2-core-3.5-scalaz-7.0.6.jar`).

**Comment by outsideMyBox** [comment]
Thanks for the swift answer!

    "org.specs2" %% "specs2-core" % "3.5-scalaz-7.0.6" % "test",
    "org.specs2" %% "specs2-junit" % "3.5-scalaz-7.0.6" % "test",

works.

**Comment by fooblahblah** [comment]
Using play-2.4.2 and play-monadic-actions (which can't use scala-7.1 and generates the error above) the following worked around it. 
```
"com.typesafe.play"             %% "play-test"                % "2.4.2"             % "test" excludeAll(ExclusionRule("org.specs2")),
"org.specs2"                    %% "specs2-core"              % "3.5-scalaz-7.0.6"  % "test",
"org.specs2"                    %% "specs2-junit"             % "3.5-scalaz-7.0.6"  % "test",
"org.specs2"                    %% "specs2-matcher-extra"     % "3.5-scalaz-7.0.6"  % "test",
"org.specs2"                    %% "specs2-mock"              % "3.5-scalaz-7.0.6"  % "test"
```

**Comment by Gneotux** [comment]
I solve my problem with 

```scala
    "io.spray"             %%   "spray-testkit"     % sprayVersion  % Test excludeAll(ExclusionRule("org.specs2")),
    "com.typesafe.akka"    %%   "akka-testkit"      % akkaVersion   % Test excludeAll(ExclusionRule("org.specs2")),
    "org.scalatest"        %%   "scalatest"         % "2.2.1"       % Test excludeAll(ExclusionRule("org.specs2")),
    "org.specs2"           %%   "specs2-core"       % "2.3.13-scalaz-7.1.0-RC1" % "test",
    "org.specs2"           %%   "specs2-junit"      % "2.3.13-scalaz-7.1.0-RC1" % "test",
    "org.specs2"           %%   "specs2-mock"       % "2.3.13-scalaz-7.1.0-RC1" % "test",
    "org.scalaz"           %%   "scalaz-core"       % "7.1.0",
```
