### ISSUE TITLE
Seeing "It is not a test" in JUnit XML Report Output

### ISSUE THREAD

**Issue by gsmaverick** [etorreborre/specs2#305]
Running SBT 0.13.6 and specs2 2.4.2 I'm seeing entries like this:

```
<testcase classname="com.inkling.export.MainSpec" name="(It is not a test)" time="-0.001">
```

in JUnit XML reports. It seems this is coming from this function: https://github.com/sbt/sbt/blob/60c8404d5ca56f5fc7c3a364bc02b477ba7c0b4f/testing/src/main/scala/sbt/JUnitXmlTestsListener.scala#L57 and for some reason the name of a test isn't bubbling up from specs2.

**Comment by RemyDeWolf** [comment]
Thank you @etorreborre, your solution works perfectly. 
If you don't want to set the testOptions at runtime, you can set everything in the build.sbt such as:
```scala
//build.sbt
lazy val myProject = (project in file("."))
  .disablePlugins (plugins.JUnitXmlReportPlugin)
  .settings(
    testOptions in Test += Tests.Argument(TestFrameworks.Specs2, "junitxml", "console"))
```
