### ISSUE TITLE
kickstart instructions not available in UserGuide

### ISSUE THREAD

**Issue by Simon-Payne** [etorreborre/specs2#317]
Hi Eric
Thank you for your excellent specs2 user guide.  Unfortunately I am short of time and needing to kickstart a dev project, and your guide, although full of lots of useful stuff, doesn't say how to get started.  e.g. what are the dependencies I need to import into my dev project to write Specs2 tests, etc.  It took me ages to just find where some of the Scala classes come from that are used as imports in the code examples.  I would really appreciate if some detail could be added about this.
thanks
Simon

**Comment by Simon-Payne** [comment]
It's okay I found them just after posting my question...http://etorreborre.github.io/specs2/ and  http://etorreborre.github.io/specs2/guide/org.specs2.guide.Runners.html
thanks

**Comment by etorreborre** [comment]
Cool, the [next user guide](http://etorreborre.github.io/specs2/guide-specs2-three/org.specs2.guide.UserGuide.html) will hopefully be easier to navigate.
