### ISSUE TITLE
If Scope extends `MustExpectations` - it causes failing tests to look like running and **passing**

### ISSUE THREAD

**Issue by maximn** [etorreborre/specs2#321]
Here's a sample code -
``` scala
package com.sample

import org.specs2.matcher.MustExpectations
import org.specs2.mutable.SpecificationWithJUnit
import org.specs2.specification.Scope


class BadTest extends SpecificationWithJUnit {

  trait ctx extends Scope with MustExpectations {}

  "Wrong statement" should {
    "be failed by a test" in new ctx {
      true must be_===(false)
    }
  }
}


//trait ctx extends Scope with Matchers with MustExpectations {
//  def someThingThatUsesMust(x: AnyRef) = x must beNull
//}

```

As you can see in the screenshot - IntelliJ shows the test as running and green.
![IntelliJ screenshot](https://www.evernote.com/shard/s203/sh/5724bdd8-5fd1-4ff6-a149-72f923e0b406/4162cb9400269c21/res/812c08f3-ce08-49b4-9ed6-833d157c2d5c/BadTest_scala_-__testapp__-_TestApp_-____Code_TestApp_.png?resizeSmall&width=832)

**Comment by etorreborre** [comment]
Yes, it needs to extend `MustThrownExpectations` for exceptions to be thrown and caught outside of the `Scope` trait.

**Comment by etorreborre** [comment]
Also, in this specific example you shouldn't need to create `MustExpectations` because `MustThrownExpectations` is already mixed in `org.specs2.mutable.SpecificationWithJUnit` and allows to create expectations already. So I guess that you are creating the `ctx` trait outside of a specific `Specification` to be able to reuse it, right?

**Comment by maximn** [comment]
Maybe I shouldn't use `MustExpectations`, but if I do, I expect to **get an error** somewhere.
Yes, I use it outside. Actually in my case my context extends a trait that extends `MustExpectations` but I wanted to provide the most simple example.

**Comment by etorreborre** [comment]
There are 2 traits offering the same API but having different implementations: `MustExpectations` and `MustThrownExpectations`. As the name indicates `MustThrownExpectations` must be used where exceptions are expected for control flow. Typically in this situation where code is being placed in the body of a trait (the `ctx` trait); if no exception is thrown there is no way to get notified of failures.

It would be better to have a compilation error when `MustExpectations` is being mixed-in with `Scope` but I don't know how to do that.

**Comment by etorreborre** [comment]
I have added 2 methods on `Scope` and `MustExpectations` to detect this issue at compile-time. I'm not sure this is the best way to do it but that should work for now.

**Comment by etorreborre** [comment]
I
