### ISSUE TITLE
Matching failing Futures

### ISSUE THREAD

**Issue by manuelbernhardt** [etorreborre/specs2#325]
I'm attempting to test if a service returns a failed Future. So far I attempted to use `throwA` but the exception does not seem to be caught, instead it propagates further and shows up as an error in the test results. Is there a better way to test this behaviour?

**Comment by etorreborre** [comment]
If you want to test failed futures you can write
```
myFuture must throwAn[Exception].await
```

**Comment by manuelbernhardt** [comment]
I can't get it to work I'm afraid...

    "The AuthenticationService" should {
    
      "fail if it takes too long" in {
        service.authenticateUser("jimmy@hendrix.com", "secret") must throwA[RuntimeException].await(1, 600.millis)
      }
    }

Results in

    [info] The AuthenticationService should
    [info] + correctly authenticate Bob Marley
    [info] + not authenticate Ziggy Marley
    [info] ! fail if it takes too long
    [error]    RuntimeException: : Future timed out after 500ms  (AuthenticationService.scala:31)
    [error] services.DummyAuthenticationService$$anonfun$authenticateUser$1.apply(AuthenticationService.scala:31)
    [error] services.DummyAuthenticationService$$anonfun$authenticateUser$1.apply(AuthenticationService.scala:23)


Might it be related to the version of `specs2`? I am using the one that comes with Play, which should be along the lines of `2.4.9`

**Comment by etorreborre** [comment]
With specs2 2.4.15, this works ok:
```scala
import org.specs2._
import org.specs2.time.NoTimeConversions
import scala.concurrent._
import duration._

class TestSpec extends mutable.Specification with NoTimeConversions {
  "The AuthenticationService" should {
    "fail if it the future throws an exception" in {
      Future { Thread.sleep(10); throw new Exception("blah"); 1 } must throwAn[Exception].await(0, 60.millis)
    }
  }
}
```
```shell
[info] TestSpec
[info]
[info] The AuthenticationService should
[info] + fail if it the future throws an exception
[info]
[info] Total for specification TestSpec
```

However I am not sure of what you want to test. Do you want to test what happens when the future throws an exception or when the future times out? If you just want to test the time out you can write:

```scala
import org.specs2._
import org.specs2.time.NoTimeConversions
import scala.concurrent._
import duration._

class TestSpec extends mutable.Specification with NoTimeConversions {
  "The AuthenticationService" should {
    "fail if it the future times out" in {
      Future { Thread.sleep(100); 1 } must be_==(1).await(0, 60.millis)
    }
  }
}
```
```shell
[info] Compiling 1 Scala source to /Users/etorreborre/projects/specs2/specs2/tests/target/scala-2.11/test-classes...
[info] TestSpec
[info]
[info] The AuthenticationService should
[info] x fail if it the future throws an exception
[error]    Timeout after 60 milliseconds (TestSpec.scala:11)
[info]
[info]
[info] Total for specification TestSpec
```

**Comment by manuelbernhardt** [comment]
Apologies, it looks like it is working with the latest specs2 version and everything works fine in a plain project with the tests. Unfortunately I can't seem to just drop in the newer version of specs in a Play project, the tests run, but they also kind of complain:

    Uncaught exception when running services.AuthenticationServiceSpec: java.lang.IncompatibleClassChangeError: Found class scalaz.Tree, but interface was expected

I'll see if the Play team plans an upgrade of specs2 in a new release. Thanks!

**Comment by etorreborre** [comment]
You can try the specs2-scalaz-7.0.6 version if Play is using scalaz 7.0.6.
