### ISSUE TITLE
Provide an eventually mockito matcher

### ISSUE THREAD

**Issue by kretes** [etorreborre/specs2#332]
Currently in specs2 I can use .eventually on any Matcher.
However when I use mockito dsl :

```
there was one(mock).deleteUser("1")
```
what I get is a 'MatchResult' not a Matcher, so I cannot call ```.eventually``` which is really elegant.

Would there be a way to do it in specs2?

**Comment by etorreborre** [comment]
You can use `eventually` on any `MatchResult`:

```scala
eventually {
  there was one(mock).deleteUser("1")
}

// or simply
eventually(there was one(mock).deleteUser("1"))`

// and if you want to specify the number of retries + sleep time between retries
eventually(retries = 2, sleep = 10.millis) {
  there was one(m).deleteUser("1")
 }
```
