### ISSUE TITLE
'exactly' collision from CalledMatchers & TraversableMatchers after upgrading to 2.4

### ISSUE THREAD

**Issue by hugebdu** [etorreborre/specs2#333]
Eric, hi.

We have many tests failing to compile after upgrading to 2.4.11 from 2.3.x.
It happens on the following line of code when Mockito trait is mixed in:

someSeq must contain(exactly(elementMatcher1, elementMatcher2))

for some reason the exactly is coming from CallableMatchers (via Mockito trait).

Any idea and workaround?

Thanks.

**Comment by etorreborre** [comment]
Can you please paste a full working (or rather broken) example. This works for me in 2.4.16
```scala
import org.specs2.Specification
import org.specs2.mock.Mockito

class TestSpec extends Specification with Mockito { def is = s2"""
   test $e1
 """

  def e1 = Seq(1, 2) must contain(exactly(be_==(1), be_==(2)))
}
```

**Comment by hugebdu** [comment]
Sure. I guess the problem occurs when Mockito is mixed in to the scope:
```scala
class DemoTest extends SpecificationWithJUnit {

  trait ctx extends Scope with Mockito with ThrownExpectations

  "bla" in new ctx {
    Seq(1, 2, 3) must contain(exactly(be_===(1), be_===(2), be_===(3)))
  }
}
```

**Comment by etorreborre** [comment]
There is indeed a collision in that case. One way to work-around it is to do a qualified import of `Matchers` called `m` for example:
```scala
import matcher.{Matchers => m, _}
class DemoTest extends SpecificationWithJUnit {

  trait ctx extends Scope with Mockito with ThrownExpectations

  "bla" in new ctx {
    Seq(1, 2, 3) must contain(m.exactly(be_===(1), be_===(2), be_===(3)))
  }
}
```
