### ISSUE TITLE
Site issue: wrong line in sbt config in "Quick Start" page

### ISSUE THREAD

**Issue by zergood** [etorreborre/specs2#335]
Hi!

Don't know actually where I should write this issue. 

This page [Quick Start](http://etorreborre.github.io/specs2/website/SPECS2-3.0/quickstart.html):

`libraryDependencies ++= Seq("org.specs2" %% "specs2-core" % 3.0 % "test"))`

should be:

`libraryDependencies ++= Seq("org.specs2" %% "specs2-core" % "3.0" % "test")`

**Comment by etorreborre** [comment]
Thanks for this!
