### ISSUE TITLE
Report slurs examples

### ISSUE THREAD

**Issue by digital-wonderland** [etorreborre/specs2#336]
Within a specification examples get added as sub-examples, if they don't contain nested examples. 

I.e. for a spec like this:
``` scala
class TestcaseSpec extends Specification {
  "Something" should {

    "do stuff" in {
      "one thing" in true
      "other thing" in true
    }

    "do not to be concatenated stuff" in true

    "do other stuff" in {
      "other" in true
    }
  }
}
```
the output is:
```
[info] Something should
[info]
[info] do stuff
[info] + one thing
[info] + other thing
[info] + do not to be concatenated stuff
[info]
[info] do other stuff
[info] + other
```
while I would expect ```do not to be concatenated stuff``` to be on the same level as ```do stuff```. It seems the formatting is reset once nested examples are encountered.

**Comment by etorreborre** [comment]
This is really tricky to get right because when you change where breaks get added you don't get the display you want either.

Most of the specifications are regular, they don't have isolated examples like that so in that case you can write (assuming you're working with specs2 3.0):
```scala
class TestcaseSpec extends Specification {
  "Something" should {

    "do stuff" in {
      "one thing" in true
      "other thing" in true
    }.br // add one more break to get a neat separation

    "do not to be concatenated stuff" in true

    "do other stuff" in {
      "other" in true
    }
  }
}
```

**Comment by etorreborre** [comment]
I had a closer look to all of this and published fixes to at least do what 3.0 what supposed to do (jar [here](https://oss.sonatype.org/content/repositories/releases/org/specs2/specs2-core_2.11/3.0-20150306080900-4d03363). On top of this new jar you will need to manually add breaks to get the display you are after (and now indentation is fixed):
```
class TestcaseSpec extends Specification {
  "Something" should {

    "do stuff" in {
      "one thing" in true
      "other thing" in true
    }; br // add one more break to get a neat separation

    "do not to be concatenated stuff" in true; br // another one here

    "do other stuff" in {
      "other" in true
    }
  }
}
```

I've got to dash off now but I'm open to discuss the subject further.

**Comment by etorreborre** [comment]
I'm closing this for now as being fixed w.r.t indentation and use of `br` which were both broken before.

**Comment by digital-wonderland** [comment]
Thanks a lot for the pointer with ```br```. This & the now working indentation do everything I was looking for.
