### ISSUE TITLE
Do not bundle mockito classes in specs2-mock jar

### ISSUE THREAD

**Issue by gnp** [etorreborre/specs2#342]
While developing command-line applications that use Play Framework 2.3.8 module play-ws to make web services calls, you need to provide an implicit instance of Application even though you are not building a web application. You can get a FakeApplication if you depend on play-test as a regular dependency instead of a test scoped dependency. However, if you then try to use sbt-assembly on your resulting application, you will get an error like this:

```
[error] (*:assembly) deduplicate: different file contents found in the following:
[error] $HOME/.ivy2/cache/org.specs2/specs2-mock_2.11/jars/specs2-mock_2.11-2.3.12.jar:org/mockito/internal/invocation/ArgumentsProcessor.class
[error] $HOME/.ivy2/cache/org.mockito/mockito-core/jars/mockito-core-1.9.5.jar:org/mockito/internal/invocation/ArgumentsProcessor.class
```

And, sure enough if you examine the specs2-mock jar file you will see that it has incorporated mockito class files:

```
$ jar tf $HOME/.ivy2/cache/org.specs2/specs2-mock_2.11/jars/specs2-mock_2.11-2.3.12.jar | grep org/mockito
org/mockito/
org/mockito/internal/
org/mockito/internal/invocation/
org/mockito/internal/matchers/
org/mockito/internal/progress/
org/mockito/internal/progress/ThreadSafeMockingProgress2$.class
org/mockito/internal/invocation/ArgumentsProcessor$$anonfun$argumentsToMatchers$1$$anonfun$apply$2.class
org/mockito/internal/matchers/EqualsFunction0$.class
org/mockito/internal/invocation/ArgumentsProcessor.class
org/mockito/internal/matchers/EqualsFunction1$.class
org/mockito/internal/progress/ThreadSafeMockingProgress2.class
org/mockito/internal/matchers/EqualsFunction0.class
org/mockito/internal/invocation/ArgumentsProcessor$.class
org/mockito/internal/invocation/MatchersBinder$.class
org/mockito/internal/progress/ThreadSafeMockingProgress2$$anonfun$reportMatchers$1.class
org/mockito/internal/invocation/ArgumentsProcessor$$anonfun$argumentsToMatchers$1$$anonfun$apply$1.class
org/mockito/internal/matchers/EqualsFunction1.class
org/mockito/internal/invocation/MatchersBinder.class
org/mockito/internal/invocation/ArgumentsProcessor$$anonfun$argumentsToMatchers$1.class
```
And it has also declared a dependency on mockito-core:

```
$ activator dependencyTree
...
[info]   | +-org.specs2:specs2-mock_2.11:2.3.12 [S]
[info]   |   +-org.hamcrest:hamcrest-core:1.3
[info]   |   +-org.mockito:mockito-core:1.9.5
[info]   |   | +-org.hamcrest:hamcrest-core:1.1 (evicted by: 1.3)
[info]   |   | +-org.hamcrest:hamcrest-core:1.3
[info]   |   | +-org.objenesis:objenesis:1.0
...
```

If we check the current state of the repo, we see that this issue remains in the project beyond the specific versions checked:

```
$ git clone https://github.com/etorreborre/specs2.git
...
$ cd specs2
$ activator package
...
$ jar tf mock/target/scala-2.11/specs2-mock_2.11-3.0.1-20150309002339-59fdac2.jar  | grep org/mockito
org/mockito/
org/mockito/internal/
org/mockito/internal/invocation/
org/mockito/internal/matchers/
org/mockito/internal/progress/
org/mockito/internal/invocation/ArgumentsProcessor$$anonfun$argumentsToMatchers$1$$anonfun$apply$1.class
org/mockito/internal/matchers/EqualsFunction1$.class
org/mockito/internal/matchers/EqualsFunction0$.class
org/mockito/internal/invocation/MatchersBinder$.class
org/mockito/internal/invocation/ArgumentsProcessor$$anonfun$argumentsToMatchers$1$$anonfun$apply$2.class
org/mockito/internal/progress/ThreadSafeMockingProgress2$$anonfun$reportMatchers$1.class
org/mockito/internal/invocation/ArgumentsProcessor.class
org/mockito/internal/progress/ThreadSafeMockingProgress2$.class
org/mockito/internal/invocation/ArgumentsProcessor$$anonfun$argumentsToMatchers$1.class
org/mockito/internal/matchers/EqualsFunction0.class
org/mockito/internal/invocation/MatchersBinder.class
org/mockito/internal/matchers/EqualsFunction1.class
org/mockito/internal/invocation/ArgumentsProcessor$.class
org/mockito/internal/progress/ThreadSafeMockingProgress2.class
```

Projects should declare their dependencies and *not* bundle their dependencies' classes. Anyone building applications using specs2 is going to be bringing in multiple copies of the mockito classes even if they don't realize it, and that is a recipe for mysterious failures.

Fortunately sbt-assembly catches this problem and refuses to build the assembly. Unfortunately, that means anyone wanting to use play-ws in a command-line program and leverage the play-test FakeApplication class in a non-testing target will have to work around this problem until it is fixed.

**Comment by etorreborre** [comment]
specs2 needs to redefine some Mockito classes to change their behaviour. In particular it allows to match byname parameters which Mockito can't handle out of the box. This is why you have some duplicated classes. 

You can work around this by using a custom made sbt assembly [`MergeStrategy`](https://github.com/sbt/sbt-assembly#merge-strategy). 

I am also wondering if you shouldn't exclude `specs2-mock` from your dependencies (by excluding it) if you don't need it.

**Comment by gnp** [comment]
Thanks for the prompt response.

I don't think you can guarantee your included classes will be used over those in the conflicting dependency jar (but I am interested to learn about it if you do have a way of doing that).

I can work around the problem and still use the play-test dependency in my project if I depend on it this way:

```
...
  "com.typesafe.play" %% "play-test" % playVersion exclude("org.specs2", "specs2-mock_2.11"),
...
```

And it looks like once SBT 0.13.8 ships, I'll be able to improve the workaround a little to this [https://github.com/sbt/sbt/pull/1748]:

```
...
  "com.typesafe.play" %% "play-test" % playVersion exclude("org.specs2" %% "specs2-mock"),
...
```

**Comment by etorreborre** [comment]
> I don't think you can guarantee your included classes will be used over those in the conflicting dependency jar (but I am interested to learn about it if you do have a way of doing that).

There's no absolute guarantee but this works if you put the specs2 jar on the class path before the mockito jar. Which I think works in sbt if you declare the specs2 dependency before the mockito one.

That's the not the most reliable way to work but that's the only trick I could find to allow people to mock functions with byname arguments which is pretty frequent in Scala.

**Comment by gnp** [comment]
Can you point me at a test case that breaks if you don't "override" these classes? It would help me to understand the situation. Are you changing the API of the mockito classes to make your feature work? What is the behavior if someone does not get the classpath ordering the way you intend?

**Comment by etorreborre** [comment]
You can try something like that:
```
trait ByName {
  def call(i: =>Int) = i
}

"this example will fail if specs2-mock.jar is not on the classpath before Mockito\n"+
"but will pass otherwise" in {
  val byname = Mock[ByName]
  byname.call(10)

  there was one(byname).call(10) 
}
```

**Comment by etorreborre** [comment]
This was just [answered today](http://stackoverflow.com/questions/28949368/mocking-a-void-function-in-scala-with-mockito) on StackOverflow.

**Comment by etorreborre** [comment]
I am closing this for now, I hope the explanation cleared things up.
