### ISSUE TITLE
problems with import language.postfixOps

### ISSUE THREAD

**Issue by vpatryshev** [etorreborre/specs2#343]
When I have this in any test, compiler says:

Error:scalac: ambiguous implicit values:
 both value postfixOps in object language of type => languageFeature.postfixOps
 and value postfixOpsAreAllowed in trait LanguageFeatures of type => languageFeature.postfixOps
 match expected type scala.languageFeature.postfixOps

And sorry, I could figure out where this comes from.

I mean, I can include postfixOpsAreAllowed into the body of the text, like in 
class TX_ExtractedEOB_Test extends TestBase
  with MockDB
  with Money
  with TimeReader {
  postfixOpsAreAllowed
  sequential
 ...

but it does not prevent scalac from issuing a warning.

Maybe just something in docs would be enough...

**Comment by etorreborre** [comment]
There is a `org.specs2.control.NoLanguageFeatures` trait you can mix-in to remove the `postfixOpsAreAllowed` implicit. There will be a new section in the next guide to explain this.

**Comment by vpatryshev** [comment]
@etorreborre, I'm still struggling with this. The section literally says:
"### Postfix operations
The notation `Seq() must be empty` is being parsed as `(Seq() must be) empty` where `empty` is a ["Postfix operator"](http://www.scala-lang.org/api/2.11.5/index.html#scala.language$$). By default Scala disallows postfix operators but they are enabled in specs2 specifications thanks to the `org.spec2.control.LanguageFeatures` trait providing the `language.postfixOps` implicit definition.
If that implicit definition conflicts with your own import of `language.postfixOps` you can use the `org.spec2.control.NoLanguageFeatures` trait to deactivate it.

So, I tried to add 'with org.spec2.control.NoLanguageFeatures' in my test class; this does not seem to work. I have my own checkers, like this:

    `def mustBeGood = if (!r.isGood) throw new FailureException(new Failure(s"Expected a good result, got $r"))`

and I could not find a way to compile a test without warnings about this. So I wonder... what's the trick?

**Comment by etorreborre** [comment]
This is a bug. I just realized that the `org.specs2.control.NoLanguageFeatures` was defining implicits.
