### ISSUE TITLE
Release a version with scalaz-stream 0.7a

### ISSUE THREAD

**Issue by julien-truffaut** [etorreborre/specs2#347]
It is required for https://github.com/RichRelevance/scalaz-netty/issues/7

```
[error] Could not run test scalaz.netty.NettySpecs: java.lang.NoSuchMethodError: scalaz.stream.Process$.Process0Syntax(Lscalaz/stream/Process;)Lscalaz/stream/Process$Process0Syntax;
```

**Comment by etorreborre** [comment]
Done: http://notes.implicit.ly/post/114607753679/specs2-3-2

**Comment by petervandenabeele** [comment]
This seems to fail for me when activating Specs2 version 3.3.1 

```
kinesis-example-scala-consumer > compile
[info] Updating {file:/Users/peter_v/Documents/data/customers/..../demo3/kinesis-example-scala-consumer/}kinesis-example-scala-consumer...
[info] Resolving org.scalaz.stream#scalaz-stream_2.11;0.7a ...
[warn] 	module not found: org.scalaz.stream#scalaz-stream_2.11;0.7a
[warn] ==== local: tried
[warn]   /Users/peter_v/.ivy2/local/org.scalaz.stream/scalaz-stream_2.11/0.7a/ivys/ivy.xml
[warn] ==== public: tried
[warn]   http://repo1.maven.org/maven2/org/scalaz/stream/scalaz-stream_2.11/0.7a/scalaz-stream_2.11-0.7a.pom
[warn] ==== Snowplow Analytics Maven repo: tried
[warn]   http://maven.snplow.com/releases/org/scalaz/stream/scalaz-stream_2.11/0.7a/scalaz-stream_2.11-0.7a.pom
[warn] ==== BintrayJCenter: tried
[warn]   http://jcenter.bintray.com/org/scalaz/stream/scalaz-stream_2.11/0.7a/scalaz-stream_2.11-0.7a.pom
[warn] ==== bigtoast-github: tried
[warn]   http://bigtoast.github.com/repo/org/scalaz/stream/scalaz-stream_2.11/0.7a/scalaz-stream_2.11-0.7a.pom
[info] Resolving jline#jline;2.12.1 ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: org.scalaz.stream#scalaz-stream_2.11;0.7a: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[trace] Stack trace suppressed: run last *:update for the full output.
[error] (*:update) sbt.ResolveException: unresolved dependency: org.scalaz.stream#scalaz-stream_2.11;0.7a: not found
[error] Total time: 4 s, completed Apr 6, 2015 4:33:29 PM
kinesis-example-scala-consumer > 
```

**Comment by etorreborre** [comment]
@petervandenabeele you need to add the `bintray` resolver to your [sbt build file](http://etorreborre.github.io/specs2/guide/SPECS2-3.3.1/org.specs2.guide.Installation.html#sbt):
```
resolvers += "scalaz-bintray" at "http://dl.bintray.com/scalaz/releases"
```

**Comment by petervandenabeele** [comment]
Thanks @etorreborre , that solved my issue :-)

**Comment by kovacshuni** [comment]
thanks

**Comment by philipwhiuk** [comment]
It seems wrong that the default (recommended) solution for Play is now to separately require a specific version of scalaz-stream which isn't packaged on Maven Central (I'm surprised you're able to package specs2 on Maven Central if all the dependencies aren't on Maven Central).

https://www.playframework.com/documentation/2.4.x/Migration24#Specs2-support-in-a-separate-module

**Comment by unkarjedy** [comment]
@etorreborre 
Bintray workaround will not work soon:
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/
Are there any plans to republish this special scalaz build somewhere?

**Comment by etorreborre** [comment]
@unkarjedy can you upgrade to a more recent version of specs2? Since [specs2 4.0.0](https://github.com/etorreborre/specs2/releases/tag/SPECS2-4.0.0) scalaz is not required anymore

**Comment by unkarjedy** [comment]
@etorreborre 
I am asking this not as a specs2 user. 
In Scala Plugin we have tests for 3.0.1 integration (among other versions).
In the context of JFrog news, we removed extra resolvers in tests and I noticed this error.
So I am now wondering what is the plans for the 3.0.1 version.
Will it be considered broken? 
If yes, then we might just remove the tests.

**Comment by etorreborre** [comment]
I see. I am not planning on maintaining versions older than 4.x (working on the 5.x series for Scala 3 at the moment) so yes consider the 3.0.1 version outdated.
