### ISSUE TITLE
No way to change default timeout for FutureMatchers.await

### ISSUE THREAD

**Issue by RichardBradley** [etorreborre/specs2#348]
I can't see any way to change the default timeout for FutureMatchers.await.

Our CI servers are slower than our dev machines, so people often find that the tests pass on their dev machine but fail on the CI server.

Akka anticipates this case and allows configurable default timeouts -- see http://doc.akka.io/docs/akka/snapshot/scala/testing.html#Accounting_for_Slow_Test_Systems

Can I do anything similar in Specs2?

Thanks,

Rich

**Comment by etorreborre** [comment]
I have tried to fix that in: `3.2-20150328050811-d146044`. I'm not sure that this is the best design though but it is the least invasive in terms of API. So, now if you pass ` { ec: ExecutionContext => Future(1) must be(1).awaitFor(10.millis)` then you will be able to "scale" the duration from the command line with the `timeFactor` argument. See the [User Guide](https://etorreborre.github.io/specs2/guide/SPECS2-3.2-20150328050811-f6f2463/org.specs2.guide.Matchers.html#out-of-the-box) for more information.

You will also see in the doc that I changed to API to remove overloaded methods with default values and fix #349.
