### ISSUE TITLE
Summary of a multi module project in SBT

### ISSUE THREAD

**Issue by gurgl** [etorreborre/specs2#352]
The function in maven/surefire of displaying a summary of a test suite run in a multimodule project feels more and more like a must have. With module i refer to mavens definition - sbt lingo would be  "nested project"?

* Like, when some module fails - it would be nice to see what tests failed at the end of the report. Not just what module failed - so i need to scroll up and find what test failed - separated by long traces.

* Also, for sanity check it would be nice with a per module 
  - stats of how many specs/tests that have run. 
  - Here just the list of modules would be a good feedback all module tests have been run

...all in all - the maven surefire way of displaying test reports is a good model i think (ignoring what it lacks when it comes to human readable output for individual tests.).

**Comment by etorreborre** [comment]
This is something that could be addressed at the sbt level but there are ways to do this in specs2 provided I do some adjustments. For example you could write this:

```scala
/**
 * This is an example of running specifications module by module
 */
class ModulesSpec extends Specification { def is =
 br ^
 Fragments.foreach(specs)(s => link(showOnly("x!") ^ s) ^ br)

 def specs =
   List(Core, JUnit, Examples)
}

object Core     extends Specification { def is = Module.specifications(getClass) }
object JUnit    extends Specification { def is = Module.specifications(getClass) }
object Examples extends Specification { def is = Module.specifications(getClass) }

object Module extends SpecificationCreation {
  def specifications(klass: Class[_], filter: String => Boolean = (s: String) => true) = {
    val name = klass.getSimpleName.replace("$", "")
    val base = DirectoryPath.unsafe(new java.io.File(".").getAbsolutePath) / FileName.unsafe(name.toLowerCase) / "src" / "test" / "scala"
    val specs = SpecificationsFinder.specifications(basePath = base, verbose = false, filter = filter).take(3)

    name.title.copy(specClass = klass) ^
    br ^
    Fragments.foreach(specs)(s => link(showOnly("!x") ^ s.is) ^ br)
  }
}
```

In the code above we create a specification at the project level containing links to other specifications representing the sub-modules. This allows a final display of all the stats

```
[info] Total for specification ModulesSpec
[info] Finished in 1 ms
[info] 12 specifications, 96 examples, 104 expectations, 0 failure, 0 error
```

Then there is one specification per module. Those specifications are built using the `SpecificationsFinder` to retrieve all the specs in a given module. 

Note that when I create links I specify what should be displayed during a run. In this case we display

 - only failure for each individual spec
 - only failures for the specification modules

We could change the statuses used at the specification level or the module level to show more or less things; show all the specifications of a given module for example.

If that plan suits you, I'll publish an interim version for you to play with.

**Comment by gurgl** [comment]
Thanks for the attention. Besides having an interrest in making my current project give easily digested reports to people involved/using it - i do care about the scala / sbt / specs2-scalatest-etc eco system evolving wo strain.  I can live with the current situation for some time. Id rather see its solved "the right way". So i should address SBT people with this inquiry then? Making it possible to provide nested project aggregated test reports of sorts?

**Comment by etorreborre** [comment]
Yes that's a good question for the sbt team. Both ScalaTest and specs2 notify sbt of "events" when there are run (failure, successes, test suite,...). Sbt could gather them into an overall summary. It looks like a cool PR if you want to do some open-source contribution :-).

I'm closing this for now.
