### ISSUE TITLE
Why isn't MockitoFunctions part of org.specs2.mock.Mockito?

### ISSUE THREAD

**Issue by kflorence** [etorreborre/specs2#353]
```scala
trait Mockito extends MocksCreation
  with CalledMatchers
  with MockitoStubs 
  with CapturedArgument 
  with MockitoMatchers
  with ArgThat
  with Expectations
```

This exposes a lot of things, but none of the `do*` methods (aside from `doAnswer` which is defined in `MockitoStubs`) -- is there any reason it's not part of the `Mockito` trait?

**Comment by etorreborre** [comment]
This is a good question. After looking at the git history and even going back to the original `specs` project I think that this is just a miss. I am going to add back this trait to the `Mockito` trait.

**Comment by kflorence** [comment]
Thanks @etorreborre!
