### ISSUE TITLE
MockitoMatchers is missing a lot of Mockito.Matchers

### ISSUE THREAD

**Issue by kflorence** [etorreborre/specs2#355]
https://github.com/etorreborre/specs2/blob/master/mock/src/main/scala/org/specs2/mock/mockito/MockitoMatchers.scala

This defines some of the `any*` matchers that are defined in Mockito, but it's missing a lot of them (such as `anyBoolean`) -- any reasoning behind this? I would suggest having them all referenced here since otherwise you have to import Mockito.Matchers yourself and you get annoying errors in your test suites because you get a mix of methods with and without parenthesis (ie: `anyString` vs `anyBoolean()`).

**Comment by etorreborre** [comment]
I agree that `anyBoolean` is missing but I'm not sure about adding the other methods which seem to be related to Java classes like `List`, `Set` or `Map`. I would probably have to name that as `anyJavaList`,... to avoid ambiguity with Scala's `List` and then add `anyList` as `any(classOf[List])`.

**Comment by kflorence** [comment]
@etorreborre that sounds like a fair compromise.
