### ISSUE TITLE
Link to examples page on the Specs2 website is broken

### ISSUE THREAD

**Issue by Kevin-Lee** [etorreborre/specs2#357]
[The link to the examples page](https://github.com/etorreborre/specs2/tree/SPECS2-3.4/examples/src/test/scala/examples) on the [Specs2 website](http://specs2.org/) is broken. It's currently redirecting to https://github.com/etorreborre/specs2/tree/SPECS2-3.4/examples/src/test/scala/examples which turns into `404`. I think it's because the tag [SPECS2-3.4](https://github.com/etorreborre/specs2/tree/SPECS2-3.4) does not exist (or not just yet?).

**Comment by etorreborre** [comment]
The tag wasn't push I guess because the Sonatype release failed in between the release process. I'm out for 4 days but I'll fix that when I come back, thanks.

**Comment by Kevin-Lee** [comment]
@etorreborre OK, so "not just yet" part was correct. :smile:
By the way, nice talk yesterday. Thanks. :+1:

**Comment by etorreborre** [comment]
Fixed now, thanks for reporting.

**Comment by Kevin-Lee** [comment]
@etorreborre Thanks Eric. :+1:
