### ISSUE TITLE
Companion objects for traits

### ISSUE THREAD

**Issue by kflorence** [etorreborre/specs2#358]
What are your thoughts about having companion objects for some of the traits (much like [scalaTest](https://github.com/scalatest/scalatest/blob/release-2.2.1-for-scala-2.11-and-2.10/src/main/scala/org/scalatest/mock/MockitoSugar.scala#L156) does for some of their Mockito classes)? I think it can be very useful in certain circumstances, for example if I want to have a trait that stubs out some mocks I can just import CompanionObject._ and then I don't have to extend another trait that provides the mocking methods I need.

**Comment by etorreborre** [comment]
I am for it and did it for many traits in the library. I'll have a look at that during this week.
