### ISSUE TITLE
Mockito "eq" matcher collides with scala.AnyRef "eq"

### ISSUE THREAD

**Issue by kflorence** [etorreborre/specs2#361]
In order to get around this in our code, we have to:

```scala
import org.mockito.Matchers.{eq => eqTo, _}
```

But it would be nice to have this functionality as part of the default set of Mockito matchers since it is a common gotcha. I can't think of a way to do it without having to add a lot of methods that delegate to the underlying java methods, though.

**Comment by etorreborre** [comment]
With the upcoming version and the fix to #355 why would you need to do an underscore import for `org.mockito.Matchers._`?

**Comment by kflorence** [comment]
You are correct, we do not need the `_` import anymore (I copy/pasted that from our local codebase, where we are not on the latest specs2 version yet) -- but we still must map `eq => eqTo`.

**Comment by etorreborre** [comment]
Sorry I don't see why you need to do that mapping? If you don't import it with `_` it shouldn't be visible at all.

**Comment by kflorence** [comment]
@etorreborre because we WANT to use `org.mockito.Matchers.eq`, but we can't because if you type "eq" it points to the `scala.AnyRef.eq` method. For example:

```scala
doReturn(foo).when(service).method(eq("test"), anyInt) // error
```

The above does not work, because `eq` = `scala.AnyRef.eq` instead of `org.mockito.Matchers.eq` -- hence why we have to import it explicitly as something else:

```scala
import org.mockito.Matchers.{eq => eqTo}
doReturn(foo).when(service).method(eqTo("test"), anyInt) // works!
```

It is the same as the problem mentioned here: https://lizdouglass.wordpress.com/2010/12/15/using-mockito-in-a-scala-unit-test/

**Comment by etorreborre** [comment]
I don't think you need Mockito's `eq`. Since you want to do equality matching you can do that directly with a specs2 matcher
```scala
trait Test {
   def method(s: String, s2: String)
}
val t = mock[Test]
t.method("test", "test2")

there was one(t).method(===("test"), ===("test2"))
```

And you can do things like
```scala
trait Test {
   def method(i: Int)
}
val t = mock[Test]
t.method(3)

there was one(t).method(be_>=(1))
```

**Comment by kflorence** [comment]
@etorreborre I will try that out, although it seems odd to me that I can use all the other Mockito matchers, but I can't use `eq`.

**Comment by etorreborre** [comment]
The idea is that you should have a lot more flexibility with specs2 matchers so that there should be no need to use Mockito matchers at all in your specification.

**Comment by etorreborre** [comment]
I'm closing this issue for now, the idea being that you should be using specs2 matchers instead of Mockito's matchers when using Mockito in specs2.

**Comment by RichardBradley** [comment]
I had the same problem. I only just found this thread.

I didn't realise that the specs2 matches could be used in place of the Mockito matchers via the ArgThat implicit converter.

There isn't a specs2 matcher for "any", is there?

I now have a mix of Mockito and Specs2 matchers when setting up stubs:

    myMock.process(any, ===(3)) returns "example"

I can't use the "equalTo" or "beEqualTo" matcher in the above example, as it's untyped. I have to use "beTypedEqualTo" if I want a non-symbolic alternative to "eq"

    myMock.process(any, beTypedEqualTo(3)) returns "example"

This is quite a bit uglier than the Mockito version:

    myMock.process(any, eq(3)) returns "example"

I think I might still use kflorence's trick and import `org.mockito.Matchers.{eq => eqTo}` (until now, I've been using `Matchers.eq`)

**Comment by etorreborre** [comment]
You can use `any[T]` or any of the specialised `anyXXX` (`anyString`, `anyBoolean`,...). 

There's otherwise not much I can do about the `eq` name :-(.

**Comment by RichardBradley** [comment]
> > There isn't a specs2 matcher for "any", is there?
> You can use any[T] or any of the specialised anyXXX (anyString, anyBoolean,...).

Sorry, you're right. The "any" matcher in my stubs is from Specs2:

    myMock.process(any, ===(3)) returns "example"
    myMock.process(any, typedEqualTo(3)) returns "example"

My only complaint is that there isn't an "eq" matcher which is both not-symbolic and not too long.

Why is the "equalTo" / "beEqualTo" matcher untyped? I suppose that can't be changed now for BC reasons.

**Comment by etorreborre** [comment]
The "historical" reason is that they are matching the `==(a: Any)` type signature in Scala.

**Comment by mcintyre94** [comment]
This would be a nice to have with the new `argThat` when verifying mocks, because using that requires a matcher to be used for all other arguments and I don't think a specs2 matcher will do the same (unless I can pull out all invocations from the Mockito mock and verify them manually with specs2 matchers?)

eg. 
` verify(mockApi).bulkCreate(argThat((nots: Traversable[Notification]) => NotificationProjection.from(nots.toSet.head).equals(expectedNotification)), >>>eq(None)<<<`

**Comment by etorreborre** [comment]
I am not sure what you are proposing (or actually what's the exact problem :-)). Do you want to sketch out a PR for your proposal?

**Comment by jsatk** [comment]
I also just ran into this mess. Thanks for typing up a solution. Would be nice to have Mockito not collide with base Scala library methods.

**Comment by kflorence** [comment]
To follow up on this, we now use https://github.com/mockito/mockito-scala which has solved this problem already.

**Comment by jsatk** [comment]
> To follow up on this, we now use https://github.com/mockito/mockito-scala which has solved this problem already.

Yeah. After digging further I realized the repo I was working in had this and just had to figure out that `eqTo` was the Mockito-scala version of `eq`.
