### ISSUE TITLE
Document per testcase timeout

### ISSUE THREAD

**Issue by pathikrit** [etorreborre/specs2#362]
I am on specs2 3.4 and I did look at [this](https://github.com/etorreborre/specs2/commits/dd57990c8a769347096dd5d2f87a1dbac07b1f69/matcher-extra/src/main/scala/org/specs2/specification/ExamplesTimeout.scala) and it was entirely not obvious how to use it:

* [ ] First I could not find it at all. Then, I realized, I have to add an extra dependency to bring it in:
`"org.specs2" %% "specs2-matcher-extra" % "3.4" % "test"`

* [ ] Then after I added `extends mutable.Specification with specification.ExamplesTimeout`, it was entirely not obvious, how to use it? Do I put it around each `should` block or each test case? I was expecting it to be something like this:

```
upTo(3.second) (someSlowFunc("hello") mustEqual "world")
```

Instead, it appears to be at a global level for all examples in a spec and not configurable per example??

* [ ] After, I did that, I got a run-time error saying no implicit java executor service (not the Scala's execution context!) is missing! At this point I gave up... 

Why can't this be as simple junit's timeout annotation or even more Scala like:

```scala
someSlowFunc("hello") mustEqual "world" inAtmost n.second
```

?

**Comment by pathikrit** [comment]
Here's a no-brainer way of doing it in ScalaTest: http://doc.scalatest.org/2.0/index.html#org.scalatest.concurrent.Timeouts

**Comment by etorreborre** [comment]
Checkout the documentation [here](https://etorreborre.github.io/specs2/guide/SPECS2-3.4-20150416001459-48da756/org.specs2.guide.TimeoutExamples.html) (the code has slightly changed as well).

**Comment by mahmoudhanafy** [comment]
I have a question regarding this. 
I tried the `ExamplesTimeout`, but I found the timed out tests were `skipped`. I need to fail tests which timeout, so I can know that there is a problem.
is there a way to achieve this?

**Comment by etorreborre** [comment]
@mahmoudhanafy you can either take some inspiration from the `ExamplesTimeout` code and write your own where you replace `orSkip` with `orFail`. Or you can transform all the timedout `Skipped` results into `Failure` in your spec with
```scala
import org.specs2.specification.AroundTimeout
import scala.concurrent.duration._
import org.specs2.concurrent.ExecutionEnv
import org.specs2.execute.{AsResult, Failure, Result, Skipped}
import org.specs2.specification.AroundEach

class MySpec(implicit ee: ExecutionEnv) extends Specification with AroundTimeout with SkipAsFail { def is = s2"""

  this should not take too long ${upTo(1.second)(e1)}

"""

  def e1 = { Thread.sleep(2000); 1 + 1 === 2 }
}

trait SkipAsFail extends AroundEach {
  def around[R : AsResult](r: =>R): Result = {
    AsResult.safely(r) match {
      case Skipped(m, e)  if m contains "TIMEOUT" => Failure(m, e)
      case other => other
    }
  }
}
```
