### ISSUE TITLE
please publish a scalaz-7.0.6 version

### ISSUE THREAD

**Issue by andyczerwonka** [etorreborre/specs2#363]
I'm using 3.4-scalaz-7.0.6-20150414054958-dce2bc3 and would like to upgrade to the official version.

**Comment by etorreborre** [comment]
Here it is: https://oss.sonatype.org/content/repositories/releases/org/specs2/specs2-core_2.11/3.5-scalaz-7.0.6. I thought I had done it but apparently something went wrong with the repository release.
