### ISSUE TITLE
Warn against using Before/After/BeforeAfter of Scope with abstract classes

### ISSUE THREAD

**Issue by ittaiz** [etorreborre/specs2#365]
Hi,
I just stumbled on to these two links [SO] (http://stackoverflow.com/questions/21154941/specs2-after-method-runs-before-the-example) [Google Group] (https://groups.google.com/forum/#!searchin/specs2-users/beforeafter|sort:relevance|spell:false/specs2-users/RY0ZQbDD-d8/HvNpEDQkTuEJ) which caused me to understand it's probably not the best idea to have my `Scope` extend one of the Before/After/BeforeAfter traits and be an abstract class due to the delayedInit rewrite.
If I'm correct in my understanding I think the documentation should warn against using abstract class so that people will be more aware.
BTW, The reason I thought of using abstract classes instead of traits is for compilation after reading the [Artima] (https://www.artima.com/articles/compile_time.html) piece.
I also think that if we're touching the [Scopes] (https://etorreborre.github.io/specs2/guide/SPECS2-3.5/org.specs2.guide.Scopes.html) documentation we should also mention the BeforeAfter trait which you re-added.

**Comment by etorreborre** [comment]
Thanks for mentioning this. Note that the Artima article recommends using an abstract class instead of a trait when lots of methods are being defined:
> We did observe that the larger the number of methods to be mixed in the more the compile time was increased
I am not sure that this applies to "small" traits like `BeforeAfter`.

**Comment by ittaiz** [comment]
Thanks for the speedy reply :-)
I agree about BeforeAfter but that is mixed in to the scope which sometimes
contains more methods.
Maybe we need (internally) to rethink what goes on the Specification and
what goes on the Scope

‏בתאריך יום שני, 27 באפריל 2015, Eric Torreborre <notifications@github.com>
כתב:

**Comment by etorreborre** [comment]
Another solution is to use the `ForEach` trait and pass to each example an object containing everything you need:
```scala
class MySpec extends Specification with ForEach[MyContext] {
  "test" >> (c: MyContext) => {
     import c._
     // stuff
     ok
  }
}
```
