### ISSUE TITLE
Fragments - regression from 2.4.11

### ISSUE THREAD

**Issue by nadavwe** [etorreborre/specs2#369]
Hey Erik,
I found two problems in specs 3.6 that work fine with 2.4.11:

the following code does not compile, while in 2.4.11 it ran the expected 4 tests:
```scala
class ShouldWithFor extends mutable.Specification {
  "Should with For comprehension" should {
  val values = Seq("a", "b", "c", "d")

  for (value <- values) {
    s"$value" in {
      success
    }
  }
 }
}
```

this next example works on 3.6, but has a strange result structure, and is missing tests "c" & "d".
in 2.4.11 the dummy clause and all 4 tests run as expected.
```scala
class ShouldWithFor extends mutable.Specification {
  "a dummy" should {
    "be successful" in {
      success
    }
  }

  val values = Seq("a", "b", "c", "d")
  for (value <- values) {
    s"$value" in {
      success
    }
  }
}
```

Thanks,
Nadav

**Comment by etorreborre** [comment]
There is a mention about this in the blog post I wrote as a [migration guide](http://etorreborre.blogspot.com.au/2014/12/specs2-three.html). The reason for suppressing the possibility to use a for loop directly is that it is not possible to detect exactly your intention whereas you are iterating to create examples or results (there were a few issues posted with that problem). So, for example, your last spec should be rewritten as:
```scala
class ShouldWithFor extends mutable.Specification {
  "a dummy" should {
    "be successful" in {
      success
    }
  }

  val values = Seq("a", "b", "c", "d")
  Fragments.foreach(values) { value =>
    s"$value" in {
      success
    }
  }
}
```

**Comment by nadavwe** [comment]
Thanks! that works perfectly.
