### ISSUE TITLE
Execute examples with a specific tag sequentially

### ISSUE THREAD

**Issue by jedesah** [etorreborre/specs2#370]
I am writing a Specification for the sample code in my README file. A few of the examples interact with IO and they need to be executed sequentially in order for me to test them properly and deterministically.

I think a nice solution to this problem would be a way to express that examples with a certain tag need to be executed sequentially from each other.

Is there a better way? What do you think?

**Comment by etorreborre** [comment]
In theory it might be possible to implement something like that but I think that this would complicate a lot the execution model. If you allow examples to be reported in a different order than what you specified, you implement the following strategy:

 - tag your examples which need to be sequentially executed
 - override the `def map(fs: Fragments)` method to return a reordered list of fragments
 - your reordering function is going to be something along the way of
    - collect the tagged examples (use `DefaultSelector.filterByMarker` and pass an `include` argument to retain only your tag)
    - put all these examples after the other ones
    - put steps doing nothing before and after each of these examples

I'm sorry this is a rough sketch. I'll try to see if I can whip some working code over the week-end.

**Comment by etorreborre** [comment]
Sorry I'm finding a bit hard to find time at the moment. Did you have a go at this? Otherwise I might try next week.

**Comment by jedesah** [comment]
Unfortunately, I have not, been a little tight on time as well :p

**Comment by etorreborre** [comment]
Ok, here is a possibility:
```
import org.specs2._
import org.specs2.main.Arguments
import org.specs2.specification.core.{Env, Fragments}
import org.specs2.specification.process.DefaultSelector

/**
 * This specification shows how to create examples using the "acceptance" style
 */
class HelloWorldSpec(val env: Env) extends Specification with SequentialTags { def is = s2"""

 This is a specification to check the 'Hello world' string

 The 'Hello world' string should
   e1 $e1
   e2 $e2 $seq
   e3 $e3
   e4 $e4 $seq
   e5 $e5
                                                     """

  def e1 = { Thread.sleep(100); "executing e1".pp; ok }
  def e2 = { Thread.sleep(100); "executing e2".pp; ok }
  def e3 = { Thread.sleep(100); "executing e3".pp; ok }
  def e4 = { Thread.sleep(10);  "executing e4".pp; ok }
  def e5 = { Thread.sleep(100); "executing e5".pp; ok }

  def seq = tag(seqTag)
  def seqTag = "seq"
}

trait SequentialTags extends Specification {
  def env: Env
  def seqTag: String

  override def map(fs: =>Fragments) =
    Fragments {
      val untagged = fs.contents |> DefaultSelector.filterByMarker(env.setArguments(Arguments("exclude", seqTag)))
      val tagged   = fs.contents |> DefaultSelector.filterByMarker(env.setArguments(Arguments("include", seqTag)))
      untagged ++ p.contents ++
      tagged.flatMap(f => (f ^ step(()) ^ br).contents)
    }
}
```

It looks like it is working even if the display could be better because it is pushing all the tagged examples at the end.

**Comment by etorreborre** [comment]
Did my code eventually help or you found another solution?

**Comment by jedesah** [comment]
Hey,

To be honest I haven't had the chance to work on the project in which I
encountered this problem. So sorry to bring up a problem and then fail to
follow up on the solution.

I will be sure to let you know what comes up when I get a chance to have a
look at the problem again with fresh eyes.

Cheers!

**Comment by etorreborre** [comment]
No worries, I'll close this for now then.
