### ISSUE TITLE
Play framework + specs2 + scalacheck: 

### ISSUE THREAD

**Issue by zbeckman** [etorreborre/specs2#372]
I'm trying (desperately!) to use ScalaCheck with specs2 (in Play Framework).

When I try to add scalacheck to my dependencies, I inevitably get this:

[error] missing or invalid dependency detected while loading class file 'JUnitRunner.class'.
[error] Could not access type DefaultSelection in package org.specs2.reporter,
[error] because it (or its dependencies) are missing. Check your build definition for
[error] missing or conflicting dependencies. (Re-run with `-Ylog-classpath` to see the problematic class path.)

Any ideas on how to resolve the conflict? As far as I now, JUnit is built-in to Play, so it's not something within my control...?

**Comment by zbeckman** [comment]
Forgot to mention: Play is the latest as of May, 2015: 2.3.9.

**Comment by etorreborre** [comment]
You need to add `"org.specs2" %% "specs2-scalacheck" % "3.6"`. Which version did you try to add?

**Comment by zbeckman** [comment]
That's the one... here's the line (commented out now, but still in my build.sbt):

//	"org.specs2" %% "specs2-scalacheck" % "3.6" % "test",

Also tried without the "test" attribute.

**Comment by etorreborre** [comment]
Can I see the rest of your build file? I want to make sure that you are not mixing specs2 2.x dependencies with 3.x. `DefaultSelection` is a specs2 2.x class which is different in 3.x. So make sure that all your specs2 dependencies are either 2.4.17 or 3.6.

**Comment by zbeckman** [comment]
Here's the build file. The two commented-out lines are the (latest variation) specs2 and scalacheck lines that I've been playing with. (I've tried several different variations so far no luck...)

Removing the preamble (project name, etc.):

```lazy val root = (project in file(".")).enablePlugins(PlayJava)

scalaVersion := "2.11.6"

val playVersion = "2.3.9"

libraryDependencies ++= Seq(
	"com.typesafe.play" %% "play" % playVersion,
	"com.typesafe.slick" %% "slick" % "3.0.0",
	"log4j" % "log4j" % "1.2.16",
	"com.h2database" % "h2" % "1.3.175",
	"org.postgresql" % "postgresql" % "9.4-1201-jdbc41",
	"org.slf4j" % "slf4j-simple" % "1.6.4", // replace with -nop
//	"org.specs2" %% "specs2-core" % "3.6" % "test",
//	"org.specs2" %% "specs2-scalacheck" % "3.6" % "test",
	// These are deprecated libraries and will be refactored out of the system. These should not be actively
	// used for new development:
	javaWs,
	javaJdbc,
	jdbc,
	javaEbean,
	cache,
	javaJpa,
	"org.springframework" % "spring-context" % "4.0.3.RELEASE",
	"org.springframework" % "spring-orm" % "4.0.3.RELEASE",
	"org.springframework" % "spring-jdbc" % "4.0.3.RELEASE",
	"org.springframework" % "spring-tx" % "4.0.3.RELEASE",
	"org.hibernate" % "hibernate-entitymanager" % "4.1.9.Final",
	"org.hibernate.javax.persistence" % "hibernate-jpa-2.0-api" % "1.0.1.Final",
	"org.hibernate" % "hibernate-core" % "4.1.9.Final",
	"net.sf.flexjson" % "flexjson" % "3.1",
	"com.notnoop.apns" % "apns" % "0.2.3",
	"org.webjars" % "bootstrap" % "3.3.4"
)

scalacOptions ++= Seq( "-deprecation", "-unchecked", "-Xelide-below", "WARNING" )

fork in run := true
```

**Comment by etorreborre** [comment]
I'm sorry I actually need more than this, we need to check what are all the dependencies pulled in. Can you execute `sbt>show test:externalDependencyClasspath`?

**Comment by zbeckman** [comment]
Here you go:

[Glimpulse] $ show test:externalDependencyClasspath
[info] List(Attributed(/Users/zbeckman/Projects/Glimpulse/Server-2/project/glimpulse-server/lib/aopalliance-1.0.jar), Attributed(/Users/zbeckman/Projects/Glimpulse/Server-2/project/glimpulse-server/lib/apns-0.2.3.jar), Attributed(/Users/zbeckman/Projects/Glimpulse/Server-2/project/glimpulse-server/lib/edb-jdbc14.jar), Attributed(/Users/zbeckman/Projects/Glimpulse/Server-2/project/glimpulse-server/lib/flexjson-3.1.jar), Attributed(/Users/zbeckman/Projects/Glimpulse/Server-2/project/glimpulse-server/lib/hibernate-core-4.2.3.Final.jar), Attributed(/Users/zbeckman/Projects/Glimpulse/Server-2/project/glimpulse-server/lib/hibernate-entitymanager-4.2.3.Final.jar), Attributed(/Users/zbeckman/Projects/Glimpulse/Server-2/project/glimpulse-server/lib/javax.persistence-2.1.0.jar), Attributed(/Users/zbeckman/Projects/Glimpulse/Server-2/project/glimpulse-server/lib/json-simple-1.1.1.jar), Attributed(/Users/zbeckman/Projects/Glimpulse/Server-2/project/glimpulse-server/lib/play-java_2.10.jar), Attributed(/Users/zbeckman/Projects/Glimpulse/Server-2/project/glimpulse-server/lib/play_2.11-2.3.0.jar), Attributed(/Users/zbeckman/Projects/Glimpulse/Server-2/project/glimpulse-server/lib/postgresql-9.1-901.jdbc4.jar), Attributed(/Users/zbeckman/Projects/Glimpulse/Server-2/project/glimpulse-server/lib/spring-aop-4.0.2.RELEASE.jar), Attributed(/Users/zbeckman/Projects/Glimpulse/Server-2/project/glimpulse-server/lib/spring-beans-4.0.2.RELEASE.jar), Attributed(/Users/zbeckman/Projects/Glimpulse/Server-2/project/glimpulse-server/lib/spring-context-4.0.2.RELEASE.jar), Attributed(/Users/zbeckman/Projects/Glimpulse/Server-2/project/glimpulse-server/lib/spring-core-4.0.2.RELEASE.jar), Attributed(/Users/zbeckman/Projects/Glimpulse/Server-2/project/glimpulse-server/lib/spring-expression-4.0.2.RELEASE.jar), Attributed(/Users/zbeckman/Projects/Glimpulse/Server-2/project/glimpulse-server/lib/spring-jdbc-4.0.2.RELEASE.jar), Attributed(/Users/zbeckman/Projects/Glimpulse/Server-2/project/glimpulse-server/lib/spring-orm-4.0.2.RELEASE.jar), Attributed(/Users/zbeckman/Projects/Glimpulse/Server-2/project/glimpulse-server/lib/spring-tx-4.0.2.RELEASE.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.6.jar), Attributed(/Users/zbeckman/.ivy2/cache/com.typesafe.play/twirl-api_2.11/jars/twirl-api_2.11-1.0.2.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.apache.commons/commons-lang3/jars/commons-lang3-3.1.jar), Attributed(/Users/zbeckman/.ivy2/cache/com.typesafe.play/play_2.11/jars/play_2.11-2.3.9.jar), Attributed(/Users/zbeckman/.ivy2/cache/com.typesafe.play/build-link/jars/build-link-2.3.9.jar), Attributed(/Users/zbeckman/.ivy2/cache/com.typesafe.play/play-exceptions/jars/play-exceptions-2.3.9.jar), Attributed(/Users/zbeckman/.ivy2/cache/com.typesafe.play/play-iteratees_2.11/jars/play-iteratees_2.11-2.3.9.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.scala-stm/scala-stm_2.11/jars/scala-stm_2.11-0.7.jar), Attributed(/Users/zbeckman/.ivy2/cache/com.typesafe/config/bundles/config-1.2.1.jar), Attributed(/Users/zbeckman/.ivy2/cache/com.typesafe.play/play-json_2.11/jars/play-json_2.11-2.3.9.jar), Attributed(/Users/zbeckman/.ivy2/cache/com.typesafe.play/play-functional_2.11/jars/play-functional_2.11-2.3.9.jar), Attributed(/Users/zbeckman/.ivy2/cache/com.typesafe.play/play-datacommons_2.11/jars/play-datacommons_2.11-2.3.9.jar), Attributed(/Users/zbeckman/.ivy2/cache/joda-time/joda-time/jars/joda-time-2.3.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.joda/joda-convert/jars/joda-convert-1.6.jar), Attributed(/Users/zbeckman/.ivy2/cache/com.fasterxml.jackson.core/jackson-annotations/bundles/jackson-annotations-2.3.2.jar), Attributed(/Users/zbeckman/.ivy2/cache/com.fasterxml.jackson.core/jackson-core/bundles/jackson-core-2.3.2.jar), Attributed(/Users/zbeckman/.ivy2/cache/com.fasterxml.jackson.core/jackson-databind/bundles/jackson-databind-2.3.2.jar), Attributed(/Users/zbeckman/.ivy2/cache/io.netty/netty/bundles/netty-3.9.8.Final.jar), Attributed(/Users/zbeckman/.ivy2/cache/com.typesafe.netty/netty-http-pipelining/jars/netty-http-pipelining-1.1.2.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.slf4j/slf4j-api/jars/slf4j-api-1.7.6.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.slf4j/jul-to-slf4j/jars/jul-to-slf4j-1.7.6.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.slf4j/jcl-over-slf4j/jars/jcl-over-slf4j-1.7.6.jar), Attributed(/Users/zbeckman/.ivy2/cache/ch.qos.logback/logback-core/jars/logback-core-1.1.1.jar), Attributed(/Users/zbeckman/.ivy2/cache/ch.qos.logback/logback-classic/jars/logback-classic-1.1.1.jar), Attributed(/Users/zbeckman/.ivy2/cache/com.typesafe.akka/akka-actor_2.11/jars/akka-actor_2.11-2.3.4.jar), Attributed(/Users/zbeckman/.ivy2/cache/com.typesafe.akka/akka-slf4j_2.11/jars/akka-slf4j_2.11-2.3.4.jar), Attributed(/Users/zbeckman/.ivy2/cache/commons-codec/commons-codec/jars/commons-codec-1.9.jar), Attributed(/Users/zbeckman/.ivy2/cache/xerces/xercesImpl/jars/xercesImpl-2.11.0.jar), Attributed(/Users/zbeckman/.ivy2/cache/xml-apis/xml-apis/jars/xml-apis-1.4.01.jar), Attributed(/Users/zbeckman/.ivy2/cache/javax.transaction/jta/jars/jta-1.1.jar), Attributed(/Users/zbeckman/.ivy2/cache/com.typesafe.play/play-java_2.11/jars/play-java_2.11-2.3.9.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.yaml/snakeyaml/bundles/snakeyaml-1.13.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.hibernate/hibernate-validator/jars/hibernate-validator-5.0.3.Final.jar), Attributed(/Users/zbeckman/.ivy2/cache/javax.validation/validation-api/jars/validation-api-1.1.0.Final.jar), Attributed(/Users/zbeckman/.ivy2/cache/com.fasterxml/classmate/bundles/classmate-1.0.0.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.jboss.logging/jboss-logging/jars/jboss-logging-3.2.0.Final.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.springframework/spring-context/jars/spring-context-4.0.3.RELEASE.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.springframework/spring-aop/jars/spring-aop-4.0.3.RELEASE.jar), Attributed(/Users/zbeckman/.ivy2/cache/aopalliance/aopalliance/jars/aopalliance-1.0.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.springframework/spring-beans/jars/spring-beans-4.0.3.RELEASE.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.springframework/spring-core/jars/spring-core-4.0.3.RELEASE.jar), Attributed(/Users/zbeckman/.ivy2/cache/commons-logging/commons-logging/jars/commons-logging-1.1.3.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.springframework/spring-expression/jars/spring-expression-4.0.3.RELEASE.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.javassist/javassist/bundles/javassist-3.19.0-GA.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.reflections/reflections/jars/reflections-0.9.8.jar), Attributed(/Users/zbeckman/.ivy2/cache/com.google.guava/guava/bundles/guava-16.0.1.jar), Attributed(/Users/zbeckman/.ivy2/cache/dom4j/dom4j/jars/dom4j-1.6.1.jar), Attributed(/Users/zbeckman/.ivy2/cache/com.google.code.findbugs/jsr305/jars/jsr305-2.0.3.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.apache.tomcat/tomcat-servlet-api/jars/tomcat-servlet-api-8.0.5.jar), Attributed(/Users/zbeckman/.ivy2/cache/com.typesafe.slick/slick_2.11/bundles/slick_2.11-3.0.0.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.reactivestreams/reactive-streams/jars/reactive-streams-1.0.0.jar), Attributed(/Users/zbeckman/.ivy2/cache/log4j/log4j/bundles/log4j-1.2.16.jar), Attributed(/Users/zbeckman/.ivy2/cache/com.h2database/h2/jars/h2-1.3.175.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.postgresql/postgresql/jars/postgresql-9.4-1201-jdbc41.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.slf4j/slf4j-simple/jars/slf4j-simple-1.6.4.jar), Attributed(/Users/zbeckman/.ivy2/cache/com.typesafe.play/play-java-ws_2.11/jars/play-java-ws_2.11-2.3.9.jar), Attributed(/Users/zbeckman/.ivy2/cache/com.typesafe.play/play-ws_2.11/jars/play-ws_2.11-2.3.9.jar), Attributed(/Users/zbeckman/.ivy2/cache/com.ning/async-http-client/jars/async-http-client-1.8.15.jar), Attributed(/Users/zbeckman/.ivy2/cache/oauth.signpost/signpost-core/jars/signpost-core-1.2.1.2.jar), Attributed(/Users/zbeckman/.ivy2/cache/oauth.signpost/signpost-commonshttp4/jars/signpost-commonshttp4-1.2.1.2.jar), Attributed(/Users/zbeckman/.ivy2/cache/com.typesafe.play/play-java-jdbc_2.11/jars/play-java-jdbc_2.11-2.3.9.jar), Attributed(/Users/zbeckman/.ivy2/cache/com.typesafe.play/play-jdbc_2.11/jars/play-jdbc_2.11-2.3.9.jar), Attributed(/Users/zbeckman/.ivy2/cache/com.jolbox/bonecp/bundles/bonecp-0.8.0.RELEASE.jar), Attributed(/Users/zbeckman/.ivy2/cache/tyrex/tyrex/jars/tyrex-1.0.1.jar), Attributed(/Users/zbeckman/.ivy2/cache/com.typesafe.play/play-java-ebean_2.11/jars/play-java-ebean_2.11-2.3.9.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.avaje.ebeanorm/avaje-ebeanorm/jars/avaje-ebeanorm-3.3.4.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.avaje.ebeanorm/avaje-ebeanorm-agent/jars/avaje-ebeanorm-agent-3.2.2.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.hibernate.javax.persistence/hibernate-jpa-2.0-api/jars/hibernate-jpa-2.0-api-1.0.1.Final.jar), Attributed(/Users/zbeckman/.ivy2/cache/com.typesafe.play/play-cache_2.11/jars/play-cache_2.11-2.3.9.jar), Attributed(/Users/zbeckman/.ivy2/cache/net.sf.ehcache/ehcache-core/jars/ehcache-core-2.6.8.jar), Attributed(/Users/zbeckman/.ivy2/cache/com.typesafe.play/play-java-jpa_2.11/jars/play-java-jpa_2.11-2.3.9.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.springframework/spring-orm/jars/spring-orm-4.0.3.RELEASE.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.springframework/spring-jdbc/jars/spring-jdbc-4.0.3.RELEASE.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.springframework/spring-tx/jars/spring-tx-4.0.3.RELEASE.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.hibernate/hibernate-entitymanager/jars/hibernate-entitymanager-4.1.9.Final.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.jboss.spec.javax.transaction/jboss-transaction-api_1.1_spec/jars/jboss-transaction-api_1.1_spec-1.0.0.Final.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.hibernate/hibernate-core/jars/hibernate-core-4.1.9.Final.jar), Attributed(/Users/zbeckman/.ivy2/cache/antlr/antlr/jars/antlr-2.7.7.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.hibernate.common/hibernate-commons-annotations/jars/hibernate-commons-annotations-4.0.1.Final.jar), Attributed(/Users/zbeckman/.ivy2/cache/net.sf.flexjson/flexjson/jars/flexjson-3.1.jar), Attributed(/Users/zbeckman/.ivy2/cache/com.notnoop.apns/apns/jars/apns-0.2.3.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.webjars/bootstrap/jars/bootstrap-3.3.4.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.webjars/jquery/jars/jquery-1.11.1.jar), Attributed(/Users/zbeckman/.ivy2/cache/com.typesafe.play/play-test_2.11/jars/play-test_2.11-2.3.9.jar), Attributed(/Users/zbeckman/.ivy2/cache/junit/junit/jars/junit-4.11.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.hamcrest/hamcrest-core/jars/hamcrest-core-1.3.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.specs2/specs2-core_2.11/jars/specs2-core_2.11-3.6.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.specs2/specs2-matcher_2.11/jars/specs2-matcher_2.11-3.6.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.specs2/specs2-common_2.11/jars/specs2-common_2.11-3.6.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.scalaz/scalaz-core_2.11/bundles/scalaz-core_2.11-7.1.1.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.scala-lang.modules/scala-parser-combinators_2.11/bundles/scala-parser-combinators_2.11-1.0.2.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.scala-lang.modules/scala-xml_2.11/bundles/scala-xml_2.11-1.0.2.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.scalaz/scalaz-concurrent_2.11/bundles/scalaz-concurrent_2.11-7.1.1.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.scalaz/scalaz-effect_2.11/bundles/scalaz-effect_2.11-7.1.1.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.scalaz.stream/scalaz-stream_2.11/bundles/scalaz-stream_2.11-0.7a.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.scodec/scodec-bits_2.11/bundles/scodec-bits_2.11-1.0.6.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-2.11.6.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.specs2/specs2-junit_2.11/jars/specs2-junit_2.11-2.3.12.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.specs2/specs2-mock_2.11/jars/specs2-mock_2.11-2.3.12.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.mockito/mockito-core/jars/mockito-core-1.9.5.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.objenesis/objenesis/jars/objenesis-1.0.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.specs2/specs2-matcher-extra_2.11/jars/specs2-matcher-extra_2.11-2.3.12.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.specs2/specs2-analysis_2.11/jars/specs2-analysis_2.11-2.3.12.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.scala-lang/scala-compiler/jars/scala-compiler-2.11.0.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.specs2/classycle/jars/classycle-1.4.3.jar), Attributed(/Users/zbeckman/.ivy2/cache/com.novocode/junit-interface/jars/junit-interface-0.11-RC1.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.scala-sbt/test-interface/jars/test-interface-1.0.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.fluentlenium/fluentlenium-festassert/jars/fluentlenium-festassert-0.9.2.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.fluentlenium/fluentlenium-core/jars/fluentlenium-core-0.9.2.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.seleniumhq.selenium/selenium-java/jars/selenium-java-2.39.0.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.seleniumhq.selenium/selenium-android-driver/jars/selenium-android-driver-2.39.0.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.seleniumhq.selenium/selenium-remote-driver/jars/selenium-remote-driver-2.39.0.jar), Attributed(/Users/zbeckman/.ivy2/cache/cglib/cglib-nodep/jars/cglib-nodep-2.1_3.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.json/json/jars/json-20080701.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.seleniumhq.selenium/selenium-api/jars/selenium-api-2.39.0.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.apache.httpcomponents/httpclient/jars/httpclient-4.3.1.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.apache.httpcomponents/httpcore/jars/httpcore-4.3.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.apache.commons/commons-exec/jars/commons-exec-1.1.jar), Attributed(/Users/zbeckman/.ivy2/cache/net.java.dev.jna/jna/jars/jna-3.4.0.jar), Attributed(/Users/zbeckman/.ivy2/cache/net.java.dev.jna/platform/jars/platform-3.4.0.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.seleniumhq.selenium/selenium-chrome-driver/jars/selenium-chrome-driver-2.39.0.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.seleniumhq.selenium/selenium-htmlunit-driver/jars/selenium-htmlunit-driver-2.39.0.jar), Attributed(/Users/zbeckman/.ivy2/cache/net.sourceforge.htmlunit/htmlunit/jars/htmlunit-2.13.jar), Attributed(/Users/zbeckman/.ivy2/cache/xalan/xalan/jars/xalan-2.7.1.jar), Attributed(/Users/zbeckman/.ivy2/cache/xalan/serializer/jars/serializer-2.7.1.jar), Attributed(/Users/zbeckman/.ivy2/cache/commons-collections/commons-collections/jars/commons-collections-3.2.1.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.apache.httpcomponents/httpmime/jars/httpmime-4.3.1.jar), Attributed(/Users/zbeckman/.ivy2/cache/net.sourceforge.htmlunit/htmlunit-core-js/jars/htmlunit-core-js-2.13.jar), Attributed(/Users/zbeckman/.ivy2/cache/net.sourceforge.nekohtml/nekohtml/jars/nekohtml-1.9.19.jar), Attributed(/Users/zbeckman/.ivy2/cache/net.sourceforge.cssparser/cssparser/jars/cssparser-0.9.11.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.w3c.css/sac/jars/sac-1.3.jar), Attributed(/Users/zbeckman/.ivy2/cache/commons-io/commons-io/jars/commons-io-2.2.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.eclipse.jetty/jetty-websocket/jars/jetty-websocket-8.1.12.v20130726.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.eclipse.jetty/jetty-util/jars/jetty-util-8.1.12.v20130726.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.eclipse.jetty/jetty-io/jars/jetty-io-8.1.12.v20130726.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.eclipse.jetty/jetty-http/jars/jetty-http-8.1.12.v20130726.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.seleniumhq.selenium/selenium-firefox-driver/jars/selenium-firefox-driver-2.39.0.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.seleniumhq.selenium/selenium-ie-driver/jars/selenium-ie-driver-2.39.0.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.seleniumhq.selenium/selenium-iphone-driver/jars/selenium-iphone-driver-2.39.0.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.seleniumhq.selenium/selenium-safari-driver/jars/selenium-safari-driver-2.39.0.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.webbitserver/webbit/jars/webbit-0.4.14.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.seleniumhq.selenium/selenium-support/jars/selenium-support-2.39.0.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.easytesting/fest-assert/jars/fest-assert-1.4.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.easytesting/fest-util/jars/fest-util-1.1.6.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.specs2/specs2-scalacheck_2.11/jars/specs2-scalacheck_2.11-3.6.jar), Attributed(/Users/zbeckman/.ivy2/cache/org.scalacheck/scalacheck_2.11/jars/scalacheck_2.11-1.12.2.jar))
[success] Total time: 0 s, completed May 12, 2015 6:46:29 PM
[Glimpulse] $

**Comment by etorreborre** [comment]
So you have a mixture of `2.3.12` and `3.6` jars. I suspect that the `2.3.12` jars are being imported by your `"com.typesafe.play" %% "play" % playVersion` dependency so you can write instead `"com.typesafe.play" %% "play" % playVersion excludeAll(ExclusionRule(organization = "org.specs2"))`

and re-add the specs2 dependencies you need manually:
```
libraryDependencies ++= Seq(
  ...
    "org.specs2" %% "specs2-core" % "3.6" % "test",
    "org.specs2" %% "specs2-junit" % "3.6" % "test",
    "org.specs2" %% "specs2-scalacheck" % "3.6" % "test",
```

**Comment by zbeckman** [comment]
That resolves the conflicts (yay!) but... having some trouble understanding why the following doesn't work. This is pasted directly from the scalacheck example code (the bit about the prop, anyhow):
```
		val accountList = forAll { n: Int => (n > 0) ==> chk(n)}
		def chk(n: Int): Unit = {
			val g = new GPGlimple(n, true, true)
			g.accountId mustEqual n
			g.id must beNone
			g.created must beNone
			g.layers must beNone
			g.version must beEqualTo(GPGlimpleModelMeta.version)
		}
		accountList.check
```
This is made more difficult because Intellij does not seem to understand ScalaCheck (it is giving code highlight errors and fails on autocompletion). But, when I compile, I get different results. So I'm not 100% sure if I'm just not understanding ScalaCheck (read the docs... several times... still confused) or if there is still some kind of conflict going on.

We use specs2 unit specification (not acceptance specifications). But I don't think that should be a problem...?

For the above, I'm getting:
[error] /Users/zbeckman/Projects/Glimpulse/Server-2/project/glimpulse-server/test/models/TestGlimpleModel.scala:39: type mismatch;
[error]  found   : Unit
[error]  required: org.scalacheck.Prop
[error] 		val accountList = forAll { n: Int => (n > 0) ==> chk(n)}

Another example: I'm using Testing In Scala as a reference, but this example from the book:
```
import org.specs2.ScalaCheck
import org.specs2.mutable.Specification
import org.scalacheck.Prop._
import org.scalacheck.{Arbitrary, Gen, Prop}

class TestClass extends Specification with ScalaCheck {

	"Using Specs2 With ScalaCheck".title ^
		"Can be used with the check method" ! usePlainCheck

	def usePlainCheck = check((x: Int, y: Int) => {
		(x + y) must be_==(y + x)
	})
}
```
Gives the following error at compile time:

[error] /Users/zbeckman/Projects/Glimpulse/Server-2/project/glimpulse-server/test/models/TestClass.scala:14: not enough arguments for method check: (prop: org.scalacheck.Prop, parameters: org.specs2.scalacheck.Parameters, prettyFreqMap: org.scalacheck.util.FreqMap[Set[Any]] => org.scalacheck.util.Pretty)org.specs2.execute.Result.
[error] Unspecified value parameters parameters, prettyFreqMap.
[error] 	def usePlainCheck = check((x: Int, y: Int) => {

**Comment by etorreborre** [comment]
First `check` was used before and has been deprecated for a couple of releases in favor of `prop`. That's the trouble with books, they don't get updated as easily as the code....

Then for the failure, you need to know that when ScalaCheck founds a counter-example, it then tries to "shrink" it, to make it smaller. In that case it found a value that was failing, `-1182321668`, the "ORIGINAL" value and then found a smaller one also failing `0`. This is why you get this failure message.

**Comment by zbeckman** [comment]
Ahhh... OK. Tricky but makes sense. ;-) Thank you!

**Comment by zbeckman** [comment]
Another question has come up… since prop is the preferred method. Does this imply that forAll is also deprecated? I was looking for a way to pass a generator to prop and couldn't see anything... most of the examples I see still talk about check, forAll, etc.

**Comment by etorreborre** [comment]
The [User Guide](https://etorreborre.github.io/specs2/guide/SPECS2-3.6/org.specs2.guide.UseScalaCheck.html) is your friend here. For example:
```
def ex1 = prop((s: String) => s must contain("a") or contain("b")).setGen(abStringGen)
```

**Comment by zbeckman** [comment]
Oh my. This is much better – I was using a very outdated online reference. Thanks.

One thing the User Guide doesn't answer: How to generate additional output in the test. For instance, I'd like to show something like:

[info] The invite service should
[info]   + serialize an invite request to/from JSON
[info]      JSON is: {...bleah...} // this does not seem to be supported by specs2...?

**Comment by etorreborre** [comment]
There is a not well known method called `updateExpected` on `Result`. You can use it to display additional information in case of a success:
```
  import org.specs2.execute._
  AsResult(1 must_== 1).updateExpected("tested with 1")
```

**Comment by zbeckman** [comment]
Thanks. Very handy. Recommend adding it to the widely used docs because mixing "println" into the code is just... meh.

**Comment by etorreborre** [comment]
I'm not too happy about this part of the API because it is a bit contrived, but yes I add this to the "How To" section. I'm closing this issue for now.
