### ISSUE TITLE
Reinstate removed links to guide.

### ISSUE THREAD

**Issue by jroper** [etorreborre/specs2#374]
This commit:

f22544d3761b98886ef56cccfc725e9e038ac53f

broke all the links to the specs guide in the following Play documentation:

https://playframework.com/documentation/2.3.0/ScalaTestingWithSpecs2
https://playframework.com/documentation/2.3.1/ScalaTestingWithSpecs2
https://playframework.com/documentation/2.3.2/ScalaTestingWithSpecs2
https://playframework.com/documentation/2.3.3/ScalaTestingWithSpecs2
https://playframework.com/documentation/2.3.4/ScalaTestingWithSpecs2
https://playframework.com/documentation/2.3.5/ScalaTestingWithSpecs2
https://playframework.com/documentation/2.3.6/ScalaTestingWithSpecs2
https://playframework.com/documentation/2.3.7/ScalaTestingWithSpecs2
https://playframework.com/documentation/2.3.8/ScalaTestingWithSpecs2
https://playframework.com/documentation/2.3.9/ScalaTestingWithSpecs2
https://playframework.com/documentation/2.3.x/ScalaTestingWithSpecs2
https://playframework.com/documentation/2.2.4/ScalaTestingWithSpecs2
https://playframework.com/documentation/2.2.5/ScalaTestingWithSpecs2
https://playframework.com/documentation/2.2.6/ScalaTestingWithSpecs2
https://playframework.com/documentation/2.2.x/ScalaTestingWithSpecs2

Would you be able to reinstate the versionless pages of the guide?  We can update the links in the latest version of our docs, but it would be nice if we didn't have to update all the historical versions in order to keep the links up to date.

This issue is exacerbated by the fact that there is now no sensible version of the docs for us to link to, Play 2.3 uses Specs 2.3 (which was the latest version when Play 2.3 was released), and the oldest that the docs go back to is 2.4, it seems odd linking to a URL that contains the 2.4 version when the version that Play is on is 2.3.  Upgrading specs to 2.4 on stable branches is not an option, since we maintain strict binary compatibility guarantees on our stable branches, and though I'm not sure whether 2.4 is binary compatible with 2.3, experience of other specs upgrades says otherwise.

**Comment by etorreborre** [comment]
I can create some versionless pages but the links are still to be slightly wrong because some headers have changed. Maybe it would be better if I re-created the 2.3 documentation and placed it under a SPECS2-2.3 tag? And do that for each precise specs2 version you want to link to?

**Comment by jroper** [comment]
A SPECS2-2.3 tag would be great, if that's not too much hassle. Play 2.2 uses specs 2.1, if it's also straight forward to regenerate the 2.1 documentation, that would be great too.

**Comment by etorreborre** [comment]
As you can see in the commit I've uploaded the user guide for 2.2 and 2.3.9 (latest version in the 2.3.x series).

**Comment by jroper** [comment]
Thanks @etorreborre!
