### ISSUE TITLE
error while loading Action, class file '/home/nyxos/.ivy2/cache/org.specs2/specs2_2.11/jars/specs2_2.11-2.3.13.jar(org/specs2/specification/Action.class)' is broken

### ISSUE THREAD

**Issue by axaluss** [etorreborre/specs2#376]
java:

    $ java -version
        java version "1.7.0_80"
        Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
        Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)

build.sbt

    scalaVersion := "2.11.6" //also with 2.11.5
    
    libraryDependencies ++= Seq( "org.specs2" %% "specs2-core" % "3.6" % "provided")

SBT:

    sbt> test

result: 

    [info] Compiling 1 Scala source to /home/nyxos/IdeaProjects/IsItWorthTheTime/backend/target/scala-2.11/test-classes...
    java.lang.ClassCastException
    [error] error while loading Step, class file '/home/nyxos/.ivy2/cache/org.specs2/specs2_2.11/jars/specs2_2.11-2.3.13.jar(org/specs2/specification/Step.class)' is broken
    [error] (class java.lang.RuntimeException/error reading Scala signature of Step.class: null)
    java.lang.ClassCastException
    [error] error while loading Action, class file '/home/nyxos/.ivy2/cache/org.specs2/specs2_2.11/jars/specs2_2.11-2.3.13.jar(org/specs2/specification/Action.class)' is broken
    [error] (class java.lang.RuntimeException/error reading Scala signature of Action.class: null)
    [error] two errors found
    [error] (easytime/test:compile) Compilation failed

**Comment by etorreborre** [comment]
You have a mix of specs2 2.3.13 jars and 3.6, but they are binary incompatible. You should just have 3.6 dependencies (if you want the most recent version of specs2).
