### ISSUE TITLE
Version conflict with org.scalamacros#quasiquotes_2.10

### ISSUE THREAD

**Issue by 2rs2ts** [etorreborre/specs2#379]
Currently specs2 depends on shapeless 2.1.0, which depends on quasiquotes 2.0.0. But in 2.10 builds specs2 itself depends on a conflicting version of quasiquotes: 2.0.1.

```
[error] (cascade-http/*:update) org.apache.ivy.plugins.conflict.StrictConflictException: org.scalamacros#quasiquotes_2.10;2.0.0 (needed by [com.chuusai#shapeless_2.10.4;2.1.0, com.chuusai#shapeless_2.10.4;2.1.0, com.chuusai#shapeless_2.10.4;2.1.0]) conflicts with org.scalamacros#quasiquotes_2.10;2.0.1 (needed by [org.specs2#specs2-common_2.10;3.6, org.specs2#specs2-core_2.10;3.6])
```

**Comment by etorreborre** [comment]
Maybe you can exclude the quasiquote dependency from specs2 when you add it to your dependencies?
```
libraryDependencies += "org.specs2" %% "specs2-core" % "3.6" excludeAll(ExclusionRule(organisation = "com.chuusai"))
```

**Comment by 2rs2ts** [comment]
@etorreborre My project ([cascade](https://github.com/paypal/cascade)) is multi-part and does not depend on a shapeless dependency in all of its subprojects. So if I exclude quasiquotes from specs2 then cascade will not compile in any subproject which does not include a shapeless dependency (and rightfully so.)

If I exclude quasiquotes from all dependencies which depend on it, and add a direct dependency, then I get this compilation error:

```
[error] /Users/angarrett/src/cascade/http/src/test/scala/com/paypal/cascade/http/tests/resource/ResourceServiceSpecs.scala:64: could not find implicit value for evidence parameter of type org.specs2.execute.AsResult[spray.routing.Directive[shapeless.HNil]]
[error]     path("ping") {
[error]         ^
[error] one error found
[error] (cascade-http/test:compileIncremental) Compilation failed
```

[Here's the line in question](https://github.com/paypal/cascade/blob/develop/http/src/test/scala/com/paypal/cascade/http/tests/resource/ResourceServiceSpecs.scala#L64). This also happens if I add quasiquotes (either version) to `dependencyOverrides`. I have been wholly unable to fix this.

This is not critical for us as we are dropping 2.10 support in cascade anyway. I thought I would just report this because it will cause problems for anyone using strict conflict resolution. I realize you [explicitly bumped the version](https://github.com/etorreborre/specs2/commit/8775233dc6bf7ff17daaf925660a961eb71b6e4e) so I'm sure you had a good reason to, but if it caused mayhem for us then it is probably causing mayhem for others.

**Comment by etorreborre** [comment]
I am closing this issue for now, please someone reopen if this is still a problem.
