### ISSUE TITLE
java.lang.Error not caught in Specification

### ISSUE THREAD

**Issue by nargov** [etorreborre/specs2#380]
Hi Eric,

I was wondering whether this is on purpose or not. I encountered it while using JMock in specs2.
Apparently, JMock throws a `java.lang.Error` when the assertions aren't satisfied.

In specs2 2.x.x, this worked since I imagine the specification caught `Throwable`, but now it crashes the framework.

Is this intended, in which case I should protect myself from these kind of errors, or is this a bug?

Here's a test that blows up:

```scala
class ErrorTest extends Specification{
  "Specs2 should handle thrown Errors" >> {
    throw new Error("Something bad happened!")
    success
  }
}
```

**Comment by etorreborre** [comment]
When I had a new look over what to consider specs2 `Errors` I ruled out `java.lang.Error` because the doc says:
```
 * An {@code Error} is a subclass of {@code Throwable}
 * that indicates serious problems that a reasonable application
 * should not try to catch. Most such errors are abnormal conditions.
```
And indeed an OOME is more than just a user exception.

I think it is unfortunate that JMock throws an Error but I think you can get around it with the following trait:
```
trait JMockAround extends AroundExample {
  def around[R : AsResult](r: =>R): Result = 
    try AsResult(r)
    catch { case t: Throwable => org.specs2.execute.Error(t) }
}
```

**Comment by nargov** [comment]
I agree it is a bit of a curious decision, I think they did it because JUnit follows the same convention.

Thanks for the help!

**Comment by etorreborre** [comment]
JUnit is slightly different because it throws `AssertionErrors`. So I was able to make a special case for it in specs2.
