### ISSUE TITLE
Crazy RFE: Easily Single Out Test Case

### ISSUE THREAD

**Issue by djspiewak** [etorreborre/specs2#381]
By far, the most common thing I do with specs (aside from writing tests) is try to debug things with the tests I've written.  And by far the most common first step in that debugging is to single out a *particular* test that I want to run, with none of the others running.  This is generally for two reasons:

- Turnaround time on changes (so I don't have to wait for an entire specification)
- Side-effect based tracing noise (so I don't have to see all the "spurious" successes)

A quick example of this:

```scala
"my thingy" should {
  "be exciting" in {
    // stuff
  }

  "be awesome" in {
    // more stuff
  }

  "be froody" in {
    // things
  }
}
```

Imagine that the "be awesome" spec is failing, but the other two are passing.  My most common response to this is to comment out the other two tests, and then go to work on being awesome.  What I *want* is to be able to do something like this:

```scala
"my thingy" should {
  "be exciting" in {
    // stuff
  }

  "be awesome" in {
    // more stuff
  }.solo

  "be froody" in {
    // things
  }
}
```

(or similar; syntax TBD)

This would result in all other tests in the specification (and potentially other `should` specifications in the same file) being skipped and *just* the "be awesome" test running.  Is this doable?

**Comment by etorreborre** [comment]
There are already 3 different ways to do this:

 1. pass the name of the example on the command line

    `sbt> testOnly *MySpec -- ex awesome`

 2. just re-run failed tests
     `// can be extended to other statuses like errors !, skipped o,...`
     `sbt> testOnly *MySpec -- was x`

 3. use a tag
```
tag ("x")
"be awesome" in {
    
}

sbt> testOnly *MySpec -- include x
```

You can find more information on how to select examples in the [User Guide](https://etorreborre.github.io/specs2/guide/SPECS2-3.6/org.specs2.guide.Selection.html).

**Comment by djspiewak** [comment]
I guess checking the documentation works too…  ;-)

**Comment by etorreborre** [comment]
Yes, something like `was x` is not very well know and can be particularly useful. I also enjoyed (no harm in appreciating one's work :-)) using `sections` to select a bunch of examples all at once, then "slide" the section to the next bunch of examples.
