### ISSUE TITLE
BeforeAfterAll adds steps without names 

### ISSUE THREAD

**Issue by sneftin** [etorreborre/specs2#385]
Use case: we are writing a base for set of our tests. The base extends Specification and BeforeAfterAll to setup an environment and  our customers will extend it. 
In implementation of BeforeAfterAll there is s a prepending and appending of steps, but with empty names. So each of our users will have these confusing steps.
It is possible to provide a name for beforeAll and afterAll steps?

**Comment by etorreborre** [comment]
What you can do is to use 2 `Examples` instead:

```
trait BeforeAfterAll2 extends SpecificationStructure with FragmentsFactory {
  def beforeAll(): Unit
  def afterAll(): Unit
  override def map(fs: =>core.Fragments) = super.map(fs).
    prepend(fragmentFactory.example("before", { beforeAll; Success() } )).
    prepend(fragmentFactory.step(()).
    append(fragmentFactory.step(()).
    append(fragmentFactory.example("after", { afterAll; Success() }))
}
```

This will display the setup/teardown "steps" with `+ before` and `+ after`.

If you don't want the `+` decoration and just some text you can go with:
```
trait BeforeAfterAll3 extends SpecificationStructure with FragmentsFactory {
  def beforeAll(): Unit
  def afterAll(): Unit
  override def map(fs: =>core.Fragments) = super.map(fs).
    prepend(fragmentFactory.text("before")).
    prepend(fragmentFactory.step(beforeAll).
    append(fragmentFactory.text("after").
    append(fragmentFactory.step(afterAll))
}
```

**Comment by sneftin** [comment]
Thanks for quick reply. 
We consider such an option but didn't want to copy/paste your implementation, which is risky since breakable.
This is why i inserted an issue. So if no plans to support it out of the box in near future, we will reconsider the risks.
What do you think?

**Comment by etorreborre** [comment]
My implementation is just packaging up something which is considered "public API": the `map` method on `SpecificationStructure`. You don't even have to expose the `beforeAll`/`afterAll` methods to the users of your trait. This way of doing things was actually *the* way in specs2 < 3.0 but before all / after all is such a common scenario that I created a special trait for it.

**Comment by sneftin** [comment]
Didn't know regarding publicity of the api.
Closing.
