### ISSUE TITLE
Check Maven Repo, almost empty Jars from Version 3 on

### ISSUE THREAD

**Issue by wir33658** [etorreborre/specs2#392]
Hi,

check http://mvnrepository.com/artifact/org.specs2/specs2_2.11 from Version 3 on. Those Jars are almost empty !!!

I guess there is something wrong.

**Comment by etorreborre** [comment]
That is to be expected. You should now use specific jars like `specs2-core` and add jars depending on the functionalities you need. See [here](https://etorreborre.github.io/specs2/guide/SPECS2-3.6.2/org.specs2.guide.Installation.html#other-dependencies).
