### ISSUE TITLE
ThrownExpectations does not throw errors for using functions that returns `Result`.

### ISSUE THREAD

**Issue by stephanh** [etorreborre/specs2#396]
I'm not sure if I am making a mistake here or if this is a bug. In the below code the second test passes even though I expect it to fail.

```scala
import org.specs2.Specification
import org.specs2.execute.Result
import org.specs2.matcher.ThrownExpectations
import org.specs2.matcher.MustMatchers._

object Other extends ThrownExpectations {
  def other: Result = {
    3 must_== 2
  }
}

class Test extends Specification with ThrownExpectations { override def is = s2"""
  other fails $test1
  test works  $test2
  """

  def test1 = Other.other

  def test2 = {
    Other.other
    2 must_== 2
  }
}
```

https://github.com/CommBank/specs-problem has a small project that reproduces the test case.

**Comment by etorreborre** [comment]
Hi Stephan,

Yes this is expected. The expression `3 must_== 2` will only throw exceptions if you extend `MustThrownExpectations`, which "wires" `ThrownExpectations` to the `must` syntax. If you just extend `ThrownExpectations` then `must` expressions are pure.

**Comment by stephanh** [comment]
Thank you Eric.
