### ISSUE TITLE
Not a git repository

### ISSUE THREAD

**Issue by JayChandler** [etorreborre/specs2#397]
When i try to build the latest master branch with sbt i get this weird error. What does it mean and how to fix it ?

![sbt-err](https://cloud.githubusercontent.com/assets/6359575/8850140/bcec44d2-3145-11e5-952f-96e5e17190ab.PNG)

**Comment by etorreborre** [comment]
There is a plugin, `promulgate`, which creates some `BuildInfo` classes, used to track the version + last commit of the code. If you start sbt in a directory having no git repository it won't be able to access the latest commit and will fail. Just do a `git init` in your directory and it should be fine (a `git clone` of the repo should work as well.

**Comment by JayChandler** [comment]
Ok this is done now it says "BAD default revision HEAD"

**Comment by etorreborre** [comment]
Sorry you also need to add a first commit.

**Comment by JayChandler** [comment]
Maybe add this to the install instructions ? Other people will have that problem too!

**Comment by etorreborre** [comment]
I would expect people to clone the git repository, can I ask what led you to a situation where you didn't have one?

**Comment by JayChandler** [comment]
I just downloaded the sources in zip format, extracted them to a folder, switched to that folder and run sbt. Saw no need or a description why i had to init a git repo or do a commit. Maybe i got i wrong but it was not clear to me. Sorry

**Comment by etorreborre** [comment]
I see. I am going to see if I can fix that in the promulgate plugin directly. There's no reason for the plugin to interfere if you just want to build.

**Comment by JayChandler** [comment]
The thing i wanted to do was  just to generate the binary for using it in my scala IDE. I am not using sbt so i needed to reference it from my IDE. That was my approach. But thx for helping me out.

**Comment by etorreborre** [comment]
I fixed the plugin so this will not happen if you build from master now.
