### ISSUE TITLE
Release for 2.12.0-M*

### ISSUE THREAD

**Issue by djspiewak** [etorreborre/specs2#399]
Put me down as interested in this!  Also the irony of me filing this ticket, given the massive delay on the corresponding ticket for scalaz-stream, is not lost on me.  :-D

**Comment by etorreborre** [comment]
I was planning to have a go at it this week-end but it might be harder than expected. I get errors like:
```
../specs2/specs2/common/src/main/scala/org/specs2/execute/ResultExceptions.scala:34: object package is not a member of package org.specs2.execute
[error] case class MyClass(list: List[_])
                                      ^
```

I don't know yet if this is an issue that is fixed in 2.12.0-M2 but if you had a version of scalaz-stream for M2, I'd like to test that. Thanks.

**Comment by etorreborre** [comment]
I also get this issue in a slightly different context
```
trait DifferenceFilter extends Function1[(Seq[_], Seq[_]), (Seq[_], Seq[_])]
[error] .../specs2/common/src/main/scala/org/specs2/text/ContentDifference.scala:105: object package is not a member of package org.specs2.text
```

**Comment by etorreborre** [comment]
Ok, I *need* M2: https://issues.scala-lang.org/browse/SI-9326. The ball is back in your court :-)

**Comment by djspiewak** [comment]
…and I need scodec-bits for M2.  Ball is in @mpilquist's court!

**Comment by mpilquist** [comment]
Published to Sonatype this morning -- should probably even be on central by now. :)

**Comment by djspiewak** [comment]
Hasn't synced yet, but probably will shortly then. I'll push a release as soon as I can!

**Comment by djspiewak** [comment]
@etorreborre Alright, 0.7.2/a is released for 2.12.0-M2.  Should be sync'd soon.

**Comment by etorreborre** [comment]
Thanks Daniel. I published a version [here](https://oss.sonatype.org/content/repositories/releases/org/specs2/specs2-core_2.12.0-M2/3.6.3/) ([corresponding branch](https://github.com/etorreborre/specs2/tree/topic/2.12)) but my preliminary tests are showing some deadlocking when I run all the specs in a given package. I don't have time to debug this for now but I'll try to have a look during the week.

**Comment by SethTisue** [comment]
if people have deadlocking issues, is there a simple workaround, like some setting they can change?

**Comment by etorreborre** [comment]
I wish I knew. There must be something because Travis is [all fine](https://travis-ci.org/etorreborre/specs2/jobs/72925432) with that branch.
