### ISSUE TITLE
Before After Quite Problematic - Not executed in Appropriate order and may lead to constructor not found

### ISSUE THREAD

**Issue by 99sono** [etorreborre/specs2#400]
Hi,

The before and after of Specs2 seems to be undeterministically unreliable on unit tests.

Unsing the following version:
 "org.specs2"        %% "specs2"             % "2.4.17"           % "test" withSources() withJavadoc()
-- By the way, on maven central the versions above (2.4.X) such as 3.3.1 all contain jars with absolutely nothing on them, just META-INF. 

Under this version, when a Specification class is tuned to with "BeforeAndAfter", then I've seen the following to phenomenas happen.

PROBLEM 1:
The before and after just runs at a completely wrong moment in time.
Namely, before x after runs as many times as many tests you have in the spec (OK)
But the before and after run all straight away before any spec actually executes.
This could be confirmed quite clearly by removing parallelism from the test and letting the tests run by a single thread one at a time.
In this case, I saw all the before and after calls being triggered.
And then after that the tests started running one after the other.

PROBLEM 2:
Sometimes, just because you have a before and after method the code blows up trying to find the constructore for the test class as demonstrated before. 
And in one specific case, in order to make the constructor to be found all I needed to was to comment the code withing the "before" method.

Following, I am puting a dummy test class that in my machine reproduces this behaviro.
Please see the  // Coment lines.

DUMMY TEST CLASS:

	import org.slf4j.Logger
	import org.slf4j.LoggerFactory
	import com.mongodb.casbah.Imports._
	import org.specs2.mutable.Specification
	import com.mongodb.casbah.commons.MongoDBObject
	import net.liftweb.common.{Box, Full, Empty, Failure}
	import org.specs2.mutable.BeforeAfter

	/** 
	 * 
	 */
	object DummyBeforeAndAfterTest  extends org.specs2.mutable.Specification with  org.specs2.mutable.BeforeAfter   {  
	    var testsExecuted = 0;
	    val LOGGER = LoggerFactory.getLogger(DummyBeforeAndAfterTest.getClass)     
	    // Set sequential execution
	    sequential
		   
	    "Spec1 Before And After Should Work " should {
	      "Before should run before" in { 
		testsExecuted +=1
		true must beTrue 
		}
	      "After should run after" in  { 
		testsExecuted +=1
		true must beTrue 
		}
	    }
		         
	   
	    def before { 
	      // IF THE FOLLOWING LOGGER CALL IS COMMENTED OUT
	      // specs2 is able to find the constructor and run the test but it will
	      // not call the before and after in the appropriate order. 
	      // the before and after will be run before the tests in the spec.
	      // Otherwise, if this line is not commented out the specs2 will blow up
	      // not finding the constructor
	      // LOGGER.info(s"BEFORE logic executed testsExecuted: $testsExecuted")
	    }   
	    def after { 
	      LOGGER.info(s"AFTER logic executed testsExecuted: $testsExecuted")
	    }
	}

And on the following block you will see both the log of when the test runs, where the code of the def before is commented out but the after block still logs how many times tests executed and comes out with zero. As well as the full stack trace for when the the before code is not commented out and blows up with cannot find constructor error.

		20:28:07.887 [pool-7-thread-1] INFO  p.g.mongodb.DummyBeforeAndAfterTest$ - AFTER logic executed testsExecuted: 0
		20:28:07.891 [pool-7-thread-1] INFO  p.g.mongodb.DummyBeforeAndAfterTest$ - AFTER logic executed testsExecuted: 0
		[info] DummyBeforeAndAfterTest

		error] 
		[error] Could not create an instance of pt.godin.mongodb.DummyBeforeAndAfterTest
		[error] 
		[error] java.lang.Exception: Can't find a constructor for class pt.godin.mongodb.DummyBeforeAndAfterTest
		[error] 
		[error] STACKTRACE
		[error]   org.specs2.reflect.Classes$class.tryToCreateObjectEither(Classes.scala:96)
		[error]   org.specs2.reflect.Classes$.tryToCreateObjectEither(Classes.scala:207)
		[error]   org.specs2.specification.SpecificationStructure$$anonfun$createSpecificationEither$2.apply(BaseSpecification.scala:119)
		[error]   org.specs2.specification.SpecificationStructure$$anonfun$createSpecificationEither$2.apply(BaseSpecification.scala:119)
		[error]   scala.Option.getOrElse(Option.scala:121)
		[error]   org.specs2.specification.SpecificationStructure$.createSpecificationEither(BaseSpecification.scala:119)
		[error]   org.specs2.runner.SbtRunner.org$specs2$runner$SbtRunner$$specificationRun(SbtRunner.scala:73)
		[error]   org.specs2.runner.SbtRunner$$anonfun$newTask$1$$anon$5.execute(SbtRunner.scala:59)
		[error]   sbt.TestRunner.runTest$1(TestFramework.scala:76)
		[error]   sbt.TestRunner.run(TestFramework.scala:85)
		[error]   sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
		[error]   sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
		[error]   sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:185)
		[error]   sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
		[error]   sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
		[error]   sbt.TestFunction.apply(TestFramework.scala:207)
		[error]   sbt.Tests$.sbt$Tests$$processRunnable$1(Tests.scala:239)
		[error]   sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:245)
		[error]   sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:245)
		[error]   sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
		[error]   sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
		[error]   sbt.std.Transform$$anon$4.work(System.scala:63)
		[error]   sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
		[error]   sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
		[error]   sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
		[error]   sbt.Execute.work(Execute.scala:235)
		[error]   sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
		[error]   sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
		[error]   sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
		[error]   sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
		[error]   java.util.concurrent.FutureTask.run(FutureTask.java:266)
		[error]   java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
		[error]   java.util.concurrent.FutureTask.run(FutureTask.java:266)
		[error]   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
		[error]   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
		[error]   java.lang.Thread.run(Thread.java:745)

		[info]  
		20:28:07.887 [pool-7-thread-1] INFO  p.g.mongodb.DummyBeforeAndAfterTest$ - AFTER logic executed testsExecuted: 0
		20:28:07.891 [pool-7-thread-1] INFO  p.g.mongodb.DummyBeforeAndAfterTest$ - AFTER logic executed testsExecuted: 0
		[info] DummyBeforeAndAfterTest
		[info] 
		[info] Spec1 Before And After Should Work  should
		[info] + Before should run before
		[info] + After should run after

What might be relevant here is the following additional information.
Machine: linux / ubuntu 14 LTS
JDK: java version "1.8.0_51 (sun jdk latest)
ScalaVersion: 2.11.7 (latest)

It would be nice if the releases you go on doing here would actually be uploaded to mvn central.
Release 3.3.1 which is empty in the mvn central repository seems to be in addition quite out of date with the latest release on the git hub repository.
And  it is not the most convenient to alway checkout the sources and build them from scratch.

Many thanks,
Kindest regards.

**Comment by etorreborre** [comment]
A few things here:

 - if you want to run code before and after each example you need to use the `BeforeAfterExample` trait and define a `before` and an `after` method. The `BeforeAfter` trait can be used with objects having an `apply` method and it will decorate this method with `before` and `after` behaviour.

 - there are indeed some empty `specs2-3.x` jars but this has been fixed after `3.3.1`. In the `3.x` series you are not supposed to use a mega `specs2` jar but finer grained ones starting with `specs2-core` (see [here](https://etorreborre.github.io/specs2/guide/SPECS2-3.6.3/org.specs2.guide.Installation.html#other-dependencies) for other dependencies). 

 - you should generally not use vals in the definition of your specification but `lazy vals` to avoid instantiation issues.

**Comment by 99sono** [comment]
HI There,
And many thanks for your feedback.

Concerning Bullet 1:
You are therefore saying that what the above example is missing is:
"an apply method"
And that trait 
"org.specs2.mutable.BeforeAfter"
taken from the online documentation is not correct, the one to be used is
"org.specs2.mutable.BeforeAfterExample" ?

<- Thanks for the clarifications on this point.

Concerning Bullet 2, many thanks for the clarifications provided.
I did search for an explanation on the online documentation - namely both in the Spec2 show case of examples as well as in the front page here on github. In neither case did I find a mention to either:
(a) The need of adding new resolvers to SBT or if maven centra repository should suffice
(b) The available set of artifacts that get published out
If this documentation does exist, it would be great if you could refer me to it.
Otherwise, It would be great if you could enhance either on github or on the show case documentation page such information.

Concerning point 3, thousand thanks for the tip. 

Kindest regards.

**Comment by etorreborre** [comment]
For bullet 1 I'm saying that you should basically ignore the `BeforeAfter` trait. The names are a bit different in `3.x` but the doc is [here](https://etorreborre.github.io/specs2/guide/SPECS2-3.6.3/org.specs2.guide.Contexts.html).

For bullet 2, the reference page is: https://etorreborre.github.io/specs2/guide/SPECS2-3.6.3/org.specs2.guide.Installation.html.

The page starts by saying that you need: `libraryDependencies += "org.specs2" %% "specs2-core" % "3.6.3" % "test"` and at the end of the page there is a section giving the names of the jars you might need additionally if you want more functionalities:

Name	 | Functionality
--------------| ----------------
specs2-matcher-extra |	for the optional specs2 matchers
specs2-scalacheck	| to use ScalaCheck properties in specifications
specs2-mock |	to use Mockito matchers
specs2-analysis |	to use the package dependencies matcher
specs2-gwt |	to write given/when/then specifications
specs2-html |	to export specifications as html
specs2-form |	to create html form-like specifications
specs2-junit |	to run specifications as JUnit tests

I'm sorry if that wasn't clear.

**Comment by 99sono** [comment]
Perfect :)

My mistake then, did not search deep enough.

**Comment by 99sono** [comment]
Just had the time to give a quick try to your suggestions.
org.specs2.specification.BeforeAfterEach
Worked perfectly.
