### ISSUE TITLE
Exception class not shown in stack trace

### ISSUE THREAD

**Issue by francisdb** [etorreborre/specs2#402]
Building using sbt

```java
[info] SimplifiedTaskSpec
[info]
[info] The simplified task format should
[error]   ! parse correctly
[error]    JsError.get (JsResult.scala:14)
[error] play.api.libs.json.JsError.get(JsResult.scala:14)
[error] play.api.libs.json.JsError.get(JsResult.scala:13)
...
```

It would be useful to also show the exception class, like here NoSuchElementException
Below an example of scalatest output for a similar test:

```java
[info] SimplifiedTaskSpecTest:
[info] - pop is invoked on a non-empty stack *** FAILED ***
[info]   java.util.NoSuchElementException: JsError.get
[info]   at play.api.libs.json.JsError.get(JsResult.scala:14)
[info]   at play.api.libs.json.JsError.get(JsResult.scala:13)
...
```

**Comment by etorreborre** [comment]
Can you post a small reproducible example please?

**Comment by etorreborre** [comment]
Forget about that I think I can reproduce.

**Comment by etorreborre** [comment]
Thanks for spotting this, that was indeed missing. You can find the fix available in `3.6.3-20150729103132-20c679e`.

**Comment by francisdb** [comment]
Always great to have the fix available in central so quickly :+1:

**Comment by etorreborre** [comment]
That's still being published so you have to wait a little bit :-).

**Comment by etorreborre** [comment]
Done now.

**Comment by francisdb** [comment]
I can confirm that this is fixed
