### ISSUE TITLE
Apparent regression in Specs 3.x: s2"..blah.." auto-examples not detected 

### ISSUE THREAD

**Issue by benhutchison** [etorreborre/specs2#406]
Apologies in advance, this might unfortunately be one of those hard-to-reproduce issues, because its coming from a fairly complex closed-src codebase with Scalajs and SBT multi-builds, and I dont have a minimized version. However, I figure you'd rather be aware than not, regardless..

* 90%+ of the specs in the codebase are auto-examples eg 
`s2"${EqivSet(Foo(1, "a"), Foo(1, "b")).size mustEqual 1}"`
* When run under any version of Specs 3.x, none of these auto-examples are found:
```
[info] Total for specification EqSetTest
[info] Finished in 0 ms
[info] 0 example, 0 failure, 0 error
```
* When run under specs 2.4.17, they are found:
```
[info] Total for specification EqSetTest
[info] Finished in 32 ms
[info] 5 examples, 0 failure, 0 error
```
* The codebase is an SBT multi-project build. The child build where the problem occurs is a Scalajs cross-build [http://www.scala-js.org/doc/sbt/cross-building.html], and the specs2 tests are associated with the JVM project of the cross-build (in `jvm/src/main/test`).

This is probably a fairly non-typical usage scenario for specs2. For the moment, Im pretty happy running on specs 2.4.x as my workaround.

**Comment by etorreborre** [comment]
Ok, can you try to:

 - invoke the implicit for creating an auto-example: 
```asResultIsInterpolatedFragment(s2"${EquivSet(Foo(1, "a"), Foo(1, "b")).size mustEqual 1})"``` (to check if this is implicit resolution)

 - add "regular" examples to one of the spec. Do they show up? Do they end up in the stats? (I suppose that they do, I just want to check)

 - do a print of all the fragments
```
  override def map(fs: =>Fragments) = {
    fs.fragments.foreach(println)
    fs
  }
```

**Comment by benhutchison** [comment]
1. `asResultIsInterpolatedFragment ` makes no difference.
2. Regular examples are picked up correctly.
3. When I print that fragment:
```
Fragment(Br, Execution(no run)) (StacktraceLocation(Some(TraceLocation(org/specs2/specification/core/Location.scala,Location.scala,org.specs2.specification.core.StacktraceLocation,apply$default$1,36))}))
Fragment(Br, Execution(no run)) (StacktraceLocation(Some(TraceLocation(org/specs2/specification/core/Location.scala,Location.scala,org.specs2.specification.core.StacktraceLocation,apply$default$1,36))}))
```

Hopefully that means something to you, but doesn't look to enlightening to me!

**Comment by etorreborre** [comment]
Short of firing up a debugger, it's hard for me to tell what's going on. If I could debug I would go to `S2StringContext` and see what's being returned by the `stringAndUpdatedDescriptionAndEnvFunctionIsInterpolatedFragment` method, line 163, to see what is being appended to the list of fragments.

Actually I have some another question. Are your specifications simple ones or do they extend a common trait doing some fancy stuff which would filter out the examples? What happens if you just run this spec:
```
class TestSpec extends Specification { def is = s2"""
 ${1 must_== 1}
"""
}
```

**Comment by benhutchison** [comment]
They extend `org.specs2.mutable.Specification`

I tested your your example above. It works correctly. But if I change it to `mutable`, it doesnt work correctly.

**Comment by etorreborre** [comment]
I found the issue. It was indeed an interaction between mutable specs and s2 strings (the examples were created but thrown away). You can try the fix in: [`specs2-core_2.11/3.6.4-20150813062946-0dbb642`](https://oss.sonatype.org/content/repositories/releases/org/specs2/specs2-core_2.11/3.6.4-20150813062946-0dbb642/).

**Comment by benhutchison** [comment]
Thanks Eric, fast work, without a reproducible example  :)
