### ISSUE TITLE
value equalTo is not a member of org.specs2.specification.core.Fragments

### ISSUE THREAD

**Issue by kflorence** [etorreborre/specs2#410]
For some reason `equalTo` is failing to work for Strings, is this expected?
`result.id` is type `Int` and `result.uid` is type `String`
This is with Scala 2.11.x and Specs2 3.6.4

<img width="1025" alt="screen shot 2015-09-01 at 5 30 11 pm" src="https://cloud.githubusercontent.com/assets/156143/9620480/6f2a533e-50cf-11e5-95fe-7e40aba174ec.png">

**Comment by kflorence** [comment]
Obvious workaround for now is to use `result.uid should equalTo(uid)`

**Comment by etorreborre** [comment]
This doesn't compile because `should` is overloaded in a mutable spec. It is usually used to write
```scala
class S extends mutable.Specification {
   "this" should {
      "be ok" in ok
      "be ko" in ko
   }
}
```
So if you want to use `should` for expectations you need to "deactivate" this meaning. Like this:
```scala
class S extends mutable.Specification with NoShouldBlock {
  "test" >> {
    "test" should be equalTo("test")
  }
}

trait NoShouldBlock extends mutable.Specification {
  override def describe(d: String) =
    super.describe(d)
}
```

**Comment by kflorence** [comment]
@etorreborre I see. That is quite annoying, especially because it works in all cases except `String`. I guess I will use `must` instead.

Eventually it might be nice to qualify the blocks with some lead in method to prevent the greedy use of the `String` implicit, like:

```scala
spec "my spec" should {
...
}
```

`spec` could return some other type than `String` which `should` could act on.

**Comment by etorreborre** [comment]
You can do that with the `describe` method:
```
describe("test") should {
  "test" should be equalTo("test")
}
```

You still need the `NoShouldBlock` trait to remove the implicit definition for should though.

**Comment by kflorence** [comment]
@etorreborre I suppose this issue can be closed, although I think using `should` for expectations is kind of a trap without qualifying it with `describe`.

**Comment by etorreborre** [comment]
The original syntax was `should ... in ... must` but some people prefer `... >> ... >> ... should`. It's hard to accommodate everyone. At least there are ways to work around the ambiguities.

**Comment by kflorence** [comment]
@etorreborre I think this is just a documentation issue. Maybe in the matchers section it could have a note about using `should` matchers within a `should` block -- or however you think is best to document this ambiguity.

Actually I don't even see the `should` block syntax mentioned on the structure page anymore, just `>>` so maybe that is the preferable syntax now?

By the way, thanks for your help, as always.
