### ISSUE TITLE
no release for 2.12.0-M1

### ISSUE THREAD

**Issue by wookietreiber** [etorreborre/specs2#412]
Would you please publish a release targeting 2.12.0-M1?

I know there already is 2.12.0-M2 but there are use cases where people want to work with / test both 2.12.0-M1 and 2.12.0-M2.

**Comment by etorreborre** [comment]
Unfortunately I can't. There are some bugs in `2.12.0-M1` and specs2 doesn't compile with it.

**Comment by wookietreiber** [comment]
Ok, thanks for letting me know.

**Comment by julien-truffaut** [comment]
@etorreborre do you know if it is also the case for 2.12.0-M2 ?
