### ISSUE TITLE
Disable the "could not find implicit value for evidence parameter"-check

### ISSUE THREAD

**Issue by drhumlen** [etorreborre/specs2#413]
Hi

Is there a way to disable the implicit evidence value requirement? We have a lot of test helpers that execute only for the side-effecting of (maybe) throwing an exception:

```
"Create a new user" in {
  Helpers.requestTest(
    call               = routes.UsersController.create,
    input              = Json.obj(.........),
    expectedOutput     = Json.obj("id" -> 42, .........),
    expectedStatusCode = 200   // OK
  )
}
```

The testing itself is done inside `requestTest`, so there is actually no implicit parameter value visible from the outside that specs2 can "see". The return type of `requestTest` is `JsValue`, because sometimes we need the return value as input for the next test. But in order to make it compile, we have to add something like `true mustBe true` or `ok` to make specs2  understand that we didn't "forget anything". I'm assuming that is why the check is there?

So my question is: is there a way to disable the "could not find implicit value for evidence parameter"-check, e.g. by import something special or mixing in some trait in our specification classes? It kinda clutters up our code to have `true mustBe true` at the end of every single test ;)    

(I know we aren't doing it particularly "functional" by relying on exception-throwing, but we already have like 10.000 tests written this way, so changing it fundamentally is a lot of hassle.)

**Comment by etorreborre** [comment]
The easy (and evil) way is to define:
```
import org.specs2.execute._
implicit def unitAsResult: AsResult[Unit] = new AsResult[Unit] {
   def asResult(u: =>Unit): Result = { u; Success() }
}

You can put this in a trait which you mix in each specification.
```
