### ISSUE TITLE
Failure's line number is not showed correctly with SpecificationLike

### ISSUE THREAD

**Issue by sdiwu** [etorreborre/specs2#415]
When using `SpecificationLike`, the failure's line number is not showed correctly. But with `Specification`, it showed correctly.

Example code with `Specification`:

	package unit.test

	import org.specs2.mutable.Specification

	class AppTest extends Specification {

		"AppTest" should {
		  "Test" in {
			println("1")
			1 === 2    // should fail at this line (this is line 10)
			println("2")
			success
		  }
		}

	}

When the test was run, the failure line number was showed correctly:

    [info] AppTest should
    [error]   x Test
    [error]    '1' is not equal to '2' (AppTest.scala:10)

But if using `SpecificationLike`:

	package unit.test

	import org.specs2.mutable.SpecificationLike

	class AppTest extends SpecificationLike {    // this is line 5

		"AppTest" should {
		  "Test" in {
			println("1")
			1 === 2    // should fail at this line (this is line 10)
			println("2")
			success
		  }
		}

	}

The line number was not correct:

    [info] AppTest should
    [error]   x Test
    [error]    '1' is not equal to '2' (AppTest.scala:5)

What is the cause of this and is there a solution?

FYI the reason I use `SpecificationLike` because I'm trying to mix akka's TestKit with Specs2. I'm following this example: https://github.com/gangstead/specs2-akka-testkit-demo/blob/master/src/test/scala/MySpec.scala

**Comment by etorreborre** [comment]
The fix is available in `specs2-core_2.11-3.6.4-20150916230958-8339115`. This is not a great fix because locations in specs2 are basically being managed by pattern matching on stacktraces :-(.

**Comment by sdiwu** [comment]
Hi, thanks for the fix.

How to get the v3.6.4-20150916230958-8339115 ? Is this fix will be available on v3.6.5 instead?

**Comment by etorreborre** [comment]
You can get it on sonatype: https://oss.sonatype.org/content/repositories/releases/org/specs2/specs2-core_2.11/3.6.4-20150916230958-8339115.

I usually push a new minor release every month or so when enough fixes / improvements have been accumulated.
