### ISSUE TITLE
TraversableOnce[String] contains matcher matches substring contents

### ISSUE THREAD

**Issue by mriehl** [etorreborre/specs2#416]
```scala
Seq("foobar") must contain("foo")
```

The above snippet works with `specs2-core` `3.6.3`. I would expect it to fail since the sequence does not, in fact, contain the string "foo".

OTOH, the following snippet fails (`List(foobar) does not contain foo but contains foobar`):

```scala
Seq("foobar") must containAllOf(Seq("foo"))
```

Is this intended?

**Comment by etorreborre** [comment]
Sorry for the delay in my answer I had some family matters to attend. This issue is the result of an abusive implicit definition which allowed to reuse the `contain` matcher defined for strings (`"foobar" must contain("foo")`.

**Comment by etorreborre** [comment]
You can test the fix with `specs2-core_2.11-3.6.4-20150923164409-7ac7257` if you want.

**Comment by mriehl** [comment]
No worries. We're grateful for your work on specs2, it's not like you owe us anything and especially not support.

Can't reproduce the error with the version you mentioned. Thanks for fixing it so quickly!
