### ISSUE TITLE
stopOnFail argument doesn't work

### ISSUE THREAD

**Issue by sdiwu** [etorreborre/specs2#418]
I found out the `stopOnFail` argument doesn't work:

    import org.specs2.mutable.Specification

    class AppTest extends Specification {
    sequential
    stopOnFail
    
      "App" should {
        "Test1" in {
          println("#### 1")
          1 === 2  // should fail at here
          success
        }
    
        "Test2" in {
          println("#### 2")
          2 === 2
          success
        }
    
        "Test3" in {
          println("#### 3")
          3 === 3
          success
        }
    
    
        "Test4" in {
          println("#### 4")
          4 === 4
          success
        }
      }
    
    }

The result I got:

    #### 1
    #### 2
    #### 3
    #### 4
    [info] AppTest
    [info]
    [info] App should
    [error]   x Test1
    [error]    '1' is not equal to '2' (AppTest.scala:12)
    [info]
    [info]   + Test2
    [info]   + Test3
    [info]   + Test4
    [info]
    [info] Total for specification AppTest
    [info] Finished in 26 ms
    [info] 4 examples, 1 failure, 0 error
    [info]

So when `Test1` failed, `Test2`, `Test3`, and `Test4` are still being run.

I remember that the `stopOnFail` used to be working on previous version (I'm not remember the version, probably v2.x).

**Comment by etorreborre** [comment]
Thanks for reporting this. I fixed this issue in `specs2-core_2.11-3.6.4-20150928232002-999c515`.
