### ISSUE TITLE
Value await is not a member of org.specs2.matcher.Matcher[Int]

### ISSUE THREAD

**Issue by zbeckman** [etorreborre/specs2#421]
Trying to await on a future does not seem to work (or, I'm doing it wrong). Example:

```
//			val list = Await.result(db.run(q), Duration.Inf).toSeq
//			list.length > 0 must beTrue

			db.run(q).map(_.length) must be_>(0).await
```
The commented lines work fine. The uncommented line results in the following error:
```
[error] /Users/zbeckman/Projects/Glimpulse/Server/project/glimpulse-server/test/models/TestPersonRelationDataModel.scala:34: value await is not a member of org.specs2.matcher.Matcher[Int]
[error] 			db.run(q).map(_.length) must be_>(0).await
```
However, `db.run()` very definitely returns a `Future`. This, for example, works fine:
```
			val x: Future[Int] = db.run(q).map(_.length)
			val y: Int = Await.result(x, Duration.Inf)
			y > 0 must beTrue
```

**Comment by etorreborre** [comment]
You need an implicit `ExecutionEnv` for the implicit class providing the `await` method to be found:
```
import org.specs2._
import org.specs2.concurrent.ExecutionEnv
import scala.concurrent._

class TestSpec(implicit ee: ExecutionEnv) extends Specification { def is = s2"""
 test $e1
"""
  def e1 = Future(1) must be_>(0).await
}
```

**Comment by zbeckman** [comment]
Awesome. Thank you! I don't think I saw this in the docs anywhere – might want to call it out (or call it out more clearly). Tried it several times... eventually got frustrated enough to complain. ;-)

**Comment by etorreborre** [comment]
There is a page in the User Guide for [execution environments](https://etorreborre.github.io/specs2/guide/SPECS2-3.6.4/org.specs2.guide.ExecutionEnvironments.html). But the guide is big and finding things is not always immediate.

**Comment by leifwickland** [comment]
Thanks for the answer, @etorreborre. I read the execution env and future matchers pages in the guide and didn't figure it out unit I saw the example above.
