### ISSUE TITLE
java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by bdrachinsky** [etorreborre/specs2#423]
I'm trying to start tests via intellij idea and sbt console then I got this and dunno what should I do.

[error]
[error] java.lang.ExceptionInInitializerError
[error]   caused by Configuration error: Configuration error[default doesn't exist]
[error]
[error] STACKTRACE
[error]   APISpec$$anonfun$11$$anonfun$apply$1$$anonfun$apply$4$$anon$3$$anonfun$9.apply(APISpec.scala:46)
[error]   APISpec$$anonfun$11$$anonfun$apply$1$$anonfun$apply$4$$anon$3$$anonfun$9.apply(APISpec.scala:46)
[error]   org.specs2.matcher.Expectable.value$lzycompute(Expectable.scala:20)
[error]   org.specs2.matcher.Expectable.value(Expectable.scala:20)
[error]   org.specs2.matcher.BeTypedEqualTo.apply(BeTypedEqualTo.scala:44)
[error]   org.specs2.matcher.Expectable.applyMatcher(Expectable.scala:50)
[error]   org.specs2.matcher.MustThrownExpectationsCreation$$anon$4.applyMatcher(MustExpectations.scala:64)
[error]   org.specs2.matcher.MatchSuccess.apply(MatchResult.scala:120)
[error]   org.specs2.matcher.NeutralMatch.apply(MatchResult.scala:184)
[error]   org.specs2.matcher.AnyBeHaveMatchers$AnyBeHaveMatchers.equalTo(AnyMatchers.scala:194)
[error]   APISpec$$anonfun$11$$anonfun$apply$1$$anonfun$apply$4$$anon$3.delayedEndpoint$APISpec$$anonfun$11$$anonfun$apply$1$$anonfun$apply$4$$anon$3$1(APISpec.scala:46)
[error]   APISpec$$anonfun$11$$anonfun$apply$1$$anonfun$apply$4$$anon$3$delayedInit$body.apply(APISpec.scala:45)
[error]   scala.Function0$class.apply$mcV$sp(Function0.scala:34)
[error]   scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
[error]   org.specs2.mutable.Around$$anonfun$delayedInit$1$$anonfun$apply$1.apply(Around.scala:15)
[error]   org.specs2.mutable.Around$$anonfun$delayedInit$1$$anonfun$apply$1.apply(Around.scala:15)
[error]   org.specs2.execute.ResultExecution$class.execute(ResultExecution.scala:25)
[error]   org.specs2.execute.ResultExecution$.execute(ResultExecution.scala:120)
[error]   org.specs2.execute.Result$$anon$10.asResult(Result.scala:230)
[error]   org.specs2.execute.AsResult$.apply(AsResult.scala:25)
[error]   org.specs2.execute.AsResult$$anonfun$effectively$1.apply(AsResult.scala:28)
[error]   org.specs2.execute.AsResult$$anonfun$effectively$1.apply(AsResult.scala:28)
[error]   org.specs2.execute.ResultExecution$class.effectively(ResultExecution.scala:41)
[error]   org.specs2.execute.ResultExecution$.effectively(ResultExecution.scala:120)
[error]   org.specs2.execute.AsResult$.effectively(AsResult.scala:28)
[error]   play.api.test.WithApplication$$anonfun$around$2.apply(Specs.scala:39)
[error]   play.api.test.WithApplication$$anonfun$around$2.apply(Specs.scala:39)
[error]   play.api.test.PlayRunners$class.running(Helpers.scala:42)
[error]   play.api.test.Helpers$.running(Helpers.scala:363)
[error]   play.api.test.WithApplication.around(Specs.scala:39)
[error]   org.specs2.mutable.Around$$anonfun$delayedInit$1.apply(Around.scala:15)
[error]   org.specs2.mutable.Around$$anonfun$delayedInit$1.apply(Around.scala:15)
[error]   org.specs2.execute.ResultExecution$class.effectively(ResultExecution.scala:41)
[error]   org.specs2.execute.ResultExecution$.effectively(ResultExecution.scala:120)
[error]   org.specs2.mutable.Around$class.delayedInit(Around.scala:15)
[error]   play.api.test.WithApplication.delayedInit(Specs.scala:36)
[error]   APISpec$$anonfun$11$$anonfun$apply$1$$anonfun$apply$4$$anon$3.<init>(APISpec.scala:45)
[error]   APISpec$$anonfun$11$$anonfun$apply$1$$anonfun$apply$4.apply(APISpec.scala:45)
[error]   APISpec$$anonfun$11$$anonfun$apply$1$$anonfun$apply$4.apply(APISpec.scala:45)
[error]   org.specs2.matcher.Scope$$anon$3$$anonfun$asResult$1.apply(ThrownExpectations.scala:139)
[error]   org.specs2.matcher.Scope$$anon$3$$anonfun$asResult$1.apply(ThrownExpectations.scala:139)
[error]   org.specs2.execute.ResultExecution$class.execute(ResultExecution.scala:25)
[error]   org.specs2.execute.ResultExecution$.execute(ResultExecution.scala:120)
[error]   org.specs2.execute.Result$$anon$10.asResult(Result.scala:230)
[error]   org.specs2.execute.AsResult$.apply(AsResult.scala:25)
[error]   org.specs2.matcher.Scope$$anon$3.asResult(ThrownExpectations.scala:139)
[error]   org.specs2.execute.AsResult$.apply(AsResult.scala:25)
[error]   org.specs2.main.CommandLineAsResult$$anon$1.asResult(CommandLineAsResult.scala:17)
[error]   org.specs2.main.CommandLineAsResult$$anonfun$apply$1.apply(CommandLineAsResult.scala:21)
[error]   org.specs2.main.CommandLineAsResult$$anonfun$apply$1.apply(CommandLineAsResult.scala:21)
[error]   org.specs2.specification.dsl.mutable.ExampleDsl1$BlockExample$$anonfun$$greater$greater$1.apply(ExampleDsl.scala:39)
[error]   org.specs2.specification.dsl.mutable.ExampleDsl1$BlockExample$$anonfun$$greater$greater$1.apply(ExampleDsl.scala:39)
[error]   org.specs2.specification.core.Execution$$anonfun$withEnv$1$$anonfun$apply$3.apply(Execution.scala:120)
[error]   org.specs2.execute.ResultExecution$class.execute(ResultExecution.scala:25)
[error]   org.specs2.execute.ResultExecution$.execute(ResultExecution.scala:120)
[error]   org.specs2.execute.Result$$anon$10.asResult(Result.scala:230)
[error]   org.specs2.execute.AsResult$.apply(AsResult.scala:25)
[error]   org.specs2.specification.core.Execution$$anonfun$withEnv$1.apply(Execution.scala:120)
[error]   org.specs2.specification.core.Execution$$anonfun$withEnv$1.apply(Execution.scala:120)
[error]   org.specs2.specification.core.Execution$$anonfun$execute$2$$anonfun$apply$2.apply(Execution.scala:70)
[error]   org.specs2.specification.core.Execution$$anonfun$execute$2$$anonfun$apply$2.apply(Execution.scala:70)
[error]   org.specs2.specification.core.Execution.setResult(Execution.scala:76)
[error]   org.specs2.specification.core.Execution$$anonfun$execute$2.apply(Execution.scala:70)
[error]   org.specs2.specification.core.Execution$$anonfun$execute$2.apply(Execution.scala:70)
[error]   scala.Option.fold(Option.scala:158)
[error]   org.specs2.specification.core.Execution.execute(Execution.scala:70)
[error]   org.specs2.specification.process.DefaultExecutor$$anonfun$executeFragment$1$$anonfun$apply$6.apply(Executor.scala:132)
[error]   org.specs2.specification.process.DefaultExecutor$$anonfun$executeFragment$1$$anonfun$apply$6.apply(Executor.scala:130)
[error]   org.specs2.specification.core.Fragment.updateExecution(Fragment.scala:44)
[error]   org.specs2.specification.process.DefaultExecutor$$anonfun$executeFragment$1.apply(Executor.scala:130)
[error]   org.specs2.specification.process.DefaultExecutor$$anonfun$executeFragment$1.apply(Executor.scala:129)
[error]   org.specs2.specification.process.DefaultExecutor$$anonfun$sequencedExecution$1.executedFragment$lzycompute$1(Executor.scala:104)
[error]   org.specs2.specification.process.DefaultExecutor$$anonfun$sequencedExecution$1.org$specs2$specification$process$DefaultExecutor$class$$anonfun$$executedFragment$1(Executor.
scala:104)
[error]   org.specs2.specification.process.DefaultExecutor$$anonfun$sequencedExecution$1$$anonfun$3.apply(Executor.scala:109)
[error]   org.specs2.specification.process.DefaultExecutor$$anonfun$sequencedExecution$1$$anonfun$3.apply(Executor.scala:109)
[error]   scalaz.concurrent.Task$$anonfun$delay$1.apply(Task.scala:272)
[error]   scalaz.concurrent.Task$$anonfun$delay$1.apply(Task.scala:272)
[error]   scalaz.concurrent.Task$$anonfun$suspend$1$$anonfun$4.apply(Task.scala:280)
[error]   scalaz.concurrent.Task$$anonfun$suspend$1$$anonfun$4.apply(Task.scala:280)
[error]   scalaz.concurrent.Task$.Try(Task.scala:385)
[error]   scalaz.concurrent.Task$$anonfun$suspend$1.apply(Task.scala:280)
[error]   scalaz.concurrent.Task$$anonfun$suspend$1.apply(Task.scala:280)
[error]   scalaz.concurrent.Future.step(Future.scala:111)
[error]   scalaz.concurrent.Future.listen(Future.scala:76)
[error]   scalaz.concurrent.Future$$anon$1$$anonfun$reduceUnordered$2$$anonfun$apply$10.apply(Future.scala:310)
[error]   scalaz.concurrent.Future$$anon$1$$anonfun$reduceUnordered$2$$anonfun$apply$10.apply(Future.scala:309)
[error]   scala.collection.Iterator$class.foreach(Iterator.scala:742)
[error]   scala.collection.AbstractIterator.foreach(Iterator.scala:1194)
[error]   scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
[error]   scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[error]   scalaz.concurrent.Future$$anon$1$$anonfun$reduceUnordered$2.apply(Future.scala:309)
[error]   scalaz.concurrent.Future$$anon$1$$anonfun$reduceUnordered$2.apply(Future.scala:305)
[error]   scalaz.concurrent.Future.listen(Future.scala:80)
[error]   scalaz.concurrent.Future$$anonfun$listen$1$$anonfun$apply$4.apply(Future.scala:80)
[error]   scalaz.concurrent.Future$$anonfun$listen$1$$anonfun$apply$4.apply(Future.scala:80)
[error]   scalaz.Free$$anonfun$map$1.apply(Free.scala:52)
[error]   scalaz.Free$$anonfun$map$1.apply(Free.scala:52)
[error]   scalaz.Free.resume(Free.scala:73)
[error]   scalaz.Free.go2$1(Free.scala:118)
[error]   scalaz.Free.go(Free.scala:122)
[error]   scalaz.Free.run(Free.scala:172)
[error]   scalaz.concurrent.Future.listen(Future.scala:77)
[error]   scalaz.concurrent.Future$$anon$1$$anonfun$reduceUnordered$2$$anonfun$apply$10.apply(Future.scala:310)
[error]   scalaz.concurrent.Future$$anon$1$$anonfun$reduceUnordered$2$$anonfun$apply$10.apply(Future.scala:309)
[error]   scala.collection.Iterator$class.foreach(Iterator.scala:742)
[error]   scala.collection.AbstractIterator.foreach(Iterator.scala:1194)
[error]   scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
[error]   scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[error]   scalaz.concurrent.Future$$anon$1$$anonfun$reduceUnordered$2.apply(Future.scala:309)
[error]   scalaz.concurrent.Future$$anon$1$$anonfun$reduceUnordered$2.apply(Future.scala:305)
[error]   scalaz.concurrent.Future.listen(Future.scala:80)
[error]   scalaz.concurrent.Future.runAsync(Future.scala:143)
[error]   scalaz.concurrent.Future.run(Future.scala:160)
[error]   scalaz.concurrent.Task.attemptRun(Task.scala:104)
[error]   org.specs2.control.ActionT$.fromTask(ActionT.scala:125)
[error]   org.specs2.control.ActionTSupport$class.fromTask(ActionT.scala:188)
[error]   org.specs2.control.package$Actions$.fromTask(package.scala:29)
[error]   org.specs2.reporter.Reporter$$anonfun$report$1.apply(Reporter.scala:47)
[error]   org.specs2.reporter.Reporter$$anonfun$report$1.apply(Reporter.scala:37)
[error]   org.specs2.runner.SbtRunner$$anonfun$specificationRun$1$$anonfun$2.apply(SbtRunner.scala:75)
[error]   org.specs2.runner.SbtRunner$$anonfun$specificationRun$1$$anonfun$2.apply(SbtRunner.scala:75)
[error]   org.specs2.control.ActionT$$anonfun$flatMap$1$$anonfun$apply$2.apply(ActionT.scala:36)
[error]   org.specs2.control.ActionT$$anonfun$flatMap$1$$anonfun$apply$2.apply(ActionT.scala:36)
[error]   org.specs2.control.StatusT$$anonfun$flatMap$1.apply(StatusT.scala:20)
[error]   org.specs2.control.StatusT$$anonfun$flatMap$1.apply(StatusT.scala:19)
[error]   scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
[error]   scalaz.WriterT$$anonfun$flatMapF$1.apply(WriterT.scala:63)
[error]   scalaz.WriterT$$anonfun$flatMapF$1.apply(WriterT.scala:62)
[error]   scalaz.effect.IO$$anonfun$flatMap$1$$anonfun$apply$9.apply(IO.scala:62)
[error]   scalaz.effect.IO$$anonfun$flatMap$1$$anonfun$apply$9.apply(IO.scala:61)
[error]   scalaz.Free$$anonfun$flatMap$1$$anonfun$apply$1.apply(Free.scala:60)
[error]   scalaz.Free$$anonfun$flatMap$1$$anonfun$apply$1.apply(Free.scala:60)
[error]   scalaz.Free.resume(Free.scala:72)
[error]   scalaz.Free.go2$1(Free.scala:118)
[error]   scalaz.Free.go(Free.scala:122)
[error]   scalaz.Free.run(Free.scala:172)
[error]   scalaz.effect.IO$class.unsafePerformIO(IO.scala:22)
[error]   scalaz.effect.IOFunctions$$anon$6.unsafePerformIO(IO.scala:227)
[error]   org.specs2.runner.SbtRunner$$anonfun$newTask$1$$anon$4.execute(SbtRunner.scala:40)
[error]   sbt.ForkMain$Run$2.call(ForkMain.java:294)
[error]   sbt.ForkMain$Run$2.call(ForkMain.java:284)
[error]   java.util.concurrent.FutureTask.run(Unknown Source)
[error]   java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[error]   java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[error]   java.lang.Thread.run(Unknown Source)
[error]
[error]   CAUSED BY Configuration error: Configuration error[default doesn't exist]
[error]   play.api.Configuration$.configError(Configuration.scala:178)
[error]   play.api.Configuration.reportError(Configuration.scala:829)
[error]   com.mechanic.core.utilities.mongo.MongoConnect$$anonfun$source$1.apply(MongoConnect.scala:117)
[error]   com.mechanic.core.utilities.mongo.MongoConnect$$anonfun$source$1.apply(MongoConnect.scala:117)
[error]   scala.collection.MapLike$class.getOrElse(MapLike.scala:128)
[error]   scala.collection.AbstractMap.getOrElse(Map.scala:59)
[error]   com.mechanic.core.utilities.mongo.MongoConnect.source(MongoConnect.scala:117)
[error]   com.mechanic.core.utilities.mongo.MongoConnect.collection(MongoConnect.scala:133)
[error]   com.mechanic.core.utilities.mongo.package$.mongoCollection(package.scala:16)
[error]   com.mechanic.core.models.MongoBase$$anon$1.<init>(MongoBase.scala:14)
[error]   com.mechanic.core.models.MongoBase.<init>(MongoBase.scala:14)
[error]   com.mechanic.core.models.System$.<init>(System.scala:20)
[error]   com.mechanic.core.models.System$.<clinit>(System.scala)
[error]   APISpec$$anonfun$11$$anonfun$apply$1$$anonfun$apply$4$$anon$3$$anonfun$9.apply(APISpec.scala:46)
[error]   APISpec$$anonfun$11$$anonfun$apply$1$$anonfun$apply$4$$anon$3$$anonfun$9.apply(APISpec.scala:46)
[error]   org.specs2.matcher.Expectable.value$lzycompute(Expectable.scala:20)
[error]   org.specs2.matcher.Expectable.value(Expectable.scala:20)
[error]   org.specs2.matcher.BeTypedEqualTo.apply(BeTypedEqualTo.scala:44)
[error]   org.specs2.matcher.Expectable.applyMatcher(Expectable.scala:50)
[error]   org.specs2.matcher.MustThrownExpectationsCreation$$anon$4.applyMatcher(MustExpectations.scala:64)
[error]   org.specs2.matcher.MatchSuccess.apply(MatchResult.scala:120)
[error]   org.specs2.matcher.NeutralMatch.apply(MatchResult.scala:184)
[error]   org.specs2.matcher.AnyBeHaveMatchers$AnyBeHaveMatchers.equalTo(AnyMatchers.scala:194)
[error]   APISpec$$anonfun$11$$anonfun$apply$1$$anonfun$apply$4$$anon$3.delayedEndpoint$APISpec$$anonfun$11$$anonfun$apply$1$$anonfun$apply$4$$anon$3$1(APISpec.scala:46)
[error]   APISpec$$anonfun$11$$anonfun$apply$1$$anonfun$apply$4$$anon$3$delayedInit$body.apply(APISpec.scala:45)
[error]   scala.Function0$class.apply$mcV$sp(Function0.scala:34)
[error]   scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
[error]   org.specs2.mutable.Around$$anonfun$delayedInit$1$$anonfun$apply$1.apply(Around.scala:15)
[error]   org.specs2.mutable.Around$$anonfun$delayedInit$1$$anonfun$apply$1.apply(Around.scala:15)
[error]   org.specs2.execute.ResultExecution$class.execute(ResultExecution.scala:25)
[error]   org.specs2.execute.ResultExecution$.execute(ResultExecution.scala:120)
[error]   org.specs2.execute.Result$$anon$10.asResult(Result.scala:230)
[error]   org.specs2.execute.AsResult$.apply(AsResult.scala:25)
[error]   org.specs2.execute.AsResult$$anonfun$effectively$1.apply(AsResult.scala:28)
[error]   org.specs2.execute.AsResult$$anonfun$effectively$1.apply(AsResult.scala:28)
[error]   org.specs2.execute.ResultExecution$class.effectively(ResultExecution.scala:41)
[error]   org.specs2.execute.ResultExecution$.effectively(ResultExecution.scala:120)
[error]   org.specs2.execute.AsResult$.effectively(AsResult.scala:28)
[error]   play.api.test.WithApplication$$anonfun$around$2.apply(Specs.scala:39)
[error]   play.api.test.WithApplication$$anonfun$around$2.apply(Specs.scala:39)
[error]   play.api.test.PlayRunners$class.running(Helpers.scala:42)
[error]   play.api.test.Helpers$.running(Helpers.scala:363)
[error]   play.api.test.WithApplication.around(Specs.scala:39)
[error]   org.specs2.mutable.Around$$anonfun$delayedInit$1.apply(Around.scala:15)
[error]   org.specs2.mutable.Around$$anonfun$delayedInit$1.apply(Around.scala:15)
[error]   org.specs2.execute.ResultExecution$class.effectively(ResultExecution.scala:41)
[error]   org.specs2.execute.ResultExecution$.effectively(ResultExecution.scala:120)
[error]   org.specs2.mutable.Around$class.delayedInit(Around.scala:15)
[error]   play.api.test.WithApplication.delayedInit(Specs.scala:36)
[error]   APISpec$$anonfun$11$$anonfun$apply$1$$anonfun$apply$4$$anon$3.<init>(APISpec.scala:45)
[error]   APISpec$$anonfun$11$$anonfun$apply$1$$anonfun$apply$4.apply(APISpec.scala:45)
[error]   APISpec$$anonfun$11$$anonfun$apply$1$$anonfun$apply$4.apply(APISpec.scala:45)
[error]   org.specs2.matcher.Scope$$anon$3$$anonfun$asResult$1.apply(ThrownExpectations.scala:139)
[error]   org.specs2.matcher.Scope$$anon$3$$anonfun$asResult$1.apply(ThrownExpectations.scala:139)
[error]   org.specs2.execute.ResultExecution$class.execute(ResultExecution.scala:25)
[error]   org.specs2.execute.ResultExecution$.execute(ResultExecution.scala:120)
[error]   org.specs2.execute.Result$$anon$10.asResult(Result.scala:230)
[error]   org.specs2.execute.AsResult$.apply(AsResult.scala:25)
[error]   org.specs2.matcher.Scope$$anon$3.asResult(ThrownExpectations.scala:139)
[error]   org.specs2.execute.AsResult$.apply(AsResult.scala:25)
[error]   org.specs2.main.CommandLineAsResult$$anon$1.asResult(CommandLineAsResult.scala:17)
[error]   org.specs2.main.CommandLineAsResult$$anonfun$apply$1.apply(CommandLineAsResult.scala:21)
[error]   org.specs2.main.CommandLineAsResult$$anonfun$apply$1.apply(CommandLineAsResult.scala:21)
[error]   org.specs2.specification.dsl.mutable.ExampleDsl1$BlockExample$$anonfun$$greater$greater$1.apply(ExampleDsl.scala:39)
[error]   org.specs2.specification.dsl.mutable.ExampleDsl1$BlockExample$$anonfun$$greater$greater$1.apply(ExampleDsl.scala:39)
[error]   org.specs2.specification.core.Execution$$anonfun$withEnv$1$$anonfun$apply$3.apply(Execution.scala:120)
[error]   org.specs2.execute.ResultExecution$class.execute(ResultExecution.scala:25)
[error]   org.specs2.execute.ResultExecution$.execute(ResultExecution.scala:120)
[error]   org.specs2.execute.Result$$anon$10.asResult(Result.scala:230)
[error]   org.specs2.execute.AsResult$.apply(AsResult.scala:25)
[error]   org.specs2.specification.core.Execution$$anonfun$withEnv$1.apply(Execution.scala:120)
[error]   org.specs2.specification.core.Execution$$anonfun$withEnv$1.apply(Execution.scala:120)
[error]   org.specs2.specification.core.Execution$$anonfun$execute$2$$anonfun$apply$2.apply(Execution.scala:70)
[error]   org.specs2.specification.core.Execution$$anonfun$execute$2$$anonfun$apply$2.apply(Execution.scala:70)
[error]   org.specs2.specification.core.Execution.setResult(Execution.scala:76)
[error]   org.specs2.specification.core.Execution$$anonfun$execute$2.apply(Execution.scala:70)
[error]   org.specs2.specification.core.Execution$$anonfun$execute$2.apply(Execution.scala:70)
[error]   scala.Option.fold(Option.scala:158)
[error]   org.specs2.specification.core.Execution.execute(Execution.scala:70)
[error]   org.specs2.specification.process.DefaultExecutor$$anonfun$executeFragment$1$$anonfun$apply$6.apply(Executor.scala:132)
[error]   org.specs2.specification.process.DefaultExecutor$$anonfun$executeFragment$1$$anonfun$apply$6.apply(Executor.scala:130)
[error]   org.specs2.specification.core.Fragment.updateExecution(Fragment.scala:44)
[error]   org.specs2.specification.process.DefaultExecutor$$anonfun$executeFragment$1.apply(Executor.scala:130)
[error]   org.specs2.specification.process.DefaultExecutor$$anonfun$executeFragment$1.apply(Executor.scala:129)
[error]   org.specs2.specification.process.DefaultExecutor$$anonfun$sequencedExecution$1.executedFragment$lzycompute$1(Executor.scala:104)
[error]   org.specs2.specification.process.DefaultExecutor$$anonfun$sequencedExecution$1.org$specs2$specification$process$DefaultExecutor$class$$anonfun$$executedFragment$1(Executor.
scala:104)
[error]   org.specs2.specification.process.DefaultExecutor$$anonfun$sequencedExecution$1$$anonfun$3.apply(Executor.scala:109)
[error]   org.specs2.specification.process.DefaultExecutor$$anonfun$sequencedExecution$1$$anonfun$3.apply(Executor.scala:109)
[error]   scalaz.concurrent.Task$$anonfun$delay$1.apply(Task.scala:272)
[error]   scalaz.concurrent.Task$$anonfun$delay$1.apply(Task.scala:272)
[error]   scalaz.concurrent.Task$$anonfun$suspend$1$$anonfun$4.apply(Task.scala:280)
[error]   scalaz.concurrent.Task$$anonfun$suspend$1$$anonfun$4.apply(Task.scala:280)
[error]   scalaz.concurrent.Task$.Try(Task.scala:385)
[error]   scalaz.concurrent.Task$$anonfun$suspend$1.apply(Task.scala:280)
[error]   scalaz.concurrent.Task$$anonfun$suspend$1.apply(Task.scala:280)
[error]   scalaz.concurrent.Future.step(Future.scala:111)
[error]   scalaz.concurrent.Future.listen(Future.scala:76)
[error]   scalaz.concurrent.Future$$anon$1$$anonfun$reduceUnordered$2$$anonfun$apply$10.apply(Future.scala:310)
[error]   scalaz.concurrent.Future$$anon$1$$anonfun$reduceUnordered$2$$anonfun$apply$10.apply(Future.scala:309)
[error]   scala.collection.Iterator$class.foreach(Iterator.scala:742)
[error]   scala.collection.AbstractIterator.foreach(Iterator.scala:1194)
[error]   scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
[error]   scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[error]   scalaz.concurrent.Future$$anon$1$$anonfun$reduceUnordered$2.apply(Future.scala:309)
[error]   scalaz.concurrent.Future$$anon$1$$anonfun$reduceUnordered$2.apply(Future.scala:305)
[error]   scalaz.concurrent.Future.listen(Future.scala:80)
[error]   scalaz.concurrent.Future$$anonfun$listen$1$$anonfun$apply$4.apply(Future.scala:80)
[error]   scalaz.concurrent.Future$$anonfun$listen$1$$anonfun$apply$4.apply(Future.scala:80)
[error]   scalaz.Free$$anonfun$map$1.apply(Free.scala:52)
[error]   scalaz.Free$$anonfun$map$1.apply(Free.scala:52)
[error]   scalaz.Free.resume(Free.scala:73)
[error]   scalaz.Free.go2$1(Free.scala:118)
[error]   scalaz.Free.go(Free.scala:122)
[error]   scalaz.Free.run(Free.scala:172)
[error]   scalaz.concurrent.Future.listen(Future.scala:77)
[error]   scalaz.concurrent.Future$$anon$1$$anonfun$reduceUnordered$2$$anonfun$apply$10.apply(Future.scala:310)
[error]   scalaz.concurrent.Future$$anon$1$$anonfun$reduceUnordered$2$$anonfun$apply$10.apply(Future.scala:309)
[error]   scala.collection.Iterator$class.foreach(Iterator.scala:742)
[error]   scala.collection.AbstractIterator.foreach(Iterator.scala:1194)
[error]   scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
[error]   scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[error]   scalaz.concurrent.Future$$anon$1$$anonfun$reduceUnordered$2.apply(Future.scala:309)
[error]   scalaz.concurrent.Future$$anon$1$$anonfun$reduceUnordered$2.apply(Future.scala:305)
[error]   scalaz.concurrent.Future.listen(Future.scala:80)
[error]   scalaz.concurrent.Future.runAsync(Future.scala:143)
[error]   scalaz.concurrent.Future.run(Future.scala:160)
[error]   scalaz.concurrent.Task.attemptRun(Task.scala:104)
[error]   org.specs2.control.ActionT$.fromTask(ActionT.scala:125)
[error]   org.specs2.control.ActionTSupport$class.fromTask(ActionT.scala:188)
[error]   org.specs2.control.package$Actions$.fromTask(package.scala:29)
[error]   org.specs2.reporter.Reporter$$anonfun$report$1.apply(Reporter.scala:47)
[error]   org.specs2.reporter.Reporter$$anonfun$report$1.apply(Reporter.scala:37)
[error]   org.specs2.runner.SbtRunner$$anonfun$specificationRun$1$$anonfun$2.apply(SbtRunner.scala:75)
[error]   org.specs2.runner.SbtRunner$$anonfun$specificationRun$1$$anonfun$2.apply(SbtRunner.scala:75)
[error]   org.specs2.control.ActionT$$anonfun$flatMap$1$$anonfun$apply$2.apply(ActionT.scala:36)
[error]   org.specs2.control.ActionT$$anonfun$flatMap$1$$anonfun$apply$2.apply(ActionT.scala:36)
[error]   org.specs2.control.StatusT$$anonfun$flatMap$1.apply(StatusT.scala:20)
[error]   org.specs2.control.StatusT$$anonfun$flatMap$1.apply(StatusT.scala:19)
[error]   scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
[error]   scalaz.WriterT$$anonfun$flatMapF$1.apply(WriterT.scala:63)
[error]   scalaz.WriterT$$anonfun$flatMapF$1.apply(WriterT.scala:62)
[error]   scalaz.effect.IO$$anonfun$flatMap$1$$anonfun$apply$9.apply(IO.scala:62)
[error]   scalaz.effect.IO$$anonfun$flatMap$1$$anonfun$apply$9.apply(IO.scala:61)
[error]   scalaz.Free$$anonfun$flatMap$1$$anonfun$apply$1.apply(Free.scala:60)
[error]   scalaz.Free$$anonfun$flatMap$1$$anonfun$apply$1.apply(Free.scala:60)
[error]   scalaz.Free.resume(Free.scala:72)
[error]   scalaz.Free.go2$1(Free.scala:118)
[error]   scalaz.Free.go(Free.scala:122)
[error]   scalaz.Free.run(Free.scala:172)
[error]   scalaz.effect.IO$class.unsafePerformIO(IO.scala:22)
[error]   scalaz.effect.IOFunctions$$anon$6.unsafePerformIO(IO.scala:227)
[error]   org.specs2.runner.SbtRunner$$anonfun$newTask$1$$anon$4.execute(SbtRunner.scala:40)
[error]   sbt.ForkMain$Run$2.call(ForkMain.java:294)
[error]   sbt.ForkMain$Run$2.call(ForkMain.java:284)
[error]   java.util.concurrent.FutureTask.run(Unknown Source)
[error]   java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[error]   java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[error]   java.lang.Thread.run(Unknown Source)
[error]
[error]
[error] This looks like a specs2 exception...
[error] Please report it with the preceding stacktrace at http://github.com/etorreborre/specs2/issues
[error]

**Comment by etorreborre** [comment]
Which version of specs2 are you using?

The issue is that your code is throwing an `ExceptionInInitializerError` which was not caught in examples before. In more recent versions you will get something like
```
[error]  ! test
[error]  java.lang.ExceptionInInitializerError: Fatal execution error, caused by blah (TestSpec.scala:13)
[error] user.TestSpec.e1(TestSpec.scala:13)
[error] user.TestSpec$$anonfun$is$1$$anonfun$apply$1.apply(TestSpec.scala:7)
[error] user.TestSpec$$anonfun$is$1$$anonfun$apply$1.apply(TestSpec.scala:7)
```

**Comment by bdrachinsky** [comment]
I'm using 2.11 version. As I understand I should upgrade my current version to the newer.

**Comment by etorreborre** [comment]
Yes if you can.
