### ISSUE TITLE
Release for 2.12.0-M3?

### ISSUE THREAD

**Issue by SethTisue** [etorreborre/specs2#425]
The Scala team would be interested in hearing if you encounter any trouble with this.

**Comment by etorreborre** [comment]
I was actually waiting for all my dependencies to have a `2.12.0-M3` release. I need:

 - `scalacheck-1.12.5`
 - `shapeless-2.2.5`
 - `scalaz-stream-0.8` and `scalaz-stream-0.7.3`

I tried to run a version of specs2 on 2.12.0-M3 with `2.12.0-M2` for those libraries and except for ScalaCheck, things seem to be running ok (see commit 02ca507 if you want to have a look at it).

**Comment by SethTisue** [comment]
tickets:

 * [ ] https://github.com/rickynils/scalacheck/issues/198
 * [ ] https://github.com/scalaz/scalaz-stream/pull/463
 * [X] https://github.com/milessabin/shapeless/issues/484

**Comment by holograph** [comment]
Seconded...

**Comment by etorreborre** [comment]
@SethTisue @holograph I have just released [`3.6.5-20151025224741-adea3e0`](https://oss.sonatype.org/content/repositories/releases/org/specs2/specs2-core_2.12.0-M3/3.6.5-20151025224741-adea3e0) with `scalaz-stream` still being using `2.12.0-M2` but all the tests are passing ok. I will do a definitive `2.12.0-M3-3.6.5` release when `scalaz-stream` is ready.

**Comment by holograph** [comment]
I'll find a way to disable Scala.js support for 2.12 specifically and then will let you know if things seem to work :-)

**Comment by holograph** [comment]
*phew* Seems to work and tests properly! Had to hack a bit at the dependency to avoid sbt errors:

```scala
        libraryDependencies <+= scalaVersion {
          case v if v startsWith "2.12" =>
            // Temporary workaround for Specs2 issue #425, see:
            // https://github.com/etorreborre/specs2/issues/425#issuecomment-150986091
            ( "org.specs2" %% "specs2-core" % "3.6.5-20151025224741-adea3e0" )
              .exclude( "org.scalaz", "scalaz-concurrent_2.12.0-M2" )
              .exclude( "org.scalaz", "scalaz-effect_2.12.0-M2" )
              .exclude( "org.scalaz", "scalaz-core_2.12.0-M2" )
              .exclude( "org.scala-lang.modules", "scala-xml_2.12.0-M2" )
              .exclude( "org.scala-lang.modules", "scala-parser-combinators_2.12.0-M2" )

          case _ => "org.specs2" %% "specs2-core" % "3.6.5"
        }
```

**Comment by etorreborre** [comment]
Wow, thanks for reporting this @holograph, good to know it's working for youu.

**Comment by holograph** [comment]
Thanks for putting the effort in, needless to say I'm a big fan of Specs2 :-)  Looking forward to a proper 3.6.5 when scalaz-stream releases...

**Comment by zaneli** [comment]
scalaz-stream 0.8a might be released for 2.12.0-M3.
https://github.com/functional-streams-for-scala/fs2/pull/519
https://github.com/coltfred/fs2/commit/a32aa343560912ff646064720edc93896871482d

**Comment by xuwei-k** [comment]
http://repo1.maven.org/maven2/org/scalaz/stream/scalaz-stream_2.12.0-M3/0.8a/

**Comment by SethTisue** [comment]
@xuwei-k thanks for the heads up. @etorreborre, IMO an M3 build of specs2 would still be worthwhile to have, if it's now possible

**Comment by seratch** [comment]
@etorreborre Would you please release new version which uses scalaz-stream 0.8a when you have time? This issue is a blocker issue for me too.

**Comment by etorreborre** [comment]
@SethTisue @xuwei-k I will try to do that when I can. Relocating the family to Berlin takes lots of time...

**Comment by etorreborre** [comment]
And the wifi access I have at the moment is horribly slow :-(

**Comment by etorreborre** [comment]
@SethTisue @xuwei-k @seratch here you go: https://oss.sonatype.org/content/repositories/releases/org/specs2/specs2-core_2.12.0-M3/3.7.

**Comment by SethTisue** [comment]
@etorreborre thanks, but I think something may have gone wrong here with the transitive dependencies? in an empty sbt 0.13.9 project with:

```
scalaVersion := "2.12.0-M3"
libraryDependencies += "org.specs2" %% "specs2-core" % "3.7"
```

I get:

```
[error] Modules were resolved with conflicting cross-version suffixes in {file:/Users/tisue/tmp/m3/}m3:
[error]    org.scalaz:scalaz-effect _2.12.0-M3, _2.12.0-M2
[error]    org.scala-lang.modules:scala-xml _2.12.0-M3, _2.12.0-M2
[error]    org.scalaz:scalaz-concurrent _2.12.0-M3, _2.12.0-M2
[error]    org.scalaz:scalaz-core _2.12.0-M3, _2.12.0-M2
[error]    org.scala-lang.modules:scala-parser-combinators _2.12.0-M3, _2.12.0-M2
```

**Comment by etorreborre** [comment]
That's weird. But I also have a terrible wifi connection at the moment and the publish process was interrupted. I'll try to publish a `3.7.1` fixing this.

**Comment by etorreborre** [comment]
@SethTisue please try again with 3.7.1 now.

**Comment by SethTisue** [comment]
LGTM (in my extremely limited testing), thanks!

**Comment by cppexpert** [comment]
Was it ever published to Maven ?

**Comment by etorreborre** [comment]
You have `specs2-core`
