### ISSUE TITLE
Mockito x.times is incorrect occasionally inside closures

### ISSUE THREAD

**Issue by kflorence** [etorreborre/specs2#428]
I believe this is most likely an issue with Mockito, but I wanted to verify and see if you've ever seen this problem before. It seems that sometimes when we try to do an exact invocation verification inside of a closure the number of times Mockito thinks the method has been called is incorrect (it seems to multiply it by three in most cases). I will try to pair down this code into a simple working example since it seems most of our use cases are pretty complex. I will say, though, that we see this with almost all of our Play! unit tests since the Play! Framework has a lot of nested closures for action composition, for example:

```scala
def foo() = Action {
  Ok("bar")
}
```

**Comment by kflorence** [comment]
Actually, these tests seem to be passing inside IntelliJ but failing on the command line via `sbt test`.

**Comment by kflorence** [comment]
Inside IntelliJ I am definitely using the `Specs2` test runner -- I am assuming SBT is using the same since we don't have any other test libraries included in our path, but I'm struggling to find a way to verify this. By the way, here is an example of the error message I see from console (but these tests pass fine inside IntelliJ, as expected):

```
[info] publishStatusNotification should
[error]   x publish a status notification to the matching webhooks
[error]    The mock was not called as expected:
[error]    webhookRepository.findByEventTypeId(1);
[error]    Wanted 1 time:
[error]    -> at com.solarmosaic.microservice.webhook.service.controller.WebhookControllerTests$$anonfun$6$$anonfun$apply$7$$anon$3$$anonfun$9$$anonfun$apply$8.apply(WebhookControllerTests.scala:92)
[error]    But was 3 times. Undesired invocation:
[error]    -> at com.solarmosaic.microservice.webhook.service.controller.WebhookControllerTests$$anonfun$6$$anonfun$apply$7$$anon$3.<init>(WebhookControllerTests.scala:91) (WebhookControllerTests.scala:92)
```

**Comment by etorreborre** [comment]
This might be due to the mocking of methods with by-name parameters. Can you make sure that the specs2-mock jar is placed before the mockito jar on the classpath? In specs2 I am overriding some of the Mockito classes to deal with methods with by-name parameters.

**Comment by etorreborre** [comment]
Otherwise, can you please create a small project on Github which I could investigate?

**Comment by kflorence** [comment]
@etorreborre could be a by-name parameter issue. When I have some extra time I will try to get some code up in a repository for you.

**Comment by kflorence** [comment]
@etorreborre I have confirmed that when running tests inside IntelliJ the classpath contains mockito jars first, and then specs2 jars. When running via the command-line this is not the case -- mockito jars come after. So this is most likely the issue. I will look into classpath ordering to see if I can address this problem. Thanks for your help, as usual!

**Comment by etorreborre** [comment]
In case you don't know you can easily reorder the jars inside intellij manually by just using arrows to move them up and down inside the `Project Structure/Modules/Dependencies` window. The order might not be preserved if you do an automated import from sbt though.

**Comment by kflorence** [comment]
@etorreborre Ordering seems easy enough in IntelliJ, but I'm not sure how to preserve order when the project is run via command-line.

**Comment by kflorence** [comment]
For future reference, if anyone stumbles into this problem and ends up here: http://stackoverflow.com/questions/33405025/sbt-modify-the-order-of-dependencies-in-the-classpath

**Comment by kflorence** [comment]
@etorreborre are you sure that `mockito` jars should come *after* `specs2-mock` jars? It seems to work the other way around (if `mockito` jars are defined *first*).

**Comment by etorreborre** [comment]
I am saying *if* the issue is related to the handling of byname parameters, this might be fixed by reordering the jars. Maybe this is a different issue? If you want me to investigate can you please re-create it in a small project on Github?

**Comment by kflorence** [comment]
@etorreborre this issue was indeed fixed by re-ordering the jars. However, in my case placing `mockito` *before* `specs2-mock` fixed the problem.

**Comment by etorreborre** [comment]
Ok, maybe this means that there is a bug in specs2 then after all. In that case it would be really nice for me to have a reproducible test case. Because having to move the mockito jar before the specs2 one means that you will miss out on the functionalities that the specs2-mock jar provides (the handling of byname parameters for example).

**Comment by kflorence** [comment]
@etorreborre Okay no problem. Let me get something up for you.

**Comment by kflorence** [comment]
@etorreborre Here is a relatively simple test case: https://github.com/kflorence/specs2-issue-428 -- I didn't spend any time pairing down dependencies but this should give you something to play with at least. Appreciate it!

**Comment by kflorence** [comment]
Something to consider: `spring-boot-starter-test` also brings in `mockito` as a dependency.

**Comment by etorreborre** [comment]
I don't know yet what is the issue but I can observe the interaction of a few things. The test passes if:

 - if I don't use `spy` on the `TestController`
 - or if I remove the byname parameter on `async` (it is not used anyway. At least or your test case, maybe not on your real project?)

**Comment by etorreborre** [comment]
I'm not sure how to fix this yet, because it looks like some unwanted side-effects with `spy`. Do you really need `spy` or `=>Future` on `async`?

**Comment by kflorence** [comment]
@etorreborre looks like I can probably get rid of the by-name parameter in this case, but this will not help me when dealing with third party code (such as Play!) where this problem will persist.

**Comment by etorreborre** [comment]
Can I ask why you need `spy`? I'm not trying to avoid fixing the issue but I don't have much time available right now so I'm trying to see if we can find a work-around (besides the re-ordering of jars).

**Comment by kflorence** [comment]
@etorreborre we generally use `spy` to shortcut method calls within the same class.

**Comment by etorreborre** [comment]
I think I found a fix. Please test `specs2-mock-3.6.5-20151108070227-1e34889`. I hope I haven't introduced any regression in the process. My existing tests are ok, it seems like this is a brand new case but the whole thing is *very* hacky.

**Comment by kflorence** [comment]
Thanks Eric, I will try out the new release as soon as possible.

**Comment by kflorence** [comment]
@etorreborre apologies for the delay, work has been hectic lately. Will try to get to this soon.

**Comment by kflorence** [comment]
@etorreborre apologies again for the massive response delay. We have been using the above version for a few weeks now without any issues so at least in our environment it doesn't seem to have caused any regressions.

**Comment by etorreborre** [comment]
@kflorence that's good to know, thanks.
