### ISSUE TITLE
Nullpointer exception when use Option with Mockito

### ISSUE THREAD

**Issue by pjolep** [etorreborre/specs2#430]
Strange exception where use Spec2 with Mockito. It says:

[error] This looks like a specs2 exception...
[error] Please report it with the preceding stacktrace at http://github.com/etorreborre/specs2/issues

Code:
 val zoneForTest = zoneDaoToDtoGet(randomZone())
  val zonesService = mock[ZonesService]
  zonesService.get returns Enumerator(zoneForTest)
  zonesService.create(any[dto.Zone.Update]) returns Future.successful(zoneForTest)
  zonesService.getById(any[ZoneID]) returns Future.successful(Option(zoneForTest))

The last line that mocks return of  Future.successful(Option(zoneForTest)) causes the error.

Both classes Zone.Update and ZoneID are case classes. Only difference is that ZoneID extends AnyVal.

Top part of stacktrace is below:

[error] 
[error] java.lang.reflect.InvocationTargetException
[error]   caused by java.lang.NullPointerException
[error] 
[error] STACKTRACE
[error]   sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[error]   sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[error]   sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[error]   java.lang.reflect.Constructor.newInstance(Constructor.java:408)
[error]   org.specs2.reflect.Classes$$anonfun$org$specs2$reflect$Classes$$createInstanceForConstructor$1$$anonfun$apply$13.apply(Classes.scala:120)
[error]   org.specs2.control.ActionT$$anonfun$safe$1.apply(ActionT.scala:89)
[error]   org.specs2.control.ActionT$$anonfun$reader$1$$anonfun$apply$6.apply(ActionT.scala:80)
[error]   org.specs2.control.Status$.safe(Status.scala:100)
[error]   org.specs2.control.StatusT$$anonfun$safe$1.apply(StatusT.scala:62)
[error]   org.specs2.control.StatusT$$anonfun$safe$1.apply(StatusT.scala:62)
[error]   scalaz.syntax.ToApplicativeOps$$anon$1.self$lzycompute(ApplicativeSyntax.scala:29)
[error]   scalaz.syntax.ToApplicativeOps$$anon$1.self(ApplicativeSyntax.scala:29)
[error]   scalaz.syntax.ToApplicativeOps$ApplicativeIdV$$anonfun$point$1.apply(ApplicativeSyntax.scala:33)
[error]   scalaz.WriterTApplicative$$anonfun$point$1.apply(WriterT.scala:268)
[error]   scalaz.WriterTApplicative$$anonfun$point$1.apply(WriterT.scala:268)
[error]   scalaz.effect.IO$$anonfun$apply$19$$anonfun$apply$20.apply(IO.scala:136)
[error]   scalaz.effect.IO$$anonfun$apply$19$$anonfun$apply$20.apply(IO.scala:136)
[error]   scalaz.FreeFunctions$$anonfun$return_$1.apply(Free.scala:326)
[error]   scalaz.FreeFunctions$$anonfun$return_$1.apply(Free.scala:326)
[error]   scalaz.std.FunctionInstances$$anon$1$$anonfun$map$1.apply(Function.scala:56)
[error]   scalaz.Free$$anonfun$run$1.apply(Free.scala:172)
[error]   scalaz.Free$$anonfun$run$1.apply(Free.scala:172)
[error]   scalaz.Free.go2$1(Free.scala:119)
[error]   scalaz.Free.go(Free.scala:122)
[error]   scalaz.Free.run(Free.scala:172)
[error]   scalaz.effect.IO$class.unsafePerformIO(IO.scala:22)
[error]   scalaz.effect.IOFunctions$$anon$6.unsafePerformIO(IO.scala:227)
[error]   org.specs2.reflect.Classes$$anonfun$createInstance$1$$anonfun$apply$1$$anonfun$3.apply(Classes.scala:38)
[error]   org.specs2.reflect.Classes$$anonfun$createInstance$1$$anonfun$apply$1$$anonfun$3.apply(Classes.scala:37)
[error]   scala.collection.immutable.List.map(List.scala:273)
[error]   org.specs2.reflect.Classes$$anonfun$createInstance$1$$anonfun$apply$1.apply(Classes.scala:37)
[error]   org.specs2.reflect.Classes$$anonfun$createInstance$1$$anonfun$apply$1.apply(Classes.scala:30)
[error]   scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
[error]   org.specs2.control.Status$class.fold(Status.scala:30)
[error]   org.specs2.control.Ok.fold(Status.scala:95)
[error]   org.specs2.control.Status$class.flatMap(Status.scala:48)
[error]   org.specs2.control.Ok.flatMap(Status.scala:95)
[error]   org.specs2.control.Status$class.map(Status.scala:45)
[error]   org.specs2.control.Ok.map(Status.scala:95)
[error]   org.specs2.control.StatusT$$anonfun$map$1.apply(StatusT.scala:16)
[error]   org.specs2.control.StatusT$$anonfun$map$1.apply(StatusT.scala:16)
[error]   scalaz.WriterT$$anonfun$map$1.apply(WriterT.scala:46)
[error]   scalaz.WriterT$$anonfun$map$1.apply(WriterT.scala:46)
[error]   scalaz.effect.IO$$anonfun$map$1$$anonfun$apply$8.apply(IO.scala:56)
[error]   scalaz.effect.IO$$anonfun$map$1$$anonfun$apply$8.apply(IO.scala:55)
[error]   scalaz.Free$$anonfun$map$1.apply(Free.scala:52)
[error]   scalaz.Free$$anonfun$map$1.apply(Free.scala:52)
[error]   scalaz.Free$$anonfun$flatMap$1$$anonfun$apply$1.apply(Free.scala:60)
[error]   scalaz.Free$$anonfun$flatMap$1$$anonfun$apply$1.apply(Free.scala:60)
[error]   scalaz.Free.resume(Free.scala:72)
[error]   scalaz.Free.go2$1(Free.scala:118)
[error]   scalaz.Free.go(Free.scala:122)
[error]   scalaz.Free.run(Free.scala:172)
[error]   scalaz.effect.IO$class.unsafePerformIO(IO.scala:22)
[error]   scalaz.effect.IOFunctions$$anon$6.unsafePerformIO(IO.scala:227)
[error]   org.specs2.runner.SbtRunner$$anonfun$newTask$1$$anon$4.execute(SbtRunner.scala:40)
[error]   sbt.TestRunner.runTest$1(TestFramework.scala:76)
[error]   sbt.TestRunner.run(TestFramework.scala:85)
[error]   sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
[error]   sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
[error]   sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:185)
[error]   sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
[error]   sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
[error]   sbt.TestFunction.apply(TestFramework.scala:207)
[error]   sbt.Tests$$anonfun$9.apply(Tests.scala:216)
[error]   sbt.Tests$$anonfun$9.apply(Tests.scala:216)
[error]   sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
[error]   sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
[error]   sbt.std.Transform$$anon$4.work(System.scala:63)
[error]   sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
[error]   sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
[error]   sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
[error]   sbt.Execute.work(Execute.scala:235)
[error]   sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
[error]   sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
[error]   sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
[error]   sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
[error]   java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]   java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]   java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error]   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error]   java.lang.Thread.run(Thread.java:745)

**Comment by pjolep** [comment]
Ok, here is work around. Problem is with AnyVal matcher. 

when(zonesService.getById(any[String].asInstanceOf[ZoneID])).thenReturn(Future.successful(Option(zoneForTest)))

Here is post:

https://groups.google.com/forum/#!topic/mockito/m_Ptz8eVH58

**Comment by etorreborre** [comment]
One comment about this. If you get such a specs2 exception this must mean that:

 1. your version of specs2 is not a recent one
 2. you have some initialisation code in the body of your specification

I recommend to use a more recent version of specs2 because it should catch and report more nicely initialization errors. Also try to use `lazy vals` to create your objects instead of vals to allows those errors to appear during the specification execution instead of popping up at construction time.
