### ISSUE TITLE
Runner exception handler doesn't print exception class on unexpected failure

### ISSUE THREAD

**Issue by danielkza** [etorreborre/specs2#431]
I'm running into some unknown issues while running tests in IntelliJ IDEA 15, but it took me a while to even figure out what was going one because all I got for error messages was this:

```
net.danielkza.http2.protocol.coders.FrameCoderTest$

This looks like a specs2 exception...
Please report it with the preceding stacktrace at http://github.com/etorreborre/specs2/issues
```

Which I figured out was actually just the message from a `ClassNotFoundException` being printed. It would be nice to print the exception class as well to make debugging easier, or the actual stack trace as the comment implies.

Info: Using Specs2 3.6.4 with Scala 2.11.7.

**Comment by danielkza** [comment]
It seems it's an IntelliJ issue. SBT prints the log output correctly. Which is quite strange to me, since looking at the code, there's no reason why one part of the message would be printed and the rest would not. Either way, doesn't seem like Specs2 is the problem. Apologies for any time wasted.

**Comment by etorreborre** [comment]
Please leave an issue on the [IntelliJ plugin site](https://youtrack.jetbrains.com/issues/SCL). IntelliJ should have the stacktrace available for printing and it is worth investigating.
