### ISSUE TITLE
tests fail without output

### ISSUE THREAD

**Issue by avdv** [etorreborre/specs2#435]
A single specification started to fail with a spurious failure:

```
info] SearchSpec
[error] Error: Total 7, Failed 0, Errors 1, Passed 6
[error] Error during tests:
[error] 	SearchSpec
[error] (search/test:testOnly) sbt.TestsFailedException: Tests unsuccessful
```

As you can see, there is no message and no exception printed. It just died silently.

On investigation, it was apparent that the spec would only run successfully when there where 10 or less examples in it. :suspect: 

Luckily, when running under jdb and with `fork in Test := false` I was able to produce a stacktrace:

```
[info] SearchSpec
[trace] Stack trace suppressed: run last search/test:testOnly for the full output.
[error] java.io.FileNotFoundException: /src/project/search/target/streams/test/test/$global/streams/succeeded_tests (Too many open files)
Could not create file /src/project/search/target/streams/compile/$global/$global/discoveredMainClasses/datajava.io.IOException: Too many open files
```

After increasing the file descriptor limit, the tests ran successfully again.

Is it possible to abort with a meaningful exception (when forking a new JVM for the tests) in this case?

**Comment by etorreborre** [comment]
I am not sure this is a specs2 issue because this seems to happen in sbt itself trying to create files. You should probably post this issue on the sbt project.

**Comment by avdv** [comment]
OK, good idea. I'll submit a report there and close this issue for now. Thank you.
