### ISSUE TITLE
Result shouldn't define an implicit def from String to Monoid[Result]

### ISSUE THREAD

**Issue by jedws** [etorreborre/specs2#439]
this should not be implicit. Leads to hilarity such as the following:

    scala> import org.specs2._, execute._
    import org.specs2._
    import execute._

    scala> "wat".zero
    <console>:17: error: value zero is not a member of String
           "wat".zero
                 ^

    scala> import Result._
    import Result._

    scala> "wat".zero
    res1: org.specs2.execute.Result =

spotted by @puffnfresh

**Comment by etorreborre** [comment]
Thanks for spotting this :+1:
