### ISSUE TITLE
Failing to integrate with Bazel build tool

### ISSUE THREAD

**Issue by orrsella** [etorreborre/specs2#440]
I've been playing with the [Bazel](https://github.com/bazelbuild/bazel) build tool, and have a running example compiling and testing Scala code [here](https://github.com/orrsella/bazel-example). One problem I'm still facing is that for some reason specs2 tests that should fail aren't failing the build. I do see them as executed (by `println`-ing from the test and seeing it in test logs), but the failing test doesn't seem to fail the build. The curious thing is that ScalaTest tests do fail the build correctly. The tests are run by invoking `JUnitCore` with a list of classes or a single tests that is `@RunWith` a custom `Suite`.

After trying to debug it, I have a suspicion that maybe the `JUnitRunner` is doing something "fishy". I created a simple project with a few tests, and then ran it manually from the command line:

```scala
package com.example

import org.junit.runner.RunWith
import org.specs2.mutable.Specification
import org.specs2.runner.JUnitRunner

@RunWith(classOf[JUnitRunner])
class Specs2Test extends Specification {
  "Foo" should {
    "bar" in {
      1 === 1
    }
  }
}
```

```bash
$ java -cp .:lib/* org.junit.runner.JUnitCore com.example.Specs2Test
JUnit version 4.12
.
Time: 0

OK (0 tests)


Time: 0.338

OK (1 test)
```

Notice the seemingly double execution of tests. It's also present for a failing test:

```bash
$ java -cp .:lib/* org.junit.runner.JUnitCore com.example.Specs2FailingTest
JUnit version 4.12
.E
Time: 0

OK (0 tests)


Time: 0.399
There was 1 failure:
1) Foo should::bar(com.example.Specs2Test)
java.lang.Exception: '1' is not equal to '2'
	at com.example.Specs2Test$$anonfun$1$$anonfun$apply$3.apply(Specs2Test.scala:12)
	at com.example.Specs2Test$$anonfun$1$$anonfun$apply$3.apply(Specs2Test.scala:12)

FAILURES!!!
Tests run: 1,  Failures: 1
```

For reference, here's the output from ScalaTest (notice only 1 tests block):

```bash
$ java -cp .:lib/* org.junit.runner.JUnitCore com.example.ScalaTest
JUnit version 4.12
.
Time: 0.15

OK (1 test)
```

A failing ScalaTest test also has only 1 tests block. Both specs2 and ScalaTest return exit code of `1` when the tests are set to fail.

I'm sort of out of ideas. Would appreciate any thoughts on this. Thanks!

**Comment by etorreborre** [comment]
If you want to test it you can grab `specs2-common-3.6.6-20151204011838-90b7de9` and `specs2-junit-3.6.6-20151204011838-90b7de9`.

By the way the tests were not executed twice but the internal JUnit reporting machinery was reporting 2 runs.

**Comment by orrsella** [comment]
Thanks @etorreborre for the quick response as always! Indeed I now only see one test run, but for some reason integration with Bazel still isn't working. I'm looking into it to try and understand where the problem lies. Will update if I find anything interesting.

**Comment by etorreborre** [comment]
Ok, please let me know if you find anything I can do.

**Comment by orrsella** [comment]
Update: specs2 works great with Bazel. It turns out that the problem was a missing jar from the classpath, namely `scodec-bits`. The missing jar caused the execution of assertions to fail/stop the test silently, with the runner reporting 0 tests ran. The reason the jar was missing is because dependencies in Bazel aren't transitive and need to be managed explicitly. As a side note, the "problem" of reporting 2 runs wasn't the cause and doesn't effect the integration. Thanks again for your help. If interested, you can play with Bazel and scala in [this repo](https://github.com/orrsella/bazel-example).

**Comment by etorreborre** [comment]
Good to know, I'm happy I could fix the double reporting anyway.
