### ISSUE TITLE
Expose an aggregator POM

### ISSUE THREAD

**Issue by ittaiz** [etorreborre/specs2#445]
Hi,
Specs2 used to have an aggregator pom which you removed, I think so that people will use the finer grain bits.
I've stumbled on to a few cases where I don't care enough or I need enough bits where I'd rather use everything.
Especially since usually these aren't transitive dependencies (usually test scope) and aren't deployed to production.
WDYT about re-exposing such an aggregator POM?
I even thought about "open sourcing" such an aggregator but it felt too ridiculous to open-source one POM file.

**Comment by etorreborre** [comment]
Yes I removed it because I was not using it and it was often falling behind the rest. The best would be to have a sbt plugin/task producing the file during the release process. Otherwise please open a PR with such a POM. I will merge it and try to keep it up to date.

**Comment by ittaiz** [comment]
First of all thanks for the super prompt reply!
Your level of responsiveness is really impressive :)
If you're ok with it I'd rather not write an sbt plugin/task since I've only worked with sbt for really small projects.
If that's ok, I'll open a PR with that POM soon.

Thanks!

**Comment by ittaiz** [comment]
Hi,
Quick Q- I tried to look for the previous pom file so I can know what's the outline of the content and where to put it but was unable. Can you point me in the right direction or commit?

Thanks

**Comment by etorreborre** [comment]
You mean this file: https://github.com/etorreborre/specs2/blob/master/pom.xml? I actually didn't realise it was still there, I thought I removed it!

**Comment by ittaiz** [comment]
I saw it but the "specs2_2.10.1" artifactId threw me off.
I was thinking more of something like a simple [aggregator pom](https://gist.github.com/ittaiz/2f43eb754b82ed52bcb2)
where to use you just add
```xml
        <dependency>
            <groupId>org.specs2</groupId>
            <artifactId>specs2_2.11</artifactId>
            <version>3.5</version>
            <type>pom</type>
            <scope>test</scope>
        </dependency>
```

**Comment by etorreborre** [comment]
Ok, I created such a file. Can you please tell me if it works ok for you? I also specified the versions for each dependency but I don't know if it is redundant or not.

**Comment by ittaiz** [comment]
Hi,
Is it published anywhere? [maven central](http://search.maven.org/#search%7Cga%7C1%7Cspecs2_2.11) doesn't show it

**Comment by etorreborre** [comment]
Sorry it is not published anywhere yet because I need to figure out how to amend my publish process to publish that pom file as an artifact.

**Comment by ittaiz** [comment]
got you, i'll check it out and "clean install" and check.
btw, you can change the packaging type to by jar which will generate an empty jar with the pom.
The main advantage is that people depend on it in a way they are more accustomed to (now they need to add <type>pom</type> in the declaration). Another possible advantage is that it might be easier for you to deploy it don't know.
The main con is that it's a bit of a hack to have an empty jar.
WDYT?

**Comment by ittaiz** [comment]
This seems to have died after 3.7
Any particular reason?

**Comment by etorreborre** [comment]
No idea. I don't have much time to investigate this right now but I reopen this issue to be aware of it.

**Comment by ittaiz** [comment]
i took a look and it seems that it just requires manual action for each release.
The actions are updating the version and pushing to maven central.
Maybe the issue should be to somehow bind this to sbt to get automation?

**Comment by etorreborre** [comment]
@ittaiz I have updated the pom but I still don't know how I can push it to maven-central (or sonatype). Do you know how to do that?

**Comment by ittaiz** [comment]
yes but it's not that easy :( How do you do it today? maybe use bintray?

**Comment by etorreborre** [comment]
For specs2 jars I use the sonatype sbt plugin. But this publishes sbt modules, not a single file. Maybe the easiest thing would be to create a specs2-pom module and publish this using the sonatype plugin?

**Comment by ittaiz** [comment]
sounds like it. Maybe it will also ease keeping the version in sync for
future versions?

**Comment by etorreborre** [comment]
Better late than ever I hope this is going to work: https://oss.sonatype.org/content/repositories/releases/org/specs2/specs2_2.12/3.8.9/specs2_2.12-3.8.9.pom.

**Comment by ittaiz** [comment]
Indeed! Thanks!

**Comment by ittaiz** [comment]
sorry for being so troublesome but it seems to have died again after 3.8.9 :(

**Comment by etorreborre** [comment]
I won't be around my laptop for the next week. Do you want to see if you can put it back for 4.x and make a PR?
