### ISSUE TITLE
Mocking method with by-name parameter calls mock 3 times instead of 1

### ISSUE THREAD

**Issue by williamho** [etorreborre/specs2#450]
I'm trying to mock a method that has a call-by-name parameter (`body`) and need to test that something gets called inside the body, as follows (simplified version of actual code):

```scala
import org.specs2.mutable._
import org.specs2.mock.Mockito

class Spec extends Specification with Mockito {
  class Timer {
    // Want to mock this method to just return `body`
    def time(body: => String): String = {
      val start = System.currentTimeMillis()
      val result = body
      val end = System.currentTimeMillis()
      println(s"${end - start}ms")

      result
    }

    def thisShouldBeCalledOnce(): String = "hello"
  }

  class MyClass(timer: Timer) {
    def doSomething(): String = {
      //println("inside method `doSomething`")

      timer.time {
        //println("inside method `doSomething` in `timer.time`")
        timer.thisShouldBeCalledOnce()
      }
    }
  }

  "timer.thisShouldBeCalledOnce should be called once" >> {
    val timer = mock[Timer]
    timer.thisShouldBeCalledOnce returns "hi"

    timer.time(anyString) answers { (params: Any, mock: Any) =>
      //println("inside `answers`, before params match")
      params match {
        case Array(f: Function0[String] @unchecked) => f()
      }
    }

    val c = new MyClass(timer)
    c.doSomething()
    there was one(timer).thisShouldBeCalledOnce() // Is actually called 3 times
  }
}
```

I expect `timer.thisShouldBeCalledOnce` to be called one time, but for some reason, when I run the test, it's called 3 times.

```
[error] x timer.thisShouldBeCalledOnce should be called once
[error]  The mock was not called as expected:
[error]  timer.thisShouldBeCalledOnce();
[error]  Wanted 1 time:
[error]  -> at Spec$$anonfun$1$$anonfun$apply$5.apply(Spec.scala:43)
[error]  But was 3 times. Undesired invocation:
[error]  -> at Spec$MyClass.doSomething(Spec.scala:23) (Spec.scala:43)
```

If I uncomment the `println` statements, I see that the mocked `timer.time` actually gets called twice before the method is actually mocked, and then called one time after:

```
inside method `doSomething`
inside method `doSomething` in `timer.time`
inside method `doSomething` in `timer.time`
inside `answers`, before params match
inside method `doSomething` in `timer.time`
```

Might be related to #428, but the fixes in that thread didn't seem to work for me.

Through google search, I found a blog post from 2014 with the same issue: [http://qiita.com/suikwasha/items/1d8ed9fca42ec732bce8](http://qiita.com/suikwasha/items/1d8ed9fca42ec732bce8#%E4%BD%95%E6%95%85%E3%81%8B3%E5%9B%9E%E5%91%BC%E3%81%B0%E3%82%8C%E3%81%A6%E3%81%97%E3%81%BE%E3%81%86%E3%83%A2%E3%83%83%E3%82%AF)
(the post is in Japanese and I can't really read it, but I don't think there was a solution/workaround)

**Comment by etorreborre** [comment]
Mockito is a tricky to deal with from a Scala perspective but what you are trying to do is even trickier. You are mocking a class, `Timer` and then expecting to have a method being called from a mocked method. 
This is generally not the case with mocks. When you mock an object, its methods are being mocked and not supposed to be executed at all. 

We should find a way to restructure this code so that it become more testable without having to change the existing specs2/mockito integration which is already pretty fragile. Could you tell me more about your exact use-case?

**Comment by williamho** [comment]
Sure -- the timer example was a bit contrived. The real use case is that there's an API helper class that has methods for making requests to a specific remote API, as well as methods that handle caching of those requests.

So instead of a method for timing, you can imagine something for caching, e.g.

```scala
class ApiHelper(/* a bunch of constructor args here */) {
  private val cache = ??? // ScalaCache

  def cached[T](key: String, ttl: Int)(body: => Future[T]): Future[T] = {
    // if key is in cache, retrieve and return it
    // otherwise evaluate body, put it in cache, and return it
  }

  def makeCachedRequest(id: Int): Future[Int] = cached(id, 123) {
    // make some request to the remote API
  }

  def makeUncachedRequest(id: Int): Future[Int] = {
    // make some different request, uncached
  }

  // a ton of other methods for requesting different API endpoints
}
```

this `ApiHelper` is meant to be instantiated once and shared by classes that need to access the API, so essentially serves as a shared cache with some utility functions.

there's some methods on other classes like:

```scala
def requestIfUserHasPermission(userId: Int): Future[Int] =
  apiHelper.cached(s"someKey-$userId", 500) {
    for {
      user <- database.get(userId) if user.hasPermission()
      response <- apiHelper.makeUncachedRequest(userId)
    } yield response
  }
```

I want to test the methods that use `apiHelper.cached`, but usually `apiHelper` is mocked, since it's kind of annoying to create one. And in most cases I just want to test that something gets called inside an `apiHelper.cached` block.

I guess one way to avoid mocking the call-by-name method is to just write a wrapper trait around the underlying ScalaCache and use that as a dependency in `ApiHelper` and any classes that use `ApiHelper` (implement a dummy `cached` method that just returns the body, only for use in tests) instead of using it directly.

**Comment by etorreborre** [comment]
What if you changed your API to:
```scala
class ApiHelper(...) {
  def cached(key: String, ttl: Int): Future[Option[Int]] = ???
}
```
Your current call is:
```scala
def defaultAction[Future[Int]]

apiHelper.cached(key)(defaultAction)
```
It becomes
```scala
apiHelper.cached(key).flatMap(_.fold(Future.apply)(defaultAction))
```
And with a bit of syntactic sugar:
```scala
implicit class FutureOption[T](f: Future[Option[T]]) {
  def orElse(other: =>Future[T]): Future[T] = 
    f.flatMap(_.fold(Future.apply)(other))
}

apiHelper.cached(key).orElse(defaultAction)
```

So my suggestion is that there is a useful combinator hidden here which you could expose to:

- simplify your testing
- reuse in other parts of your application

**Comment by williamho** [comment]
I see what you mean -- I could then easily mock `apiHelper.cached(key)` to return `Future(None)`, which means `defaultAction` always gets evaluated.

But on the other hand, it loses the convenience of having the result of `defaultAction` be automatically be added back to the cache (with the original specified key and TTL) after it's evaluated.

If I go with that route, everyone that calls `orElse` will need to remember to add it to the cache at the end of the passed-in block, or I'll need to make some cache-specific variant of `FutureOption` that maintains the key and TTL values and puts them in the cache after `orElse` is called. There's definitely a bunch of ways to do it, but I guess this isn't specifically related to specs2/mockito anymore.

I guess if the original code snippet is supposed to have undefined behavior (or if it's a "won't fix"), feel free to close this, and I'll decide on some solution that doesn't involve mocking a `Function0` parameter.

**Comment by etorreborre** [comment]
Actually I didn't understand the behaviour of adding the default to the cache in that case. Then maybe my  other question is why do you need a byname parameter for the `Future`. I suspect that is because you are using Scala futures which are really annoying because they start being evaluated as soon as they are created. This is a major reason why I prefer Scalaz Futures.

Anyway I am going to fix this for now because I'm afraid to break things in the mockito integration to cover for a use case where I feel (I might be wrong) that there are better ways to structure the code.

**Comment by williamho** [comment]
Yeah, it's using a scala Future (the entire `cached` method is just a thin wrapper around ScalaCache's [`cachingWithTTL`](https://github.com/cb372/scalacache#basic-cache-operations) which also accepts a call-by-name Future)

Anyway, thanks for the help -- the original way I structured the tests definitely seemed problematic, even as I was initially writing them.
