### ISSUE TITLE
weird behaviour with futures and await

### ISSUE THREAD

**Issue by kpbochenek** [etorreborre/specs2#452]
Hi,

I have some intuition why this might happen but I would love to get an explanation what is going on.

Snippet: https://gist.github.com/kpbochenek/487a3f62540a1bf68d7d

Each test creates an Actor and wants to get answer on a question(totally isolated tests).
Because we get future from asking actor I want to match it with ".await"
But because in my real example actor refreshes it's state every Xms it might not return correct answer on a first try. That's why I am using "eventually" and asking actor in a loop

With my snippet half of tests fail and half passes randomly.

But when running with "sequential" all tests pass.

I assume I hit some deadlock / threads exhaustion? and it somehow blocks checking result?

Another thing is, when I do block instead of ".await" in all cases:
```Await.result((underTest ? ADD(1, 1)).mapTo[RESULT], 1.second) must beEqualTo(RESULT(2))```
Then all works just fine.

**Comment by etorreborre** [comment]
Is `actorOf` creating one new actor each time or retrieving the same one?

**Comment by kpbochenek** [comment]
a new one.

**Comment by etorreborre** [comment]
Maybe you can try to use the `TestKit` execution context instead of the one from specs2?

You can create one with `ExecutionEnv.fromExecutionContext`.

**Comment by etorreborre** [comment]
Did you make any progress on this issue?

**Comment by kpbochenek** [comment]
I tried to tackle this today but again no luck(just for curiosity, I eventually went with "sequential").

When I have less than 8 tests in suite it works fine, with 8 or more it starts spinning infinitely.

I also tried to reproduce this on futures but I had some issues with mutable.Specification.
I tried immutable one but it looks like it runs only 4 tests in parallel.

I don't have time to investigate more, snippet to reproduce this issue is still valid.
If you can apply some changes to make this tests pass that would solve this issue.

If you don't want to investigate I think this can be closed.

**Comment by kpbochenek** [comment]
Oh actually I tried again with futures and it is the same (> 7 tests of this type)
```
"t1" in { implicit ec: ExecutionEnv =>

      val f: Future[String] = computeFuture()

      eventually {

        f must beEqualTo("Completed").await

      }
    }```

`def computeFuture(): Future[String] = Future {
    println("COMPLETED!")
    "Completed"
  }`

this time:

import scala.concurrent.ExecutionContext.Implicits.global

so no Akka at all

**Comment by etorreborre** [comment]
Would you mind to extend your gist as a small github project that I could investigate on my side? I am tempting to more or less keep the same code and remove specs2 progressively from the picture to see what happens. For example use JUnit for the tests with specs2 matchers.

**Comment by kpbochenek** [comment]
https://github.com/kpbochenek/specs2-thread-issue

> sbt "testOnly com.kpbochenek.ClassFutureSpec

**Comment by etorreborre** [comment]
There is a workaround [here](https://github.com/kpbochenek/specs2-thread-issue/pull/1).

**Comment by kpbochenek** [comment]
Thanks for investigation.
It's bad you weren't able to find a root cause to this :/

I hope others won't hit the same issue.

**Comment by etorreborre** [comment]
I had a look at this issue yesterday and I am still investigating it. There should be no difference in how the execution environment is used so I would like to understand what is going on there.
