### ISSUE TITLE
"must not(be)" doesn't fail

### ISSUE THREAD

**Issue by holograph** [etorreborre/specs2#458]
The following assertion passes, but should actually fail:

```scala
        val a = 8
        a must not(be)
```

This might seem a bit strange, but using `be` is a useful pattern in matcher libraries, for example:
```scala
case class Result(...)
case class ServerResponse(results: Seq[Result], ...)

def haveResults(resultsMatcher: Matcher[Seq[Result]] = be): Matcher[ServerResponse] =
  resultsMatcher ^^ { resp: ServerResponse => resp.results }

val someResult: Result = ...
serverResponse1 must haveResults(contain(someResult))
serverResponse2 must not(haveResults())     // <-- This fails

**Comment by etorreborre** [comment]
Hi Tomer, I think `not(beEmpty)` should be used here:
```scala
class TestMutableSpec extends mutable.Specification with ResultMatchers {

  case class Result(n: Int)
  case class ServerResponse(results: Seq[Result])

  def haveResults: Matcher[ServerResponse] =
    haveResults(not(beEmpty[Seq[Result]]).updateMessage(_ => "There are no results"))

  def haveResults(resultsMatcher: Matcher[Seq[Result]]) =
    resultsMatcher ^^ { resp: ServerResponse => resp.results }

  val someResult: Result = Result(3)

  eg { ServerResponse(List(someResult)) must haveResults(contain(someResult)) }
  eg { ServerResponse(List(someResult)) must haveResults }
  eg { ServerResponse(List()) must not(haveResults) }

  eg { (ServerResponse(List(someResult)) must not(haveResults)) must beFailing }
  eg { (ServerResponse(List()) must haveResults) must beFailing }
}
```

All those examples pass as expected
```
[info] TestMutableSpec
[info]
[info] + ServerResponse(List(someResult)) must haveResults(contain(someResult))
[info] + ServerResponse(List(someResult)) must haveResults
[info] + ServerResponse(List()) must not(haveResults)
[info] + (ServerResponse(List(someResult)) must not(haveResults)) must beFailing
[info] + (ServerResponse(List()) must haveResults) must beFailing
[info]
```

Also note the overloading on `haveResults` which allows to drop the parentheses :-).

**Comment by holograph** [comment]
That's a nice workaround, but is less generic: we use this pattern for many different things, not just sequences, it was just the most ready-to-hand example. I still feel the original version ought to work -- we've a number of (transparently) failing tests because of it. Unfortunately I couldn't figure out why it fails -- applying a NeutralMatch to a NotMatch seems like it *should* have the right result.

**Comment by etorreborre** [comment]
The problem I see with using `be` alone is that it will give the same answer *regardless of the actual value*, but you expect different results with those 2 examples:
```
// this one should fail
ServerResponse(List(someResult)) must not(haveResults)

// this one should succeed
ServerResponse(List()) must not(haveResults)
```

**Comment by holograph** [comment]
That is a fair point, in retrospect that isn't particularly useful. There might still be a bug here, but I'll leave that consideration to you :-)

**Comment by etorreborre** [comment]
Yes, `be` is more like a syntactic trick to enable expressions like `path must be aFile`. But the meaning of these things taken separately might not make any sense. I will have a look at `not(be)` though to see if anything is missing and if "fixing" it doesn't break anything else.

**Comment by holograph** [comment]
Cool. I'll keep track, thanks!
