### ISSUE TITLE
Transient match error

### ISSUE THREAD

**Issue by samueltardieu** [etorreborre/specs2#459]
Using specs2 3.7.

From time to time (I'd say once every 100 runs) I get a match error while the pattern does match:

```
[info] db.insert() should
[info]   + be able to insert a new document with an explicit id
[info]   + be able to insert a new document with an explicit non-ASCII id
[info]   + be able to insert a new document with an explicit id in batch mode
[info]   + be able to insert a new document with an implicit id
[error]   x be able to insert a new document with an implicit id in batch mode
[error]    '4dc4acc6dc17b92f48bc1f2dfd2e6aa4' doesn't match '[0-9a-f]{32}' (DatabaseSpec.scala:118)
```

(the check is from https://github.com/samueltardieu/canape/blob/master/src/test/scala/DatabaseSpec.scala#L117-L119)

The id indeed matches the regular expression, confirmed with cut-n-paste in the REPL:

``` scala
scala> """^[0-9a-f]{32}$""".r.findFirstIn("4dc4acc6dc17b92f48bc1f2dfd2e6aa4")
res0: Option[String] = Some(4dc4acc6dc17b92f48bc1f2dfd2e6aa4)
```

**Comment by etorreborre** [comment]
Unfortunately I cannot reproduce on my side but I suspect that this could be because of concurrent calls to `Pattern.compile` under the covers. Can you please try this version `3.7.2-20160307084521-17e150e` (I have just added a `synchronized` block around the `compile` call)?

As a temporary work-around you can also set your specification as `sequential` but it's a shame since you made efforts to keep all your tests independent :-).

**Comment by samueltardieu** [comment]
Indeed, I prefer to have all my tests run in parallel and stress the database rather than keep it slow and easy and discover that the database itself has problems handling the stress at run time.

I indeed suspected `Pattern.compile`, but even when stressing it explicitly I can't provoke a failure. The test below should make 1,000,000 calls to `Pattern.compile` and to `matching`, with a parallelism level of 100 (as soon as a future is completed, a new one will be started to maintain the requested parallelism level).

```scala
import java.util.regex.Pattern

import akka.actor.ActorSystem
import akka.stream.ActorMaterializer
import akka.stream.scaladsl.Source
import org.specs2.mutable._

import scala.concurrent.duration._
import scala.concurrent.{Await, Future}

class MatcherSpec extends Specification {

  "The matcher" should {

    "not choke on parallel invocations" in {
      implicit val system = ActorSystem()
      implicit val materializer = ActorMaterializer()
      implicit val dispatcher = system.dispatcher
      val r = Source(1 to 1000000).mapAsyncUnordered(100) { _ =>
        Future { "4dc4acc6dc17b92f48bc1f2dfd2e6aa4" must be matching Pattern.compile("""[0-9a-f]{32}""") }
      }.runFold(true)(_ && _.isSuccess)
      Await.result(r, 5.seconds) must beTrue
    }
  }

}
```

So I'd say parallelism in `Pattern.compile` is not a likely suspect.

I'll check with the new version, but drawing conclusions will be difficult since the failure is not systematic.

**Comment by samueltardieu** [comment]
Same error (after 5 tries) with `3.7.2-20160307084521-17e150e`.

```
[error]   x be able to insert a new document with an implicit id
[error]    '4dc4acc6dc17b92f48bc1f2dfd60247c' doesn't match '[0-9a-f]{32}' (DatabaseSpec.scala:114)
```

I'll have to investigate further on my side. Thanks for your time!

**Comment by samueltardieu** [comment]
Interestingly, I've changed the test into:

``` scala
    "be able to insert a new document with an implicit id in batch mode" in new freshDb {
      val r = waitForResult(insertedId(db.insert(JsObject(Nil), batch = true)))
      r must have size 32
      r must be matching "[0-9a-f]{32}"
    }
```

and I can still make it fail the same way at the `matching` line (I wondered if some extra invisible characters could have been inserted in the string). It really has size 32. This is puzzling:

```
[error]   x be able to insert a new document with an implicit id
[error]    '4dc4acc6dc17b92f48bc1f2dfd696e68' doesn't match '[0-9a-f]{32}' (DatabaseSpec.scala:114)
```

**Comment by etorreborre** [comment]
I couldn't make it fail either but that's the only source of non thread-safety I could see. Thanks for keeping me updated!

**Comment by etorreborre** [comment]
Any news on this?

**Comment by samueltardieu** [comment]
I haven't had time to investigate. You can close it if you want, I'll reopen if I have any news.

**Comment by etorreborre** [comment]
Ok, thanks.
