### ISSUE TITLE
org.specs2.runner.files can not create specification

### ISSUE THREAD

**Issue by shell-software** [etorreborre/specs2#464]
Hi,

I faced with a problem while running **org.specs2.runner.files** from the Maven exec plugin: **Specs2** does not run specification and logs the following warning:
```
Warnings:

[warn] cannot create specification <Spec class name>
```
which I found in **SpecificationsFinder#findSpecifications**:

```scala
 SpecificationStructure.create(name, classLoader, Some(env)).map(s => Option(s)).
          orElse(warn("[warn] cannot create specification "+name).as(none[SpecificationStructure]))
```

Wondering whether I'm doing something wrong or is it an issue?

My dependencies:
**org.scala-lang:scala-library:2.12.0-M3**
**org.specs2:specs2-core_2.12.0-M3:3.7.2**

Maven **Exec** plugin configuration:
```xml
<plugin>
	<groupId>org.codehaus.mojo</groupId>
	<artifactId>exec-maven-plugin</artifactId>
	<version>1.4.0</version>
	<configuration>
		<executable>java</executable>
		<arguments>
			<argument>-classpath</argument>
			<classpath />
			<argument>org.specs2.runner.files</argument>
			<argument>html</argument>
			</arguments>
	</configuration>
</plugin>
```

**Comment by etorreborre** [comment]
It is hard to tell without knowing more about the project state. Can you check that the class with the right name is indeed on the classpath?

Can you create an instance of that class? (maybe try with a trivial spec).

**Comment by shell-software** [comment]
Great! You are completely right!

**Exec** plugin is watching for *classes* directory, instead of *test-classes*, so actually **Specs2** can't find the class. One more thing that confused me is that instead of **ClassNotFoundException** it was just a warning message

Thanks again and sorry for taking your time
Have a nice day
