### ISSUE TITLE
!pandoc exclamation mark is treated as a history expansion feature in bash

### ISSUE THREAD

**Issue by shell-software** [etorreborre/specs2#468]
Hi

This is a quite tricky issue

The same command
```shell
java -cp <CPASSPATH> org.specs2.runner.files html !pandoc
```
on Windows OS runs successfully, while on Unix OS with bash terminal fails

This happens, because exclamation mark (**!**) is treated as a history expansion feature in bash and thus **!pandoc** argument needs to be enclosed in single quotes: **'!pandoc'**. 
This, however, results in supporting multiple scripts for different OS types or _if condition_ block

The suggestion is to replace the exclamation mark for the pandoc negate argument by something else (like **pandoc false**)

Also, as far as pandoc is not enabled by default on most systems, it would be better to disable it by default

Thank you

**Comment by etorreborre** [comment]
Did you actually tried `pandoc false`? This should work.

**Comment by shell-software** [comment]
It works. Thanks
