### ISSUE TITLE
Specs2 release for 2.12.0-M4?

### ISSUE THREAD

**Issue by SethTisue** [etorreborre/specs2#469]
The Scala team would be interested in hearing if you encounter any trouble with publishing Specs2 for M4 (which is already on Maven Central and will be announced shortly).

We're aware, of course, that you'll need to wait until your dependencies have been published. (M4 and M3 generate pretty dramatically different bytecode, so it's highly unlikely you could get away with using old M3 stuff.)

pinging some maintainers of known dependencies: @milessabin @rickynils @xuwei-k 

* [x] Scalatest
* [x] macro-paradise
* [x] macro-compat
* [x] Shapeless
* [x] ScalaCheck 1.11
* [x] ScalaCheck 1.12
* [x] ScalaCheck 1.13
* [x] Scala.js
* [x] scalaz 7.1
* [x] scalaz 7.2
* [x] scalaz-stream
* [ ] kind-projector

**Comment by xuwei-k** [comment]
scalaz depends on kind-projector and scala-js: @non @sjrd

**Comment by SethTisue** [comment]
re: Scala.js, at https://groups.google.com/d/msg/scala-internals/NZ4pVWB4HWY/CWtJJCqbHAAJ @sjrd said he won't be able to publish until after April 10

**Comment by etorreborre** [comment]
Thanks @SethTisue for pinging me, I will trigger a build as soon as my dependencies are ready (this also includes scalaz-stream).

**Comment by milessabin** [comment]
Scala.js is the blocker for shapeless too. Is there anyone else who can make the release in @sjrd's absence?

**Comment by sjrd** [comment]
No, I'm the only one with all the necessary accesses. Unfortunately, this is the one week of the year where I'm completely unable to do it.

**Comment by milessabin** [comment]
Given how fundamental Scala.js has become to the whole Scala ecosystem it might be an idea to consider widening the pool of people who are able to publish releases (something I need to do for shapeless too).

**Comment by milessabin** [comment]
FYI, shapeless is blocked on macro-compat (me) which is blocked on macro-paradise. I've pinged @xeno-by to publish a build.

**Comment by milessabin** [comment]
And it seems that macro-paradise has a scalatest dependency ... pinging @bvenners.

**Comment by SethTisue** [comment]
@bvenners told me yesterday he's working on a ScalaTest release

**Comment by bvenners** [comment]
Chee seng got them released last night:

https://oss.sonatype.org/content/groups/public/org/scalatest/scalatest_2.12.0-M4/

**Comment by xeno-by** [comment]
Released macro-paradise 2.1.0 for 2.12.0-M4: https://oss.sonatype.org/content/repositories/releases/org/scalamacros/paradise_2.12.0-M4/.

**Comment by milessabin** [comment]
I've just published macro-compat-1.1.1, and shapeless-2.2.5 and 2.3.0 for Scala 2.12.0-M4, JVM only.

**Comment by InTheNow** [comment]
This gist is 4 months old, would it be useful to have a new one? Please don't say "yes" unless you need it, as there is an hour or so worth of work:
https://gist.github.com/InTheNow/4c49a2e90c6bc1f7b1e8

**Comment by rickynils** [comment]
ScalaCheck 1.11.6 and 1.12.5 for Scala 2.12.0-M4 are available (JVM only). 1.13.0 is not, due to https://github.com/rickynils/scalacheck/issues/230

**Comment by xuwei-k** [comment]
scalaz 7.2 depends on kind-projector and Scala.js, but scalaz 7.1 depends on scalacheck only. I will release scalaz 7.1 for Scala 2.12.0-M4 ASAP

**Comment by etorreborre** [comment]
Note that specs2 depends on scalaz 7.2 so I still will need to wait for that one before I publish (and it also depends on ScalaCheck 1.13).

**Comment by sjrd** [comment]
Scala.js 0.6.8 is published on Sonatype for 2.12.0-M4. It should hit Central soon.

Note that earlier releases of Scala.js will *not* work at all with M4.

**Comment by xuwei-k** [comment]
I just published Scalaz 7.2.2 for 2.12.0-M4. but
- without `scalaz-scalacheck-binding_sjs0.6_2.12.0-M4` because `scalacheck_sjs0.6_2.12.0-M4` not available
- with some hack (due to `kind-projector_2.12.0-M4` not available) https://github.com/xuwei-k/scalaz/commit/745f1f15c329ec6594f4d15d5ac1f60896b95271

**Comment by xuwei-k** [comment]
https://twitter.com/mpilquist/status/720380316951658496

**Comment by etorreborre** [comment]
@rickynils what are you eventually going to do with rickynils/scalacheck#230? @adriaanm @SethTisue should I publish a specs2 version with ScalaCheck on `2.12.0-M3`?

**Comment by rickynils** [comment]
@etorreborre There will be a ScalaCheck 1.13.1 release for M4 soon

**Comment by etorreborre** [comment]
@rickynils cool, thanks

**Comment by rickynils** [comment]
@etorreborre ScalaCheck 1.13.1 is available now (for both JVM and JS). Built with Scala 2.10, 2.11 and 2.12.0-M4.

**Comment by bvenners** [comment]
We released:

ScalaTest 3.0.0-M16-SNAP4 for Scala 2.12.0-M4

For Scala.js and JVM that uses the new ScalaCheck release 1.13.1 for same.

The previous release we did for 2.12.0-M4 did not include a release for Scala.js because of a missing ScalaCheck dependency.

Bill

**Comment by holograph** [comment]
+1, hopefully this is the last blocker for wix/accord#69...

**Comment by etorreborre** [comment]
@holograph @SethTisue @xuwei-k I eventually did a release without `kind-projector`: [`specs2 3.7.3`](https://oss.sonatype.org/content/repositories/releases/org/specs2/specs2-core_2.12.0-M4/3.7.3).

**Comment by xuwei-k** [comment]
https://oss.sonatype.org/content/repositories/releases/org/specs2/specs2-scalacheck_2.12.0-M4/3.7.3/specs2-scalacheck_2.12.0-M4-3.7.3.pom

Why `specs2-scalacheck_2.12.0-M4` depends on `scalacheck_2.12.0-M3` ? it should be `scalacheck_2.12.0-M4` ?

**Comment by holograph** [comment]
There still appears to be a dependency on kind-projector:

```scala
[info] com.wix:accord-specs2-3-x_2.12.0-M4:0.6-SNAPSHOT [S]
[info]   +-com.wix:accord-api_2.12.0-M4:0.6-SNAPSHOT [S]
[info]   +-org.specs2:specs2-core_2.12.0-M4:3.7.3 [S]
[info]     +-org.scala-lang:scala-reflect:2.12.0-M4 [S]
[info]     +-org.specs2:specs2-matcher_2.12.0-M4:3.7.3 [S]
[info]       +-org.specs2:specs2-common_2.12.0-M4:3.7.3 [S]
[info]         +-org.scala-lang:scala-reflect:2.12.0-M4 [S]
[info]         +-org.scalaz.stream:scalaz-stream_2.12.0-M4:0.8.1a [S]
[info]         | +-org.scalaz:scalaz-concurrent_2.12.0-M4:7.2.2 [S]
[info]         | | +-org.scalaz:scalaz-core_2.12.0-M4:7.2.2 [S]
[info]         | | +-org.scalaz:scalaz-effect_2.12.0-M4:7.2.2 [S]
[info]         | |   +-org.scalaz:scalaz-core_2.12.0-M4:7.2.2 [S]
[info]         | |
[info]         | +-org.scalaz:scalaz-core_2.12.0-M4:7.2.2 [S]
[info]         | +-org.scodec:scodec-bits_2.12.0-M4:1.0.12 [S]
[info]         |
[info]         +-org.scalaz:scalaz-concurrent_2.12.0-M4:7.2.2 [S]
[info]         | +-org.scalaz:scalaz-core_2.12.0-M4:7.2.2 [S]
[info]         | +-org.scalaz:scalaz-effect_2.12.0-M4:7.2.2 [S]
[info]         |   +-org.scalaz:scalaz-core_2.12.0-M4:7.2.2 [S]
[info]         |
[info]         +-org.scalaz:scalaz-core_2.12.0-M4:7.2.2 [S]
[info]         +-org.scalaz:scalaz-effect_2.12.0-M4:7.2.2 [S]
[info]         | +-org.scalaz:scalaz-core_2.12.0-M4:7.2.2 [S]
[info]         |
[info]         +-org.spire-math:kind-projector_2.12.0-M3:0.7.1 [S]
[info]           +-org.scala-lang:scala-compiler:2.12.0-M3 [S]
[info]             +-org.scala-lang.modules:scala-parser-combinators_2.12.0-M3:1.0.4 [S]
[info]             +-org.scala-lang:scala-reflect:2.12.0-M3 (evicted by: 2.12.0-M4)
[info]             +-org.scala-lang:scala-reflect:2.12.0-M4 [S]
[info]
```

**Comment by xuwei-k** [comment]
> There still appears to be a dependency on kind-projector:

I write `ExclusionRule `
https://github.com/scalikejdbc/scalikejdbc/pull/513/files

**Comment by holograph** [comment]
Workaround:

```scala
libraryDependencies += ( "org.specs2" %% "specs2-core" % "3.7.3" ).exclude( "org.spire-math", "kind-projector_2.12.0-M3" )
```

This could of course break at runtime due to kind-projector being compiled with M3.

**Comment by xuwei-k** [comment]
I just submit a pull request. kind-projector dependency is unnecessary in runtime (need only in compile-time).
https://github.com/etorreborre/specs2/pull/476

**Comment by etorreborre** [comment]
@holograph @xuwei-k sorry I'll try to publish a `3.7.3.1` without this dependency to get a "clean" release.

**Comment by etorreborre** [comment]
@holograph @xuwei-k I hope [this one](https://oss.sonatype.org/content/repositories/releases/org/specs2/specs2-core_2.12.0-M4/3.7.3.1) is better.

**Comment by holograph** [comment]
Yep, that works. No workarounds required. Thanks!
