### ISSUE TITLE
Add SBT tags to specs2 tests

### ISSUE THREAD

**Issue by pauldraper** [etorreborre/specs2#470]
The allows for advanced control over the concurrency of specs.

For example, if some specifications are memory intensive, they could be tagged with `memory` and SBT could limit the number of memory-intensive tasks that are run. Or if some specifications rely on shared resources (file system, database, etc.), they could be tagged and SBT could ensure that only one is run at a time. SBT allows extensive customization of concurrency, across all tasks (tests or otherwise): http://www.scala-sbt.org/0.13/docs/Parallel-Execution.html

Currently, specs2 defines no tags on SBT tasks. https://github.com/etorreborre/specs2/blob/SPECS2-3.7.3/core/src/main/scala/org/specs2/runner/SbtRunner.scala#L30

The mechanism for tagging would have to be such that it could be determined quickly without running the tests. Perhaps the existing `tag` fragment would work. I'm not sure.

Here is an example using annotations:

http://stackoverflow.com/questions/36585241/use-sbt-tags-to-control-specs2-test-concurrency

**Comment by etorreborre** [comment]
Can you please try out `3.7.3-20160413201225-0d1765e`? It grabs the tags from the specification (created with `tag` or `section`) and pass them to sbt.

**Comment by etorreborre** [comment]
Hi @pauldraper, did that work for you?

**Comment by etorreborre** [comment]
I am closing this for now, please reopen if this doesn't work for you.
