### ISSUE TITLE
Hitting Thread limit

### ISSUE THREAD

**Issue by PhillipTaylor** [etorreborre/specs2#472]
Hi, we use this pattern when writing tests..

```
[snip]
      val application = new GuiceApplicationBuilder()
        .overrides(bind[Options].toInstance(mocks.options))
        .build

      "return all the customer facing options when dc is specified" in new WithApplication(application) {

        // Test
        val blahResponse =
          route(mocks.requestWithDC)
            .get
[snip]
```

However our application hits Linux's limit of max threads per process. Looking at Thread namespace confirms this as well as checking /proc/<pid>/tasks and changing ulimit.

With the pattern we've gone down, that is, each test defining a new "WithApplication" and each application being unique, how can I ensure that the threads are closed/ended/cleaned up before the next one beings please?

**Comment by etorreborre** [comment]
All the futures you are using are using the global execution context, aren't they?

One solution might be to create on `ExecutionContext` per spec and use that one to create your futures:
```scala
class MySpec extends Specification with AfterAll {

   implicit lazy val ec: ExecutionContext = // create the Execution context 

   def afterAll = ec.shutdown

   "your tests here".txt

}

**Comment by PhillipTaylor** [comment]
Thank you
