### ISSUE TITLE
duplicate http in scm:connection 

### ISSUE THREAD

**Issue by MasseGuillaume** [etorreborre/specs2#473]
https://github.com/etorreborre/specs2/blob/master/project/build.scala#L380

I assume you ment:
` <connection>scm:http:http://etorreborre@github.com/etorreborre/specs2.git</connection>`

Outch, 3 strikes he's out !

**Comment by etorreborre** [comment]
Thanks, 3 times :-) (the beauty of copy-pasting ...).
