### ISSUE TITLE
XmlMatchers beEqualToIgnoringSpace also ignores order

### ISSUE THREAD

**Issue by joescii** [etorreborre/specs2#474]
I discovered that `beEqualToIgnoringSpace` from `XmlMatchers` also ignores the order of child nodes. To my surprise, this passes:

```scala
"beEqualToIgnoringSpace" should {
  "check the order of nodes" in {
    val a =
      <parent>
        <order></order>
        <matters></matters>
      </parent>

    val b =
      <parent>
        <matters></matters>
        <order></order>
      </parent>

    a must beEqualToIgnoringSpace(b)
  }
}
```

Console output:

```text
[info] Xml Spec
[info]
[info] beEqualToIgnoringSpace should
[info]   + check the order of nodes
[info]
[info]
[info] Total for specification Xml Spec
[info] Finished in 40 ms
[info] 1 example, 0 failure, 0 error
[info]
```

Of course, `beEqualTo` fails this comparison as I would expect.  

I have it reproduced [here](https://github.com/joescii/specs2-samples) using Scala `2.11.7` and Specs2 `3.7`.

**Comment by etorreborre** [comment]
This is indeed a bug. Please try the fix in `3.7.3-20160425073425-05c39c0`.

**Comment by joescii** [comment]
Did you publish that version? The default resolver (`resolvers += "scalaz-bintray" at "http://dl.bintray.com/scalaz/releases"`) doesn't find it. I also don't see a tag for it in github which I could publish locally.

**Comment by etorreborre** [comment]
It is published on Sonatype. The fix should be in [this jar](https://oss.sonatype.org/content/repositories/releases/org/specs2/specs2-matcher-extra_2.11/3.7.3-20160425073425-05c39c0/) in particular.
