### ISSUE TITLE
Guide for 3.8.1 and 3.8.2 returns 404

### ISSUE THREAD

**Issue by avdv** [etorreborre/specs2#480]
I didn't know where else to put this, but accessing https://etorreborre.github.io/specs2/guide/SPECS2-3.8.2/org.specs2.guide.UserGuide.html returns a 404 page not found.

It seems in https://github.com/etorreborre/specs2/tree/gh-pages/guide/SPECS2-3.8.1 and https://github.com/etorreborre/specs2/tree/gh-pages/guide/SPECS2-3.8.2 has something gone amiss or wasn't generated.

**Comment by etorreborre** [comment]
Yes, I'm on it, thanks, I'll keep you updated. In the meantime you can use https://etorreborre.github.io/specs2/guide/SPECS2-3.8/org.specs2.guide.UserGuide.html.

**Comment by etorreborre** [comment]
Please the latest one for [3.8.3](https://etorreborre.github.io/specs2/guide/SPECS2-3.8.3/org.specs2.guide.UserGuide.html) now.
