### ISSUE TITLE
module not found: org.specs2#specs2-common_2.11;3.8.3

### ISSUE THREAD

**Issue by an-tex** [etorreborre/specs2#482]
Hi,

having 

`"org.specs2" %% "specs2-core" % "3.8.3" % "test"`

in by build.sbt leads to:

```
[warn]  Note: Unresolved dependencies path:
[warn]          org.specs2:specs2-common_2.11:3.8.3
[warn]            +- org.specs2:specs2-matcher_2.11:3.8.3
[warn]            +- org.specs2:specs2-core_2.11:3.8.3 ([..]/build.sbt#L1-12)
[warn]            +- [...]:commontest_2.11:1.0-SNAPSHOT
```
Adding

`https://oss.sonatype.org/content/repositories/releases`

as a resolver doesn't help either.

Cheers

**Comment by etorreborre** [comment]
This module is now available on Sonatype: https://oss.sonatype.org/content/repositories/releases/org/specs2/specs2-common_2.11/3.8.3

but I am republishing other modules which were not released for some unknown reason.
