### ISSUE TITLE
scalaz-stream issues

### ISSUE THREAD

**Issue by apurva-sharma** [etorreborre/specs2#485]
[error] java.lang.NoClassDefFoundError: scalaz/stream/Process$WriterSyntax$
[error]
[error] STACKTRACE
[error]   org.specs2.data.Fold$$anonfun$runFoldLast$1.apply(Fold.scala)
[error]   org.specs2.data.Fold$$anonfun$runFoldLast$1.apply(Fold.scala:179)
[error]   scalaz.syntax.BindOps$$anonfun$$greater$greater$1.apply(BindSyntax.scala:19)
[error]   scalaz.concurrent.Task$$anonfun$flatMap$1$$anonfun$1.apply(Task.scala:36)
[error]   scalaz.concurrent.Task$$anonfun$flatMap$1$$anonfun$1.apply(Task.scala:36)
[error]   scalaz.concurrent.Task$.Try(Task.scala:387)
[error]   scalaz.concurrent.Task$$anonfun$flatMap$1.apply(Task.scala:36)
[error]   scalaz.concurrent.Task$$anonfun$flatMap$1.apply(Task.scala:34)
[error]   scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
[error]   scalaz.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:58)
[error]   scalaz.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:58)
[error]   scalaz.concurrent.Future.step(Future.scala:109)
[error]   scalaz.concurrent.Future.listen(Future.scala:75)
[error]   scalaz.concurrent.Future.runAsync(Future.scala:142)
[error]   scalaz.concurrent.Future.run(Future.scala:159)
[error]   scalaz.concurrent.Task.attemptRun(Task.scala:104)
[error]   org.specs2.control.ActionT$.fromTask(ActionT.scala:125)
[error]   org.specs2.control.ActionTSupport$class.fromTask(ActionT.scala:188)
[error]   org.specs2.control.package$Actions$.fromTask(package.scala:29)
[error]   org.specs2.reporter.Reporter$$anonfun$report$1.apply(Reporter.scala:47)
[error]   org.specs2.reporter.Reporter$$anonfun$report$1.apply(Reporter.scala:37)
[error]   org.specs2.runner.SbtRunner$$anonfun$specificationRun$1$$anonfun$2.apply(SbtRunner.scala:75)
[error]   org.specs2.runner.SbtRunner$$anonfun$specificationRun$1$$anonfun$2.apply(SbtRunner.scala:75)
[error]   org.specs2.control.ActionT$$anonfun$flatMap$1$$anonfun$apply$2.apply(ActionT.scala:36)
[error]   org.specs2.control.ActionT$$anonfun$flatMap$1$$anonfun$apply$2.apply(ActionT.scala:36)
[error]   org.specs2.control.StatusT$$anonfun$flatMap$1.apply(StatusT.scala:20)
[error]   org.specs2.control.StatusT$$anonfun$flatMap$1.apply(StatusT.scala:19)
[error]   scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
[error]   scalaz.WriterT$$anonfun$flatMapF$1.apply(WriterT.scala:63)
[error]   scalaz.WriterT$$anonfun$flatMapF$1.apply(WriterT.scala:62)
[error]   scalaz.effect.IO$$anonfun$flatMap$1$$anonfun$apply$9.apply(IO.scala:62)
[error]   scalaz.effect.IO$$anonfun$flatMap$1$$anonfun$apply$9.apply(IO.scala:61)
[error]   scalaz.Free$$anonfun$flatMap$1$$anonfun$apply$1.apply(Free.scala:60)
[error]   scalaz.Free$$anonfun$flatMap$1$$anonfun$apply$1.apply(Free.scala:60)
[error]   scalaz.Free.resume(Free.scala:72)
[error]   scalaz.Free.go2$1(Free.scala:118)
[error]   scalaz.Free.go(Free.scala:122)
[error]   scalaz.Free.run(Free.scala:172)
[error]   scalaz.effect.IO$class.unsafePerformIO(IO.scala:22)
[error]   scalaz.effect.IOFunctions$$anon$6.unsafePerformIO(IO.scala:227)
[error]   org.specs2.runner.SbtRunner$$anonfun$newTask$1$$anon$4.execute(SbtRunner.scala:40)
[error]   sbt.ForkMain$Run$2.call(ForkMain.java:294)
[error]   sbt.ForkMain$Run$2.call(ForkMain.java:284)
[error]   java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error]   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error]   java.lang.Thread.run(Thread.java:745)
[error]
[error]
[error] This looks like a specs2 exception...
[error] Please report it with the preceding stacktrace at http://github.com/etorreborre/specs2/issues
[error]

My build.sbt has:

resolvers += "scalaz-bintray" at "http://dl.bintray.com/scalaz/releases"
"// http://mvnrepository.com/artifact/org.scalaz.stream/scalaz-stream_2.11
libraryDependencies += "org.scalaz.stream" % "scalaz-stream_2.11" % "0.8"

**Comment by etorreborre** [comment]
I don't know which version of specs2 you are using but you possibly need version 8a of scalaz-stream instead of 8.

BTW there is no more dependency on Scalaz stream from specs2 > 3.8.

**Comment by etorreborre** [comment]
Is this fixed now?

**Comment by etorreborre** [comment]
I'm closing this issue. Please re-open it if you still have a problem with scalaz-stream.
