### ISSUE TITLE
Publish 3.8.3 build for Scala 2.10

### ISSUE THREAD

**Issue by kflorence** [etorreborre/specs2#486]
Seems to be missing: https://oss.sonatype.org/content/repositories/releases/org/specs2/specs2-core_2.10/

**Comment by etorreborre** [comment]
Sorry about that, I'll check that tomorrow and re-publish.

**Comment by etorreborre** [comment]
There was an error when generating scaladoc for some modules under Scala 2.10. This is fixed now.
