### ISSUE TITLE
Scala 2.12.0-M5

### ISSUE THREAD

**Issue by schmitch** [etorreborre/specs2#489]
Do you mind making a new release for Scala 2.12.0-M5?
http://www.scala-lang.org/news/2.12.0-M5/

Thanks!

**Comment by etorreborre** [comment]
I was thinking about doing that and then I realized I had a few dependencies. I can at the very least publish a version of `specs2-core` as soon as there is a version of Scalaz 7.2.2 for Scala 2.12.0-M5.

So I created an [issue](https://github.com/scalaz/scalaz/issues/1215) for it which you can watch.

**Comment by etorreborre** [comment]
Scalaz is now published and I was planning to do a quick publish of `specs2-core`. Unfortunately there seems to be some new compilation errors with `M5`. I need to investigate that tomorrow.

**Comment by etorreborre** [comment]
@schmitch you should now be able to use [`specs2-core-3.8.4`](https://oss.sonatype.org/content/repositories/releases/org/specs2/specs2-core_2.12.0-M5/3.8.4) with Scala `2.12.0-M5`.

**Comment by schmitch** [comment]
Thanks

**Comment by schmitch** [comment]
Unfortunatly my project I want to test also uses:
- specs2-junit
- specs2-mock
- specs2-matcher-extra

However I know that its hard to publish version when it depends on other projects, but when you do it (sooner or later) and run into trouble's and your time is limited, just ping me and I try to help, too.

**Comment by etorreborre** [comment]
Please wait a bit, I should be able to publish those when I arrive at work this morning.

**Comment by schmitch** [comment]
Don't rush!

**Comment by etorreborre** [comment]
Those jars have now been published.
