### ISSUE TITLE
Errors during spec initialization are swallowed entirely

### ISSUE THREAD

**Issue by Joe-Edwards** [etorreborre/specs2#495]
The following spec:
```
import org.specs2.mutable.Specification

class TestSpec extends Specification {
  throw new Exception("Useful exception message")

  "A test that clearly isn't going to run" should {
    "not matter" in {
      ok
    }
  }
}
```
outputs:
```


This looks like a specs2 exception...
Please report it with the preceding stacktrace at http://github.com/etorreborre/specs2/issues
 
```
(Blank lines and all). I'd expect to see (at least) the exception message so I can diagnose what's going on.

By doing a little bit of digging, I think the problem is in SpecificationStructure.create where it falls back to using the companion object. If I change the specification to be an object instead of a class, then it prints a big stacktrace as I'd expect.

**Comment by Joe-Edwards** [comment]
Sorry! I looked at https://mvnrepository.com/artifact/org.specs2/specs2_2.11 and assumed 3.7 was the latest release. Importing 3.8.4 properly fixes it, thanks.

**Comment by vpatryshev** [comment]
Thank you! (Took me time to figure out what the heck is going on...)
