### ISSUE TITLE
Result.foreach calls each case twice?

### ISSUE THREAD

**Issue by kflorence** [etorreborre/specs2#496]
```scala
"tests" should {
  "pass" in {
    Result.foreach("+-.,!@#$%^&*();\\/|<>\"'".toList) { char =>
      println(char)
      char.toString === char.toString
    }
  }
}
```

This test seems to be causing each `Result` to be executed twice:

```
+
+
-
-
.
.
,
,
!
!
@
@
#
#
$
$
%
%
^
^
&
&
*
*
(
(
)
)
;
;
\
\
/
/
|
|
<
<
>
>
"
"
'
'
```

FYI this is with version 3.6.5, I have not tried the most recent version.

**Comment by etorreborre** [comment]
Thanks for reporting this. This is an issue with a byname parameter evaluated twice. It is fixed in `3.8.4-20160723101923-39456c4`.
