### ISSUE TITLE
Extend rendering framework to combine markdown with scalatex and use full fledged strategic term rewriting

### ISSUE THREAD

**Issue by SemanticBeeng** [etorreborre/specs2#498]
I suggest there should be a conversion to Markdown AST and not Markdown text.

There is this other thing called Scalatex that could be mixed it to enhance the text formatting power to generate nicely formatted user guide pages.

See [Scalatex rationale](http://archive.is/3fJrJ#selection-7891.1-7925.204) for motivation.

It would be nice for the conversion from `Fragments*` (this is like an AST, no?) to a presentation AST (markdown + scalatex) so it is all strongly typed. 
As "strongly typed" Markdown we can use https://github.com/timo-schmid/mdtags or  https://github.com/stanch/scalatags-md, for example.

The strategic programming part could be done with `Kiama` so that users have full freedom to convert spec code to other things using strategic programming. 

Thoughts?

**Comment by SemanticBeeng** [comment]
The suggestion to bring strategic programming in is likely also motivated by the hope to become able to wrap R code with Specs2 tests and thus glue R code with typesafe Scala code. Like discussed in the past, the runtime engine could be `Renjin` or `FastR`. This way `Specs2` (or `StrategicSpec` ;-) ) could become the way to port/bring scientific code to Scala.

**Comment by etorreborre** [comment]
I want to leave the possibility to write some simple markdown as text. 

But adding a more predictable html/markdown using tags is a good idea. This is however not something I can put high on my priorities list at the moment :-(. 

This might not be too hard to do for a motivated individual, as a separate module, though (like `specs2-scalatex` :-). The idea would be to

 - add a new `Description` type to be used in fragments
 - add an implicit to be associate such a description to some execution code as a `Fragment`
 - create a new `Reporter` to translate this markup to html

**Comment by etorreborre** [comment]
I am closing this as an "issue" which could be reopened as a discussion on the [mailing-list](https://groups.google.com/forum/#!forum/specs2-users).
