### ISSUE TITLE
User guide renders badly on iOS safari

### ISSUE THREAD

**Issue by lunaryorn** [etorreborre/specs2#499]
Hello,

on iOS Safari the navigation menu obscures the content of the [user guide](https://etorreborre.github.io/specs2/guide/SPECS2-3.8.4/org.specs2.guide.UseScalaCheck.html).  Below is a screenshot of the zoomed page:

![img_2792](https://cloud.githubusercontent.com/assets/224922/17359534/4a3155ea-5967-11e6-9da5-07e0f066b8d1.PNG)

**Comment by etorreborre** [comment]
This is where I would be happy to get some help :-).

I know next to nothing about how to use CSS to do proper rendering on different devices and I don't have time right now to pour into this. So a PR would be welcome :-)!
