### ISSUE TITLE
org.specs2.runner.files ability to find specs in classpath

### ISSUE THREAD

**Issue by valdemaras-wix** [etorreborre/specs2#503]
We're working on a bazel rule to run specs2 tests.

Currently the files runner can find the tests in a source folder - but what would be really useful is to find the tests in the classpath according to a pattern. Basically instead of searching for files in _filesrunner.basePath_ look for them in the classpath.

This is currently not possible, right? Do you think it would be good to have this feature in files runner? Perhaps we could even do a pull request for this.

**Comment by etorreborre** [comment]
Yes at first glance this is a good idea.

**Comment by etorreborre** [comment]
Do you have any plan for a PR or should I close it for now?

**Comment by etorreborre** [comment]
I am closing this for now because I don't have time to work on it. Please open a PR if you want to contribute :-).
