### ISSUE TITLE
Scala 2.12 RC1

### ISSUE THREAD

**Issue by schmitch** [etorreborre/specs2#504]
Would be great to have a release against Scala 2.12 RC1.
I at least need:
- "specs2-core"
- "specs2-junit"
- "specs2-mock"
- "specs2-matcher-extra"

So probably need to wait if dependencies are on Scala 2.12 RC1

**Comment by etorreborre** [comment]
You can use `specs2-core_2.12.0-RC1-3.8.4-20160909214031-92b5f32` (and others) until I do a proper `3.8.5` release.

**Comment by etorreborre** [comment]
`3.8.5`
