### ISSUE TITLE
This looks like a specs2 exception

### ISSUE THREAD

**Issue by vn971** [etorreborre/specs2#505]
Reporting as described in SBT console:

```
[error] 
[error] java.lang.NullPointerException
[error] 
[error] STACKTRACE
[error]   java.util.GregorianCalendar.<init>(GregorianCalendar.java:739)
[error]   java.util.Calendar$Builder.build(Calendar.java:1482)
[error]   sun.util.locale.provider.CalendarProviderImpl.getInstance(CalendarProviderImpl.java:88)
[error]   java.util.Calendar.createCalendar(Calendar.java:1666)
[error]   java.util.Calendar.getInstance(Calendar.java:1613)
[error]   org.specs2.time.HmsTimer$class.getTime(Timer.scala:84)
[error]   org.specs2.time.SimpleTimer.getTime(Timer.scala:87)
[error]   org.specs2.time.HmsTimer$class.start(Timer.scala:21)
[error]   org.specs2.time.SimpleTimer.start(Timer.scala:87)
[error]   org.specs2.specification.process.DefaultExecutor$$anonfun$executeFragment$1$$anonfun$apply$6.apply(Executor.scala:131)
[error]   org.specs2.specification.process.DefaultExecutor$$anonfun$executeFragment$1$$anonfun$apply$6.apply(Executor.scala:130)
[error]   org.specs2.specification.core.Fragment.updateExecution(Fragment.scala:44)
[error]   org.specs2.specification.process.DefaultExecutor$$anonfun$executeFragment$1.apply(Executor.scala:130)
[error]   org.specs2.specification.process.DefaultExecutor$$anonfun$executeFragment$1.apply(Executor.scala:129)
[error]   org.specs2.specification.process.DefaultExecutor$$anonfun$sequencedExecution$1.executedFragment$lzycompute$1(Executor.scala:104)
[error]   org.specs2.specification.process.DefaultExecutor$$anonfun$sequencedExecution$1.org$specs2$specification$process$DefaultExecutor$class$$anonfun$$executedFragment$1(Executor.scala:104)
[error]   org.specs2.specification.process.DefaultExecutor$$anonfun$sequencedExecution$1$$anonfun$4.apply(Executor.scala:110)
[error]   org.specs2.specification.process.DefaultExecutor$$anonfun$sequencedExecution$1$$anonfun$4.apply(Executor.scala:110)
[error]   scalaz.concurrent.Task$.Try(Task.scala:385)
[error]   org.specs2.data.Processes$$anonfun$start$1.apply(Processes.scala:96)
[error]   org.specs2.data.Processes$$anonfun$start$1.apply(Processes.scala:96)
[error]   scalaz.concurrent.Future$$anonfun$apply$15$$anon$3.call(Future.scala:367)
[error]   scalaz.concurrent.Future$$anonfun$apply$15$$anon$3.call(Future.scala:367)
[error]   java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error]   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error]   java.lang.Thread.run(Thread.java:745)
[error] 
[error] 
[error] This looks like a specs2 exception...
[error] Please report it with the preceding stacktrace at http://github.com/etorreborre/specs2/issues
[error]  
```

**Comment by vn971** [comment]
sbtVersion 0.13.12
specs2-core 3.3.1
specs2-junit 3.3.1

**Comment by etorreborre** [comment]
Can you please also post your JDK version?

**Comment by etorreborre** [comment]
And maybe bit more context:

 - is it deterministic?
 - does this happen for all specs?
 - what is your timezone?
 - what is your Java default locale? `Locale.getDefault(Locale.Category.FORMAT)`

**Comment by vn971** [comment]
@etorreborre , thanks for your reply.
```
java -version
openjdk version "1.8.0_102"
OpenJDK Runtime Environment (build 1.8.0_102-b14)
OpenJDK 64-Bit Server VM (build 25.102-b14, mixed mode)
```
* it's not deterministic. I've actually seen specs2 stack traces from time to time, but usually there is a good explanation in that you were doing something strange. This time it was just a normal compilation/test cycle though, so I guessed I could write.
* it just happened once and then disappeared. I'm not sure whether it was a single test or many, because I was using `~testOnly .......`. The error happened _after_ some tests started running (I see their output in the terminal), but _before_ the test name was printed in the console.
* `java.util.TimeZone.getDefault
res1: java.util.TimeZone = sun.util.calendar.ZoneInfo[id="Europe/Moscow",offset=10800000,dstSavings=0,useDaylight=false,transitions=79,lastRule=null]`
* LOCALE might be a bit unusual: `java.util.Locale.getDefault(java.util.Locale.Category.FORMAT)
res3: java.util.Locale = en_DK`

**Comment by vn971** [comment]
Note that everything is all right for me (obviously), so I'm just writing because specs2 asked to do that. Feel free to close or anything.

**Comment by vn971** [comment]
Also, AFAIremember there was a keyboard interruption around that time (I think I pressed Enter once or twice).

**Comment by etorreborre** [comment]
Thanks for the info. I can see several possibilities here:

 - your tests are manipulating some of the static internals of `Calendar`
 - `Calendar.getInstance` is not threadsafe

I am going to close this issue for now since this is a rare occurrence. Let's reopen it if it becomes a problem.

**Comment by vn971** [comment]
Sure, thanks again.
