### ISSUE TITLE
NoReferenceDsl trait should also override `mutableLinkFragment` and `mutableSeeFragment`

### ISSUE THREAD

**Issue by sirthias** [etorreborre/specs2#514]
The `NoReferenceDsl` trait implementation in 3.8.5 appears to be incomplete.
I have to manually override the `mutableLinkFragment` and `mutableSeeFragment` implicits to really prevent collisions on `~` pimps.

**Comment by etorreborre** [comment]
Hi Matthias, you can use `3.8.5-20161006092037-b43b121` which contains a trait for mutable specs: `org.specs2.specification.dsl.mutable.NoReferenceDsl`.

**Comment by sirthias** [comment]
Thanks, Eric!
