### ISSUE TITLE
implicit val order = inOrder(mock) also needed for just one mock

### ISSUE THREAD

**Issue by lukas-c-wilhelm** [etorreborre/specs2#518]
When verifying the order in which mocks are called, I noticed that an implicit order of mocks is also needed if there is just one mock involved. This works, but should not
```
import org.specs2.mock.Mockito
import org.specs2.Specification

class Test extends Specification with Mockito{

  override def is=s2"""
      test $test
    """

  def test = {
    val s = mock[List[String]]

    s.contains("s")
    s.contains("t")

    //implicit val mockOrder = inOrder(s)

    there was one(s).contains("t") andThen one(s).contains("s")
  }
}
```
Also, I noticed that for mutable specifications it fails even if the mock order is correct. This fails, but should not
```
package persistence

import org.specs2.mock.Mockito
import org.specs2.mutable.Specification

class Test extends Specification with Mockito{

  override def is=s2"""
      test $test
    """

  def test = {
    val s = mock[List[String]]

    s.contains("s")
    s.contains("t")

    implicit val mockOrder = inOrder(s)

    there was one(s).contains("s") andThen one(s).contains("t")
  }
}
```
Overall this is not that bad and one can work with it. But if this is intended, then maybe the documentation should be updated.

**Comment by etorreborre** [comment]
I just published `specs2-mock_2.11-3.8.5-20161026191608-25b45a8` if you want to try this quick fix. Also I changed the User Guide to indicate that it is necessary to use `inOrder` even if it is just for one mock.
