### ISSUE TITLE
Scala 2.12 released

### ISSUE THREAD

**Issue by mslinn** [etorreborre/specs2#519]
Looking forward to a version of Specs2 that is compatible

**Comment by etorreborre** [comment]
I will release it as soon as shapeless and scalacheck are out since I'm depending on those 2 libs for some modules.

**Comment by etorreborre** [comment]
Waiting on [ScalaCheck #291](https://github.com/rickynils/scalacheck/issues/291) and [Shapeless #651](https://github.com/milessabin/shapeless/issues/651).

**Comment by xuwei-k** [comment]
https://oss.sonatype.org/content/repositories/releases/com/chuusai/shapeless_2.12/

**Comment by etorreborre** [comment]
I'm on it today.

**Comment by etorreborre** [comment]
Done.
