### ISSUE TITLE
Github-Pages: Learn Example leads to a 404 

### ISSUE THREAD

**Issue by Jentsch** [etorreborre/specs2#522]
Hi,
I found a broken link on the Github-Pages. The Link Learn -> Examples (Screenshot below) in the menu leads nowhere. Probably a tag for 3.8.6 release is missing.

Kind regards,
Daniel

![spectacle x14127](https://cloud.githubusercontent.com/assets/818446/19998498/60def316-a26d-11e6-9cb2-125ccc83cf43.png)

**Comment by etorreborre** [comment]
Thanks this is fixed now.
