### ISSUE TITLE
Errors thrown outside of a spec lead to "This looks like a specs2 exception" without stack trace

### ISSUE THREAD

**Issue by richardTingle** [etorreborre/specs2#524]
If a specification is written with a runtime error that is outside of a specification an error which has no stacktrace and blames specs2 is raised rather than a full exception.

> com.xxxxx.EvilSpec$
>
>
>This looks like a specs2 exception...
>Please report it with the preceding stacktrace at http://github.com/etorreborre/specs2/issues
 
In the below example the json is invalid (missing a comma). This was running under intelliJ in a scala play application

```
class EvilSpec  extends Specification{

  var jsonString =
    s"""
      {
        "id": "1"
        "pubRefs": "hi"
      }
    """
  Json.parse(jsonString)

  "EvilSpec" should {

    "show a stacktrace on error" in {
      Json.parse(jsonString)
      1 mustEqual 1

    }

  }

}
```

**Comment by etorreborre** [comment]
Which version of specs2 are you using? Can you please try with `3.8.6`?

**Comment by richardTingle** [comment]
I seem to be on 3.6.6 which is what specs2 % Test in my build.sbt gets me. I'll see if I can get a later version manually

![image](https://cloud.githubusercontent.com/assets/6330028/20678316/26f45e28-b58e-11e6-9099-9489e86d69f2.png)


libraryDependencies ++= Seq(
  ......
  ......
  , specs2 % Test
)

**Comment by etorreborre** [comment]
I tested `3.8.6` with Intellij and it works fine for me:
![image](https://cloud.githubusercontent.com/assets/10988/20700129/bb874334-b60b-11e6-8b94-3b5370be168b.png)

**Comment by etorreborre** [comment]
Any news?

**Comment by richardTingle** [comment]
Yes that does indeed seem to resolve the issue. Thanks
