### ISSUE TITLE
Specs2 with latest scalaz (7.2.7)

### ISSUE THREAD

**Issue by noahlz** [etorreborre/specs2#525]
I need to upgrade to a version of Specs 2.x but with support for the latest scalaz 7.2.7

In my SBT config, I declare:

`"org.specs2" %% "specs2" % "2.5" % "it,test"`

and also 

`"org.scalaz" %% "scalaz-core" % "7.2.7"`

However, build fails at artifact resolution with:

```
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.scalaz.stream#scalaz-stream_2.10;0.5: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn]  Note: Unresolved dependencies path:
[warn]          org.scalaz.stream:scalaz-stream_2.10:0.5
[warn]            +- org.specs2:specs2_2.10:2.5 (/home/nzucker/project/build.scala#L194)
[warn]            +- com.novus:properties_2.10:5.1.1-SNAPSHOT
[info] Resolving org.scalaz.stream#scalaz-stream_2.10;0.5 ...
```

What additional steps can I take to resolve this?

**Comment by noahlz** [comment]
Looks like this is an issue similar to #295?

**Comment by noahlz** [comment]
I made a cursory attempt to just depend on 0.8.6 but it does not compile...

Waiting for feedback.

**Comment by etorreborre** [comment]
I think that you indeed need to add the bintray resolver to your build 
```
resolvers += "scalaz-bintray" at "http://dl.bintray.com/scalaz/releases"
```
You can also just add `specs2-core` and maybe `specs2-junit` to your build instead of the complete `specs2` jar (which disappears in 3.x anyway).

**Comment by noahlz** [comment]
Depending on the sub-modules did the trick! I had to depend on specs2-scalacheck as well.

Thanks!
