### ISSUE TITLE
si2712plugin should not be added when running on Scala 2.12

### ISSUE THREAD

**Issue by SethTisue** [etorreborre/specs2#526]
this is causing a build failure in the Scala 2.12 community build. the responsible commit is: https://github.com/etorreborre/specs2/commit/048431856f823b89e4c71ec1de0f0a3530bae612

at https://github.com/milessabin/si2712fix-plugin, Miles himself recommends only using the plugin with Scala 2.10, not 2.11. so I'm a little surprised to see the hardcoded _2.11.8 version

it doesn't matter to me what you do for 2.11, but in any case, can you make it so that you check `CrossVersion.partialVersion(scalaVersion)` and _not_ enable the plugin when you're on 2.12?

in the meantime, in the community build I will freeze specs2 at a recently green version (5f35b86b451b0c6f231b514c84c48c39508bf8cf)

**Comment by SethTisue** [comment]
P.S. I'm puzzled that if you think you need the plugin, that you _don't_ seem to be using `-Ypartial-unification` on 2.12...?

**Comment by etorreborre** [comment]
Thanks @SethTisue for the heads-up. I will fix this during the week-end (and use `-Ypartial-unification` for 2.12).

**Comment by etorreborre** [comment]
@SethTisue the build is [fixed now](https://travis-ci.org/etorreborre/specs2/builds/181144145).

**Comment by SethTisue** [comment]
thanks Eric! giving it a try over at https://github.com/scala/community-builds/pull/428
