### ISSUE TITLE
Specs finder ignores exceptions in constructor of specs (no FAIL written)

### ISSUE THREAD

**Issue by gdiet** [etorreborre/specs2#527]
In the attached example project [example.zip](https://github.com/etorreborre/specs2/files/642136/example.zip), when in SBT I execute "testOnly example.FinderIndex", it seems all Tests are OK. However, in the constructor of BadSpec an Exception is thrown - but the finder silently ignores it.

I would like the finder to add some sort of failure to the test protocol when an exception is thrown in a specification class constructor.

Yes I know that setup should be done in the beforeAll() method - Exceptions there are reported alright. However, there are a number of pitfalls an ordinary programmer can fall into so a constructor exception is thrown. And simply ignoring them is not the best option :)

We like the finders - we think they are a definite improvement over manually creating a linked index (also in the example - see LinkedIndex.scala). Can the Exception-in-constructor problem be fixed (or is a good workaround available that does not include executing the tests twice)?

**Comment by etorreborre** [comment]
Thanks for the small project where I could reproduce the issue. This is a bug which I just fixed but I currently have some issues releasing a new version.

**Comment by etorreborre** [comment]
Ok, done `3.8.6-20161209163125-607148b`.

**Comment by gdiet** [comment]
Thank you for the quick reaction on this issue, and for the great testing stuff you provide in the specs2 project!

**Comment by etorreborre** [comment]
@gdiet please ignore that version because it has serious issues and go back to `3.8.6` for now. Thanks and sorry for that.
