### ISSUE TITLE
Regression: 'beforeAll' may not be invoked

### ISSUE THREAD

**Issue by peter-empen** [etorreborre/specs2#528]
Hi Eric,

beforeAll/afterAll work as a charme with 3.8.6.

However, when switching to 3.8.6-20161209163125-607148b, we are observing the following regression:
When executing specs in a suite made up of several spec references, the specs2 execution engine may call for a given subspec

- beforeAll/afterAll pairweise as expected
- afterAll without calling beforeAll (regression) or
- neither beforeAll, nor afterAll (regression).

**Comment by etorreborre** [comment]
Would you have an example I could reproduce? I have made some substantial changes recently so it is possible that there is a regression.

**Comment by etorreborre** [comment]
I can reproduce a case where `beforeAll` is not called. I will fix and propose a new version.

**Comment by etorreborre** [comment]
This should be fixed in `3.8.6-20161219103851-1c1f07b` (available in a few minutes).
