### ISSUE TITLE
Could not find artifact org.specs2:specs2_2.12:pom:3.8.6

### ISSUE THREAD

**Issue by elega9t** [etorreborre/specs2#529]
Hi,

I am using org.specs2.mutable.SpecificationWithJUnit for my testing which used to be provided from org.specs2:specs2_2.11:pom dependency. After I updated scala 2.11 to 2.12, I noticed that there is no artifact for org.specs2:specs2_2.11:pom. Help please.

**Comment by etorreborre** [comment]
Can you try to add `"org.specs2" %% "specs2-junit" % "3.8.6"` to your build. This is how you should get the `specs2-junit` dependency.

**Comment by etorreborre** [comment]
Did that work for you? Please re-open if not.
