### ISSUE TITLE
Make compatible with Scalaz 7.3

### ISSUE THREAD

**Issue by sellout** [etorreborre/specs2#530]
I tried to do this myself by making the 7.1 version work, but it might require a separate set of artifacts?

I ran into two issues. The first (which I fixed) is that things like `Tree.leaf` are gone in Scalaz 7.3 (deprecated in 7.2), but it was easy to replace with `Leaf`. The other (which I couldn’t fix) is that the order of parameters to `tailRecM` changed betwen Scalaz 7.2 and 7.3, so that blows up anything using `BindRec`. I was hoping there was some syntax for tailRecM that would hide the difference in the type class, but no such luck.

I would be happy to submit a PR if anyone thinks they could help me sort out the `tailRecM` issue.

**Comment by etorreborre** [comment]
My good year resolution is to get rid of the Scalaz dependency by inlining it into specs2 and removing the parts I don't need. In the meantime we could try the following (ugly) workaround:
```
implicit def EffMonad[R] = new Monad[Eff[R, ?]] with BindRec[Eff[R, ?]] {
    def tailrecM[A, B](f: A => Eff[R, \/[A, B]])(a: A): Eff[R, B] =
      bind(f(a)) {
        case \/-(b)   => pure(b)
        case -\/(next) => tailrecM(f)(next)
      }

    def tailrecM[A, B](a: A)(f: A => Eff[R, \/[A, B]]): Eff[R, B] =
      bind(f(a)) {
        case \/-(b)   => pure(b)
        case -\/(next) => tailrecM(next)(f)
      }
```

Then each scalaz version would have its own definition.

I used to isolate differences between scalaz versions into different source packages and have sbt select the right one based on the scalaz version but in that case it means duplicating a big chunk of code.

Thanks a lot for your upcoming PR!

**Comment by sellout** [comment]
Cool. I think I got something working. PR coming shortly.
