### ISSUE TITLE
Mutable maps equality comparison fails

### ISSUE THREAD

**Issue by elahrvivaz** [etorreborre/specs2#538]
Using specs2 3.8.7, The following test fails on the `mustEqual`:

```
import org.junit.runner.RunWith
import org.specs2.mutable.Specification
import org.specs2.runner.JUnitRunner

@RunWith(classOf[JUnitRunner])
class MutableMapTest extends Specification {
  "mutable maps" should {
    "be equals" in {
      val m1 = scala.collection.mutable.HashMap.empty[String, Long].withDefaultValue(0)
      val m2 = scala.collection.mutable.HashMap.empty[String, Long].withDefaultValue(0)
      val keys = (0 to 100).map(_.toString)
      keys.foreach(k => m1(k) += 1)
      keys.reverse.foreach(k => m2(k) += 1)
      m1 == m2 must beTrue
      m1 mustEqual m2
    }
  }
}
```

It seems like it is falling to the GenTraversableOnce comparison in beTypedEqualTo, which fails due to the lack of ordering:

https://github.com/etorreborre/specs2/blob/SPECS2-3.8.6/matcher/src/main/scala/org/specs2/matcher/BeTypedEqualTo.scala#L49

Thanks,

**Comment by etorreborre** [comment]
Thanks for reporting this issue. In the next version `3.8.8` the equality matchers have been upgraded to support a better display of differences. This new version will also fix this issue.

You can access a preview with [`3.8.7-20170202003034-3739406`](`https://oss.sonatype.org/content/repositories/releases/org/specs2/specs2-core_2.11/3.8.7-20170202003034-3739406`).

**Comment by elahrvivaz** [comment]
thanks!
