### ISSUE TITLE
Int <: Any, but class ContainWithResultSeq is invariant in type T

### ISSUE THREAD

**Issue by algui91** [etorreborre/specs2#543]
Writing a test in which I want to check that all the values in a tuple are >0, I get the following error:

```
[error] ./src/test/scala/FlowCollectorSpec.scala:84: type mismatch;
[error]  found   : org.specs2.matcher.ContainWithResultSeq[Int]
[error]  required: org.specs2.matcher.ContainWithResultSeq[Any]
[error] Note: Int <: Any, but class ContainWithResultSeq is invariant in type T.
[error] You may wish to define T as +T instead. (SLS 4.5)
[error]         result must contain(allOf(be_>(0)))
```

The type of the tuple is `Tuple6[BigInt, BigInt, BigInt, Double, Double, Double]`

I am not able to get it to compile.

What is happening?

Regards

**Comment by etorreborre** [comment]
You have values of different types in your tuple so you won't be able to find a type `T` that is common to `BigInt` and `Double` and use `be_>(0)` which is expecting a `T` having a `Numeric` instance. If the values for your test are small (and not really big ints) you can convert all of them to `Double` and then you should be able to use `be_>(0)`.

**Comment by algui91** [comment]
Thanks, now I get:

```
[error]  found   : org.specs2.matcher.ContainWithResultSeq[Int]
[error]  required: org.specs2.matcher.Matcher[(Double, Double, Double, Double, Double, Double)]
[error]         result(0) must contain(allOf(be_>(0)))
```

**Comment by etorreborre** [comment]
Yes, now you need to transform your tuple into a `List` to be able to use `contain`. You can do that using shapeless.

**Comment by algui91** [comment]
It was simpler xD, I just needed to change

`result(0) must contain(allOf(be_>(0)))`

by 

`result(0) must contain(allOf(be_>(0.0)))`

**Comment by etorreborre** [comment]
Oh, great then!
