### ISSUE TITLE
Asserting failure of a Scalaz Task

### ISSUE THREAD

**Issue by SystemFw** [etorreborre/specs2#544]
Hi,

As far as I could tell, specs2 makes it easy to assert that a stdlib Future should fail with a specific exception by ``` myFuture  must throwA[MyException].await``` , but the same functionality is not readily available for Scalaz Task. 

Would you be interested in a pull request adding a similar Matcher for Task, e.g. ``` myTask must failWith[MyException]``` ?   

Alternatively, is there an easy way of achieving the above which I might have missed? The code for failWith is fairly small, but I still feel like it's an important enough use case to deserve a specific Matcher, your mileage may vary of course :)

**Comment by etorreborre** [comment]
I didn't realize that this was missing from the `TaskMatchers` trait. On the other hand you can always `attempt` a `Task` and then write `returnValue(beLeft[MyException])`. Anyway this seems like a useful addition if you want to make a PR.

**Comment by ChristopherDavenport** [comment]
May want to close now that its implemented. Tried to help and realized I had been beaten to the punch. :smile:

**Comment by etorreborre** [comment]
That's right, let's close.
