### ISSUE TITLE
Task Matchers Documentation

### ISSUE THREAD

**Issue by SystemFw** [etorreborre/specs2#547]
As far as I could tell, the matchers for scalaz Task are not documented in the User Guide, and one needs to look at the tests to learn how to use them.  Would you be interested in a PR to the Guide adding the missing docs?

**Comment by etorreborre** [comment]
Definitely :-).

**Comment by SystemFw** [comment]
Cool. I'll add something by next Monday (possibly earlier).

**Comment by etorreborre** [comment]
Thanks.

**Comment by SystemFw** [comment]
This should probably be closed now :)

**Comment by etorreborre** [comment]
Yes, let's close it now :-)
