### ISSUE TITLE
API incompatibility between 3.8.5 and 3.8.8

### ISSUE THREAD

**Issue by avdv** [etorreborre/specs2#550]
We have a library with some test utilities which is compiled against specs2 3.8.5 (scala 2.11).

When upgrading the specs2 module inside the project where we're using our library, we get this error running `sbt test`:

```
[error]      java.lang.NoSuchMethodError: Fatal execution error, caused by org.specs2.matcher.ValueCheck$.typedValueCheck(Ljava/lang/Object;)Lorg/specs2/matcher/BeEqualTypedValueCheck; 
```

**Comment by etorreborre** [comment]
That's right, the `implicit def typedValueCheck[T : Diffable](expected: T)` method has gained a new implicit parameter `Diffable[T]` to be able to do a better job at showing differences with matchers. I am sorry I didn't realize this would break binary compatibility.

**Comment by etorreborre** [comment]
@avdv is there anything else I can do for you? Can I close this issue?

**Comment by avdv** [comment]
Oh yeah, close it. Maybe a good idea to employ the sbt-mima-plugin to avoid those things in the future. Thanks!
