### ISSUE TITLE
Release processes are broken?

### ISSUE THREAD

**Issue by lukestephenson** [etorreborre/specs2#552]
Hello, 

I've noticed for 3.8.7 and 3.8.8 there is no git release / tag (see https://github.com/etorreborre/specs2/releases).

Also, the page hosting the release notes is not visible http://notes.implicit.ly/tagged/specs2.  May or may not be related.

**Comment by etorreborre** [comment]
I have fixed the git releases (I had just forgotten to push the tags) but the `notes.implicit.ly` site is down. I tried to contact @n8than via twitter but got no answer yet.
