### ISSUE TITLE
Some inheritance errors are not caught by the typecheck macro

### ISSUE THREAD

**Issue by SystemFw** [etorreborre/specs2#554]
Repro:
`Scala version = 2.11.8`
`Specs2 version = 3.8.8`

```Scala
import org.specs2.mutable.Specification
import org.specs2.execute.Typecheck._
import org.specs2.matcher.TypecheckMatchers

class ReproSpec extends Specification with TypecheckMatchers {
  "The typecheck macro" should {
    "allow testing for inheritance errors" in {
      trait Foo[A]
      // object A extends Foo[Int] with Foo[String] // Error: illegal inheritance
      // trait E extends E // Error: Illegal cyclic reference

      { typecheck("trait E extends E") must not succeed }
      { typecheck("object A extends Foo[Int] with Foo[String]") must not succeed }
    }

    "allow testing for conflicting members" in {
      trait A {
        def foo: Int = 1
      }
      trait B {
        def foo: Int = 1
      }
      // object C extends A with B // Error: object C inherits conflicting members

      typecheck("object C extends A with B") must not succeed 
    }.pendingUntilFixed("This is not caught")

    "allow testing for unimplemented members" in {
      trait Bar { def foo }
      //object B extends Bar // Error: object creation impossible

      typecheck("object B extends Bar") must not succeed 
    }.pendingUntilFixed("This is not caught")
  }
}
```

As an additional bit of weirdness, in some cases `typecheck` seems to be influenced by the presence of a blank line before the assertions.
```Scala
import org.specs2.mutable.Specification
import org.specs2.execute.Typecheck._
import org.specs2.matcher.TypecheckMatchers
import org.specs2.matcher.ResultMatchers

class ReproSpec extends Specification with TypecheckMatchers with ResultMatchers {
 "typecheck is influenced by blank lines, if there's code before them" >> {
    "Blank line before assertion" >> {
      trait Foo[A]
     
      { typecheck("object A extends Foo[Int] with Foo[String]") must succeed }
      { typecheck("object A extends Foo[Int] with Foo[String]") must not succeed }
    }.must(beFailing) // the test passes as the assertions fail

    "Comment instead of blank line" >> {
      trait Foo[A]
      // this breaks it
      { typecheck("object A extends Foo[Int] with Foo[String]") must succeed }
      { typecheck("object A extends Foo[Int] with Foo[String]") must not succeed }
    }.must(beFailing).pendingUntilFixed("the test fail as the assertions pass!")
  }
}
```

Sorry for the lenghty issue :)

**Comment by etorreborre** [comment]
Unfortunately I don't know how to fix this. I am basically using a macro calling `context.typecheck` here and I don't see what I could modify to fix this. The same issue occurs with Shapeless `illTyped` method so it might just be a limitation of macros + typechecking.

**Comment by SystemFw** [comment]
That's what I thought... I *suspect* different type of errors are caught during different phases of the compiler, and `context.typecheck` only covers some, which unfortunately makes this behaviour also hard to document.
I agree that there's nothing specs2 could do to fix this at the moment. If I find out more details/a solution I'll let you know

**Comment by etorreborre** [comment]
Thanks, I will close this for now, please reopen if you find anything new.

**Comment by SystemFw** [comment]
Just commenting here for posterity: the `typecheck` macro covers the `typer` phase of the compiler, the errors above are caught during the `refchecks` phase. That's not much one can do short of implementing a new macro to cover both compiler phases.

**Comment by etorreborre** [comment]
Do you know a way to access the typechecking of the `refchecks` phase with the current macro system?

**Comment by SystemFw** [comment]
From what I could see (brief look at the code, [quick question on reddit](https://www.reddit.com/r/scala/comments/5ztjrl/would_scalacsbt_benefit_from_something_like_rust/)), no.

I am also worried by the fact that a possible solution would be too tied to the scalac internals. I have been meaning to bring up this question to people that might know more (both the shapeless and scala.meta people come to mind), but I haven't quite gotten around to it.

**Comment by etorreborre** [comment]
Ok, thanks for (type :-)) checking.

**Comment by SystemFw** [comment]
:)
