### ISSUE TITLE
Can't use mutable.Spec/SpecWithJUnit with mutable.ExampleDsl

### ISSUE THREAD

**Issue by ittaiz** [etorreborre/specs2#565]
Hi,
When one wants to use a `mutable.Spec` (in our case SpecWithJUnit) and mix-in mutable.ExampleDsl they can not due to conflicting members from `ExampleDsl0` and `ExampleDsl1`.
My full intent was to use `ExampleDsl` with `FragmentsDsl` and `SpecWithJUnit` but the below is the minimal reproduction of the issue.
My current workaround is to just inherit from `mutable.SpecificationWithJUnit`
```scala
package com.ittaiz.specs2.example

import org.specs2.mutable.Spec
import org.specs2.specification.dsl.mutable.ExampleDsl

class ConflictTest extends Spec with ExampleDsl {
}
```
Error message:
```
Error:(6, 7) class ConflictTest inherits conflicting members:
  method blockExample in trait ExampleDsl0 of type (d: String)ConflictTest.this.BlockExample  and
  method blockExample in trait ExampleDsl1 of type (d: String)ConflictTest.this.BlockExample
(Note: this can be resolved by declaring an override in class ConflictTest.)
class ConflictTest extends Spec with ExampleDsl {
```

**Comment by etorreborre** [comment]
I just published `3.8.9-20170404161946-46dd4cb` which should fix this issue.

**Comment by ittaiz** [comment]
I'm currently on 3.7 and not sure when I can upgrade so if the above compiles in the above feel free to close it. Thanks for the responsiveness!

**Comment by etorreborre** [comment]
Ok, please reopen if that doesn't work for you.
