### ISSUE TITLE
Matcher[String] has compilation issues with "should"

### ISSUE THREAD

**Issue by asflierl** [etorreborre/specs2#570]
```scala
import org.specs2.mutable

class MeepSpec extends mutable.Specification {
  "A string can contain another" in {
    "asd" should contain("a")
  }
}
```

fails to compile (in Scala 2.12.1):
```
[error] [...]\src\test\scala\meep\MeepSpec.scala:7: overloaded method value should with alternatives:
[error]   (fs: => org.specs2.specification.core.Fragments)(implicit p1: org.specs2.control.ImplicitParameters.ImplicitParam1)org.specs2.specification.core.Fragments <and>
[error]   (f: => org.specs2.specification.core.Fragment)org.specs2.specification.core.Fragment
[error]  cannot be applied to (org.specs2.matcher.Matcher[String])
[error]     "asd" should contain("a")
[error]           ^
[error] one error found
```

If I substitute `should` with `must`, the spec compiles just fine.

**Comment by etorreborre** [comment]
Thanks for noticing this. In principle you could mix-in the `NoBlockDsl` trait to deactivate the `should` notation for blocks but this won't work. I need to reorganise a bit the implicits to make this happen.

**Comment by etorreborre** [comment]
Also another workaround for that specific case of matching a string with `should`, you can force the correct implicit to compile with:
```scala
theValue("asd") should contain("a")
```

**Comment by asflierl** [comment]
Thanks for suggesting the workaround! I can work with that for now (or just get over it and work with "must" :D ).

**Comment by etorreborre** [comment]
I am closing this issue with the provided work-around then.
