### ISSUE TITLE
publish for 2.13.0-M1

### ISSUE THREAD

**Issue by SethTisue** [etorreborre/specs2#573]
on the one hand it's quite early in the 2.13 cycle, but on the other hand specs2 is an enabler for many other projects

https://github.com/scala/make-release-notes/blob/2.13.x/projects-2.13.md shows that some dependencies are available including scalaz. is there anyone in your dependency tree we should gently nudge to get their 2.13 ball rolling, so specs2 can eventually publish?

**Comment by etorreborre** [comment]
There is shapeless, scalacheck and cats.

**Comment by SethTisue** [comment]
Shapeless and ScalaCheck have published for 2.13.0-M1.

for cats, I opened https://github.com/typelevel/cats/issues/1648

**Comment by etorreborre** [comment]
@SethTisue I also need  `org.spire-math#kind-projector_2.13.0-M1;0.9.3` (see #574 ).

**Comment by SethTisue** [comment]
that's https://github.com/non/kind-projector/issues/50 which I have now added to the bottom of https://github.com/scala/make-release-notes/blob/2.13.x/projects-2.13.md

**Comment by SethTisue** [comment]
kind-projector is available now (0.9.4)

**Comment by etorreborre** [comment]
Hi @SethTisue thanks for the update, there's now a [specs2 version for Scala 2.13.0-M1](https://oss.sonatype.org/content/repositories/releases/org/specs2/specs2-core_2.13.0-M1/3.9.0).
