### ISSUE TITLE
possible bug in org.specs2.Specification.is function. 

### ISSUE THREAD

**Issue by abdelhakimMouslih** [etorreborre/specs2#575]
Hello spec2 team,

[Spec2Test.txt](https://github.com/etorreborre/specs2/files/990335/Spec2Test.txt)
I encountered the behavior described bellow, and i'm not sure whether it is a bug or i'm misusing the is function declaration.
I attached my source file with this issue just in case it's a problem with the file encoding
This is the class i used to reproduce the behavior in my setup (my setup information below) : 
```
class Spec2Test extends org.specs2.Specification {
  override def is =
    s2"""
  canParse tests:
    should be OK $ok
    should be ignored
    should be ignored
    should be ignored
    should be OK $ok
    should be OK $ok
      """
}
```

expected sbt output : 
```
[info] Spec2Test
[info]   tests:
[info]     + should be OK
[info]      should be ignored
[info]       should be ignored
[info]       should be ignored
[info]     +  should be OK
[info]     + should be OK
```

actual sbt output:
```
[info]   tests:
[info]     + should be OK
[info]     + should be ignored
[info]       should be ignored
[info]       should be ignored
[info]       should be OK
[info]     + should be OK
```
as you can see the second expectation should be ignored, but it is marked as test OK, and the second to last expectation should be marked as OK, but it is ignored.

my setup info :
using  ubuntu 16.04 with intellij 
scalaVersion := "2.11.11"
libraryDependencies ++= Seq("org.specs2" %% "specs2-core" % "3.8.9" % "test")
scalacOptions in Test ++= Seq("-Yrangepos")
scalacOptions ++= Seq(
  "-target:jvm-1.6",
  "-encoding", "UTF-8",
  "-unchecked",
  "-deprecation",
  "-Xfuture",
  "-Yno-adapted-args",
  "-Ywarn-dead-code",
  "-Ywarn-numeric-widen",
  "-Ywarn-value-discard",
  "-Ywarn-unused"
)

**Comment by etorreborre** [comment]
Hi @abdelhakimMouslih. The behaviour you are seeing is expected but might not be obvious at first glance. Maybe it is easier to understand what happens if you write you spec like this:
```
  example1 $ok

  example2
  example2
  example2
  example2 $ok

  example3 $ok
```
Then the output is 
```scala
[info]  + example1
[info]  
[info]  + example2
[info]    example2
[info]    example2
[info]    example2
[info]  
[info]  + example3
```
What happens is that `example2` has a multi-line description. If you want some lines to be treated as pure text you need to use a different indentation:
```
  example1 $ok

  some text
  some text
  some text
    example2 $ok

  example3 $ok
```
Which prints
```
[info]  + example1
[info]
[info]   some text
[info]   some text
[info]   some text
[info]     + example2
[info]
[info]   + example3
```
Or add a newline
```
  example1 $ok
  some text
  some text
  some text

  example2 $ok
  example3 $ok
```
Which prints
```
[info]   + example1
[info]   some text
[info]   some text
[info]   some text
[info]
[info]   + example2
[info]   + example3
```
But I agree that you example seems mystifying at first :-).

**Comment by abdelhakimMouslih** [comment]
Hello @etorreborre 
Thank you for your kind reply.

**Comment by etorreborre** [comment]
I'm closing this for now, please ask again if you have other questions (you can also ask on the [gitter channel](https://gitter.im/etorreborre/specs2?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge))
