### ISSUE TITLE
specs2-cats_2.12 not found

### ISSUE THREAD

**Issue by tmccombs** [etorreborre/specs2#579]
I tried to add a dependency on specs2_2.12 version 3.8.9.

The POM file lists specs2-cats_2.12 version 3.8.9 as a dependency, but this artifact doesn't exist on maven central. In fact I can't find any specs2-cats artifacts for scala 2.12.

**Comment by etorreborre** [comment]
ok, thanks for telling me, I'll check that later today.

**Comment by etorreborre** [comment]
Actually now I remember why there's no `specs2-cats` in `3.8.9`. That's because the only reason why it was there in the first place was to provide `Xor` matchers for cats `0.7.2`. But then `Xor` was removed. This leaves us with the issue of having an incorrect pom file and I think I should just remove the cats module now from the project to fix this.

**Comment by tmccombs** [comment]
Sounds good. Thanks for looking at that.

**Comment by etorreborre** [comment]
The correct pom file will be published with the next specs2 release (I can't modify the already published one). If this is a problem for you I will publish a `3.9.1` version. (`3.9.0` is the current one).

**Comment by jdrphillips** [comment]
Where are the new versions published? Maven central only has `3.8.9` and `2.4.17` for `specs2`

http://repo1.maven.org/maven2/org/specs2/specs2_2.12/

The documentation references Sonatype but there doesn't seem to be any `2.12` artifacts on there at all.

**Comment by etorreborre** [comment]
You should depend directly on specific modules like [`specs2-core`](https://oss.sonatype.org/content/repositories/releases/org/specs2/specs2-core_2.12/3.9.4/). You can find it on the [maven repo](http://repo1.maven.org/maven2/org/specs2/specs2-core_2.12/3.9.4).

There is also a aggregated `specs2` pom file but I think I need to take some manual steps to publish it.

**Comment by jdrphillips** [comment]
Thanks for the explanation
