### ISSUE TITLE
JsonTypeMatcherDouble is missing

### ISSUE THREAD

**Issue by DanielHeath** [etorreborre/specs2#582]
Looking in https://github.com/etorreborre/specs2/blob/master/matcher-extra/src/main/scala/org/specs2/matcher/JsonMatchers.scala I see that there are implicit conversions from int, bool, string, array and map - but not from Double or BigDecimal.

This means in specs I can assert that a value is an integer in a JSON document, but not a decimal value.

Related: https://github.com/etorreborre/specs2/issues/307

**Comment by DanielHeath** [comment]
Wow thanks :)

**Comment by etorreborre** [comment]
New jars will be on the way today.

**Comment by etorreborre** [comment]
This fix is now released as part of `3.9.1-20170630055143-1856170`.
