### ISSUE TITLE
JUnit Report XML names are wrong when the "exclude" testOptions argument is set

### ISSUE THREAD

**Issue by peyerc** [etorreborre/specs2#583]
Hi Eric. I noticed in one of our projects which is using Specs2, that the name of the test cases in the JUnit Report XML are wrongly generated, when the "exclude" testOptions argument is set. The Problem is, that the text from the first unit specification is added to the following titles of all the test cases. Without the option everything looks ok.

**JUnit XML Report generated without the option**

    ...
    <testcase name="This is a test group::with section 2, which should::execute test 2A" classname="MultipleShouldBlockTest" time="0.223">
    </testcase>
    <testcase name="This should not be the prefix::of all test case names in the JUnit XML" classname="MultipleShouldBlockTest" time="0.154">
    </testcase>
    <testcase name="This is a test group::with section 1, which should::execute test 1B" classname="MultipleShouldBlockTest" time="0.202">
    </testcase>
    <testcase name="This is a test group::with section 1, which should::execute test 1A" classname="MultipleShouldBlockTest" time="0.197">
    </testcase>
    ...
    
**JUnit XML Report generated XML with the option**

    ...
    <testcase name="This should not be the prefix::This is a test group::with section 1, which should::execute test 1A" classname="MultipleShouldBlockTest" time="0.115">        
    </testcase>
    <testcase name="This should not be the prefix::This is a test group::with section 1, which should::execute test 1B" classname="MultipleShouldBlockTest" time="0.120">
    </testcase>
    <testcase name="This should not be the prefix::This is a test group::with section 1, which should::with section 2, which should::execute test 2A" classname="MultipleShouldBlockTest" time="0.127">
    </testcase>
    <testcase name="This should not be the prefix::of all test case names in the JUnit XML" classname="MultipleShouldBlockTest" time="0.086">
    </testcase>
    ...

I've created a repo, where the problem can be reproduced by commenting the exclude option in.
https://github.com/mmz-srf/specs2-junit-report-issue

**Comment by etorreborre** [comment]
Thanks for reporting this issue, it is fixed in `3.9.1-20170630155617-0057b1d`.

**Comment by peyerc** [comment]
Cool, now it works! Thank you very much!
