### ISSUE TITLE
NPE when setting expectations twice on a mockito mock using specs2 matcher that uses SeqLinesDiffable

### ISSUE THREAD

**Issue by iouwon** [etorreborre/specs2#584]
[simple app that demonstrates the issue](https://github.com/iouwon/spec2)

The cause seems to be in the interaction between MockMethodInterceptor.interceptAbstract (when setting expectations on the mock the argument values passed by mockito are null), the first expectation call causing the stubbed member in InvocationContainerImpl.findAnswerFor to have values meaning it is iterated over and the matchers evaluated for the second expectation setting call on the mock, and SeqLinesDiffable.diff calling argument.toList during said matcher evaluation. Since argument is null by virtue of what mockito passed during expectation setting argument.toList fails with an NPE

I'm not sure whether this is a mockito issue or a spec2 issue but I thought I'd start here, since the SeqLinesDiffable should probably be null safe

**Comment by etorreborre** [comment]
Thanks for reporting this. It indeed looks like Mockito can pass a null value in your special case. I protected the `HamcrestMatcherAdapter` against those null values so that we don't have to do defensive checks in the rest of specs2 matchers.

Do you need this fix to be published quickly?

**Comment by iouwon** [comment]
No, we worked around it by using answer and responding based on pattern
matching on the params arg in the function you pass to it.

I sort of think when mockito detects an expectation setting call in the
mock interceptor that it shouldn't be checking to see if it has an answer
for it, maybe by passing some context thru, irrespective of the null value
method call in the specs2 matcher
