### ISSUE TITLE
IntelliJ: Specs2 runner and ExecutionEnv

### ISSUE THREAD

**Issue by kflorence** [etorreborre/specs2#585]
This issue is not related to the specs2 code base, most likely it is some sort of issue with IntelliJ, but I wanted to document it here along with a workaround and hopefully get pointed to the appropriate place to file a bug.

# The problem
When using a test class with a defined implicit `ExecutionEnv`, as denoted [here](https://etorreborre.github.io/specs2/guide/SPECS2-3.9.1/org.specs2.guide.ExecutionEnvironments.html), IntelliJ seems to no longer recognize the class as a test class (and hence does not show any "run" options in the menu when you right click on the filename).

Example class:

```scala
class MyTests(implicit ee: ExecutionEnv) extends mutable.Specification {
...
}
```

# Workaround
Moving the implicit from the class to a property of the class resolves the problem.

```scala
class MyTests extends mutable.Specification {
  implicit val ee: ExecutionEnv = ExecutionEnv.fromGlobalExecutionContext
}
```

But this is rather annoying. Do you know where I can file this bug?

**Comment by etorreborre** [comment]
This is indeed an Intellij issue and a regression apparently because it used to work. Can you please open a ticket on [youtrack](https://youtrack.jetbrains.com/issues/SCL]?

**Comment by kflorence** [comment]
@etorreborre thanks -- I will file this soon and then close this issue.

**Comment by kflorence** [comment]
Filed as https://youtrack.jetbrains.com/issue/SCL-12433

**Comment by etorreborre** [comment]
Thanks Kyle.
