### ISSUE TITLE
scala-native support

### ISSUE THREAD

**Issue by xuwei-k** [etorreborre/specs2#591]

**Comment by etorreborre** [comment]
I knew it. I knew someone would ask for a scala-native build next :-)

**Comment by etorreborre** [comment]
I am going to close this for now because I realistically don't have the time to implement it.

**Comment by francisdb** [comment]
Tried some things and first blocker is [scalacheck not yet being published for scala native](
https://github.com/rickynils/scalacheck/issues/396)

**Comment by lolgab** [comment]
Scalacheck author didn't reply about publishing scalacheck native on github issue, so I published myself a version on maven under my groupid: "com.github.lolgab" %%% "scalacheck" % "0.4.1"

**Comment by lolgab** [comment]
I published scala-parser-combinators artifact too: "com.github.lolgab" %%% "scala-parser-combinators" % "1.1.2"
