### ISSUE TITLE
How to parse a variable in the given stage using GWT style?

### ISSUE THREAD

**Issue by starwander** [etorreborre/specs2#595]
Hi guys,
I am new to specs2. So maybe this is a silly question.
I want to parse a string variable during given stage, but the test gives a exception "error while interpreting an action java.util.concurrent.ExecutionException: Boxed Error".
I also tried Snippets trait, but it seems no help.
Can anyone helps me out of this? Thanks a lot!
My test code looks like:
```
  val goodSignature = sign("myToken", "myTimestamp", "myNonce")

  def is =
    s2"""
  Tests of signature check ${signatureTest.start}
    Given request uri {/myToken}
      And with nonce parameter {myNonce}
      And with timestamp parameter {myTimestamp}
      And with correct signature {${goodSignature}}
    When recieve the request by method {GET}
    Then should get a response with code {200} ${signatureTest.end}
"""

  val signatureTest =
    Scenario("signature test")
      .given(aString)
      .given(aString)
      .given(aString)
      .given(aString)
      .when(aString) {
        case method :: signature :: timestamp :: nonce :: uri :: _ => {
          request[MatchResult[Any]](method, s"$uri?nonce=$nonce&timestamp=$timestamp&signature=$signature")(_)
        }
      }
      .andThen(anInt) {
        case expectedCode :: rsp :: _ => rsp {
          status.intValue() shouldEqual expectedCode
        }
      }

```

**Comment by etorreborre** [comment]
Hi, could you please me which version you are using? Also since this is a concurrent exception you might want to try to add `sequential` to your specification
```scala
def is = sequential ^ s2"..."
```
I am sorry I don't have much time to try to reproduce this issue right now, I'll try tomorrow.

**Comment by starwander** [comment]
I'm using 3.9.2. And I have just tried sequential but still got same exception. It seems related to shapeless. Here is the full exception stack:
00:05:04.860 [DEBUG] [TestEventLogger] com.qianshui17.service.application.wechat.mp.WechatMpSignatureSpec > step.classMethod FAILED
00:05:04.860 [DEBUG] [TestEventLogger]     java.lang.ClassCastException: shapeless.HNil$ cannot be cast to shapeless.$colon$colon
00:05:04.860 [DEBUG] [TestEventLogger]         at com.qianshui17.service.application.wechat.mp.WechatMpSignatureSpec$$anonfun$1.apply(WechatMpSignatureSpec.scala:57)
00:05:04.860 [DEBUG] [TestEventLogger]         at com.qianshui17.service.application.wechat.mp.WechatMpSignatureSpec$$anonfun$1.apply(WechatMpSignatureSpec.scala:56)
00:05:04.860 [DEBUG] [TestEventLogger] 
00:05:04.860 [DEBUG] [TestEventLogger] com.qianshui17.service.application.wechat.mp.WechatMpSignatureSpec > Given request uri {/notify/wechat/mp}      And with nonce parameter {0123456789}      And with timestamp parameter {1234567890}      And with correct signature {9aeb08162ba52ec971c22d957df360bca0d6b869::}::    When recieve the request by method GET::Then should get a response with code 200 STARTED
00:05:04.860 [DEBUG] [TestEventLogger] 
00:05:04.860 [DEBUG] [TestEventLogger] com.qianshui17.service.application.wechat.mp.WechatMpSignatureSpec > Given request uri {/notify/wechat/mp}      And with nonce parameter {0123456789}      And with timestamp parameter {1234567890}      And with correct signature {9aeb08162ba52ec971c22d957df360bca0d6b869::}::    When recieve the request by method GET::Then should get a response with code 200 STARTED
00:05:04.860 [DEBUG] [TestEventLogger] 
00:05:04.860 [DEBUG] [TestEventLogger] com.qianshui17.service.application.wechat.mp.WechatMpSignatureSpec > Given request uri {/notify/wechat/mp}      And with nonce parameter {0123456789}      And with timestamp parameter {1234567890}      And with correct signature {9aeb08162ba52ec971c22d957df360bca0d6b869::}::    When recieve the request by method GET::Then should get a response with code 200 SKIPPED
00:05:04.860 [DEBUG] [TestEventLogger] 
00:05:04.860 [DEBUG] [TestEventLogger] com.qianshui17.service.application.wechat.mp.WechatMpSignatureSpec STANDARD_OUT
00:05:04.860 [DEBUG] [TestEventLogger]     error while interpreting an action java.util.concurrent.ExecutionException: Boxed Error
00:05:04.860 [DEBUG] [TestEventLogger] 
00:05:04.860 [DEBUG] [TestEventLogger] com.qianshui17.service.application.wechat.mp.WechatMpSignatureSpec FAILED

**Comment by etorreborre** [comment]
I could reproduce a class cast exception with `4.0.0-RC2` and `3.9.4`. I'll have a closer look at it hopefully tomorrow because I don't there's much of a workaround you can use now.

**Comment by starwander** [comment]
OK, looking forward to be solved.

**Comment by etorreborre** [comment]
I found what the problem is, I should be able to provide a fix tomorrow. The issue comes from invoking a method in the interpolated string `{${goodSignature}}`.

**Comment by etorreborre** [comment]
A fix is now available in `3.9.5`.

**Comment by starwander** [comment]
Great! Thanks a lot! I'll try 3.9.5 later. 
When will 3.9.5 be available on maven repository?

**Comment by etorreborre** [comment]
It's on Sonatype, so it should be available very soon in the maven repository.
