### ISSUE TITLE
Missing version 2.5 for scala 2.12

### ISSUE THREAD

**Issue by halvorgb** [etorreborre/specs2#598]
Hey, we're trying to upgrade to `scala 2.12`, but we aren't able to due to incompatible transitive dependencies.

We're using twitter/finatra (depends on `specs2-2.4.17`) and various wrapper libraries (poi, aws-scala, ...) that depend on `scalaz-7.2.x`.  While`specs2-{sub-project}-2.4.17` depends on `scalaz-7.1.0`.

In `scala 2.11` we hit the sweet spot by depending on `specs2-2.5`, but that version is not published for `scala 2.12`. Is it possible to do so? What effort would be required?

**Comment by etorreborre** [comment]
Hi, I had a quick at it (with `0e6f61045d4c`) and I am missing a bunch of dependencies:
```
[warn] 	:: org.scalaz.stream#scalaz-stream_2.12;0.5: not found
[warn] 	:: org.scalamacros#quasiquotes_2.12;2.0.1: not found
[warn] 	:: org.scalaz#scalaz-core_2.12;7.2.0: not found
[warn] 	:: org.scalaz#scalaz-concurrent_2.12;7.2.0: not found
[warn] 	:: org.scalacheck#scalacheck_2.12;1.12.1: not found
[warn] 	:: org.scala-lang.modules#scala-parser-combinators_2.12;1.0.3: not found
[warn] 	:: org.scalamacros#paradise_2.12.0;2.0.1: not found
[warn] 	:: org.scoverage#scalac-scoverage-plugin_2.12;0.99.5: not found
```
I don't have time right now to dive into each of them but if you could find suitable versions for each I could modify my build file and publish a specs2 2.5 for Scala 2.12

**Comment by halvorgb** [comment]
* quasiquotes is not needed for `2.12` iirc
* scalaz-core and scalaz-concurrent: `7.25`
* scalacheck: `1.12.6`
* scala-parser-combinators: `1.0.6`
* paradise: `2.1.1`
* sbt-scoverage: `1.5.1`

scalaz-stream tougher, I can't find a release for scalaz 7.2 and scala 2.12, it became fs2 as far as I know? Might have to port some code to fs2 here :(

I got the project to compile in scala 2.12, but loads of tests either fail compiling or fail.

My expermentation branch:
https://github.com/etorreborre/specs2/compare/specs2-2.x...halvorgb:specs2-2.5-scala-2.12

**Comment by halvorgb** [comment]
Hm, nevermind the `scalaz-streams` pessimism: `0.8.6a` is depends on `scalaz` `7.2.7` and is published for 2.12.

**Comment by etorreborre** [comment]
Thanks, based on your branch, I publish [this](https://oss.sonatype.org/content/repositories/releases/org/specs2/specs2-core_2.12/2.5/). Does that work ok for you?

**Comment by halvorgb** [comment]
Yes that works for me, thank you!
