### ISSUE TITLE
Release for 2.13.0-M2

### ISSUE THREAD

**Issue by MasseGuillaume** [etorreborre/specs2#601]
Would it be possible to release specs2 for Scala 2.13.0-M2? Thanks!

**Comment by etorreborre** [comment]
Which specs2 version do you need? The latest one in the 3.x series or 4.x?

**Comment by etorreborre** [comment]
I did a quick assessment of the dependencies involved and I realize that I need 
```
org.spire-math:kind-projector_2.13.0-M2:0.9.4
```

**Comment by etorreborre** [comment]
[Done](https://oss.sonatype.org/content/repositories/releases/org/specs2/specs2-core_2.13.0-M2/4.0.1/)
