### ISSUE TITLE
Mock init fails for class with type parameter

### ISSUE THREAD

**Issue by randm-ch** [etorreborre/specs2#603]
As described in [this question on StackOverflow](https://stackoverflow.com/questions/46448457/scala-mock-init-fails-with-cats-io-type-parameter), I had a problem with mocking my repository class that takes a type parameter.

I was confronted with the following exception:

    java.lang.ClassCastException: codegen.java.lang.Object$MockitoMock$641592186 cannot be cast to cats.effect.IO (MyRepositorySpec.scala:19)

Which occured when running this test code:

    class MyRepositorySpec extends Specification with Mockito with TestData {
        ...
        val m = mock[MyDAO[IO]].smart
        m.createTable returns IO { Right[Throwable, Int](1) } // <- this is line 19
    
        val r = new MyRepository[IO](m)
        r.setup.unsafeRunSync() must beNone
        ...
    }

`MyDAO` looks like this:

    class MyDAO[M[_] : Monad](val transactor: Transactor[M])(implicit val AE: ApplicativeError[M, Throwable]) extends DataAccessObject[M, MyObject]

and the `DataAccessObject` like this:

    trait DataAccessObject[M[_], T <: Entity]

As you can see in the answer, using `org.mockito.Mockito#when(m.createTable) thenReturn IO { Right[Throwable, Int](1) }` instead of `m.createTable returns IO { Right[Throwable, Int](1) }` solved the problem. I therefore concluded that there must be a problem with `specs2`s mocking code. Tested with `specs2` 3.9.1 and 3.9.5. Do you see another problem with my code or do you agree?

Thanks for all the work you do here. Cheers!

**Comment by etorreborre** [comment]
I fixed this issue on master which means this is going to go to `4.0.0`. Do you need a quick release for `3.9.5`?

**Comment by randm-ch** [comment]
@etorreborre Cool! Thank you very much. It's fine by me, I can wait for the new release since there's a workaround for now :+1:
