### ISSUE TITLE
Env injection creates one Env per spec, which is not shut down afterwards

### ISSUE THREAD

**Issue by thatfulvioguy** [etorreborre/specs2#604]
I'm using specs2 3.9.4 and per the guide page on [Environments](https://etorreborre.github.io/specs2/guide/SPECS2-3.9.5/org.specs2.guide.Environment.html), I tried out having my test run's Env injected into a spec by declaring a contructor parameter.

However, I thought that I'd be getting a reference to an Env that's global to my test run since that page always says "the Env object", and that it'd be the same one that specs2 uses to execute fragments and would then be cleaned up later. What I found is that one Env is created per spec that uses one and that it doesn't get shut down by the framework afterwards, so any threads of associated Executors, ExecutionContexts, etc. hang around after a test run and prevent the test run's classloader from being GCed.

This minimal-ish contrived example leaves behind one thread with name prefix specs2.fixed.env and another with specs2.scheduled.env after each run:
```scala
import java.util.concurrent.TimeUnit

import org.specs2.mutable.Specification
import org.specs2.specification.core.Env

class EnvSpec1(env: Env) extends Specification {
  "do a thing" in {
    env.scheduledExecutorService.schedule(() => "hello", 100, TimeUnit.MILLISECONDS).get() must beEqualTo("hello")
    env.executorService.submit(() => "hello2").get() must beEqualTo("hello2")
  }
}

class EnvSpec2(env: Env) extends Specification {
  "do another thing" in {
    env.scheduledExecutorService.schedule(() => "hello", 100, TimeUnit.MILLISECONDS).get() must beEqualTo("hello")
    env.executorService.submit(() => "hello2").get() must beEqualTo("hello2")
  }
}
```

**Comment by etorreborre** [comment]
Please add the version number.

**Comment by thatfulvioguy** [comment]
Done :+1: And sorry for any confusion caused by me hitting enter too early by mistake!

**Comment by etorreborre** [comment]
Do you have the option to try `4.0.0-RC5`? This issue should be fixed there. You have the option to either:

 - use `class EnvSpec1(env: Env)` and get a user env which should be shutdown when all the specs have been executed

 - use `class EnvSpec1(val env: Env) extends Specification with OwnEnv` which will give you `ownEnv` which is instantiated only for that spec. There is also a `OwnExecutionEnv` trait if you just need that

**Comment by thatfulvioguy** [comment]
Upgrading to 4.0.0 works as expected. Thanks a lot!
