### ISSUE TITLE
Provide opt-out for `===` operator

### ISSUE THREAD

**Issue by nigredo-tori** [etorreborre/specs2#611]
It's common practice to avoid `==` operator in Scala, using some type-safe version of it instead. Both Cats and Scalaz provide the alternative `a === b` syntax. This expression is expected to compile only if `a` and `b` have the same type (and if we have a correct typeclass instance in scope).

Yet specs2 nonchalantly provides its own `===` operators inside specifications, which always compiles, but throws in case of a failure. This behaviour is confusing and bug-prone.

It's probably too late to disable this syntax by default, but we can at least allow the user to opt out, with some `NoTripleEquals` trait in the cake.

**Comment by etorreborre** [comment]
Did you try the `org.specs2.matcher.NoTypedEqual` trait :-)?

**Comment by etorreborre** [comment]
By the way `===` is the moral equivalent of `==` in specs2 and there is also `====`, the equivalent of `===` in scalaz/cats which is typesafe.

**Comment by nigredo-tori** [comment]
> org.specs2.matcher.NoTypedEqual

Thank you, I somehow missed that. Will try it first thing Monday. This should cover my problem, so I'm closing this issue.

> By the way === is the moral equivalent of == in specs2

Only in that it doesn't check typing in compile-time. Their semantics have little in common.

The thing that gets me about all this is that you still can cast the result to `Boolean` somehow, even though it never returns `false`, throwing instead (at least in my experience, with mutable `Specification`). You can't meaningfully use it as an expression, but the types allow it.

> and there is also ====, the equivalent of === in scalaz/cats which is typesafe.

Nice to know, although I still prefer using the same syntax in tests that I use in the application code.

Thanks again.
