### ISSUE TITLE
3.8/9 thread leak when using implicit spec-scoped ExecutionEnv

### ISSUE THREAD

**Issue by francisdb** [etorreborre/specs2#612]
```scala
class Test(implicit ee: ExecutionEnv) extends Specification{

  "this" should {
    "do that" in {
      Future(success).await
    }
  }

}
```

After running the above test I see 1 remaining threads named `specs2.fixed.env-####`
When adding more test cases there are up to the number of cores of these threads leaked
On every run more threads are added.

This seems to be fixed in 4.x but I was wondering if there is a workaround for 3.x that we could use to fix this until play migrates to 4.x

**Comment by etorreborre** [comment]
Ok, I need to check why it was the case under 3.9.x. But not today or even tomorrow because I'm sick with probably the flu or something similar :-(.

**Comment by francisdb** [comment]
Never mind, looks like we can use 4.x with play :-)
Get well soon!

**Comment by etorreborre** [comment]
Great, good to know!
