### ISSUE TITLE
Indirectly using CharSequenceReader on Scala.js causes runtime error

### ISSUE THREAD

**Issue by mdedetrich** [etorreborre/specs2#618]
I am trying to use Specs2 4.0.2 for scalajson (https://github.com/mdedetrich/scalajson) in Scala.js  and I get the following stacktrace
```
[info] Fast optimizing /Users/matthewdedetrich/github/scalajson/js/target/scala-2.11/scalajson-test-fastopt.js
[error] Referring to non-existent class scala.util.parsing.input.CharSequenceReader
[error]   called from org.specs2.text.InterpolatedParsers$class.interpolate(org.specs2.text.InterpolatedParsers,java.lang.String)java.lang.String
[error]   called from org.specs2.text.Interpolated.interpolate(java.lang.String)java.lang.String
[error]   called from org.specs2.text.Interpolated.expressions()scala.collection.Seq
[error]   called from org.specs2.specification.create.S2StringContextCreation$class.s2(org.specs2.specification.create.S2StringContextCreation,java.lang.String,scala.Boolean,scala.collection.Seq,scala.collection.Seq,scala.collection.Seq,scala.collection.Seq,scala.collection.Seq)org.specs2.specification.core.Fragments
[error]   called from org.specs2.Specification.s2(java.lang.String,scala.Boolean,scala.collection.Seq,scala.collection.Seq,scala.collection.Seq,scala.collection.Seq,scala.collection.Seq)org.specs2.specification.core.Fragments
[error]   called from specs.unsafe.JBoolean$$anonfun$is$1.apply()org.specs2.specification.core.Fragments
[error]   called from specs.unsafe.JBoolean$$anonfun$is$1.apply()java.lang.Object
[error]   called from org.specs2.control.Exceptions$class.trye(org.specs2.control.Exceptions,scala.Function0,scala.Function1)scala.util.Either
[error]   called from org.specs2.control.Exceptions$.trye(scala.Function0,scala.Function1)scala.util.Either
[error]   called from org.specs2.main.SmartDiffs$.fromString(java.lang.String)scala.util.Either
[error]   called from org.specs2.main.Report$.extract(scala.collection.Seq,org.specs2.main.SystemProperties)org.specs2.main.Report
[error]   called from org.specs2.main.Arguments$.extract(scala.collection.Seq,org.specs2.main.SystemProperties)org.specs2.main.Arguments
[error]   called from org.specs2.main.Arguments$.apply(scala.collection.Seq)org.specs2.main.Arguments
[error]   called from org.specs2.specification.core.EnvDefault$.$default()org.specs2.specification.core.Env
[error]   called from org.specs2.specification.core.Env$.apply$default$7()scala.util.Random
[error]   called from org.specs2.runner.BaseSbtRunner.env$lzycompute()org.specs2.specification.core.Env
[error]   called from org.specs2.runner.BaseSbtRunner.env()org.specs2.specification.core.Env
[error]   called from org.specs2.runner.BaseSbtRunner.done()java.lang.String
[error]   called from org.scalajs.testinterface.internal.Master.runnerDone(scala.runtime.BoxedUnit)java.lang.String
[error]   called from org.scalajs.testinterface.internal.Master.$$anonfun$2(scala.runtime.BoxedUnit)java.lang.String
[error]   called from org.scalajs.testinterface.internal.Master.<init>(java.lang.String)
[error]   called from org.scalajs.testinterface.internal.Master.__exportedInits
[error]   exported to JavaScript with @JSExport
[error] involving instantiated classes:
[error]   org.specs2.text.Interpolated
[error]   specs.JValue
[error]   specs.unsafe.JArray
[error]   specs.unsafe.JString
[error]   specs.unsafe.JNumber
[error]   specs.unsafe.JObject
[error]   specs.JString
[error]   specs.JBoolean
[error]   specs.JNumber
[error]   specs.unsafe.JValue
[error]   specs.JObject
[error]   specs.JArray
[error]   specs.unsafe.JBoolean
[error]   specs.unsafe.JBoolean$$anonfun$is$1
[error]   org.specs2.control.Exceptions$
[error]   org.specs2.main.SmartDiffs$
[error]   org.specs2.main.Report$
[error]   org.specs2.main.Arguments$
[error]   org.specs2.specification.core.EnvDefault$
[error]   org.specs2.specification.core.Env$
[error]   org.specs2.runner.SlaveSbtRunner
[error]   org.specs2.runner.MasterSbtRunner
[error]   org.scalajs.testinterface.internal.Master
```

It appears that for some type of tests, we end up using `org.specs2.text.InterpolatedParsers.interpolate`. This ends up calling `scala.util.parsing.input.CharSequenceReader` which doesn't exist on the Scala.js platform. I don't think that Scala.js will support `CharSequenceReader` because the platform has no concept of `Char` (`Char` is an Opaque type on Scala.js, see https://www.scala-js.org/doc/interoperability/types.html and https://stackoverflow.com/a/27823467).

I think it may make more sense to just refactor the code so that we don't use `CharSequenceReader`, although adding `CharSequenceReader` to Scala.js might be an option?

**Comment by mdedetrich** [comment]
So some update, @sjrd has been helping in the gitter channel, this class is meant to be part of scala-parser-combinators (which is now a module), however even if you explicit add this with

```sbt
    libraryDependencies ++= Seq(
      "org.specs2" %%% "specs2-core" % specs2Version % Test,
      "org.specs2" %%% "specs2-scalacheck" % specs2Version % Test,
      "org.scalacheck" %%% "scalacheck" % scalaCheckVersion % Test,
      "org.scala-lang.modules" %%% "scala-parser-combinators" % "1.0.6" % Test
    )
```
The error still occurs

**Comment by mdedetrich** [comment]
Okay, so it turns out that there is a massive issue with the published version of scale-parser-combinators 1.0.6, i.e. see https://github.com/scala/scala-parser-combinators/issues/130

Using 1.0.5 seems to work, @etorreborre should I close this issue or leave it open as a reference?

**Comment by etorreborre** [comment]
I think I had to update to 1.0.6 for some reason because 1.0.5 was not working for me. As a result I got stuck on this.

**Comment by mdedetrich** [comment]
@etorreborre Do you remember what the issue with 1.0.5 was? 1.0.5 is whats working for me (and 1.0.6 is whats obviously not working due to it missing class files for Scala.js)

**Comment by etorreborre** [comment]
No I don't remember I think that some js tests were not passing in the test suite. Can you try a PR with 1.0.5 and enabling the JS tests again? https://github.com/etorreborre/specs2/blob/master/.travis.yml#L41

**Comment by etorreborre** [comment]
I know now why 1.0.5 is problematic. There's no build for Scala 2.13.0-M2. I have just released `4.0.2-bc9c22b-20171213063838` for Scala 2.11.11 and 2.12.3 if that helps.

**Comment by mdedetrich** [comment]
It was actually happening because you accidentally used `%%` in one spot instead of `%%%`, I fixed this in my PR

When looking at the build, I noticed a few other things which aren't entirely correct. i.e. you are using js `libraryDependencies` in the core projects (they should only be included in the js version of the project)

I will do another PR tonight to clean up the build and fix these things

**Comment by mdedetrich** [comment]
I am going to close this issue since we found the underlying problems, with master in the right state right now we just need to deploy a new version of specs2, targeting parser-combinators either for version `1.0.5` or `1.0.7`.
