### ISSUE TITLE
specs2 3.x: org.specs2.specification.IsolatedExecutionSpec started failing in Scala 2.12.3

### ISSUE THREAD

**Issue by SethTisue** [etorreborre/specs2#622]
in the Scala community build, we don't run specs2's tests. I tried re-enabling that but I get:

```
[info] IsolatedExecutionSpec
[info] 
[info]  We want to be able to isolate the execution of examples if isolated == true
[info]  The isolated fragments must run with their own class instance
[error]    x for a mutable spec
[error]  List(example1: n is 2 but should be 1, Pending(isolation mode failure - could not find an isolated fragment to execute)) does not contain example1, example2 but contains example1: n is 2 but should be 1, Pending(isolation mode failure - could not find an isolated fragment to execute) (IsolatedExecutionSpec.scala:22)
[info] 
[error]    x for an acceptance spec
[error]  List(example1: i is 2 but should be 1, example2) does not contain example1 but contains example1: i is 2 but should be 1 (IsolatedExecutionSpec.scala:26)
[info] 
```

the problem is reproducible outside of the community build: check out the `specs2-3.x` branch and run `core/test:testOnly *IsolatedExecutionSpec`. it passes on 2.12.2 which is the 2.12 version on that branch, but if you do `++2.12.3` or `++2.12.4` first, it fails.

since specs2 is of fundamental importance to the Scala ecosystem, it would be awesome if we could run your tests in the community build — at least in the `core` project, perhaps more! any clue what's going on with this one test...?

**Comment by SethTisue** [comment]
`examples.MutableStackIsolatedSpec` is affected as well

**Comment by SethTisue** [comment]
these are the only two failures.

**Comment by etorreborre** [comment]
Hi Seth, my plate is a bit full at the moment and this functionality in specs2 is one of the hairiest one. Surprise, surprise it involves mutation :-).

I have done a first investigation and saw nothing obvious for now. The first spec can be fixed by executing the example specs sequentially but applying that trick to the `MutableStackIsolatedSpec` doesn't work.

If this proves blocking for the community we can do a release without this functionality because this is not the most essential one in specs2 (basically it tries to accomodate the fact that you might use mutation in your spec, what was I even thinking?).

**Comment by SethTisue** [comment]
> If this proves blocking for the community [...]

The community build won't be blocked regardless; I can fork specs2 and delete those two tests. It's really up to you whether you consider this otherwise worth pursuing.

**Comment by etorreborre** [comment]
Yes I would like to get to the bottom of it because I don't see how a minor Scala version bump should have an effect on anything.

**Comment by etorreborre** [comment]
At least I checked that everything is ok on the 4.x branch, so that will give a good incentive for people to upgrade :-).

**Comment by etorreborre** [comment]
I am closing this issue because I unfortunately don't have time to investigate it :-(.

**Comment by SethTisue** [comment]
makes sense. note that the Scala 2.13 community build is now on specs2 4.x, anyway.
