### ISSUE TITLE
"No template file found" problem (ONLY in Windows)

### ISSUE THREAD

**Issue by lanjiann** [etorreborre/specs2#623]
I tried to use ```specs2``` to generate a html format test report.
I first did this in a Windows 10, and it didn't work. However, it works in a linux.

The error message in my Windows 10 is ```No template file found at /C:/Users/lanjian/Downloads/preowned-kitten/target/specs2-reports/templates/specs2.html```. By the way, I use sbt. One thing I think I should mention is that, after running ```sbt test``` I can find a _specs2.html_ file in the path given above. However, it seems specs2 cannot locate it when it wanted to use it.

My _build.sbt_ file content:
```
import scala.sys.process.Process

name := "preowned-kittens"

scalaVersion := "2.12.4"

lazy val gitHeadCommitSHA = taskKey[String]("Determines the current git commit SHA")

lazy val makeVersionProperties = taskKey[Seq[File]]("Makes a version.properties file.")

gitHeadCommitSHA in ThisBuild := Process("git rev-parse HEAD").lineStream.head

lazy val common =
  project.in(file("common")).
    settings(
      makeVersionProperties := {
        val propFile = new File((resourceManaged in Compile).value, "version.properties")
        val content = ("version=%s" + scala.util.Properties.lineSeparator) format gitHeadCommitSHA.value
        IO.write(propFile, content)
        Seq(propFile)
      }

    )

lazy val analytics =
  project.in(file("analytics")).
    dependsOn(common).
    settings(
    )

lazy val website =
  project.in(file("website")).
    dependsOn(common).
    settings(
    )

testOptions in (ThisBuild, Test) += Tests.Argument(TestFrameworks.Specs2, "html")

libraryDependencies in ThisBuild ++=
  Seq(
    "org.specs2" %% "specs2-core" % "4.0.2" % Test,
    "org.specs2" %% "specs2-html" % "4.0.2" % Test,
    "org.scala-lang.modules" %% "scala-xml" % "1.0.6" % Test)
```

**Comment by etorreborre** [comment]
By any chance, is this covered by this PR? https://github.com/etorreborre/specs2/pull/614

**Comment by lanjiann** [comment]
I tried the one you mentioned, and I think it doesn't cover my case. I can still see the error message.

**Comment by etorreborre** [comment]
Ok, thank you for trying. I will try to have a look at this before the end of the week.

**Comment by etorreborre** [comment]
The problem could be the leading `/` in front of the `out` path. Maybe you can try to force it to be correct by passing `html.outdir C:/Users/lanjian/Downloads/preowned-kitten/target/specs2-reports` as an argument.

**Comment by etorreborre** [comment]
@asflierl Andreas could you please have a look at this issue since you also have a windows environment?

**Comment by asflierl** [comment]
I have no access to a Windows environment until next week, but I can have a look at the issue then.

**Comment by etorreborre** [comment]
Thanks @asflierl

**Comment by asflierl** [comment]
the issue seems to be that `java.io.File` accepts and "properly" treats paths like "/C:/..." but `java.nio.file.Path` does not

**Comment by etorreborre** [comment]
So we need to find why we form such a path in the first place. Possibly this is the result of doing a `split` on `/`.

**Comment by asflierl** [comment]
most probably https://github.com/etorreborre/specs2/blob/1085f971cb6579555cebef179f2b84c408694cda/common/shared/src/main/scala/org/specs2/io/DirectoryPath.scala#L33

if we're on Windows, and the first "directory" is actually a drive letter, we have to omit the leading "/"

**Comment by asflierl** [comment]
I just wonder why my projects on Windows don't suffer from this problem

**Comment by etorreborre** [comment]
I'm closing this issue for now until someone wants to reopen it and has a clue with what's going on on windows.

**Comment by cheevo** [comment]
Still happening on windows with 4.5.1
cmd:         sbt clean coverage test
error:        [error] No template file found at /C:/useful/....spec2.html
cause :      leading "/" causing issue.
dependency :    "org.specs2" %% "specs2-html" % "4.5.1" % Test ."org.specs2" %% "specs2-html" %

**Comment by etorreborre** [comment]
I'm sorry you're also having this issue, did you try the work-around [here](https://github.com/etorreborre/specs2/issues/623#issuecomment-354655213)? And otherwise would you mind spending some time working with me to debug this issue since I don't have a Windows machine?

**Comment by cheevo** [comment]
The workaround testOptions in Test += Tests.Argument("html.outdir","C:/verify")
has same issue No template file found at /C:/verify/ . The leading edge is always added.
I'm willing to test any patch you may have to resolve this issue.
