### ISSUE TITLE
BeforeAll / AfterAll fail silently

### ISSUE THREAD

**Issue by phile314-fh** [etorreborre/specs2#625]
I would expect the whole test specification to fail if a BeforeAll / AfterAll fails. However, exceptions in BeforeAll  / AfterAll are silently ignored. Example test:

```
package ch.isska.viskar.logic

import org.specs2.mutable.Specification
import org.specs2.specification.BeforeAfterAll

object BeforeAfterAllExample extends Specification with BeforeAfterAll {

  override def beforeAll(): Unit = {
    throw new RuntimeException()
  }

  "test" >> {
    1 must_=== 1
  }

  override def afterAll(): Unit = {
    throw new RuntimeException()
  }
}
```

Actual Output is Success, expected output is Failure.

I had a bug in my ``beforeAll`` code, and the current behavior makes it difficult to track down those failures. I also find this behavior surprising, as at least for me it doesn't make much sense to run the tests when the test setup has failed.

I also have found a email thread about this ( https://groups.google.com/forum/#!topic/specs2-users/6PEkpAzT080 ). I tried out the solution suggested in there, but adding ``stopOnError`` just makes specs2 ignore the test when the ``beforeAll`` function fails.

**Comment by etorreborre** [comment]
Thanks for the report, I fixed this issue, I will publish a version today.

**Comment by etorreborre** [comment]
Please try [`4.0.2-3eab439-20180109215419`](https://oss.sonatype.org/content/repositories/releases/org/specs2/specs2-core_2.12/4.0.2-3eab439-20180109215419).

**Comment by phile314-fh** [comment]
Thank you for the quick fix, works perfectly!

**Comment by eyalroth** [comment]
@etorreborre What should be the expected behavior as of 4.3.3? `beforeAll` still seem to fail silently.

**Comment by symbiont-eric-torreborre** [comment]
I tested as of `4.10.0` which is the latest published version and I get
```
tests> testOnly *BeforeAfterAllExampleSpec
[info] Compiling 1 Scala source to /Users/etorreborre/projects/specs2/specs2/tests/target/scala-2.13/test-classes ...
[error] !
[error]  org.specs2.specification.core.FatalExecution: null (TestSpec.scala:28)
[error] user.BeforeAfterAllExampleSpec$.beforeAll(TestSpec.scala:28)
[error] CAUSED BY
[error]  java.lang.RuntimeException: null (TestSpec.scala:28)
[error] user.BeforeAfterAllExampleSpec$.beforeAll(TestSpec.scala:28)
[info] BeforeAfterAllExampleSpec
[info] o test
[info] SKIPPED
[error] !
[error]  org.specs2.specification.core.FatalExecution: null (TestSpec.scala:36)
[error] user.BeforeAfterAllExampleSpec$.afterAll(TestSpec.scala:36)
[error] CAUSED BY
[error]  java.lang.RuntimeException: null (TestSpec.scala:36)
[error] user.BeforeAfterAllExampleSpec$.afterAll(TestSpec.scala:36)
[info] Total for specification BeforeAfterAllExampleSpec
[info] Finished in 246 ms
[info] 1 example, 3 expectations, 0 failure, 2 errors, 1 skipped
[error] Error: Total 3, Failed 0, Errors 2, Passed 0, Skipped 1
[error] Error during tests:
[error] 	user.BeforeAfterAllExampleSpec
```

**Comment by eyalroth** [comment]
@etorreborre Seems to fail to work with `sequential`:

```scala
@RunWith(classOf[JUnitRunner])
class FooMeSpec extends Specification with BeforeAll {

    sequential

    def beforeAll(): Unit = {
        throw new Exception("hey")
    }

    "foo" should {
        "1" in {
            1 mustEqual 1
        }
    }
}
```

Also, when it does work, it does not print the exception, which is really unfortunate.

**Comment by symbiont-eric-torreborre** [comment]
This is what I get with `sequential` (and `sbt` not `junit`):
```
[error] !
[error]  java.lang.Exception: hey (TestSpec.scala:24)
[error] user.FooMeSpec.beforeAll(TestSpec.scala:24)
[info] FooMeSpec
[info] foo should
[info]   + 1
[info] Total for specification FooMeSpec
[info] Finished in 469 ms
[info] 1 example, 2 expectations, 0 failure, 1 error
[error] Error: Total 2, Failed 0, Errors 1, Passed 1
[error] Error during tests:
[error] 	user.FooMeSpec
[error] (Test / testOnly) sbt.TestsFailedException: Tests unsuccessful
```
While without `sequential` I get:
```
[error] !
[error]  org.specs2.specification.core.FatalExecution: hey (TestSpec.scala:24)
[error] user.FooMeSpec.beforeAll(TestSpec.scala:24)
[error] CAUSED BY
[error]  java.lang.Exception: hey (TestSpec.scala:24)
[error] user.FooMeSpec.beforeAll(TestSpec.scala:24)
[info] FooMeSpec
[info] foo should
[info]   o 1
[info] SKIPPED
[info] Total for specification FooMeSpec
[info] Finished in 363 ms
[info] 1 example, 2 expectations, 0 failure, 1 error, 1 skipped
[error] Error: Total 2, Failed 0, Errors 1, Passed 0, Skipped 1
[error] Error during tests:
[error] 	user.FooMeSpec
```
When you write "it does not print the exception" do you mean with sbt or something else like IntelliJ? 

In any case the behaviour should be the same with or without sequential (the test should be skipped) so I will fix that at least.

**Comment by eyalroth** [comment]
@symbiont-eric-torreborre I'm running with gradle and intellij, and I am seeing anything that goes to stdout / stderr, but not this exception when it's thrown in `beforeAll`.

PS did you just change your username? 😃

**Comment by etorreborre** [comment]
No, I frequently forget to switch my profile on Github between closed source for work and open source :-)
