### ISSUE TITLE
java.lang.reflect.InvocationTargetException caused by java.lang.IllegalAccessError: class org.mockito.internal.creation.jmock.ClassImposterizer$1 cannot access its superclass org.mockito.internal.creation.cglib.MockitoNamingPolicy

### ISSUE THREAD

**Issue by Afif00** [etorreborre/specs2#628]

**Comment by etorreborre** [comment]
I'm sorry, is there a question :-)? This kind of issue might be caused by some incompatibilities between libraries so you should check your dependencies and in particular check if `mockito-core` has version `2.7.22`.

**Comment by Afif00** [comment]
True that was it, had to do with a clash with transitive dependencies. resolved it by removing the bad one
