### ISSUE TITLE
please release new version for scala-js with depends on scala-parser-combinators 1.1.0

### ISSUE THREAD

**Issue by xuwei-k** [etorreborre/specs2#636]
specs2-common_sjs0.6_2.12 4.0.2 depends on scala-parser-combinators_2.12 1.0.6. (**NOT** scala-parser-combinators_sjs0.6_2.12 !)

https://repo1.maven.org/maven2/org/specs2/specs2-common_sjs0.6_2.12/4.0.2/specs2-common_sjs0.6_2.12-4.0.2.pom

also scala-parser-combinators 1.0.6 is broken https://github.com/scala/scala-parser-combinators/issues/119

**Comment by etorreborre** [comment]
Sorry I just saw this issue now, the email had arrived in my spam folder. I will deploy a `4.0.3` tomorrow.

**Comment by etorreborre** [comment]
Done: https://oss.sonatype.org/content/repositories/releases/org/specs2/specs2-core_2.12/4.0.3

**Comment by xuwei-k** [comment]
Thanks! 👍
