### ISSUE TITLE
SpecWithJUnit creates a separate execution pool for each specification

### ISSUE THREAD

**Issue by laurynasl-wix** [etorreborre/specs2#648]
We've recently updated to Specs 4.0.3 and it seems that the JUnitRunner creates new ExecutionContexts for each Spec(ification)WithJUnit. This is a problem, because for each specification 16 threads are created by default (if you have 8 cores). This seems to be a regression. To recreate this I think it's enough to create two specifications with junit and run them with Maven surefire or the like. Let me know if you need more information.

**Comment by etorreborre** [comment]
Would you mind setting up a small github project with maven for me?

**Comment by laurynasl-wix** [comment]
Will try to later today.

**Comment by etorreborre** [comment]
Thank you!

**Comment by etorreborre** [comment]
BTW you can at least reduce the number of threads by setting `-Dspecs2threadsnb=2` (I don't advise to use `1` because this might create some deadlocks).

**Comment by laurynasl-wix** [comment]
Thanks, I used `-Dspecs2.threadsNb=1 -Dspecs2.specs2ThreadsNb=2` to work around the issue

**Comment by laurynasl-wix** [comment]
Here you go https://github.com/laurynasl-wix/specs2-junit-issue.

**Comment by etorreborre** [comment]
Thank you, I have fixed the issue and pushed a fix to master. However I cannot yet publish a new version because I have a setup issue with my new laptop. I will try to fix and publish later.

**Comment by laurynasl-wix** [comment]
Awesome, thank you!

**Comment by etorreborre** [comment]
I have just released a version which you can try `4.0.4-f9521ff54-20180413093135`.

**Comment by laurynasl-wix** [comment]
Great!
