### ISSUE TITLE
`setMessage` on `beFalse` does not update the failure message

### ISSUE THREAD

**Issue by avdv** [etorreborre/specs2#655]
Hi.

Just a minor thing I have noticed recently:

Example:
```scala
true must beFalse.setMessage("expected false!")
```
Output:
```
the value is true
```
I am using specs2 version 4.2.0.

Thanks!

**Comment by etorreborre** [comment]
Damn, this only happens with mutable specifications. This is fine:
```scala
class TestSpec extends Specification { def is = s2"""

 e1 $e1

"""

  def e1 =  {
    true must beFalse.setMessage("expected false!")
  }

}
```
I will investigate, thanks.

**Comment by etorreborre** [comment]
This is fixed now and will go into the next version. Please tell me if you would like to have an interim version.

**Comment by avdv** [comment]
> This is fixed now and will go into the next version. Please tell me if you would like to have an interim version.

Thanks alot! No sweat, I'll wait for the next version! :smiley:
