### ISSUE TITLE
Add matchers for Cats

### ISSUE THREAD

**Issue by nigredo-tori** [etorreborre/specs2#658]
Since `core` got rid of its scalaz dependency, it would make sense to provide a `specs2-cats` module again, in the same spirit as `specs2-scalaz`. At the very least it should include `Eq` matchers, and possibly matchers for `Validated` and `IO`, too (the last one is in `cats-effect`). I imagine porting `Equals`, `Validated` and `Futurez` machinery from `specs2-scalaz` would suffice.

Sorry if there is already something like this somewhere - a cursory search didn't turn up anything useful.

**Comment by etorreborre** [comment]
I agree, it would be nice to have. It's also a great contributor project if you want to get started with open-source!

**Comment by etorreborre** [comment]
I think I should actually move those matchers to different projects so that specs2 can be published independently of cats when there's a major Scala version out for example.

**Comment by etorreborre** [comment]
There are cats matchers now so I'm going to close this issue. Please reopen if you want to add other matchers.
