### ISSUE TITLE
Build fails on Java 8

### ISSUE THREAD

**Issue by dragos** [etorreborre/specs2#661]
Since 8f8337217a838d73feeed764867682c57c71babd one can't build specs2 on Java 8. Not sure if this is intentional, so feel free to close if that's the case (the reason is that `--add-modules` in `.sbtopts` is not understood by older JVMs).

**Comment by etorreborre** [comment]
Yes I decided to move on to more recent versions of the JDK but I don't know how to have `--add-modules` being ignored by JDK 8. It seems that an option is to use `-[`XX:+IgnoreUnrecognizedVMOptions`](https://bugs.openjdk.java.net/browse/JDK-6788376)

**Comment by etorreborre** [comment]
I pushed this flag on master if you have some time to try it out.

**Comment by dragos** [comment]
Yeap, this fixes it, thanks!
