### ISSUE TITLE
Release 3.x with scalacheck 1.14.0

### ISSUE THREAD

**Issue by nigredo-tori** [etorreborre/specs2#662]
At the moment `discipline` can't upgrade to Specs2 4.x in its 2.10 configuration, and this [locks the update to scalacheck 1.14.0](https://github.com/typelevel/discipline/issues/52) as well. Since the changes in the scalacheck API are relatively minor, we can switch to 1.14.0 in the legacy specs2 branch (3.x) to facilitate that transition.

**Comment by etorreborre** [comment]
I've had some issues in publishing this release, I hope I will fix them tomorrow.

**Comment by etorreborre** [comment]
Ok `3.10.0` is at least available for Scala `2.12`: https://oss.sonatype.org/content/repositories/releases/org/specs2/specs2-core_2.12/3.10.0. Do you need other Scala versions right now?

**Comment by etorreborre** [comment]
Done, I might as well release 2.11 now :-)

**Comment by etorreborre** [comment]
Done for [Scala 2.11](https://oss.sonatype.org/content/repositories/releases/org/specs2/specs2-core_2.11/3.10.0/) as well.
