### ISSUE TITLE
StackIsolatedSpec failing in Scala 2.12 community build

### ISSUE THREAD

**Issue by SethTisue** [etorreborre/specs2#673]
seen at e.g. https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3012/consoleFull

```
[specs2] [info] StackIsolatedSpec
[specs2] [info]                                                                              
[specs2] [info]  A Stack with limited capacity can either be:
[specs2] [info]  1. Empty
[specs2] [info]    when the stack is empty 
[specs2] [info]    + stack must be empty
[specs2] [info]    + stack.top must throwA[NoSuchElementException]
[specs2] [info]    + stack.pop must throwA[NoSuchElementException]
[specs2] [info]  2. Non-empty and not full
[specs2] [info]    when the stack is not empty and not full 
[specs2] [info]    + stack must not be empty
[specs2] [info]    + stack.top === normalStack.top; stack === normalStack
[specs2] [error]    ! stack.pop === normalStack.top; stack !== normalStack
[specs2] [error]  java.util.NoSuchElementException: head of empty list (StackIsolatedSpec.scala:25)
[specs2] [error] examples.StackIsolatedSpec.$anonfun$is$22(StackIsolatedSpec.scala:25)
[specs2] [error] examples.StackIsolatedSpec.$anonfun$is$21(StackIsolatedSpec.scala:25)
[specs2] [info]    + stack push 1; stack.top === 1; stack !== normalStack
[specs2] [info]  3. Full
[specs2] [info]    when the stack is full 
[specs2] [info]    + (stack push 1) must throwAn[Error]
[specs2] [info] Total for specification StackIsolatedSpec
[specs2] [info] Finished in 118 ms
[specs2] [info] 8 examples, 11 expectations, 0 failure, 1 error
```

the problem is reproducible outside dbuild with `resolvers += "scala-integration" at "https://scala-ci.typesafe.com/artifactory/scala-integration/"`, `++2.12.7-bin-5622f5d!`, `examplesJVM/testOnly *StackIsolatedSpec`

**Comment by etorreborre** [comment]
I fixed the spec by running it sequentially. This is one of the hairiest functionality of specs2, I will need more time to investigate if the spec can be run concurrently again. But that should do it for the community build for now, thanks for warning me. Also it's weird that travis didn't fail on that one but possibly travis has less concurrency available.

**Comment by SethTisue** [comment]
scala/community-builds@bd44dfda8ac7521776066b034ce0cafb635db766

optimistically closing, I'll return here if I see the failure again.

**Comment by SethTisue** [comment]
another `StackIsolatedSpec` failure, details a little different, seen at https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/3042/consoleFull

```
[specs2] [info]  3. Full
[specs2] [info]    when the stack is full 
[specs2] [error]    x (stack push 1) must throwAn[Error]
[specs2] [error]  Expected: java.lang.Error. Got nothing (StackIsolatedSpec.scala:30)
```

**Comment by SethTisue** [comment]
dealing with it for now by skipping the test: scala/community-builds@1ae9f44e5199a75b1bbdfd10a64dd32ed33a346d

**Comment by etorreborre** [comment]
Ok thanks I will try to revisit this part (which is one of the worst of specs2, I'm on the verge of just removing that feature)
