### ISSUE TITLE
JMock expectation error details are dumped and doesn't propagate

### ISSUE THREAD

**Issue by nairoa** [etorreborre/specs2#690]
It looks like resolving issue #672 introduced a regression in the interoperability with JMock.
The commit introducing this change was 24962cedeb0d8d390637baf20386635dd6b0a13d. 
It looks like the exception details are lost when replacing ExpectationError with Failure where details are simply FromExpectationError.

This seriously degrades our workflow with the combination of specs2 and JMock.

Looking into possible solutions, I see the following options:
1. revert that commit - but that will bring back the original issue (which is not nice but bearable).
2. correctly interpret and cast ExpectationError so a suitable Failure can be constructed from it (and as a result the correct junitFailure). This will require a dependency on JMock that I think you tried to avoid.
3. create some kind of a hook to allow client code to invade error handling and correctly interpret the error themselves.

WDYT?

**Comment by etorreborre** [comment]
I would like to find a way to collect those details which presumably are stored somewhere with an `ExpectationError` and set them on a `Failure`. Could you please create a small project showing the issue? (preferably using sbt). Thanks (Also I'm leaving on vacations on Tuesday so we'd better find a solution fast :-)).

**Comment by nairoa** [comment]
I created a branch on the specs2-jmock repo with a minimal example that demonstrate the issue.
https://github.com/wix/specs2-jmock/tree/minimal-example-of-degradation

**Comment by etorreborre** [comment]
Thanks I hope I can find a bit of time to fix this today.

**Comment by etorreborre** [comment]
The fix seems easy enough, I used the `toString` method on the exception which delegates to the Hamcrest `SelfDescribing` machinery. I am now publishing `4.3.3-RC1` for you to try.

**Comment by etorreborre** [comment]
Sorry I had some publishing issues apparently and I am currently on vacations with limited access to internet. Can you publish locally from master?

**Comment by nairoa** [comment]
Verified it works the minimal example with a locally published version.
Thanks!

**Comment by etorreborre** [comment]
I will be home on Thursday and I should be able to publish a release then

**Comment by nadavwe** [comment]
great, thanks! =)

**Comment by etorreborre** [comment]
Hi I have released 4.3.3 now

**Comment by nairoa** [comment]
Thanks!

**Comment by etorreborre** [comment]
Good I'm closing this issue now.
