### ISSUE TITLE
JUnitRunner: beforeAll and afterAll steps registered as a test in junit

### ISSUE THREAD

**Issue by kaatzee** [etorreborre/specs2#691]
When there is implemented beforeAll or/and afterAll method in test they are registered as test called 'step' in junit. 

I have provided project (https://github.com/kaatzee/specs2Issues) to reproduce this issue. Run https://github.com/kaatzee/specs2Issues/blob/master/src/test/scala/s2i/beforeandafterallastest/HelloWorldSpec.scala test with JUnitRunner.

**Comment by etorreborre** [comment]
fixed with #700
