### ISSUE TITLE
JUnitRunner: test marked as pendingUntilFixed not displayed correctly in junit.

### ISSUE THREAD

**Issue by kaatzee** [etorreborre/specs2#693]
Issue is reproduced here: https://github.com/kaatzee/specs2Issues/blob/master/src/test/scala/s2i/pendinguntilfixed/HelloWorldSpec.scala. Just run it with JUnitRunner.

According to https://memorynotfound.com/add-junit-listener-example/ ignored test should be registered in JUnit without firing 'start'. This code is also provided in https://github.com/kaatzee/specs2Issues/blob/master/src/test/java/s2i/junitlistener/RunListenerTest.java.

**Comment by etorreborre** [comment]
fixed with #700
