### ISSUE TITLE
Scala specs2 Test reports for integration tests.

### ISSUE THREAD

**Issue by navneetchamala** [etorreborre/specs2#702]
Hi,

   I am trying to generate *.xml test reports for my integration tests (IT). I am able to do it for unit tests by passing the testOptions in my build.sbt file but that doesn't work for my IT since I dont run them using sbt test but use the Runners class. So, I use something like sbt e2e-tests/run to execute my IT.

**Comment by navneetchamala** [comment]
Thanks for the quick response,
I am trying to run it like this, `sbt <module-name>/run` by passing the arguments through the `build.sbt` file like `testOptions in Test += Tests.Argument("junitxml", "html", "console")` .

I also tried to pass the arguments within the run method that I've overridden like : 
```
val arguments = Arguments.apply("junitxml", "console", "html")
val env = Env(arguments=Arguments, lineLogger = consoleLogger)
```

Neither of them worked. Could you help me with an example if my implementation is itself wrong here.

Thanks,
Navneet

**Comment by etorreborre** [comment]
I'm not sure I understand. If you are running `sbt <module-name>/run` method that means that you have a `main` method in your `<module-name>` isn't it? What is inside this `main` method?

**Comment by etorreborre** [comment]
I'm closing this issue now please reopen if you want to discuss it more.
