### ISSUE TITLE
Jenkins xUnit cannot parse JUnit XML with a time value in exponential notation

### ISSUE THREAD

**Issue by peyerc** [etorreborre/specs2#703]
In our JUnit XML Output we have time values in exponential notation which cannot be parsed by the Jenkins plugin xUnit. Is this something, which can be considered as bug or is our test time value not supported?

```
INFO: [JUnit] - 41 test report file(s) were found with the pattern '**/target/test-reports/*.xml' relative to '/var/lib/jenkins/jobs/test/workspace' for the testing framework 'JUnit'.
WARNING: The file '/var/lib/jenkins/jobs/test/workspace/target/test-reports/ch.srg.test.episode.function.EpisodeCreatorHttpIntegrationTest.xml' is an invalid file.
WARNING: At line 2 of file:/var/lib/jenkins/jobs/test/workspace/target/test-reports/ch.srg.test.episode.function.EpisodeCreatorHttpIntegrationTest.xml:cvc-pattern-valid: Value '3.069005969049E9' is not facet-valid with respect to pattern '(([0-9]{0,3},)*[0-9]{3}|[0-9]{0,3})*(\.[0-9]{0,3})?' for type 'SUREFIRE_TIME'.
WARNING: At line 2 of file:/var/lib/jenkins/jobs/test/workspace/target/test-reports/ch.srg.test.episode.function.EpisodeCreatorHttpIntegrationTest.xml:cvc-attribute.3: The value '3.069005969049E9' of attribute 'time' on element 'testsuite' is not valid with respect to its type, 'SUREFIRE_TIME'.
ERROR: The plugin hasn't been performed correctly: The result file '/var/lib/jenkins/jobs/test/workspace/target/test-reports/ch.srg.test.episode.function.EpisodeCreatorHttpIntegrationTest.xml' for the metric 'JUnit' is not valid. The result file has been skipped.
```

**Comment by etorreborre** [comment]
In which xml field are you seeing this value?

**Comment by peyerc** [comment]
It's in testsuite and testcase:

```
<?xml version='1.0' encoding='UTF-8'?>
<testsuite hostname="..." name="ch.srg.tmsclient.episode.function.EpisodeCreatorHttpIntegrationTest" tests="2" errors="0" failures="0" skipped="2" time="3.069703825896E9">
    ...
    <testcase classname="ch.srg.tmsclient.episode.function.EpisodeCreatorHttpIntegrationTest" name="Calling the create episode function should::return the expected result" time="1.534851912947E9">
        <skipped/>
    </testcase>
    <testcase classname="ch.srg.tmsclient.episode.function.EpisodeCreatorHttpIntegrationTest" name="Calling the create episode function should::return the expected success" time="1.534851912949E9">
    <skipped/>
</testcase>
    <system-out><![CDATA[]]></system-out>
    <system-err><![CDATA[]]></system-err>
</testsuite>
```

**Comment by etorreborre** [comment]
The code for time formatting is [here](https://github.com/etorreborre/specs2/blob/master/junit/shared/src/main/scala/org/specs2/reporter/JUnitXmlPrinter.scala#L114):
```scala
def formatTime(t: Long) = "%.3f" format (t / 1000.0)
```
It is not yet clear to me why it ends up like this. Which Scala/JVM versions are you running on?

**Comment by etorreborre** [comment]
Also those are *huge* execution times, how is the execution in reality?

**Comment by peyerc** [comment]
We are using Scala 2.12 with Java 1.8.0_181. SBT has version 1.2.1

The execution time in fact is only 21 ms for a result value of 3.070011625146E9.

`[info] EpisodeCreatorHttpIntegrationTest
[info] Calling the create episode function should
[info]   o return the expected result
[info] SKIPPED
[info]   o return the expected success
[info] SKIPPED
[info] Total for specification EpisodeCreatorHttpIntegrationTest
[info] Finished in 21 ms
`

`WARNING: The file '/var/lib/jenkins/jobs/tms-client-scala-mockintegration/workspace/target/test-reports/ch.srg.tmsclient.episode.function.EpisodeCreatorHttpIntegrationTest.xml' is an invalid file.
WARNING: At line 2 of file:/var/lib/jenkins/jobs/tms-client-scala-mockintegration/workspace/target/test-reports/ch.srg.tmsclient.episode.function.EpisodeCreatorHttpIntegrationTest.xml:cvc-pattern-valid: Value '3.070011625146E9' is not facet-valid with respect to pattern '(([0-9]{0,3},)*[0-9]{3}|[0-9]{0,3})*(\.[0-9]{0,3})?' for type 'SUREFIRE_TIME'.
`

**Comment by peyerc** [comment]
I just realized that we are using an old Specs2 (3.9.4) version on the Jenkins Build in question. When I have results with a more recent version I will update this issue.

**Comment by peyerc** [comment]
Indeed with a recent version of Specs2 (4.0.3) the problem is gone. Sorry for any troubles caused.

**Comment by etorreborre** [comment]
No worries I'm glad everything's fixed for you.
