### ISSUE TITLE
Problem: Throwing Sub-class of scala.util.control.NoStackTrace Appears to Not Fail Test

### ISSUE THREAD

**Issue by kevinmeredith** [etorreborre/specs2#714]
Hello!

In the following, it seems to me that testing `net.Test` should fail in the same fashion as `net.Test2`. However, it apparently does not:

```scala
$cat build.sbt
scalaVersion := "2.12.7"

libraryDependencies += "org.specs2" %% "specs2-core" % "4.3.4"
$cat src/test/scala/net/Test.scala
package net

import org.specs2.mutable.Specification

object Test extends Specification {

  object MyErr extends scala.util.control.NoStackTrace

  "throwing a NoStackTrace" >> {
    "..." >> {
     val x: Int = throw MyErr
     x ==== 10
    }
  }
}

$cat src/test/scala/net/Test2.scala
package net

import org.specs2.mutable.Specification

object Test2 extends Specification {

 object MyErr2 extends RuntimeException("!")

 "throwing a RuntimeException" >> {
    "..." >> {
     val x: Int = throw MyErr2
     x ==== 10
    }   
 }

}


$sbt "; testOnly net.Test"
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=2G; support was removed in 8.0
[info] Loading settings for project global-plugins from idea.sbt ...
[info] Loading global plugins from /Users/kmeredith/.sbt/1.0/plugins
[info] Loading project definition from /Users/kmeredith/Workspace/specs2-issue/project
[info] Loading settings for project specs2-issue from build.sbt ...
[info] Set current project to specs2-issue (in build file:/Users/kmeredith/Workspace/specs2-issue/)
[info] Test
[info] throwing a NoStackTrace
[error] net.Test$MyErr$
[info] Passed: Total 0, Failed 0, Errors 0, Passed 0
[success] Total time: 2 s, completed Oct 10, 2018 6:07:03 PM
$sbt "; testOnly net.Test2"
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=2G; support was removed in 8.0
[info] Loading settings for project global-plugins from idea.sbt ...
[info] Loading global plugins from /Users/kmeredith/.sbt/1.0/plugins
[info] Loading project definition from /Users/kmeredith/Workspace/specs2-issue/project
[info] Loading settings for project specs2-issue from build.sbt ...
[info] Set current project to specs2-issue (in build file:/Users/kmeredith/Workspace/specs2-issue/)
[info] Test2
[info] throwing a RuntimeException
[error]   ! ...
[error]    net.Test2$MyErr2$: ! (Test2.scala:-1)
[error] net.Test2$MyErr2$.<clinit>(Test2.scala)
[error] net.Test2$.$anonfun$new$2(Test2.scala:11)
[info] Total for specification Test2
[info] Finished in 157 ms
[info] 1 example, 0 failure, 1 error
[error] Error: Total 1, Failed 0, Errors 1, Passed 0
[error] Error during tests:
[error] 	net.Test2
[error] (Test / testOnly) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 2 s, completed Oct 10, 2018 6:07:15 PM
```

**Comment by etorreborre** [comment]
Interesting, there might be some special casing of exceptions which does this. I will have a look.

**Comment by kevinmeredith** [comment]
Thanks, @etorreborre, for taking a look.

My teammate observed this behavior. He further said:

> It looks to me like these silently failing tests stem from https://github.com/etorreborre/specs2/blob/SPECS2-4.0.3/common/shared/src/main/scala/org/specs2/execute/ResultExecution.scala#L24 not handling Throwables. Extending Exception rather than just Throwable or NoStackTrace (which itself extends Throwable) allows the failures to be caught and reported.

**Comment by etorreborre** [comment]
Right, I see now the idea is that `Throwables` that are not `Exceptions` are generally `Errors` like OOME or `LinkageError` which I indeed don't try to catch in the test. That being said it must be caught somewhere because it is then silent.

**Comment by etorreborre** [comment]
Also what is surprising is that sbt displays an error but reports a success eventually.

**Comment by etorreborre** [comment]
Ok, I found where the reporting was missing. This is fixed on master. Do you need anything like this soon?

**Comment by gebner** [comment]
We have also been surprised by this behavior (and missed some bugs in the past).  Why are some exceptions ignored at all?  I would have expected a test to fail if there is any error at all, in particular if there's a severe one like `LinkageError` etc.

**Comment by kevinmeredith** [comment]
> Ok, I found where the reporting was missing. This is fixed on master. Do you need anything like this soon?

Thanks a lot, @etorreborre! Are you able to please cut a release? Then, I'll upgrade to that version.

**Comment by etorreborre** [comment]
Done `4.3.5` is out now.

**Comment by etorreborre** [comment]
Yep let's do it.
