### ISSUE TITLE
Partial information when one test infinitely loops

### ISSUE THREAD

**Issue by buzden** [etorreborre/specs2#720]
Consider that specs2 is used with `ScalaCheck` and specification extends typelevel's `Discipline`. Consider that `def is` contains the discipline's `checkAll` call. I.e., 

```scala
import org.specs2._
import org.typelevel.discipline.Discipline

class Spec extends Specification with ScalaCheck with Discipline { def is = s2"""
  Whatever laws
    $monadLaws
  """

  def monadLaws = checkAll(MonadTests[Whatever].monad[Int, Int, String])
}
```

This means that a single item inside the `def is` corresponds to several tests.

If one particular test inside these tests loops infinitely, then the problem is that being run with `sbt test`, specs2 does not print any information about such `Spec` specification (as if it was not started). Being run with IntelliJ IDEA, I can see that some tests have passed but running is still performed (however, being stuck).

Maybe, results printing should be a little bit more eager when running through `sbt test`?

**Comment by etorreborre** [comment]
Can you create a small project reproducing the issue please? I would like to play with it. There might already be several options we can use (including putting a simple `sequential`) to catch this issue.

**Comment by buzden** [comment]
Sorry for retarding! Please find [here](https://github.com/etorreborre/specs2/files/2600402/small-bad-monad.zip) an archive with a small reproducing project.

When this project is tested using IntelliJ IDEA, I can see that 11 tests have passed and that tests are still pending (although, never ending and not showing the name of infinitely looping test).

![idea-shows-succ-tests](https://user-images.githubusercontent.com/2602116/48784122-15b21300-ecf3-11e8-98de-37590fb86802.png)

However, being run using `sbt test`, nothing except the compiling `[info]` messages are shown.

If I had two monads -- one which infinitely loops and another which is correct -- `sbt test` would show me okays for the good monad (assuming its testing starts first) but still shows nothing for the bad (infinitely looping) one.

**Comment by etorreborre** [comment]
Thank you for this small project. One thing you can do is to use the `ExamplesTimeout` trait decribed [here](https://etorreborre.github.io/specs2/guide/SPECS2-4.3.4/org.specs2.guide.TimeoutExamples.html) and pass `timeout 100` (`100 ms`) on the command line. Then you should see
```
[info] BadMonadLawsSpec
[info]   BadMonad laws
[info]     monad laws must hold for BadMonad
[info] + monad.ap consistent with product + map
[info] + monad.applicative homomorphism
[info] + monad.applicative identity
[info] + monad.applicative interchange
[info] + monad.applicative map
[info] + monad.applicative unit
[info] o monad.apply composition
[info] TIMEOUT: 100 milliseconds
[info] o monad.covariant composition
[info] TIMEOUT: 100 milliseconds
[info] + monad.covariant identity
[info] o monad.flatMap associativity
[info] TIMEOUT: 100 milliseconds
[info] + monad.flatMap consistent apply
[info] o monad.flatMap from tailRecM consistency
[info] TIMEOUT: 100 milliseconds
[info] + monad.invariant composition
[info] + monad.invariant identity
[info] o monad.map flatMap coherence
[info] TIMEOUT: 100 milliseconds
[info] + monad.map2/map2Eval consistency
[info] + monad.map2/product-map consistency
[info] o monad.monad left identity
[info] TIMEOUT: 100 milliseconds
[info] o monad.monad right identity
[info] TIMEOUT: 100 milliseconds
[info] + monad.monoidal left identity
[info] + monad.monoidal right identity
[info] + monad.mproduct consistent flatMap
[info] + monad.productL consistent map2
[info] + monad.productR consistent map2
[info] + monad.semigroupal associativity
[info] o monad.tailRecM consistent flatMap
[info] TIMEOUT: 100 milliseconds
[info] o monad.tailRecM stack safety
[info] TIMEOUT: 100 milliseconds
[info] Total for specification BadMonadLawsSpec
[info] Finished in 580 ms
[info] 27 examples, 1809 expectations, 0 failure, 0 error, 9 skipped
[info] Passed: Total 27, Failed 0, Errors 0, Passed 18, Skipped 9
```

**Comment by buzden** [comment]
By the way, I realized that setting `logBuffered` option to `false` in `build.sbt` as it is described [in the guide](https://etorreborre.github.io/specs2/guide/SPECS2-4.3.4/org.specs2.guide.Runners.html) actually solves issue of printing information along the execution. So, I'm closing this.
