### ISSUE TITLE
[Feature request] Introduce test dependency

### ISSUE THREAD

**Issue by zafarella** [etorreborre/specs2#721]
would be really useful to have such feature

**Comment by etorreborre** [comment]
Could you please elaborate? What would be the use case? What would be the syntax? What would be the execution model?

**Comment by zafarella** [comment]
Sorry missed your comments. So, what i had in mind is execution of one test to be dependent on another test, similar to what testNG have (`http://testng.org/doc/documentation-main.html#dependencies-with-annotations`)

**Comment by etorreborre** [comment]
Something you can do is to group your tests and insert steps in between with `stopOnFail`: https://etorreborre.github.io/specs2/guide/SPECS2-4.2.0/org.specs2.guide.Execution.html#stop-the-execution. Then the rest of the specification will be skipped if the first group of examples doesn't pass.
The advantages over TestNG is that you don't have to explicitly declare groups and that in a given group the tests still execute concurrently (unless the whole spec is `sequential`).
Can you please try this approach and tell me how it works for you?

**Comment by zafarella** [comment]
Thank you @etorreborre , let me give it a try. Will update whenever will have a chance

**Comment by etorreborre** [comment]
Just looking at this issue again now :-). Did you have a chance to try what I suggested?

**Comment by zafarella** [comment]
Sorry, did not had a chance to test it frankly.

**Comment by etorreborre** [comment]
No problem. I will maybe revisit this subject in the future
