### ISSUE TITLE
`showtimes` option seems to print incorrect data

### ISSUE THREAD

**Issue by buzden** [etorreborre/specs2#728]
_Disclaimer: since, we are talking about wall time intervals measured locally in unreapeatable circumstances, this all may be a nut._

After #720 I tried to use `ExamplesTimeout` and maybe I'm using it in a wrong way. But what I can see is that when using `showtimes` option with the `timeout` one when using `ExamplesTimeout`, printed time values strangely depend on the given timeout. In the [example project](https://github.com/buzden/small-bad-monad/) (at least, at the git tag [specs2-issue-728](https://github.com/buzden/small-bad-monad/releases/tag/specs2-issue-728)) when you run `sbt` console and run it using various timeouts, you get the following.

- **1 second timeout**

  Running `testOnly -- showtimes timeout 1000` you get
  ```
  [info] BadMonadLawsSpec
  [info]   BadMonad laws
  [info]     monad laws must hold for BadMonad
  [info] + monad.ap consistent with product + map (382 ms)
  [info] + monad.applicative homomorphism (101 ms)
  [info] + monad.applicative identity (108 ms)
  [info] + monad.applicative interchange (112 ms)
  [info] + monad.applicative map (106 ms)
  [info] + monad.applicative unit (127 ms)
  [info] + monad.apply composition (311 ms)
  [info] + monad.covariant composition (119 ms)
  [info] + monad.covariant identity (7 ms)
  [info] + monad.flatMap associativity (144 ms)
  [info] + monad.flatMap consistent apply (109 ms)
  [info] o monad.flatMap from tailRecM consistency (1 second, 18 ms)
  [info] TIMEOUT: 1000 milliseconds
  ... (cut for clarity)
  [info] Passed: Total 27, Failed 0, Errors 0, Passed 23, Skipped 4
  [success] Total time: 15 s, ...
  ```

  So, you can see rather small execution times and time 1-second timeout (as expected) when using `tailRecM` (this example has infinitely looping implementation for this function).

- **10 seconds timeout**

  Running `testOnly -- showtimes timeout 10000` you get
  ```
  [info] BadMonadLawsSpec
  [info]   BadMonad laws
  [info]     monad laws must hold for BadMonad
  [info] + monad.ap consistent with product + map (1 second, 116 ms)
  [info] + monad.applicative homomorphism (1 second, 39 ms)
  [info] + monad.applicative identity (1 second, 8 ms)
  [info] + monad.applicative interchange (1 second, 4 ms)
  [info] + monad.applicative map (1 second, 31 ms)
  [info] + monad.applicative unit (11 ms)
  [info] + monad.apply composition (1 second, 39 ms)
  [info] + monad.covariant composition (1 second, 55 ms)
  [info] + monad.covariant identity (1 second, 5 ms)
  [info] + monad.flatMap associativity (1 second, 39 ms)
  [info] + monad.flatMap consistent apply (1 second, 9 ms)
  [info] o monad.flatMap from tailRecM consistency (10 seconds, 11 ms)
  [info] TIMEOUT: 10000 milliseconds
  ... (cut for clarity)
  [info] Passed: Total 27, Failed 0, Errors 0, Passed 24, Skipped 3
  [success] Total time: 62 s, ...
  ```

  You can see nice 10 seconds timeout for the `tailRecM` test but... Why, do you think, we have all passing tests shown time increased?

- **100 seconds timeout**

  If you try more, i.e. `testOnly -- showtimes timeout 100000`, you get
  ```
  [info] BadMonadLawsSpec
  [info]   BadMonad laws
  [info]     monad laws must hold for BadMonad
  [info] + monad.ap consistent with product + map (10 seconds, 227 ms)
  [info] + monad.applicative homomorphism (10 seconds, 272 ms)
  [info] + monad.applicative identity (10 seconds, 303 ms)
  [info] + monad.applicative interchange (10 seconds, 343 ms)
  [info] + monad.applicative map (10 seconds, 31 ms)
  [info] + monad.applicative unit (10 seconds, 72 ms)
  [info] + monad.apply composition (10 seconds, 103 ms)
  [info] + monad.covariant composition (10 seconds, 123 ms)
  [info] + monad.covariant identity (10 seconds, 13 ms)
  [info] + monad.flatMap associativity (10 seconds, 88 ms)
  [info] + monad.flatMap consistent apply (10 seconds, 104 ms)
  [info] o monad.flatMap from tailRecM consistency (1 minute 40 seconds, 10 ms)
  [info] TIMEOUT: 100000 milliseconds
  ... (cut for clarity)
  [info] Passed: Total 27, Failed 0, Errors 0, Passed 24, Skipped 3
  [success] Total time: 256 s, ...
  ```

  You see even more increating of shown time for the passing tests.

So, maybe this is because of parallel execution of tests, but what I see is incorrect shown time for passed tests when timeout is set, which equals usually approx. 10% of the timeout (and in other cases it is equal to timeout). This looks suspicious and incorrect. What do you think?

**Comment by buzden** [comment]
I don't know whether this is related or not, but usage of `ExamplesTimeout` even without any `timeout` option seems to increase testing time by approximately factor 12!

**Comment by etorreborre** [comment]
That's weird indeed. I'm on vacations right now I will have a look at this when I come back.

**Comment by etorreborre** [comment]
I suspect that the wait the `terminate` matcher works internally is flawed. It runs both the action to check for termination + a timer and I suppose it waits until the timer is finished to see if the original action terminated ok. I'll try to tackle that during the week

**Comment by etorreborre** [comment]
The solution is indeed to change the implementation of the `ExamplesTimeout` trait with:
```
def aroundTimeout(to: Duration)(implicit ee: ExecutionEnv): Around =
    new Around {
      def around[T : AsResult](t: =>T) = {
        try Await.result(Future(AsResult(t))(ee.executionContext), to)
        catch { case e: Exception => Skipped("TIMEOUT!!! "+to.toString) }
      }
    }
```
Now you should see proper timings.
