### ISSUE TITLE
Test that should fail, passes

### ISSUE THREAD

**Issue by samthebest** [etorreborre/specs2#729]
The following does not fail the tests, so exit code is still 0, `$? = 0`

```
import org.specs2.mutable.Specification

object Test extends Specification {
  "Foo" should {
    throw new Exception("boom")

    "test" in {
      1 must_=== 1
    }
  }
```

One has to actually read the logs and see the error!  Obviously for automated builds this is a big problem.

Version "4.3.4"

**Comment by etorreborre** [comment]
Which command do you use to run the tests? I've just tried `sbt test` on a project having that spec and with `specs2-4.4.1` and I get `1` as the exit code. Can you try to upgrade `specs2` to a more recent version maybe?

**Comment by samthebest** [comment]
@etorreborre  Thanks, updating to 4.4.1 fixed the issue.

**Comment by etorreborre** [comment]
👍
