### ISSUE TITLE
tests hanging in Scala community build

### ISSUE THREAD

**Issue by SethTisue** [etorreborre/specs2#732]
seen at e.g. https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/4231/ . it's been happening consistently. I can work around it for now by rewinding to 96211c1f0a4519b93c3

**Comment by etorreborre** [comment]
Thanks @SethTisue I'm going to have a look at that. There's indeed a one line change which seems to affect 2 specifications, either one passes and the other one blocks or one fails and the other one passes.

**Comment by etorreborre** [comment]
@SethTisue this commit should the 2 failing specs: 72d897c  but let's wait for the CI to tell us :-)

**Comment by SethTisue** [comment]
let's see how 
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/4267/ (404 til Jenkins wakes up) does

**Comment by etorreborre** [comment]
The build is failing but apparently not because of specs2
