### ISSUE TITLE
exception when mocking method, from previous mock 

### ISSUE THREAD

**Issue by avilshadow** [etorreborre/specs2#734]
Sorry, seems I can`t make the title more readable.
the main inconvinience with default mocking way in org.specs2.mock.Mockito
this "returns" looks like call method before mock it.
yes I could use doReturn and etc.. bet it is not so convinient.

see [scastie](https://scastie.scala-lang.org/EvqsV8R8TzKO4yq6Uma6aw) or put it in test

```
import org.specs2.mock.Mockito
import org.specs2.mutable.Specification

class Spec extends Specification with Mockito {
  trait Reade {
    def read: String
  }

"test" in {
  val reader = mock[Reade]
  reader.read throws new UnsupportedOperationException("oops, error happens!")
  reader.read must throwA[UnsupportedOperationException]

  reader.read returns "woha!" // there should not be an UnsupportedOperationException
  reader.read mustEqual "woha!"
}
}

**Comment by etorreborre** [comment]
I think you need to reset your mock in that case, with `Mockito.reset` (https://static.javadoc.io/org.mockito/mockito-core/2.25.1/org/mockito/Mockito.html#17). Don't you?

**Comment by avilshadow** [comment]
yes, possible workaround. a bit better as for me use doReturn().when() mocking style, which has better behaviour
