### ISSUE TITLE
Publish for Scala 2.13-RC1?

### ISSUE THREAD

**Issue by mslinn** [etorreborre/specs2#738]
I see the version for 2.13-M5. Any chance of publishing Specs2 for the RCs?

(specs2-core  and specs2-junit)

**Comment by etorreborre** [comment]
I published it 2 weeks ago: https://repo1.maven.org/maven2/org/specs2/specs2-core_2.13.0-RC1/4.5.1, can't you access it on Sonatype?

**Comment by mslinn** [comment]
Ah, you are correct, thank you!
