### ISSUE TITLE
Multiple parameter lists and by-name parameters breaks stubbing

### ISSUE THREAD

**Issue by afine** [etorreborre/specs2#740]
I ran into this issue with both 4.3.4 and 4.1.0:

We would like to stub a method that looks similar to this:
```scala
class Cache {
  def getFromCache(fallback: => Future[Thing])(implicit key: String): Future[Thing] = ...
}
```

by doing something like:
```scala
val mock = mock[Cache]
mock.getFromCache(any[Future[Thing]]())(be(key)).returns(...)
```

Any invocation of the `getFromCache` method results in a `null` value on 4.3.4.

On 4.1.0 we see:
```
org.mockito.exceptions.misusing.InvalidUseOfMatchersException: 
Invalid use of argument matchers!
2 matchers expected, 1 recorded:
-> at org.specs2.mock.mockito.ArgThat$class.argThat(ArgThat.scala:10)
```

After some debugging I believe this has to do with the order the matchers are "reported" to matcher storage. 

I can work around the issue by doing something like:
```scala
val mock = mock[Cache]
val arg1 = any[Future[Thing]]()
val arg2 = be(key)
mock.getFromCache(arg1)(arg2).returns(...)
```

**Comment by etorreborre** [comment]
I'm am going to look into this but you are a good candidate for testing the migration to `mockito-scala` :-). Indeed the support of Mockito is going to be deprecated in specs2 in favour of `mockito-scala`.

Please try to use `org.mockito.mockito-scala-1.4.0-beta.8` and talk to @bbonnano on [gitter](https://gitter.im/etorreborre/specs2) to get some help with the migration (you can already find some details in the latest gitter messages).

**Comment by afine** [comment]
In order to close the loop on this and avoid leaving you hanging I wanted to let you know that this code has been refactored so these mocks would not be necessary and I will likely not have the time to test `mockito-scala` in the immediate future. 
 
In the event I run into similar issues in the future I will definitely give it a shot.

**Comment by etorreborre** [comment]
Great thanks for letting me know. I'm going to bet on the non-return of this issue so that I can focus on other things :-).
