### ISSUE TITLE
Publish for Scala 2.13.0-RC2

### ISSUE THREAD

**Issue by dwijnand** [etorreborre/specs2#741]
See https://github.com/scala/make-release-notes/blob/2.13.x/projects-2.13.md for both the state of specs2's dependencies and also update it when this issue is resolved.

Blocked on (non-exhaustive):
- [x] https://github.com/typelevel/kind-projector/issues/103
- [ ] https://github.com/rickynils/scalacheck/issues/471

**Comment by SethTisue** [comment]
ScalaCheck has published: https://repo1.maven.org/maven2/org/scalacheck/scalacheck_2.13.0-RC2/1.14.0/

**Comment by etorreborre** [comment]
Done thanks to @rossabaker: https://github.com/etorreborre/specs2/pull/742

**Comment by dwijnand** [comment]
Excellent, thank you.

**Comment by dwijnand** [comment]
@etorreborre for the avoidance of doubt, you closed the issue because you're publishing now?  I'm not seeing anything at https://repo1.maven.org/maven2/org/specs2/specs2-core_2.13.0-RC2/ right now.

**Comment by etorreborre** [comment]
Yes jars are on the way but my connection is slower than I expected :-)

**Comment by etorreborre** [comment]
Here it is: https://oss.sonatype.org/#nexus-search;quick~specs2-core_2.13.0-RC2
