### ISSUE TITLE
Publish for 2.13.0

### ISSUE THREAD

**Issue by raboof** [etorreborre/specs2#745]

**Comment by symbiont-eric-torreborre** [comment]
Thanks for putting this issue on my radar, I will publish as soon as my dependencies are published.

**Comment by SethTisue** [comment]
ScalaCheck 1.14.0 has now been published for Scala 2.13.

**Comment by symbiont-eric-torreborre** [comment]
Thanks @SethTisue I'm now only waiting on cats to publish their artifacts (and ideally kind-projector but I can work around that).

**Comment by SethTisue** [comment]
kind-projector published, but under a new version number: 0.10.3

**Comment by symbiont-eric-torreborre** [comment]
Thanks

**Comment by etorreborre** [comment]
Done.

**Comment by SethTisue** [comment]
https://repo1.maven.org/maven2/org/specs2/specs2-core_2.13/4.5.1/ :+1:
