### ISSUE TITLE
Quotes are not added to Options in failure messages in Scala 2.13

### ISSUE THREAD

**Issue by jcazevedo** [etorreborre/specs2#749]
In Scala 2.13, `Option` extends `IterableOnce` and `TraversableOnce` is a (deprecated) alias to `IterableOnce`. This creates an inconsistency with the output of failure messages including `Option`s, since `Option`s become unquoted in Scala 2.13, but quoted in Scala versions below 2.13:

https://github.com/etorreborre/specs2/blob/8305db76c5084e4b3ce5827ce23117f6fb6beee4/common/shared/src/main/scala/org/specs2/text/Quote.scala#L14-L24

@etorreborre: I'd be happy to submit a PR to fix this, but I'd like your input first. Should `Option`s be quoted or unquoted?

**Comment by etorreborre** [comment]
I would say let's embrace 2.13 and make `Option` quoted. And yes I would be happy with a PR :-)
