### ISSUE TITLE
[Feature Request] Ability to specify ScalaCheck parameters such as minSuccessfulTests  for each property

### ISSUE THREAD

**Issue by jkleckner** [etorreborre/specs2#750]
Some properties of `ScalaCheck` are heavyweight and some less so.

It would be very nice to have a way to set the `minSuccessfulTests` and `maxDiscardRatio` inline with a test or at the class level.

**Comment by symbiont-eric-torreborre** [comment]
Do you mean this: https://etorreborre.github.io/specs2/guide/SPECS2-4.3.4/org.specs2.guide.UseScalaCheck.html#test-properties?

**Comment by jkleckner** [comment]
Uh, yes thanks.  The disconnect between `minTestsOk` as an argument and `minSuccessfulTests` as a parameter in `ScalaCheck` threw me off in my searching...

**Comment by symbiont-eric-torreborre** [comment]
Yes that's my fault for preferring shorter names :-)

**Comment by jkleckner** [comment]
@symbiont-eric-torreborre Not a problem.  Thank you very much for specs2.  I created a trivial MR #752 to make note of this.
