### ISSUE TITLE
SpecificationsFinder omits specs with comments in the package definition

### ISSUE THREAD

**Issue by peter-empen** [etorreborre/specs2#755]
Looking into why a specific spec was not included by the finder we found out that it will be included if we remove a  comment like in
```
package x
package y // some comment
package z
```
Although rarely needed, it would be nice one could use comments there while relying on finder results.

**Comment by symbiont-eric-torreborre** [comment]
That's the benefit of regex parsing instead of relying on a proper language parser :-). I will see if I can get around this but don't expect it too soon because I'm on vacation at the end of the week and quite busy until then.

**Comment by peter-empen** [comment]
No hurry, we moved the comment to the top of the file. So it's just a precaution for the future.
Have a nice vacation!
