### ISSUE TITLE
Nested mutable examples not running with Scala 2.13

### ISSUE THREAD

**Issue by jroper** [etorreborre/specs2#757]
This spec here:

https://github.com/jroper/play-geojson/blob/master/src/test/scala/au/id/jazzy/play/geojson/ExampleSpec.scala

Has examples nested two deep (ie, `"foo" should { "do something" in { "bar" in { ... } } }`. Using specs 4.6.0, this runs fine with Scala 2.11 and 2.12, but with 2.13, it doesn't run at all, it's as if the specs aren't there. Not sure if this is a Scala issue, specs2 issue, or if it's by design with Scala 2.13 and I need to update my specs.

**Comment by symbiont-eric-torreborre** [comment]
Hi James, I'm on holidays at the moment for 10 more days. I will have a look at that when I come back and unfortunately I have no idea of what is wrong there (also kind of annoyed that the current test suite does not cover this case)

**Comment by etorreborre** [comment]
Actually I couldn't resist having a quick look. It seems that changing `object ExampleSpec` to `class ExampleSpec` fixes the issue. At least you have a work-around and I have a small reproducible case to investigate.

**Comment by jroper** [comment]
Thanks @etorreborre! Please enjoy your holiday, don't let my problems get in your way :)

**Comment by etorreborre** [comment]
Wow, I need further investigation but it seems that Scala 2.12 was actually buggy w.r.t the initialization of objects where the code in the body of an object would run twice and this would discover the spec fragments properly. Whereas in 2.13 the initialization of an object is done only once and now the code discovering the fragments is buggy. This can only encourage me to remove that complicated code which was only there to support a marginal feature.

**Comment by etorreborre** [comment]
I'm closing this issue. The code which is causing this will disappear anyway in the next major version of specs2.

**Comment by xuwei-k** [comment]
https://github.com/etorreborre/specs2/pull/826 🙏
