### ISSUE TITLE
Wrong line number in stacktrace

### ISSUE THREAD

**Issue by dawidchodura** [etorreborre/specs2#781]
I'm having trouble configuring specs2 so that the stacktrace of the exception would contain the correct line number, where it occurred.

I've prepared the minimal example (specs2 4.8.0, scala 2.12.10) with the exception thrown on line number 11:
https://github.com/dawidchodura/specs2-exception-sscce/blob/master/src/test/scala/example/ExampleTest.scala#L11

When I run `mvn clean install` I get the line number 9 in the stacktrace:
```
00:07:53.821 [INFO] Running example.ExampleTest
00:07:54.586 [ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.756 s <<< FAILURE! - in example.ExampleTest
00:07:54.587 [ERROR] Example should::report the line number of the exception(example.ExampleTest)  Time elapsed: 0.004 s  <<< ERROR!
java.lang.RuntimeException: Which line did this exception occur at?
	at example.ExampleTest.$anonfun$new$2(ExampleTest.scala:9)
```

When I remove `new InnerScope` it correctly reports line number 11:
```
00:09:29.241 [INFO] Running example.ExampleTest
00:09:30.021 [ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.768 s <<< FAILURE! - in example.ExampleTest
00:09:30.021 [ERROR] Example should::report the line number of the exception(example.ExampleTest)  Time elapsed: 0.003 s  <<< ERROR!
java.lang.RuntimeException: Which line did this exception occur at?
	at example.ExampleTest.$anonfun$new$2(ExampleTest.scala:11)
```
However I need the solution, where I will be able to keep the `new InnerScope`, so removing it is not enough.

I've tried adding `failtrace` and `fullstacktrace` to `maven-surefire-plugin` attribute `argLine`, which should help according to the ConsoleOutput manual, but it doesn't change anything. The manual does not mention `maven-surefire-plugin`, so I suspect I'm not passing the system properties correctly, therefore they are not picked up by specs2.
```
-Dspecs2.failtrace=true -Dfailtrace=true -Dspecs2.fullstacktrace=true -Dfullstacktrace=true
```
https://github.com/dawidchodura/specs2-exception-sscce/blob/master/pom.xml#L85

ConsoleOutput manual:
https://etorreborre.github.io/specs2/guide/SPECS2-4.6.0/org.specs2.guide.ConsoleOutput.html

In Troubleshooting manual in section `custom-output` I've read that adding `verbose` will give me `messages including exceptions and stacktraces about what is going on`. I've tried adding it, but it doesn't help either. I'm probably missing the same thing as with failtrace and fullstacktrace.
```
-Dspecs2.verbose=true -Dverbose=true
```
https://etorreborre.github.io/specs2/guide/SPECS2-4.6.0/org.specs2.guide.Troubleshooting.html#custom-output

I've tried adding `args.report(failtrace = true)` to the test class, but nothing changed - the same exception on line number 9 instead of 11 was reported.
```
import org.specs2.main.ArgProperties

class (...) with ArgProperties {

args.report(failtrace = true)

(...)
```

Could you help me configure specs2, so that I can get the correct line number in the exception stack trace?

**Comment by etorreborre** [comment]
Hi, thanks for reporting this issue which seems to be several issues at once. I tried your code with sbt and things seem to work fine so I suspect the combination of maven+junit+Scope must be fatal here. Unfortunately I can't put my finger on it yet. I will continue digging.

**Comment by symbiont-eric-torreborre** [comment]
Sorry for the delay. I've been doing some investigation but I don't have good news :-(. 

First of all you can specify that you want to display `fullStackTraces` by setting a system property in you pom file, this works fine:
```
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.22.2</version>
                <configuration>
                    <redirectTestOutputToFile>false</redirectTestOutputToFile>
                    <useSystemClassLoader>false</useSystemClassLoader>
                    <systemPropertyVariables>
                        <fullstacktrace/>
                    </systemPropertyVariables>
                </configuration>
            </plugin>
```
Then I checked the stack trace of the exception that specs2 forwards to Maven/Surefire/JUnit and the stacktrace is complete, something like
```
java.lang.Exception: Which line did this exception occur at?
	at example.ExampleTest$$anon$1.<init>(ExampleTest.scala:12)
	at example.ExampleTest.$anonfun$new$2(ExampleTest.scala:11)
	at org.specs2.matcher.Scope$$anon$3.$anonfun$asResult$1(ThrownExpectations.scala:156)
	at org.specs2.execute.ResultExecution.execute(ResultExecution.scala:24)
	at org.specs2.execute.ResultExecution.execute$(ResultExecution.scala:21)
	at org.specs2.execute.ResultExecution$.execute(ResultExecution.scala:134)
	at org.specs2.execute.Result$$anon$4.asResult(Result.scala:246)
	at org.specs2.execute.AsResult$.apply(AsResult.scala:32)
	at org.specs2.execute.AsResult$.$anonfun$safely$1(AsResult.scala:40)
```
Unfortunately when maven reports it the first line disappears. I even tried with the latest surefire plugin `3.0.0-M3` and I get the same issue. From there I think you only have 2 options:

 - try to reproduce the same issue with a regular Maven/JUnit test using Scala
 - or remove the use of `InnerScope`

Sorry I wish I had a better fix for you.

**Comment by etorreborre** [comment]
Sorry for the delay. I've been doing some investigation but I don't have good news :-(.

First of all you can specify that you want to display fullStackTraces by setting a system property in you pom file, this works fine:
```
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.22.2</version>
                <configuration>
                    <redirectTestOutputToFile>false</redirectTestOutputToFile>
                    <useSystemClassLoader>false</useSystemClassLoader>
                    <systemPropertyVariables>
                        <fullstacktrace/>
                    </systemPropertyVariables>
                </configuration>
            </plugin>
```
Then I checked the stack trace of the exception that specs2 forwards to Maven/Surefire/JUnit and the stacktrace is complete, something like
```
java.lang.Exception: Which line did this exception occur at?
	at example.ExampleTest$$anon$1.<init>(ExampleTest.scala:12)
	at example.ExampleTest.$anonfun$new$2(ExampleTest.scala:11)
	at org.specs2.matcher.Scope$$anon$3.$anonfun$asResult$1(ThrownExpectations.scala:156)
	at org.specs2.execute.ResultExecution.execute(ResultExecution.scala:24)
	at org.specs2.execute.ResultExecution.execute$(ResultExecution.scala:21)
	at org.specs2.execute.ResultExecution$.execute(ResultExecution.scala:134)
	at org.specs2.execute.Result$$anon$4.asResult(Result.scala:246)
	at org.specs2.execute.AsResult$.apply(AsResult.scala:32)
	at org.specs2.execute.AsResult$.$anonfun$safely$1(AsResult.scala:40)
```
Unfortunately when maven reports it the first line disappears. I even tried with the latest surefire plugin `3.0.0-M3` and I get the same issue. From there I think you only have 2 options:

 - try to reproduce the same issue with a regular Maven/JUnit test using Scala
 - or remove the use of `InnerScope`

Sorry I wish I had a better fix for you.
