### ISSUE TITLE
publish 4.8.0 for Scala Native

### ISSUE THREAD

**Issue by rwhaling** [etorreborre/specs2#782]
could you publish specs2 4.8.0 to Maven Central for Scala Native?  the most recent version published for Native is 4.7.0, and we need 4.8.0 to be able to support SN in Zio and a few other libraries - happy to help out in any way that I can!

Zio PR:
https://github.com/zio/zio/pull/1428

cc @sideeffffect

**Comment by symbiont-eric-torreborre** [comment]
Hi Richard, I tried to publish the native jars tonight but I have [an issue with my signing key](https://issues.sonatype.org/browse/OSSRH-52848). I tried different things and it seemed to work at some stage but it eventually doesn't. I will have to wait on the Sonatype team.

**Comment by sideeffffect** [comment]
@symbiont-eric-torreborre could you please send us link to the failure? Maybe we could help :)

**Comment by etorreborre** [comment]
Yay, I was able to publish right now. Possibly the key servers had an issue yesterday. Thanks for proposing your help!

The artifacts are will available at: https://repo1.maven.org/maven2/org/specs2/specs2-core_native0.4.0-M2_2.11/4.8.0 once the Sonatype <-> Maven central is done.

**Comment by rwhaling** [comment]
thanks so much!
