### ISSUE TITLE
Performance degradation/non-termination on upgrade to 4.8.0 

### ISSUE THREAD

**Issue by Synesso** [etorreborre/specs2#788]
I haven't been able to isolate the cause, but upgrading

```-      "org.specs2" %% "specs2-core" % "4.7.1" % "test,it",
-      "org.specs2" %% "specs2-mock" % "4.7.1" % "test",
-      "org.specs2" %% "specs2-scalacheck" % "4.7.1" % "test"
+      "org.specs2" %% "specs2-core" % "4.8.0" % "test,it",
+      "org.specs2" %% "specs2-mock" % "4.8.0" % "test",
+      "org.specs2" %% "specs2-scalacheck" % "4.8.0" % "test"
```

Causes my test suite to take significantly longer and thrash the CPU. Travis jobs often time out.

Upgrading to 4.8.1 did not resolve this.

https://github.com/Synesso/scala-stellar-sdk/commit/be3b74409977abdb7c7d4009478cf550a6680a90

**Comment by etorreborre** [comment]
Not good :-(. I will try to see what could have contributed to this but I won't be able to devote much time because my next 2 weeks are going to be very busy. Let's see, hopefully something obvious will stand out.

**Comment by etorreborre** [comment]
I had a quick look at the differences between `4.7.1` and `4.8.1`: https://github.com/etorreborre/specs2/compare/c99945291...68ecf16cc. Most of the commits are dependencies upgrades but I think the best would be if you could check out specs2, revert to one of these old commits, publish locally and see if you can see the performance drop down. By bisecting on the right commit we will get a lot more information.

**Comment by Synesso** [comment]
```e94715dce5b0cd9afb72066c929b8da5ffd67f19 is the first bad commit
commit e94715dce5b0cd9afb72066c929b8da5ffd67f19
Author: kenji yoshida <6b656e6a69@gmail.com>
Date:   Tue Sep 17 19:09:02 2019 +0900

    Update scalacheck to 1.14.1-RC2. remove lolgab scalacheck (#766)
```

**Comment by etorreborre** [comment]
Great find. Since ScalaCheck `1.14.2` is out we can try that one instead or maybe come back to `1.14.0`?

**Comment by etorreborre** [comment]
I can see that you've moved on to more recent versions of specs2 and scalacheck and your test suite seems to be passing reasonably well. So I assume I can close this issue now :-).

**Comment by Synesso** [comment]
Yes, thank you.
