### ISSUE TITLE
new test failures on master (SpecificationsFinderSpec, SourceFileSpec)

### ISSUE THREAD

**Issue by SethTisue** [etorreborre/specs2#798]
```
[error] Failed: Total 766, Failed 3, Errors 0, Passed 763, Pending 1
[error] Failed tests:
[error] 	org.specs2.runner.SpecificationsFinderSpec
[error] 	org.specs2.text.SourceFileSpec
[error] (coreJVM / Test / test) sbt.TestsFailedException: Tests unsuccessful
```

this turned up in the Scala community build: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/5360/artifact/logs/specs2-build.log

(but no worries, I can just use an older commit for now)

**Comment by etorreborre** [comment]
Thanks Seth this was the result of an incorrect fix I did in a rush yesterday.
