### ISSUE TITLE
Broken Examples link

### ISSUE THREAD

**Issue by quartin** [etorreborre/specs2#805]
Hey! I was navigating in the website and noticed it isn't published with the latest release, it is still pointing to `4.6.0`. This wouldn't be a big problem, but this version in particular has a broken examples link (points to `https://github.com/etorreborre/specs2/tree/SPECS2-4.6.0/examples/src/test/scala/examples/jvm`).

**Comment by etorreborre** [comment]
Hi, thanks for reporting this, I have now fixed those links.
