### ISSUE TITLE
publish for Scala.js 1.0?

### ISSUE THREAD

**Issue by SethTisue** [etorreborre/specs2#807]

**Comment by etorreborre** [comment]
I had a look at this last week-end and the issue I found was that scala-parser-combinators didn't have a version 1.0 for Scala.js: https://mvnrepository.com/artifact/org.scala-lang.modules/scala-parser-combinators. Is this something that you could push?

**Comment by SethTisue** [comment]
ticket is https://github.com/scala/scala-parser-combinators/issues/265 . maybe @Philippus will get to it this weekend; if he doesn't have time, I'll tackle it myself on Tuesday

**Comment by Philippus** [comment]
It's released now, https://search.maven.org/search?q=scala-parser-combinators_sjs1_2.1.

**Comment by symbiont-eric-torreborre** [comment]
Thank you @Philippus, I will try to do a release this week-end.

**Comment by etorreborre** [comment]
Thank you @Philippus, I will try to do a release this week-end.

**Comment by etorreborre** [comment]
I just released `specs2-4.9.1` for ScalaJS 1.0 (it should be available soon [here](https://repo1.maven.org/maven2/org/specs2/specs2-core_2.13/4.9.1/).

Just one note, I could not publish the additional modules depending on shapeless since there's not a shapeless version for ScalaJS 1.0 yet (AFAIK).

Thanks again @SethTisue and @Philippus for pushing this.

**Comment by SethTisue** [comment]
Shapeless is available now.

**Comment by etorreborre** [comment]
I see that some code has been committed but I don't see any new release: https://mvnrepository.com/artifact/com.chuusai/shapeless. Is it anywhere else?

**Comment by etorreborre** [comment]
Ok, I just saw Miles's message: https://github.com/milessabin/shapeless/pull/967#issuecomment-593135545. Maybe the artifacts haven't reach Maven's repository yet

**Comment by etorreborre** [comment]
Got it now :-)

**Comment by etorreborre** [comment]
And... `specs2-4.9.2` is now published, hopefully with everything working (see #810)
