### ISSUE TITLE
Missing pages in scaladocs

### ISSUE THREAD

**Issue by tmccombs** [etorreborre/specs2#815]
Many pages seem to be missing in the scaladocs for versions more recent than 4.3.4. For example https://etorreborre.github.io/specs2/api/SPECS2-4.8.3/org/specs2/mock/Mockito.html returns a 404. Even though searching for Mockito gives me a link there.

**Comment by etorreborre** [comment]
Thanks, this is fixed now I had a bunch of bad settings.
