### ISSUE TITLE
almost everything is close to 1E-300

### ISSUE THREAD

**Issue by xxyyz** [etorreborre/specs2#818]
d must beCloseTo(1E-300, SignificantFigures(15))
isSuccess
for almost any Double d.

Try e.g. d = 1D or d = 1E300, which, I believe, should fail.

Moreover, this is true for any 'target' and 'significantFigures' if their exponents' sum is bigger than ~308.

The root cause is that 'Math.pow(10, (sf.number - o - 1).toDouble))' is Double.Infinity in BeSignificantlyCloseTo (https://github.com/etorreborre/specs2/blob/d37f9b761626c78eec93094e722849e0cf98a057/matcher/shared/src/main/scala/org/specs2/matcher/NumericMatchers.scala#L223).

A quick improvement would be to compare the exponents ('order': https://github.com/etorreborre/specs2/blob/d37f9b761626c78eec93094e722849e0cf98a057/matcher/shared/src/main/scala/org/specs2/matcher/NumericMatchers.scala#L230) of 'actual' and 'target' and if their difference is bigger than sf.number, then return false without further checks. I guess however, that this simple change would not fix all such issues, especially in edge cases, where the difference is around sf.number...

The twin of this issue is that 
0 must beCloseTo(1E-300, SignificantFigures(15))
isFailure, though it should be success.

The root cause is that num.toDouble(actual) is 0D and 0D * Double.Infinity (infinity again coming from 'Math.pow(10, (sf.number - o - 1).toDouble))') is Double.NaN, which is not equal to anything, so 'a == t' (in https://github.com/etorreborre/specs2/blob/d37f9b761626c78eec93094e722849e0cf98a057/matcher/shared/src/main/scala/org/specs2/matcher/NumericMatchers.scala#L225) will be false.

I also think these functions should not accept bigger significantFigures, than Double's decimal precision, which is 15-16 digits. In other words,
x must beCloseTo(y, SignificantFigures(z))
should return false if (x!=y) && z>16 (unless we would have special implementation for Longs where we have a bit more usable digits).

Another issue: beCloseTo's docstring refers to 'x' -- I think it should be "actual".

**Comment by etorreborre** [comment]
Please have a look at this commit: 924aa8b9cc793cd0d88ca0236875513e6297a04e and tell me if the implementation makes sense to you. I took some inspiration from [this SO question](https://stackoverflow.com/questions/7572309/any-neat-way-to-limit-significant-figures-with-bigdecimal) and it turns out that another case was actually wrong in the test suite!

**Comment by xxyyz** [comment]
Thanks for the very quick fix! I also appreciate the new tests :)
I made some additional tests on my own and the new code seems to work well, according to them.

Will you also fix the docstring in line 71/72? ("x" -> "actual")

Now, as BigDecimal is used anyway internally, an improvement could be to be prepared to work with BigDecimals directly if they are passed to beCloseTo (e.g. like in 'BigDecimal("123.4") must beCloseTo(BigDecimal("123"),  SignificantFigures(25))') -- in such cases, in the new code we first turn the got BigDecimal into Double and then back to BigDecimal, so we loose precision and still can't really work with sf.number > 16.
