### ISSUE TITLE
Linking errors with Scala.js 1.0

### ISSUE THREAD

**Issue by tindzk** [etorreborre/specs2#824]
I am currently implementing Scala.js 1.0 support in Bloop (https://github.com/scalacenter/bloop/pull/1234) and am getting linking errors after upgrading the Specs2 dependency of the `cross-test-build-scalajs-1.0` test project:

```shell
$ sbt
[info] Loading settings for project global-plugins from plugins.sbt ...
[info] Loading global plugins from /home/tim/.sbt/1.0/plugins
[info] Loading settings for project cross-test-build-scalajs-1-0-build from plugins.sbt ...
[info] Loading project definition from /dev/shm/cross-test-build-scalajs-1.0/project
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[info] Loading settings for project cross-test-build-scalajs-1-0 from build.sbt ...
[info] Set current project to cross-test-build-scalajs-1-0 (in build file:/dev/shm/cross-test-build-scalajs-1.0/)
[info] sbt server started at local:///home/tim/.sbt/1.0/server/0b4179c0e7dbfebe6c96/sock
sbt:cross-test-build-scalajs-1-0> test
[info] Compiling 1 Scala source to /dev/shm/cross-test-build-scalajs-1.0/test-project/js/target/scala-2.13/classes ...
[info] Compiling 1 Scala source to /dev/shm/cross-test-build-scalajs-1.0/test-project/js/target/scala-2.13/test-classes ...
[info] Fast optimizing /dev/shm/cross-test-build-scalajs-1.0/test-project/js/target/scala-2.13/test-project-test-fastopt.js
[error] Referring to non-existent class org.specs2.Specification
[error]   called from hello.Specs2Test
[error]   called from core module analyzer
[error] Referring to non-existent class org.specs2.Specification
[error]   called from constructor hello.Specs2Test.<init>()void
[error]   called from static constructor hello.Specs2Test.<clinit>()void
[error]   called from core module analyzer
[error] Referring to non-existent method constructor org.specs2.Specification.<init>()void
[error]   called from constructor hello.Specs2Test.<init>()void
[error]   called from static constructor hello.Specs2Test.<clinit>()void
[error]   called from core module analyzer
[error] There were linking errors
[error] (test-projectJS / Test / fastOptJS) There were linking errors
[error] Total time: 7 s, completed Apr 4, 2020 7:01:15 PM
```

The problem appears only when Specs2 and uTest are used in the same project. This is surprising since uTest does not depend on Specs2 at all.

The bug is reproducible with this project: https://github.com/tindzk/cross-test-build-scalajs-1.0-bug After removing these two lines from the `build.sbt`, the linking errors vanish:

```scala
libraryDependencies += "com.lihaoyi" %%% "utest" % "0.7.4" % Test,
testFrameworks += new TestFramework("utest.runner.Framework")
```

Any pointers would be greatly appreciated.

**Comment by etorreborre** [comment]
Hi Tim, unfortunately I don't know what's wrong there. This might be a classloader issue related to [that issue](https://github.com/etorreborre/specs2/issues/819). It is worth asking someone (@eed3si9n ?) working on sbt, they might have more clues than me :-).

**Comment by eed3si9n** [comment]
The problem still occurs with sbt 1.2.8 it seems, so I don't think it's related to sbt 1.3.x changes (Coursier and ClassLoader layering). If specs2 is available on the classpath and if Scala.JS is failing to link, then I'd guess the problem is in the linker?

**Comment by etorreborre** [comment]
@eed3si9n should we create an issue on the ScalaJS project then?

**Comment by eed3si9n** [comment]
It's still speculation but yea.

**Comment by tindzk** [comment]
Thanks for looking into it! I will open an issue on Scala.js' bug tracker.

**Comment by tindzk** [comment]
As pointed out by @sjrd, the libraries should be specified with `%%%` instead of `%%`. Changing it accordingly resolves the linking errors.
