### ISSUE TITLE
Assertion always pass while using default parameters

### ISSUE THREAD

**Issue by manish7-thakur** [etorreborre/specs2#840]
Hi,

The assertion always passes no matter what value you assert against when default value is not passed in assertions. e.g The below tests passes but if you provide default value explicitly in assertion, it fails. Tested with latest version buts seems like `3.8.9` also has it.

```
import org.specs2.mock.Mockito
import org.specs2.mutable.Specification

class SampleSpec extends Specification with Mockito {
  "this" should {
    "fail" in {
      val someMock = mock[Calc]
      val test = new Test(someMock)
      test.process()
      there was one(someMock).foo(2)
    }
  }
}

class Calc {
  def foo(i: Int, default: Int = 0) = {
    println(i)
  }
}
class Test(calc: Calc) {
  def process() = {
    calc.foo(1)
  }
}
```

Its even more freaking when default parameter is a `Boolean`. The below fails as specs says the actual argument passed for boolean value is `false`.

```
  class SampleSpec extends Specification with Mockito {
    "this" should {
      "pass" in {
        val someMock = mock[Calc]
        val test = new Test(someMock)
        test.process()
        there was one(someMock).foo(1, true)
      }
    }
  }

  class Calc {
    def foo(i: Int, default: Boolean = true) = {
      println(i)
    }
  }
  class Test(calc: Calc) {
    def process() = {
      calc.foo(1)
    }
  }
```

**Comment by etorreborre** [comment]
I am sorry but I don't have much time at the moment to investigate this kind of issue. The support for Mockito in specs2 is really hacky and I would recommend you to migrate to mockito-scala if you can. The next major specs2 version which is targeting Scala 3 will drop its mockito module in favour of mockito-scala which is supporting Scala and Mockito much better.

**Comment by manish7-thakur** [comment]
@etorreborre Thanks for the update. I'll use try to use `mockito-scala`, No worries.

**Comment by etorreborre** [comment]
I'm closing this issue since the recommendation is indeed to use `mockito-scala` now
