### ISSUE TITLE
IOMatchers implicit values catsEffectTimer and catsEffectContextShift drift into test scope leading to conflicts in implicit value resolution

### ISSUE THREAD

**Issue by islazh** [etorreborre/specs2#843]
Hi,

The implicits `catsEffectTimer` and `catsEffectContextShift` in IOMatchers are drifting into the scope of tests where we would normally provide our own `cats.effect.Timer[IO]` and `cats.effect.ContextShift[IO]`, for example to start up a service to run tests against. We then get a conflict in implicit resolution.

While it's possible for tests to just use these implicit values from `IOMatchers`, it's slightly strange and unexpected behaviour from a matchers class and it means it's harder to control the environment in tests. Maybe `IOMatchers` could be changed to limit the scope of the implicits or for them to be explicitly passed in? It would be considered a breaking change as there will be tests out there that rely on these values under the hood. However I think it will lead to clearer and more predictable test writing.

In addition, `catsEffectTimer` and `catsEffectContextShift` currently use the global `ExecutionContext`. Maybe they could be changed to use the ExecutionContext provided by Specs2?

**Comment by etorreborre** [comment]
I don't think that this issue still makes sense with cats-effect 3. If that is the case can you please re-open it in the `specs2-cats` project https://github.com/etorreborre/specs2-cats? Thank you.
