### ISSUE TITLE
any[T] matcher behaviour, using an implicit argument in a separated parameter group

### ISSUE THREAD

**Issue by Baztoune** [etorreborre/specs2#854]
Hi, I encountered an issue using specs2 and Mockito matchers, in a very specific use case. Basically, I was trying to mock a service method that takes an implicit database session as a 2nd parameter group argument, but also has a default value (`def find(id:Long)(implicit dBSession:DBSession = AutoSession) = ???`). 

I tried to reduce it to this minimal reproducible example below. I know that we can't combine matchers with raw values (`InvalidUseOfMatchersException`), but because `param2` is in an implicit with a default value and is in a second parameter group, there is no compilation or execution error. It simply returns `null`, which was tough to understand.

edit : not sure if the issue comes from the specs2 integration. If it's a pure mockito issue, please let me know

```
import org.specs2.mock.Mockito
import org.specs2.mutable.Specification

class MyServiceTest extends Specification with Mockito {

  class MyService {
    def test(param1: String)(implicit param2: String = "ABCD"): String = s"$param1#$param2"
  }

  "mocked method" should {
    "return expected value when arg matches literal value" in {
      val service = mock[MyService]

      service.test("match") returns "SUCCESS"
      service.test("match") === "SUCCESS" // OK
    }

    "return expected value when arg matches any (default param matcher NOT defined)" in {
      val service = mock[MyService]

      service.test(anyString) returns "SUCCESS"
      service.test("yolo") === "SUCCESS" // FAILS null != SUCCESS
    }

    "return expected value when arg matches any (default param matcher defined), using any[String]" in {
      val service = mock[MyService]

      service.test(any[String]())(any[String]()) returns "SUCCESS"
      service.test("yolo")("123") === "SUCCESS" // Ok
      service.test("yolo") === "SUCCESS" // OK
    }

    "return expected value when arg matches any (default param matcher defined), using anyString" in {
      val service = mock[MyService]

      service.test(anyString)(anyString) returns "SUCCESS"
      service.test("yolo")("123") === "SUCCESS" // Ok
      service.test("yolo") === "SUCCESS" // FAILS null != SUCCESS
    }
  }
}

```

Now I know how to be more careful it my tests and prevent this situation. But is it a known issue, and is it worth fixing it ? Thank you for your work

**Comment by etorreborre** [comment]
Unfortunately the use of Mockito is very hacky in specs2 since it was originally designed to be used with Scala. These days I recommend people to migrate to (`mockito-scala`)[https://github.com/mockito/mockito-scala/] for that reason.

**Comment by Baztoune** [comment]
Thank you for your quick answer. I understand that the use of Mockito is hacky. I wasn't even aware of the `mockito-scala` project so I'll have a look, thanks for the advice. Feel free to close the issue if it is not relevant

**Comment by Baztoune** [comment]
Ah! The issue is discussed on the [mockito-scala Readme](https://github.com/mockito/mockito-scala/#mixing-normal-values-with-argument-matchers)

```
So far there is one caveat, if you have a curried function that has default arguments on the second (or any following) argument list, the macro that achieves this will fail, this is related to how the default method is created by the compiler. I'll write a more detailed explanation at some point, but there are more than one reason why this is probably never going to work The workaround is quite easy though, just provide a value (or a matcher) for that argument and you are good to go.
```

**Comment by etorreborre** [comment]
I see, thanks for investigating. I'm closing this issue then.
