### ISSUE TITLE
Usage with rest-assured

### ISSUE THREAD

**Issue by najibghadri** [etorreborre/specs2#865]
Hello, just a question. We need to do API testing for our scala service, and we also do Unit testing. Since we already use Specs2 we wonder, is it feasible to user Specs with https://rest-assured.io/ ?

**Comment by etorreborre** [comment]
Hi, possibly you can create an [`AroundEach` trait](https://etorreborre.github.io/specs2/guide/SPECS2-4.0.1/org.specs2.guide.Contexts.html#aroundeach) which will "wrap" each example of a specs2 specification with some code to catch the exceptions thrown by rest-assured (I assume those are standard `AssertException`s) and then convert them to a `specs2` failure (using the `org.specs2.execute.Failure` class). 

Please create a small demo project on github if you're stuck and I will help you from there.

**Comment by najibghadri** [comment]
Thanks a lot @etorreborre . We haven't decided yet, if we move forward I will do the demo.

**Comment by etorreborre** [comment]
Closing this issue now.
