### ISSUE TITLE
Very generic error message in Intellij

### ISSUE THREAD

**Issue by longliveenduro** [etorreborre/specs2#878]
I get the following when I run a test in Intellij using Specs 4.10.0:

InvocationTargetException for 'main' in org.specs2.NotifierRunner: null

The test runs in sbt.

I do understand that this is most likely not a bug in Specs2 but probably some kind of sbt, classpath or Intellij import problem, but a more helpful error message would be very nice.

I've simply imported the build.sbt of the project.
I saw an old post with that error message and you suggested a to add an option to show the full stacktrace. But that was in sbt. How do I get a better error message in IntelliJ?

This was the old one using the Specs2 Runner : https://github.com/etorreborre/specs2/issues/626

**Comment by etorreborre** [comment]
Can you please try the latest version [`specs2-4.10.5`](https://repo1.maven.org/maven2/org/specs2/specs2-core_2.13/4.10.5/)?

**Comment by longliveenduro** [comment]
Thank you for your reply. I tried the 4.10.5 in the meantime. Same
error message.

**Comment by etorreborre** [comment]
I don't know what to say. Is there a way for you to get a stacktrace?

**Comment by longliveenduro** [comment]
I've added `@RunWith(classOf[JUnitRunner])`

and then got

`
java.lang.AbstractMethodError: org.specs2.text.Interpolated.scala$util$parsing$combinator$Parsers$$lastNoSuccessVar()Lscala/util/DynamicVariable;
	at scala.util.parsing.combinator.Parsers$NoSuccess.<init>(Parsers.scala:165)
	at scala.util.parsing.combinator.Parsers$Failure.<init>(Parsers.scala:193)
`

Does this help? We are using Scala 2.11.12

**Comment by longliveenduro** [comment]
I took the whole command line and let it run in the console I get the same error, but when I remove the parser combinators 1.0.4 from the classpath, it seems to work.

The problem is now that our build sbt doesn't include the parser-combinators jar. So I do not have a clue how this two different version of the parser combinators come into the classpath of the Specs2 execution.

**Comment by etorreborre** [comment]
Something else you can try is to use the `-Yrangepos` option:
```
scalacOptions in Test ++= Seq("-Yrangepos")
```
This should side-step the problem altogether but only if the compiler works ok with `-Yrangepos` on `2.11.12` which I can't remember.

**Comment by longliveenduro** [comment]
Using the dependency graph plugin with test:dependencyTree I see this:

```
[0m[[0minfo[0m] [0m  |   +-org.specs2:specs2-matcher-extra_2.11:4.10.0 [S][0m
[0m[[0minfo[0m] [0m  |     +-org.portable-scala:portable-scala-reflect_2.11:1.0.0 [S][0m
[0m[[0minfo[0m] [0m  |     | +-org.scala-lang:scala-reflect:2.11.11 [S][0m
[0m[[0minfo[0m] [0m  |     | [0m
[0m[[0minfo[0m] [0m  |     +-org.scala-sbt:test-interface:1.0[0m
[0m[[0minfo[0m] [0m  |     +-org.specs2:specs2-analysis_2.11:4.10.0 [S][0m
[0m[[0minfo[0m] [0m  |     | +-org.portable-scala:portable-scala-reflect_2.11:1.0.0 [S][0m
[0m[[0minfo[0m] [0m  |     | | +-org.scala-lang:scala-reflect:2.11.11 [S][0m
[0m[[0minfo[0m] [0m  |     | | [0m
[0m[[0minfo[0m] [0m  |     | +-org.scala-lang:scala-compiler:2.11.11 [S][0m
[0m[[0minfo[0m] [0m  |     | | +-org.scala-lang.modules:scala-parser-combinators_2.11:1.0.4 (evicted by: 1.1.2)[0m
[0m[[0minfo[0m] [0m  |     | | +-org.scala-lang.modules:scala-parser-combinators_2.11:1.1.2 [S][0m
```

Looks like Scala compiler 2.11.11 pulls in 1.0.4. and 1.1.2. That doesn't make sense to me

**Comment by etorreborre** [comment]
I think that's because the compiler pulls `1.0.4` but specs2 specifies `1.1.2`: https://github.com/etorreborre/specs2/blob/master/project/depends.scala#L39. Maybe you can try `dependencyOverrides` in sbt: https://stackoverflow.com/questions/36501352/how-to-force-a-specific-version-of-dependency

**Comment by etorreborre** [comment]
I probably did not catch this issue because I'm always using `-Yrangepos` (and I haven't been using Scala `2.11` for a long time :-))

**Comment by longliveenduro** [comment]
Ah ok, thank you very much for your help!
