### ISSUE TITLE
java.util.NoSuchElementException: None.get -- when creating a matcher for Option[String]

### ISSUE THREAD

**Issue by xxyyz** [etorreborre/specs2#890]
I have an `Option[String]` with the meaning:
`None` = everything is OK;
`Some(text)` = something is not OK; explanation comes in `text`

I would like to create a matcher for it in the following way:
`def beOK: Matcher[Option[String]] = { x: Option[String] => (x.isEmpty, x.get) }`

This results in the exception "java.util.NoSuchElementException: None.get"

If I change the matcher, then it works:
`def beOK: Matcher[Option[String]] = { x: Option[String] => (x.isEmpty, x.getOrElse("Never used text??")) }`

I do not see `Never used text??` in the test outcome, it seems to be unnecessary.

I guess the fix would be to change
`implicit def functionToMatcher[T](f: (T => Boolean, String)): Matcher[T] =`
to
`implicit def functionToMatcher[T](f: (T => Boolean, => String)): Matcher[T] =`
in https://github.com/etorreborre/specs2/blob/master/matcher/shared/src/main/scala/org/specs2/matcher/MatchersImplicits.scala#L135?

**Comment by etorreborre** [comment]
That string is used to output a failure message, like:
```
def beOK: Matcher[Option[String]] = 
  (x.isEmpty, s"expected None, got: $x")
```

I agree that it would be best to have a byname parameter there and avoid evaluating that string if possible. That being said, in the next specs2 version I'm simplifying the way results are implemented and part of that simplification implies that failure messages will not be lazy. So it's a good habit to make sure that failure messages can be evaluated even in case of a success.
