### ISSUE TITLE
Improve documentation on how to use specs2 runners

### ISSUE THREAD

**Issue by LLCampos** [etorreborre/specs2#935]
[Here](https://etorreborre.github.io/specs2/guide/SPECS2-4.10.0/org.specs2.guide.RunInShell.html) are the docs that I think might need some improvements.

First, the commands seem to be wrong? For example, `specs2.files` doesn't exist, it should be `org.specs2.runner.files`?

Another problem I'm hitting is that it is not clear how to send arguments to the runners and which of them are valid. For example, doing `org.specs2.runner.files -- exclude myTag` seem to work ok, but not `org.specs2.runner.files -- plan true`.

This is especially hard to figure out since the runner doesn't report on bad arguments.

**Comment by etorreborre** [comment]
I totally agree with you. I started at having a look at this documentation for the next major release but I will give a go at improving the current one

**Comment by etorreborre** [comment]
I have published a new version, `4.12.0` where:

 - the `specs2.files` object is where it should be
 - I did a pass over [the documentation](https://etorreborre.github.io/specs2/guide/SPECS2-4.12.0/org.specs2.guide.RunInShell.html)
 - there are better diagnostics with `filesrunner.verbose` when searching for specifications to execute
 - the `verbose` option will warn you if there any unrecognized flag/option on the command line (this is not a very satisfactory solution but I hope it will help in the meantime)
