### ISSUE TITLE
Allow global configuration of number of retries in await

### ISSUE THREAD

**Issue by ittaiz** [etorreborre/specs2#943]
Hi,
We (Wix) are using specs2 all across our code base (millions of LOC) and we have a flakiness problem (many of the tests call async APIs).
The main problem stems from the fact that CI machines are slower than dev machines and so tests which are ok on dev machines start being flaky on CI from time to time.

We are interested in having a global configuration of the number of retries in await.
Our thought was to have a "multiplier" like param (defaults to 1) and then we can configure it to be 2/3/5 on CI.
We'd love for it to apply on both default number of retries and explicitly configured number of retries.

We'll be glad to contribute this change.

WDYT?

cc @viliusl @rotemmiz

**Comment by etorreborre** [comment]
Hi, if you look at the `Futures` tab on the [Matchers user guide page](https://etorreborre.github.io/specs2/guide/SPECS2-4.12.0/org.specs2.guide.Matchers.html#out-of-the-box), you can see that there is a `timefactor` option for this:
```
sbt> testOnly *MyFuturesSpec* -- timeFactor 3
```
Can you please try it out and tell me if it works for you?

**Comment by symbiont-eric-torreborre** [comment]
@ittaiz did you have time to look at this issue?

**Comment by etorreborre** [comment]
Please re-open this issue if you can't make it work

**Comment by ittaiz** [comment]
Hi,
First I want to apologize.
I opened this issue on behalf of a colleague who was supposed to have capacity to take it forward but then got a ton of unexpected stuff so couldn't reply.
I kept expecting he follow up here but I feel some explanation is expected here.
Concretely I'm not sure this flag is good enough for this use case because it will make CI runs longer even when the future is ready. If you increase the number of retries you only pay the extended cost when you have to.

**Comment by etorreborre** [comment]
That makes sense. Actually that's on me I did not fully understand the request. I added a `retriesFactor` command line parameter to `4.12.3` if you want to try it out.

**Comment by ittaiz** [comment]
Thanks! Hopefully I'll get someone soon to try it out. 
Appreciate your time :)
