### ISSUE TITLE
Document `.setMessage` 

### ISSUE THREAD

**Issue by LLCampos** [etorreborre/specs2#960]
No mention of `setMessage` function for matchers seems to be mentioned in the docs:

https://etorreborre.github.io/specs2/guide/5.0.0-ALPHA-03/search.html?q=setMessage

**Comment by etorreborre** [comment]
The search could be improved (I don't know how yet, I'm using a js library). The `setMessage` function is actually described on this page on [`Expectation Description`](https://etorreborre.github.io/specs2/guide/5.0.0-ALPHA-03/org.specs2.guide.ExpectationDescription.html#enhance-failures-messages)

**Comment by etorreborre** [comment]
I'm opening an issue for the search library: https://github.com/etorreborre/specs2/issues/961

**Comment by etorreborre** [comment]
The search was actually broken on recent version. It is now [fixed](https://etorreborre.github.io/specs2/guide/5.0.0-RC-12/search.html?q=setMessage):
<img width="716" alt="image" src="https://user-images.githubusercontent.com/10988/136695791-b1c55b15-4388-4a87-ad98-dd988517d4f7.png">
