### ISSUE TITLE
Use a better execution context for ScalaJS

### ISSUE THREAD

**Issue by etorreborre** [etorreborre/specs2#967]
At the moment, timeout are not supported out of the box in specs2 when using ScalaJS. The reason is explained in detail in a [ScalaJS issue](https://github.com/scala-js/scala-js/issues/4129).

If the `Polyfill` execution context is extracted in its own library, use it as the default execution context for ScalaJS.

Additional question for @djspiewak: is it still necessary to provide an option to override the execution context in specs2?

**Comment by vasilmkd** [comment]
It would be very helpful if an overridable execution context exists in specs2. I do not see the `Polyfill` execution context being extracted in its own library very soon. I may be wrong.

**Comment by vasilmkd** [comment]
Also one more question, I tried your `4.12.4-js-ec` version locally, and I cannot do the following override in `mutable.Specification`. What am I missing?
https://github.com/etorreborre/specs2/blob/ca7d444a1219ff1a6dc260b9720c51d4b4c8d252/core/js/src/test/scala/org/specs2/JsExecutionContextSpec.scala#L26-L27

**Comment by etorreborre** [comment]
> I do not see the Polyfill execution context being extracted in its own library very soon. I may be wrong.

The [discussion is still active](https://github.com/scala-js/scala-js/issues/4129#issuecomment-892983081) so I'm hopeful!

> It fails and reports that jsExecutionContext does not exist

I don't know. I'm still working on a temporary version with this capability + [this issue](https://github.com/etorreborre/specs2/issues/968). I will publish a SNAPSHOT when it's ready.

**Comment by vasilmkd** [comment]
Yes, no rush, I understand it is incomplete.

**Comment by etorreborre** [comment]
Done with `5.0.0-RC-07`
