### ISSUE TITLE
specs2-commons depends on parser-combinators 2.0.0

### ISSUE THREAD

**Issue by melezov** [etorreborre/specs2#980]
Ever since 4.12.2, specs2-commons is depending on scala-parser-combinators 2.x:
https://mvnrepository.com/artifact/org.specs2/specs2-common_2.13/4.12.2

    +-org.specs2:specs2-common_2.13:4.12.3 [S]
      +-org.portable-scala:portable-scala-reflect_2.13:1.1.1 [S]
      +-org.scala-lang.modules:scala-parser-combinators_2.13:2.0.0 [S]
      +-org.scala-lang:scala-reflect:2.13.6 [S]
      +-org.scala-sbt:test-interface:1.0
      +-org.specs2:specs2-fp_2.13:4.12.3 [S]

I'm raising this in light of the recent [scala-xml revert to 1.3.x line](https://github.com/etorreborre/specs2/releases/tag/SPECS2-4.12.5) in 4.12.5 as it might be something to reconsider.
Also, the code mentions that combinators 2.x are a requirement for `scala-matcher-extra` (https://github.com/etorreborre/specs2/blob/master/project/depends.scala#L18), but as you can see above it's being used within commons, so everywhere

scala-parser-combinators 2.x seems to be binary incompatible with 1.x as posted here:
https://github.com/scala/scala-parser-combinators/releases/tag/v2.0.0

This causes issues when adding specs2 to e.g. Play projects.
Perhaps explicitly overriding the version to either 2.x or 1.x would work in this type of setup. Will test on our CI.

    [error] java.lang.RuntimeException: found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
    [error]
    [error]         * org.scala-lang.modules:scala-parser-combinators_2.13:2.0.0 (early-semver) is selected over {1.1.2, 1.1.2, 1.1.2}
    [error]             +- org.specs2:specs2-common_2.13:4.12.3               (depends on 2.0.0)
    [error]             +- org.playframework.anorm:anorm_2.13:2.6.10          (depends on 1.1.2)
    [error]             +- com.typesafe.play:play_2.13:2.8.8                  (depends on 1.1.2)
    [error]             +- com.typesafe:ssl-config-core_2.13:0.4.2            (depends on 1.1.2)

I don't have a suggestion on how to proceed, raising for awareness.

**Comment by etorreborre** [comment]
Thanks for reporting this. I'm thinking that we should apply the same treatment as for `scala-xml`: leave `scala-parser-combinators-1.x ` for `specs2-4.x` and `scala-parser-combinators-1.x` for `specs2-5.x`. Especially since in `specs2-5.x`, there's no need anymore for using `scala-parser-combinators` in `specs2-common` or `specs2-core` (it is now only used in `specs2-matcher-extra`)

**Comment by melezov** [comment]
It makes a lot of sense, since then a minor (patch) release such as 4.12.1 -> 4.12.x would not cause disruptions.
When people perform major upgrades such as 4.x -> 5.x they will pay a lot more attention to resolving dependencies correctly.

**Comment by etorreborre** [comment]
fixed now with `4.12.6`

**Comment by mkurz** [comment]
Yeah, scala-parser-combinators is the same story like scala-xml, we should stay on 1.x for specs 4.12.x

**Comment by mkurz** [comment]
Update from 2025:

Regarding the error message from this issue:

> ```
> [error] java.lang.RuntimeException: found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
> [error]
> [error]         * org.scala-lang.modules:scala-parser-combinators_2.13:2.0.0 (early-semver) is selected over {1.1.2, 1.1.2, 1.1.2}
> [error]             +- org.specs2:specs2-common_2.13:4.12.3               (depends on 2.0.0)
> [error]             +- org.playframework.anorm:anorm_2.13:2.6.10          (depends on 1.1.2)
> [error]             +- com.typesafe.play:play_2.13:2.8.8                  (depends on 1.1.2)
> [error]             +- com.typesafe:ssl-config-core_2.13:0.4.2            (depends on 1.1.2)
> ```

Play and anorm will upgrade to v2 for Scala 2.13 in their next major release:
- https://github.com/playframework/playframework/pull/13197
- https://github.com/playframework/anorm/pull/638
- ssl-config dropped scala-parser-combinator in v0.6.0, so this is not a problem anymore.

> Yeah, scala-parser-combinators is the same story like scala-xml, we should stay on 1.x for specs 4.12.x

This statement is not 100% true (anymore). We should stay on 1.x for Scala 2.12.x, but upgrade to v2 for Scala 2.13+.

Other libraries do use that approach as well, I am 100% sure this is the way to go:

- https://github.com/eed3si9n/scalaxb/blob/v1.12.2/project/dependencies.scala#L69-L72
- https://github.com/sbt/sbt-pgp/blob/v2.3.1/project/Dependencies.scala#L17-L22
