### ISSUE TITLE
specs2 `4.12.10` and `4.12.11` do not respect `pendingUntilFixed`

### ISSUE THREAD

**Issue by vasilmkd** [etorreborre/specs2#987]
Here is a minimal reproduction sbt [project](https://github.com/vasilmkd/specs2-pending-until-fixed-repro).

Version 4.12.9 works fine.

**Comment by etorreborre** [comment]
Thanks for the repro. This is indeed a regression from the improper revert of the `PendingUntilFixed` changes [I eventually had to do](https://github.com/etorreborre/specs2/issues/984#issuecomment-913767036).

`specs2-4.12.12` should fix that.

**Comment by vasilmkd** [comment]
No worries, these things happen. 😄 Thanks for the quick turnaround.
